linuxmint/cinnamon-spices-applets

places-with-terminal@mtwebster/files/places-with-terminal@mtwebster/applet.js

places-with-terminal@mtwebster has not been working for some time because it
1. referenced `nautilus` and `gnome-control-center`
2. used a custom Menu that contained a function call `PopupMenu.PopupMenu.prototype._init` that used an invalid signature
This fix brings the applet back to a working state and additionally contains one small improvement: After clicking the terminal icon for a place, the popup menu now closes.

reactivate  places-with-terminal@mtwebster

---

stopwatch@pdcurtis/README.md

- This adds a README.md file to the stopwatch applet so it is documented in the new Cinnamon Spices.
- The README.md is based on the previous Spices web site and the internal help file which will be updated in due course.
- It is also a minimal test of he overall Fork, Clone, Branch, Push procedure for making changes to an applet is correct before updating other applets and also checking that the markdown formating is correct for Github

Add README.md file to Stopwatch Applet

---

scripts@paucapo.com/files/scripts@paucapo.com/applet.js
scripts@paucapo.com/files/scripts@paucapo.com/settings-schema.json

Using "title" as name for an setting causes problems with cinnamon-json-makepot, i.e. when you want to create a translation template. (see https://github.com/linuxmint/cinnamon-spices-applets/issues/37)
Because there's an item called "title" for "pages" and "sections", which is expecting a value.

scripts@paucapo: change "title" to "paneltitle" in settings-schema

---

vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/applet.js

now the function able to run any image even if it's has spaces in its name.
before the single quote the command will be like this
( vmplayer /home/username/vmware/vm machine/vm machine.vmx )
but unfortunately it wont run becouse of those spaces,
after wraping the path with single quotes it will run smoothly :+1: 
( vmplayer '/home/username/vmware/vm machine/vm machine.vmx' )

[vboxlauncher@mockturtl] Fixed startVmplayerImage Function : not starting VMs with spaces in its name

---

clipboard-qr@wrouesnel/README.md
clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/applet.js

When closing QR scanner without having scanned anything, the applet does not pop up anymore.
Catch this error.
Restore Readme from wayback machine

clipboard-qr@wrouesnel: fix applet from crashing

---

weather@mockturtl/files/weather@mockturtl/po/LINGUAS
weather@mockturtl/files/weather@mockturtl/po/ko.po

I translated **weather@mockturtl** into Korean for l10n support. I added a new file `po/ko.po` and added a new line `ko` in `po/LINGUAS`. Please check. Thanks.
@mockturtl

weather@mockturtl: add Korean translation support

---

search-box@mtwebster/files/search-box@mtwebster/3.2/applet.js

Readd "return true" to signal callback, which was deleted in last commit.
Encode the symbol '
Else you get an error, if you search for something like "What's up?"

search-box@mtwebster: fix error, when ' is used

---

weather@mockturtl/files/weather@mockturtl/applet.js
weather@mockturtl/files/weather@mockturtl/settings-schema.json

@mockturtl: The ability to change the key binding was added to the settings-schema.json file and the necessary library was imported into applet.js to grab the keybinding from the settings and assign it to the function on_applet_clicked().

weather@mockturtl applet: [[Feature]] Added in the Functionality to Summon the Applet by Key Command

---

places-bookmarks@dmo60.de/README.md
places-bookmarks@dmo60.de/files/places-bookmarks@dmo60.de/applet.js
places-bookmarks@dmo60.de/files/places-bookmarks@dmo60.de/metadata.json
places-bookmarks@dmo60.de/files/places-bookmarks@dmo60.de/po/es.po
places-bookmarks@dmo60.de/files/places-bookmarks@dmo60.de/po/localization-template.pot
places-bookmarks@dmo60.de/files/places-bookmarks@dmo60.de/settings-schema.json

- Removed custom menu prototype in favor of using **Applet.AppletPopupMenu**. Fixes #245.
- Added full support for Cinnamon 3.2 and its vertical panels.
- Added possibility to configure applet using Cinnamon's native settings system.
- Removed single instance restriction due to the implementation of a settings system.
- Added custom translation mechanism and localizations to be able to translate the new strings added by the settings system implementation.
- Added connection to automatically update applet menu when adding/removing/reordering bookmarks/places.
Ping to applet author: @dmo60
Sorry, I got a little carried away with the changes. My initial intention was to just fix #245, but then I saw that I could add some other improvements and I just did it. Of course, feel free to reject …

Places (places-bookmarks@dmo60.de) update

---

0dyseus@CustomCinnamonMenu/HELP.md
0dyseus@CustomCinnamonMenu/files/0dyseus@CustomCinnamonMenu/HELP.html
0dyseus@DesktopHandler/HELP.md
0dyseus@DesktopHandler/files/0dyseus@DesktopHandler/HELP.html
0dyseus@ExtensionsManager/HELP.md
0dyseus@ExtensionsManager/files/0dyseus@ExtensionsManager/HELP.html
0dyseus@PopupTranslator/HELP.md
0dyseus@PopupTranslator/files/0dyseus@PopupTranslator/HELP.html
0dyseus@QuickMenu/HELP.md
0dyseus@QuickMenu/files/0dyseus@QuickMenu/HELP.html
0dyseus@window-list-fork/HELP.md
0dyseus@window-list-fork/files/0dyseus@window-list-fork/HELP.html

- Updated help file.
- Updated help file.
- Updated help file.
- Updated help file.
- Updated help file.
- Updated help file.

Applets updates

---

0dyseus@CustomCinnamonMenu/files/0dyseus@CustomCinnamonMenu/metadata.json
0dyseus@DesktopHandler/files/0dyseus@DesktopHandler/metadata.json
0dyseus@ExtensionsManager/files/0dyseus@ExtensionsManager/metadata.json
0dyseus@PopupTranslator/files/0dyseus@PopupTranslator/metadata.json
0dyseus@QuickMenu/files/0dyseus@QuickMenu/metadata.json
0dyseus@SysmonitorByOrcus/files/0dyseus@SysmonitorByOrcus/metadata.json
0dyseus@window-list-fork/files/0dyseus@window-list-fork/metadata.json
Cinnamenu@json/files/Cinnamenu@json/metadata.json
IcingTaskManager@json/files/IcingTaskManager@json/metadata.json
IcingTaskManager@json/src/metadata.json
PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/metadata.json
axos88@countdown-timer/files/axos88@countdown-timer/metadata.json
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/metadata.json
betterlock/files/betterlock/metadata.json
bumblebee@pdcurtis/files/bumblebee@pdcurtis/metadata.json
collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/metadata.json
feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/metadata.json
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/metadata.json
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/metadata.json
nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/metadata.json
rancher@centurix/files/rancher@centurix/metadata.json
sane-menu@nooulaif/files/metadata.json
serviceLauncher@hulygun/files/metadata.json
stopwatch@pdcurtis/files/stopwatch@pdcurtis/metadata.json
window-buttons-with-title2@hanspr/files/window-buttons-with-title2@hanspr/metadata.json
window-buttons-with-title@fmete/files/window-buttons-with-title@fmete/metadata.json
windowTitle2@hanspr/files/windowTitle2@hanspr/metadata.json

>The dangerous property in metadata.json should not be there. It interferes with the scanning of the applet when it is installed by the user.
pings:
@hulygun @mickaelalbertus @centurix @nooulaif @pdcurtis @hanspr @jaszhix @feuerfuchs @fmete @entelechy @axos88 @Odyseus @jake1164

26 Applets: Remove dangerous flags

---

betterlock/files/betterlock/metadata.json
betterlock/files/betterlock/po/es.po

- Added *hide-configuration* property to the metadata.json file to hide the *Configure...* item on applet context menu since it isn't really needed.
- Added Spanish localization.
Ping to author: @entelechy

Num Lock/Caps Lock indicator with MessageTray notifications (betterlock) update

---

netusagemonitor@pdcurtis/README.md
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/README.md
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/applet.js
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/changelog.txt
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/po/netusagemonitor.pot

* Additional PopupMenu.PopupMenuSection added  so 'standard' context menu items are retained when the menu is refreshed.
* Update netusagemonitor.pot using cinnamon-json-makepot --js po/netusagemonitor.pot as a string was removed.
* Version and changes information updated in applet.js and changelog.txt
* Update README.md (2x) to acknowledge contributions from @collinss and @Odyseus for this  easy and elegant solution to the problem

netusagemoninitor@pdcurtis (NUMA) Update to v3.1.1

---

netusagemonitor@pdcurtis/README.md
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/README.md
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/applet.js
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/changelog.txt
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/metadata.json

* Change spawn_command_line_sync to spawn_command_line_async to remove one reason for 'dangerous' classification.
* Correct several spelling errors in comments and .md files.
Does anybody know an alternative to use of Gtop which also leads to the 'dangerous classification being set? The code using it is minimal
`this.gtop = new GTop.glibtop_netload();`
and
```
GTop.glibtop_get_netload(this.gtop, this.monitoredInterfaceName);
this.upOld = this.gtop.bytes_out;
this.downOld = this.gtop.bytes_in;
```

netusagemoninitor@pdcurtis (NUMA) Update to v3.1.2

---

temperature@fevimu/files/temperature@fevimu/applet.js

Replace unspaced unicode upper O symbol with real degree symbol and spacing between numbers and °C
https://en.wikipedia.org/wiki/Celsius

 temperature@fevimu: Degree symbol

---

Cinnamenu@json/CHANGELOG.md
Cinnamenu@json/files/Cinnamenu@json/buttons.js
Cinnamenu@json/files/Cinnamenu@json/metadata.json
Cinnamenu@json/files/Cinnamenu@json/panel.js

* Fixed the application list view having excessive width.
* Refined the width for the grid at all column counts.
* Fixed the search box height for some themes.
* Made the applet compatible with Cinnamon Git.

Cinnamenu: Update to 1.2.1

---

search-box@mtwebster/files/search-box@mtwebster/metadata.json
search-box@mtwebster/files/search-box@mtwebster/po/ru.po

use proper language ID, i.e. ru.po instead of ru_RU.po
more than one instance causes problems

search-box@mtwebster: max-instance 1 and ru.po

---

stopwatch@pdcurtis/README.md
stopwatch@pdcurtis/files/stopwatch@pdcurtis/README.md
stopwatch@pdcurtis/files/stopwatch@pdcurtis/applet.js
stopwatch@pdcurtis/files/stopwatch@pdcurtis/changelog.txt
stopwatch@pdcurtis/files/stopwatch@pdcurtis/metadata.json

* Bug corrected in Context Menu -> Pause
* Use of this.UUID = metadata.uuid removed which makes use of const UUID in l10n more obvious.

Update stopwatch@pdcurtis to version 2.0.4

---

BgRadio@spacy01/files/BgRadio@spacy01/applet.js
axos88@countdown-timer/files/axos88@countdown-timer/applet.js
netctlstatus@prmurthy/files/netctlstatus@prmurthy/applet.js
netctlsystraymenu@prmurthy/files/netctlsystraymenu@prmurthy/applet.js
search-box@mtwebster/files/search-box@mtwebster/applet.js
shutdown-timer@webum.by/files/applet.js
system-monitor@ebbes/files/system-monitor@ebbes/applet.js
temperature@fevimu/files/temperature@fevimu/applet.js
timer-notifications@markbokil.com/files/timer-notifications@markbokil.com/applet.js

PanelMenu was removed in Cinnamon 3.4
These applets import PanelMenu, but never use them, which will cause these applets to crash in Cinnamon 3.4.
notify authors about this bugfix:
@mtwebster 
@spacy01 
@axos88 
@prmurthy
@webum.by
@mbokil
@fevimu
@ebbes
Fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/332

9 Applets: remove unused `const PanelMenu` - bugfix for Cinnamon 3.4

---

stopwatch@pdcurtis/files/stopwatch@pdcurtis/applet.js
stopwatch@pdcurtis/files/stopwatch@pdcurtis/changelog.txt
stopwatch@pdcurtis/files/stopwatch@pdcurtis/metadata.json

* Improved l10n Support:
- UUID set from metadata.uuid so no need for explicit definition.
-  _() function now checks for system translations if a local one not found.
This applet It is not only useful in its own right but is also provides a 'tutorial' framework for other more complex applets - for example it provides a settings screen and a 'standard' right click (context) menu which opens the settings panel and a housekeeping sub-menu accessing help and a version/update files. It now has an example of how to implement l10n  support in a more general manner based on ideas from @Odyseus, @lestcape and @NikoKrause which will, after further testing, be incorporated into my other current  applets and those under development.

Update stopwatch@pdcurtis to version 2.0.5

---

weather@mockturtl/files/weather@mockturtl/applet.js

@mockturtl 
```
(cinnamon:6699): Cjs-WARNING **: JS ERROR: TypeError: weather.item is undefined
refreshWeather/<@/home/jason/.local/share/cinnamon/applets/weather@mockturtl/applet.js:415:11
soupQueue@/home/jason/.local/share/cinnamon/applets/weather@mockturtl/applet.js:390:7
```

weather@mockturtl: Apply 3.4 fixes

---

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/2.6/applet.js
CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/3.2/applet.js
betterplaces@bownz/files/betterplaces@bownz/applet.js
betterplaces@dewman12/files/betterplaces@dewman12/applet.js
cwgMintMenu@clockworkgobin.org/files/cwgMintMenu@clockworkgobin.org/applet.js
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletGui.js
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/applet.js
profile-switcher@pixunil/files/profile-switcher@pixunil/applet.js
sane-menu@nooulaif/files/applet.js
stopwatch@pdcurtis/files/stopwatch@pdcurtis/applet.js
text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/applet.js

mozjs38 crashes if one is ecountered within the same scope
this prevents the applet to crash in Cinnamon 3.4
@collinss 
@NikoKrause
@cardsurf
@pdcurtis 
@bownz
@dewman12
@clockworksimon
@pixunil
@nooulaif

[3.4] Several applets: remove duplicate 'let' declarations

---

netusagemonitor@pdcurtis/README.md
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/README.md
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/applet.js
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/changelog.txt
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/metadata.json
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/po/netusagemonitor.pot

* Harmonise with code written by author for vnstat@cinnamon.org and revert 3.1.2 until further testing.
* Updated netusagemonitor.pot using cinnamon-json-makepot --js po/netusagemonitor.pot as string added. 
* Tidy up comments in applet.js
* Update README.md to remove a couple of references to Ubuntu from early days.
* Usual updates to new version in applet.js, changelog and metadata.json
@muzena and @giwhub Please note I have updated the .pot as an extra string has been added. Many thanks for your previous translations.

netusagemonior@pdcurtis Update to v3.2.1

---

betterlock/info.json
rprego@rprego.com/info.json
sysmenu@tuxuls@gmail.com/info.json
uptime@vatanuki.kun/info.json

The author names do not respond to any github user name or the authors do not respond at all, therefore set author to 'none' and give credit to them as original author.

Several applets: Set author with no corresponding github user name to none

---

github-projects@morgan-design.com/files/github-projects@morgan-design.com/applet.js
github-projects@morgan-design.com/files/github-projects@morgan-design.com/metadata.json

@jamesmorgan
This prevents the applet from crashing on Cinnamon 3.4 due to a strict
mode error.
```
error t=2017-05-13T20:27:15.664Z redeclaration of formal parameter options
trace t=2017-05-13T20:27:15.664Z 
Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:155:13
Extension@/usr/share/cinnamon/js/ui/extension.js:116:5
loadExtension@/usr/share/cinnamon/js/ui/extension.js:449:25
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:236:13
---------------->
error t=2017-05-13T20:27:15.664Z [Applet "github-projects@morgan-design.com"]: Error importing applet.js from github-projects@morgan-design.com
```

github-projects@morgan-design.com: Add Cinnamon 3.4 compatibility fix

---

ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/applet.js

Add a minimum timeout to prevent capture the unwanted applet menu within the screenshot (still opened when the capture happens)

[ScreenShot+RecordDesktop] add capture timeout

---

vnstat@linuxmint.com/README.md
vnstat@linuxmint.com/files/vnstat@linuxmint.com/applet.js

* Changes made by because `_updateDevice` function was not working - Issue #152
`_UpdateDevice()` commented out and replaced by a cut down version of the one used in
networkusagemonitor@pdcurtis 
with two associated functions getInterfaces() and isInterfaceAvailable() added
`const NetworkManager = imports.gi.NetworkManager` added
diagnostic call `global.logError("Test not error - vnstat using device: " + this._device);` added. 
`GLib.spawn_command_line_sync()` replaced by` GLib.spawn_command_line_async()`
* Tested with normal connections made by network manager.
* Will probably not find connections not made within Network Manager such as Bluetooth PAN connections or USB mobile internet modems.
@clefebvre I failed to find the error in the original active device identification function …

vnstat@linuxmint.com Patch 1

---

a4techTool@mous/info.json
binaryclock@entelechy/info.json
location-detection@heimdall/info.json
restart-cinnamon@kolle/info.json
temperature@fevimu/info.json
toggle_LookingGlass@kolle/info.json

Those applets are abandoned. The authors have never responded and they haven't been active on GitHub for years. So set author to `none` and mention them in `original_author`
@entelechy
@heimdall
@mous
@kolle
@fevimu

6 applets: set author to none for abanonded applets

---

timer-notifications@markbokil.com/files/timer-notifications@markbokil.com/applet.js

const AppOptions is re-assigned, which cannot be done in ES2015.
@mbokil

timer-notifications@markbokil.com: Cinnamon 3.4 fix

---

SW++@mohammad-sn/files/SW++@mohammad-sn/applet.js
SW++@mohammad-sn/files/SW++@mohammad-sn/settings-schema.json

@mohammad-sn
This fixes the following issues when the applet is added to the panel (default settings):
- Icon is now visible and the applet is clickable. Defaults to the ```user-desktop```.
- Preserved the applet width from the theme unless explicitly set.
- Preserved the hover bg color from the theme unless explicitly set.
Misc:
- Removed duplicate ```on_applet_removed_from_panel``` method and added its contents to the first one.
- Removed white space.

SW++@mohammad-sn: Prevent overriding of Cinnamon styles if not explicitly set in the applet's configuration

---

bash-sensors@pkkk/files/bash-sensors@pkkk/applet.js

This is the other half of my failed commit (https://github.com/linuxmint/cinnamon-spices-applets/pull/739). This time the `bash-sensors@pkkk` is addressed, solving #553 and correcting some style incongruences. It also marginally simplifies a loop and corrects the trimming done inside it (to avoid under-trimming).

bash-sensors@pkkk: Correct code style / indentation, simplify loops and fix #553

---

force-quit@cinnamon.org/files/force-quit@cinnamon.org/applet.js

It turns out xkill should get called only after releasing the mouse button, since on_applet_clicked fires on button press event, unless you release the mouse button really quick, it would not work. Calling xkill on button release event fixes it.

force-quit: fix force quit not working #69

---

IcingTaskManager@json/files/IcingTaskManager@json/3.4/applet.js

The Babel transpiler turns ES2015 code into ES5, but all of the features used in this applet are available in the mozjs38 engine. This decreases initialization time for Cinnamon 3.4 using mozjs38, as Babel is a large file.

Icing Task Manager: Skip Babel transform if mozjs38 is in use

---

Cinnamenu@json/files/Cinnamenu@json/applet.js
Cinnamenu@json/files/Cinnamenu@json/cinnode_modules/cinnode/node_modules.js

The Babel transpiler turns ES2015 code into ES5, but all of the features used in this applet are available in the mozjs38 engine. This decreases initialization time for Cinnamon 3.4 using mozjs38, as Babel is a large file. This also adds a debug state that prevents module caching.

Cinnamenu: Skip Babel transform if mozjs38 is in use, add debug state

---

rancher@centurix/files/rancher@centurix/metadata.json
rancher@centurix/files/rancher@centurix/reload.sh
rancher@centurix/files/rancher@centurix/util.js

Ensure that the configuration dialog settings are resolved correctly before being used. By default the configuration dialog will always prefix selected paths with file://. In order to wrangle ~ locations using GLib.get_home_dir(), we need to remove this prefix.

rancher@centurix: Correctly resolve directories selected through the settings dialog

---

rancher@centurix/files/rancher@centurix/applet.js
rancher@centurix/files/rancher@centurix/homestead.js
rancher@centurix/files/rancher@centurix/metadata.json

Homestead and Vagrant are upgrade independently, later versions of Homestead require Vagrant v1.9 or higher. Provide behaviour to download the latest Vagrant.
Provide a configuration folder fallback location to assist in older Homestead installations still located in the ~/.homestead location.

rancher@centurix: Add a Vagrant version check, deal with older Homestead config locations

---

weather@mockturtl/files/weather@mockturtl/applet.js
weather@mockturtl/files/weather@mockturtl/metadata.json
weather@mockturtl/files/weather@mockturtl/settings-schema.json

In most weather forecasts, it is extremely common to display the high temperature first and the low temperature second (I believe it's the convention). Examples include https://www.weather.com, the weather displayed in Google search, and the weather displayed in the iOS weather app. 
Before, this weather applet only displayed the low temperature first. I have added the option to display the high temperature first. This should improve experience for many users.
Note, this is my first public contribution and I'm not quite sure how the versioning works. I read the semantic versioning document, but I'm not sure if this counts as a minor or patch update. Let me know if I did it wrong and I'll fix the metadata.json appropriately!

weather@mockturtl: Added option to show high temperature first in forecast

---

rancher@centurix/files/rancher@centurix/applet.js

It was assumed that the IconApplet's built in _menuManager was a good idea to use as a menu manager for the applet as a whole, but it doesn't play well with the AppletSettings menu. Left clicking a menu built with _menuManager and then immediately right-clicking for the configuration menu can leave Cinnamon in a partially un-working state. Might need more probing around that area to figure out what the exact cause is as it looks like an issue upstream in the Applet.

rancher@centurix: The IconApplet _menuManager doesn't play well with AppletSettings configuration menu

---

cheaty@centurix/files/cheaty@centurix/applet.js
cheaty@centurix/files/cheaty@centurix/metadata.json
cheaty@centurix/files/cheaty@centurix/reload.sh

IconApplet's _menuManager property doesn't manage menus correctly when the applet has a right click context menu for configuration options. Left click the applet and then immediately right click can place Cinnamon in a weird state sometimes.

cheaty@centurix: Stop using the _menuManager in IconApplet as it doesn't play well with the configuration context menu

---

0dyseus@PopupTranslator/README.md
0dyseus@PopupTranslator/files/0dyseus@PopupTranslator/HELP.html
0dyseus@PopupTranslator/files/0dyseus@PopupTranslator/applet.js
0dyseus@PopupTranslator/files/0dyseus@PopupTranslator/metadata.json
0dyseus@PopupTranslator/files/0dyseus@PopupTranslator/po/0dyseus@PopupTranslator.pot
0dyseus@PopupTranslator/files/0dyseus@PopupTranslator/po/cs.po

Popup Translator (0dyseus@PopupTranslator) update

---

0dyseus@DesktopHandler/README.md
0dyseus@DesktopHandler/files/0dyseus@DesktopHandler/HELP.html
0dyseus@DesktopHandler/files/0dyseus@DesktopHandler/applet.js
0dyseus@DesktopHandler/files/0dyseus@DesktopHandler/metadata.json
0dyseus@DesktopHandler/files/0dyseus@DesktopHandler/po/0dyseus@DesktopHandler.pot

Desktop Handler (0dyseus@DesktopHandler) update

---

0dyseus@QuickMenu/README.md
0dyseus@QuickMenu/files/0dyseus@QuickMenu/HELP.html
0dyseus@QuickMenu/files/0dyseus@QuickMenu/applet.js
0dyseus@QuickMenu/files/0dyseus@QuickMenu/metadata.json
0dyseus@QuickMenu/files/0dyseus@QuickMenu/po/0dyseus@QuickMenu.pot

Quick Menu (0dyseus@QuickMenu) update

---

0dyseus@WallpaperChangerApplet/README.md
0dyseus@WallpaperChangerApplet/files/0dyseus@WallpaperChangerApplet/HELP.html
0dyseus@WallpaperChangerApplet/files/0dyseus@WallpaperChangerApplet/metadata.json
0dyseus@WallpaperChangerApplet/files/0dyseus@WallpaperChangerApplet/po/0dyseus@WallpaperChangerApplet.pot
0dyseus@WallpaperChangerApplet/files/0dyseus@WallpaperChangerApplet/po/cs.po

Wallpaper Changer (0dyseus@WallpaperChangerApplet) update

---

0dyseus@window-list-fork/README.md
0dyseus@window-list-fork/files/0dyseus@window-list-fork/2.8/applet.js
0dyseus@window-list-fork/files/0dyseus@window-list-fork/HELP.html
0dyseus@window-list-fork/files/0dyseus@window-list-fork/applet.js
0dyseus@window-list-fork/files/0dyseus@window-list-fork/metadata.json
0dyseus@window-list-fork/files/0dyseus@window-list-fork/po/0dyseus@window-list-fork.pot

Window list (Fork By Odyseus) (0dyseus@window-list-fork) update

---

0dyseus@SysmonitorByOrcus/README.md
0dyseus@SysmonitorByOrcus/files/0dyseus@SysmonitorByOrcus/HELP.html
0dyseus@SysmonitorByOrcus/files/0dyseus@SysmonitorByOrcus/applet.js
0dyseus@SysmonitorByOrcus/files/0dyseus@SysmonitorByOrcus/metadata.json
0dyseus@SysmonitorByOrcus/files/0dyseus@SysmonitorByOrcus/po/0dyseus@SysmonitorByOrcus.pot

System Monitor (Fork By Odyseus) (0dyseus@SysmonitorByOrcus) update

---

0dyseus@CustomCinnamonMenu/README.md
0dyseus@CustomCinnamonMenu/files/0dyseus@CustomCinnamonMenu/HELP.html
0dyseus@CustomCinnamonMenu/files/0dyseus@CustomCinnamonMenu/applet.js
0dyseus@CustomCinnamonMenu/files/0dyseus@CustomCinnamonMenu/metadata.json
0dyseus@CustomCinnamonMenu/files/0dyseus@CustomCinnamonMenu/po/0dyseus@CustomCinnamonMenu.pot
0dyseus@CustomCinnamonMenu/files/0dyseus@CustomCinnamonMenu/po/cs.po

Custom Cinnamon Menu (0dyseus@CustomCinnamonMenu) update

---

0dyseus@ExtensionsManager/README.md
0dyseus@ExtensionsManager/files/0dyseus@ExtensionsManager/HELP.html
0dyseus@ExtensionsManager/files/0dyseus@ExtensionsManager/applet.js
0dyseus@ExtensionsManager/files/0dyseus@ExtensionsManager/metadata.json
0dyseus@ExtensionsManager/files/0dyseus@ExtensionsManager/po/0dyseus@ExtensionsManager.pot
0dyseus@ExtensionsManager/files/0dyseus@ExtensionsManager/po/cs.po

Extensions Manager (0dyseus@ExtensionsManager) update

---

nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/CHANGELOG.md
nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/README.md
nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/applet.js
nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/changelog.txt
nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/metadata.json
nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/po/nvidiaprime.pot
nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/settings-schema.json

* Add checks that nvidia drivers and nvidia-settings are loaded
* Allow GPU temperature to be displayed in vertical panels but shorten (by removing the degree symbol) if over 100 degrees on vertical panels.
* Update nvidiaprime.pot to identify changes which need to be translated.

nvidiaprime@pdcurtis Update to Version 3.3.1

---

bumblebee@pdcurtis/files/bumblebee@pdcurtis/CHANGELOG.md
bumblebee@pdcurtis/files/bumblebee@pdcurtis/README.md
bumblebee@pdcurtis/files/bumblebee@pdcurtis/applet.js
bumblebee@pdcurtis/files/bumblebee@pdcurtis/changelog.txt
bumblebee@pdcurtis/files/bumblebee@pdcurtis/metadata.json
bumblebee@pdcurtis/files/bumblebee@pdcurtis/po/bumblebee.pot
bumblebee@pdcurtis/files/bumblebee@pdcurtis/settings-schema.json

* Allow GPU temperature to be displayed in vertical panels but shorten (by removing the degree symbol) if over 100 degrees on vertical panels.
* Update bumblebee.pot to identify changes which need to be translated

bumblebee@pdcurtis Update to Version 3.2.2

---

github-projects@morgan-design.com/files/github-projects@morgan-design.com/applet.js
github-projects@morgan-design.com/files/github-projects@morgan-design.com/po/de.po
github-projects@morgan-design.com/files/github-projects@morgan-design.com/po/github-projects.pot

* Repositories name doesn't need to be translated
* make title translatable
* use format instead of append. Not all languages do have the users name at the end. format replaces %s with the users name. This way the position of the users name is up to the translator
@jamesmorgan please check

github-projects@morgan-design.com: improve translations

---

placesCenter@scollins/files/placesCenter@scollins/applet.js

The in operator doesn't work like what supposed here, for an array, it refers to the index, not the value, also the true/false parameter for hide_applet_label functions were misplaced. This fixes #249
@collinss

places center: fix panel text not shown

---

collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/applet.js
collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/metadata.json

When indicator support was enabled in Cinnamon 3.4, the applet would freeze on expand.

collapsible-systray@feuerfuchs.eu: Fix issues with Cinnamon 3.4 + AppIndicators

---

hideable-applets@cardsurf/files/hideable-applets@cardsurf/applet.js

Added search for applet icons in: `~/.cinnamon/spices.cache/applet` and `/usr/share/cinnamon/applets` directories as mentioned [here](https://github.com/linuxmint/cinnamon-spices-applets/pull/910#issuecomment-309481745).

[hideable-applets@cardsurf] Search for applet icons in more directories

---

axos88@countdown-timer/files/axos88@countdown-timer/applet.js

```AppOptions``` is re-assigned on [line 297](https://github.com/jaszhix/applets/blob/ec78fdf16ac29d276746b1be2e992c0543aa45d4/axos88%40countdown-timer/files/axos88%40countdown-timer/applet.js#L297), this is a no-op in strict mode.
@axos88 
Closes #927

axos88@countdown-timer: Fix re-assignment of const AppOptions

---

multicore-sys-monitor@ccadeptic23/CHANGELOG_OLD.md
multicore-sys-monitor@ccadeptic23/README.md

This will help avoid confusion seen in the applet's comments and #935.

multicore-sys-monitor@ccadeptic23: Move the old unmaintained changelog to its own file, clean up readme grammar

---

timer-notifications@markbokil.com/files/timer-notifications@markbokil.com/applet.js
timer-notifications@markbokil.com/files/timer-notifications@markbokil.com/config.js

Instead of having the timers presets hardcoded in applet.js, now they are easily configurable in config.js, like this:
```
Timers: [
{ minutes: 240, label: '240 Minutes - 4 hours'},
{ minutes: 180, label: '180 Minutes - 3 hours'},
{ minutes: 120, label: '120 Minutes - 2 hours'},
90,
{ minutes: 60, label: '60 Minutes - 1 hour'},
45,
30,
{ minutes: 25, label: '25 Minutes - 1 Pomodoro'},
20,
15,
10,
5,
3,
1
]
```
@mbokil

timer-notifications@markbokil.com: Putting timer presets to config file

---

.github/ISSUE_TEMPLATE

This was in my original issue I opened about the issue template in #34. I think it is a basic thing issue templates should have, and makes it much easier to maintain applets. Issues are a chance for users to be a part of the development process, so I think it is fair to encourage including a little more info on Github.

Spices repo: Amend the issue template with a suggestion of adding debugging information

---

IcingTaskManager@json/CHANGELOG.md
IcingTaskManager@json/files/IcingTaskManager@json/appGroup.js
IcingTaskManager@json/files/IcingTaskManager@json/appList.js
IcingTaskManager@json/files/IcingTaskManager@json/metadata.json
IcingTaskManager@json/files/IcingTaskManager@json/specialMenus.js

* Fixed a bug preventing some apps, such as Transmission, from having their app button removed from the panel after they are closed.
* Fixed a couple warnings when windows are minimized through ITM.

Icing Task Manager: Update to 4.6.1

---

windowlist@cobinja.de/files/windowlist@cobinja.de/3.2/applet.js

This fixes a bug, where windows from different application like LibreOffice Writer and Calc were put on the same button.

[windowlist@cobinja.de] Fix LibreOffice (and possibly others) app association

---

sysmonitor@orcus/files/sysmonitor@orcus/metadata.json
sysmonitor@orcus/files/sysmonitor@orcus/providers.js

I have fixed #1008. The applet should now load properly when the function GTop.glibtop.get_netlist is not exposed through GObject introspection or is missing for some other reason.

sysmonitor@orcus: Fixed issue with a missing function in some distributions

---

feeds@jonbrettdev.wordpress.com/CHANGELOG
feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/ConfigFileManager.py
feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/metadata.json

Found that on 18.2 the applet will not create the default feeds.json config file if the data folder does not exist.

feeds@jonbrettdev.wordpress.com Resolved issue on mint 18.2 

---

bumblebee@pdcurtis/files/bumblebee@pdcurtis/CHANGELOG.md
bumblebee@pdcurtis/files/bumblebee@pdcurtis/applet.js
bumblebee@pdcurtis/files/bumblebee@pdcurtis/changelog.txt
bumblebee@pdcurtis/files/bumblebee@pdcurtis/metadata.json

* Change to the check that bumblebee is installed to use presence of optirun rather than bumblebeed. 
* This solves an issue raised by @Kickertom when the applet is used with LMDE (resolves #1136)

bumblebee@pdcurtis Update to Version 3.2.3

---

redshift@marvel4u/files/redshift@marvel4u/applet.js

@Marvel4U @Martin1887 
Following up on discussion in #1149, this sets the icon size to 24px due to a change in behavior on SVG symbolic icons in Cinnamon 3.6.

redshift@marvel4u: Ensure the icon size is 24px

---

redshift@marvel4u/files/redshift@marvel4u/applet.js

@Marvel4U @Martin1887 
This corrects #1170. I was only seeing the correct icon size when reloading the applet, but when re-adding it to the panel the issue persisted. The icon size has to be set whenever the icon changes. Tested against 3.4. Sorry!
By the way, I noticed tabs and spaces are getting mixed up in this file, that's why Github shows the indentation being off.

redshift@marv4u: Fix up #1170

---

.github/LICENSES/AGPL-3.0
.github/LICENSES/Apache-2.0
.github/LICENSES/CC0-1.0
.github/LICENSES/GPL-2.0
.github/LICENSES/GPL-3.0
.github/LICENSES/MIT
.github/LICENSES/README.md
TouchpadIndicatorClassic@lusito.info/info.json
devutils@fogl/info.json
multicore-sys-monitor@ccadeptic23/info.json
printers@linux-man/info.json
rwall@typicalfoobar/info.json
stackoverflow-questions-notifier@higuaro/info.json
timeout@narutrey/info.json

The LICENSE files are copied from here: https://choosealicense.com/licenses/
The license key in the applets was set respectively to the LICENSE file, which was stored in those applets.

[WIP] add LICENSES to repo and license key to info.json files

---

batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/CHANGELOG.md
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/applet.js
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/changelog.txt
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/metadata.json

Bug Fix for use with early versions of Cinnamon
* Inhibited use of hide_applet_label() to Cinnamon version 3.2 or higher in vertical panels.
* Corrected 'Icon Only' display mode

batterymonitor@pdcurtis Update to Version 1.3.1

---

bumblebee@pdcurtis/files/bumblebee@pdcurtis/CHANGELOG.md
bumblebee@pdcurtis/files/bumblebee@pdcurtis/applet.js
bumblebee@pdcurtis/files/bumblebee@pdcurtis/changelog.txt
bumblebee@pdcurtis/files/bumblebee@pdcurtis/metadata.json

Fix to allow use with early versions of Cinnamon
* Inhibit use of hide_applet_label() unless Cinnamon version 3.2 or higher in use.

bumblebee@pdcurtis Update to Version 3.2.4

---

nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/CHANGELOG.md
nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/applet.js
nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/changelog.txt
nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/metadata.json

Fix to allow use with early versions of Cinnamon
* Inhibit use of hide_applet_label() unless Cinnamon version 3.2 or higher in use.

nvidiaprime@pdcurtis Update to Version 3.3.3

---

stevedore@centurix/files/stevedore@centurix/applet.js
stevedore@centurix/files/stevedore@centurix/docker.js

@Centurix 
The TerminalReader import was removed from docker.js because it was
unused.

stevedore@centurix: Fix imports for Cinnamon 3.6

---

batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/CHANGELOG.md
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/README.md
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/applet.js
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/changelog.txt
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/metadata.json
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/batterymonitor.pot

* Add checks that sox and zenity are installed and warn that full facilities are not available without them.
* Improve handling of completely empty batteries.
* Update README.md, CHANGELOG.md and metadata.json
* Update batterymonitor.pot so translations can be updated.

batterymonitor@pdcurtis Update to Version 1.3.2

---

printers@linux-man/files/printers@linux-man/applet.js

Trying to fix a rare issue: out2.split(...)[1] is undefined.

printers@linux-man: Better default printer detection

---

netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/CHANGELOG.md
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/README.md
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/applet.js
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/changelog.txt
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/metadata.json
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/po/netusagemonitor.pot
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/settings-schema.json

* Add check that GTop library is installed using a try and catch(e) technique
* Remove some additional duplicate let declarations occurrences which could give difficulties in Cinnamon 3.4
* Changes to l10n translation support to bring ahead of GTop test.
* Update CHANGELOG.md, README.md, settings-schema.json and metadata.json
* Update netusagemonitor.pot so translations can be updated.

netusagemonitor@pdcurtis Update to Version 3.2.3

---

batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/CHANGELOG.md
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/applet.js
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/changelog.txt

* Change code showing as depreciated, and giving a harmless warning, in .xsession-errors.
Change too minor to justify a new version number

batterymonitor@pdcurtis Update Version 1.3.2

---

windowlist@cobinja.de/CHANGELOG.md
windowlist@cobinja.de/README.md
windowlist@cobinja.de/files/windowlist@cobinja.de/3.2/applet.js
windowlist@cobinja.de/files/windowlist@cobinja.de/3.2/settings-schema.json
windowlist@cobinja.de/files/windowlist@cobinja.de/po/de.po
windowlist@cobinja.de/files/windowlist@cobinja.de/po/windowlist@cobinja.de.pot

New Features
--
- Added pinning per workspace
- Add ability to only show windows that are present on the same monitor as the applet
- Shrink thumbnails when too many windows are open
Bugfixes
--
- Fix after StBoxLayout was switched to ClutterBoxLayout (Necessary on future versions of Cinnamon, won't break on Cinnamon 3.2)
- Fix some windows like Spotify not showing (Fixes #1230)
Various
--
- Update pot-file and German translation
- Added tooltips to some settings
- Use the new handleDragOut method to delete the drag placeholder (Will only work on future versions of Cinnamon, won't break on Cinnamon 3.2)

[windowlist@cobinja.de] Update to version 2.0

---

IcingTaskManager@json/CHANGELOG.md
IcingTaskManager@json/files/IcingTaskManager@json/3.2/appGroup.js
IcingTaskManager@json/files/IcingTaskManager@json/3.2/appList.js
IcingTaskManager@json/files/IcingTaskManager@json/3.2/applet.js
IcingTaskManager@json/files/IcingTaskManager@json/3.2/specialMenus.js
IcingTaskManager@json/files/IcingTaskManager@json/metadata.json

* Fixed cycling thumbnail menus via the hotkey not working.
* Fixed some apps indicating attention when they are first starting up.
* Fixed focused title display mode showing all button labels.
* Fixed app icon size preferences not being applied when labels are shown on buttons.
* Fixed empty thumbnails being added to the hover menu.
* Fixed labels not hiding when pinned apps are closed.

IcingTaskManager@json: 6.0.1

---

tracker@glebihan/files/tracker@glebihan/applet.js
tracker@glebihan/files/tracker@glebihan/po/de.po
tracker@glebihan/files/tracker@glebihan/po/tracker@glebihan.pot

Could someone test this... Some translation did not show up inside the applet, although I restart cinnamon after installing this translation via `./cinnamon-spices-makepot tracker@glebihan -i`.

tracker@glebihan: Prepare applet.js for translations, add pot file and de.po

---

feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/applet.js

@jake1164 The last one looks like it was a typo, but it also required me to reverse the logic of the conditional for it to work right (I think it worked before - imperfectly - because it was comparing undefined with whatever this.unread_count is, which will always evaluate to false, causing the unread count to be used no matter what). You know the code better than I do. Could you look this over and make sure I got everything right?

feeds applet: fix some warnings in .xsession-errors

---

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/3.4/applet.js
CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/metadata.json
CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/CinnVIIStarkMenu.pot

linter fixes:
* remove unused variables
* add missing semicolons
Make applet smarter and adapt to vertical panels: [upstream improvement](linuxmint/Cinnamon@3870e42#diff-d17569cee3da8241949ef0a60bc3f128)
use a generic clutter actor container to overlay vector box: [upstream fix](linuxmint/Cinnamon@1c513b2#diff-d17569cee3da8241949ef0a60bc3f128)
fix menu crash, if user has deleted default folder as Download, etc.
update .pot file

CinnVIIStarkMenu@NikoKrause: v1.13

---

radio@driglu4it/files/radio@driglu4it/applet.js

On Linux Mint 18.2 with moc 2.6-alpha1 the command "mocp -c -a -p [stream-url]" doesn't start the MOC-Server by default, it produces the message "FATAL_ERROR: The server is not running!"
Now before playing a stream, the applet will try to start the MOC-Server with "mocp -S"
@Driglu4it

radio@driglu4it: Make sure, MOC-Server is running before playing

---

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/DataProviders.js
multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/Graphs.js
multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json

Thanks to Pavel S for emailing the patch in af1175f, which fixes glibtop flooding the log with warnings.
- Fixed the network activity
- Fixed Spidermonkey warnings on network device change

multicore-sys-monitor@ccadeptic23: 1.7.2

---

temperature@fevimu/files/temperature@fevimu/applet.js
temperature@fevimu/files/temperature@fevimu/settings-schema.json

Hi, I created a setting to reduce the precision of the temperature. In my case, I found the value always changing a bit distractive. With this setting, only the integer part of the value is show for both Celsius and Fahrenheit (28 instead of 28.5).
I labeled the setting as "Show only integer part of temperature". I feel it is a bit geekish for public in general. I'm accepting better suggestions for this if the change is accepted.
@fevimu @NikoKrause

temperature@fevimu: Added setting to reduce precision

---

IcingTaskManager@json/.eslintrc.json
IcingTaskManager@json/CHANGELOG.md
IcingTaskManager@json/files/IcingTaskManager@json/3.4/appGroup.js
IcingTaskManager@json/files/IcingTaskManager@json/3.4/appList.js
IcingTaskManager@json/files/IcingTaskManager@json/3.4/applet.js
IcingTaskManager@json/files/IcingTaskManager@json/3.4/constants.js
IcingTaskManager@json/files/IcingTaskManager@json/3.4/settings-schema.json
IcingTaskManager@json/files/IcingTaskManager@json/3.4/specialMenus.js
IcingTaskManager@json/files/IcingTaskManager@json/3.4/store.js
IcingTaskManager@json/files/IcingTaskManager@json/3.4/stylesheet.css
IcingTaskManager@json/files/IcingTaskManager@json/3.4/utils.js
IcingTaskManager@json/files/IcingTaskManager@json/metadata.json
IcingTaskManager@json/files/IcingTaskManager@json/po/bg.po
IcingTaskManager@json/files/IcingTaskManager@json/po/da.po
IcingTaskManager@json/files/IcingTaskManager@json/po/de.po
IcingTaskManager@json/files/IcingTaskManager@json/po/default.pot
IcingTaskManager@json/files/IcingTaskManager@json/po/es.po
IcingTaskManager@json/files/IcingTaskManager@json/po/fr.po
IcingTaskManager@json/files/IcingTaskManager@json/po/he.po
IcingTaskManager@json/files/IcingTaskManager@json/po/hr.po
IcingTaskManager@json/files/IcingTaskManager@json/po/pl.po
IcingTaskManager@json/files/IcingTaskManager@json/po/ru.po
IcingTaskManager@json/files/IcingTaskManager@json/po/sv.po
IcingTaskManager@json/files/IcingTaskManager@json/po/tr.po
IcingTaskManager@json/files/IcingTaskManager@json/po/zh_CN.po

* Fixed windows from all workspaces showing, and added an option to show all workspaces.
- Also properly handles sticky windows that are marked as visible on all workspaces.
* Fixed per-monitor window mode not working correctly on the primary monitor.
- When toggling this setting, it will now take effect on all ITM instances.
* Fixed  pinning/unpinning apps in ungrouped app mode.
* Added an option to disable icons in the thumbnail menu.
* Added an option to scroll windows while hovering over an app's thumbnail menu.
* Added a transition duration override option for app buttons, and the option to a assign the checked pseudo class as an override.
* Added an option to show a "New Window" context menu item.
* Improved theme compatibility for the closed pinned app styling.
* Fixed multiple app …

IcingTaskManager@json: 6.2.0

---

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/fr.po

Hi,
In the french translation the name "Cinnamon" has been translated to "Cannelle", but since it's a proper name it shouldn't be translated.

CinnVIIStarkMenu: French description update

---

Cinnamenu@json/CHANGELOG.md
Cinnamenu@json/files/Cinnamenu@json/applet.js
Cinnamenu@json/files/Cinnamenu@json/metadata.json

Caused by the search text signal handler getting called when the ClutterText value switches back to hint text.
Closes #1567

Cinnamenu@json: Fix tooltips persisting after the menu is closed

---

color-picker@fmete/files/color-picker@fmete/applet.js

Closes https://github.com/linuxmint/cinnamon-spices-applets/issues/1578

color-picker@fmete: Use symbolic icon as default

---

temperature@fevimu/files/temperature@fevimu/applet.js

Fix only applies to ISA adapters and not the other sources of temperatures.

temperature@fevimu: Fixes where cores represented by 2 digits (e.g. Core 11) were not showing up in the results

---

hideable-applets@cardsurf/files/hideable-applets@cardsurf/applet.js
hideable-applets@cardsurf/files/hideable-applets@cardsurf/appletGui.js
hideable-applets@cardsurf/files/hideable-applets@cardsurf/files.js

- Fixed strict mode errors
- Fixed Glib warnings
- Switched applet over to new importer so it reloads correctly
@cardsurf

hideable-applets@cardsurf: Fix for Cinnamon 3.8

---

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/DataProviders.js
multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/use_old_nm.sh

Fixes #1616.
Makes the applet use either the `NetworkManager` and `NMClient` (as required for Linux Mint and older Fedoras) or just the `NM` (as required for newest Fedora) depending on which of those was previously loaded by Cinnamon. Loading both sets causes Cinnamon to crash.
The applets `vnstat@linuxmint.com`, `turbonote@iksws.com.br`, and `netusagemonitor@pdcurtis` will likely also need similar updates to become compatible with the newest Fedora. It is possible that even Linux Mint will move Cinnamon to using the newer `NM` library soon and thus these updates will be required even for Linux Mint.

Updates multicore-sys-monitor to work on Fedora

---

printers@linux-man/README.md
printers@linux-man/files/printers@linux-man/applet.js
printers@linux-man/files/printers@linux-man/metadata.json

A low-overhead way to make the applet partially usable at the multiple cases where DBus connection with Cups is lost.

printers@linux-man: Update when closing menu

---

calendar@simonwiles.net/files/calendar@simonwiles.net/applet.js

It more or less boils down to personal preference but I do think there's reasonable logic for this change:
bolding confuses the displayed times with the same level of importance as the date at the top of the applet and tugs the eyes in multiple directions in terms of where they're supposed to give focus.
Making the world times un-bold makes them stick out since they don't share the same style as the Date at the top and that the rest of the calendar likely doesn't share the same font size as the world times.
@simonwiles

[[Feature]] Display World Times in a Non-Bold Font Style – calendar@simonwiles.net

---

calendar@simonwiles.net/files/calendar@simonwiles.net/applet.js
calendar@simonwiles.net/files/calendar@simonwiles.net/settings-schema.json

Add to applet's setting the ability to assign a key command for drawing up the Applet via the keyboard:
Calling said key command will draw up the applet as if clicking on it.
@simonwiles

[[Feature]] Add Ability to Assign Key Command to Activate Applet Click Behavior – calendar@simonwiles.net

---

IcingTaskManager@json/files/IcingTaskManager@json/3.4/constants.js
IcingTaskManager@json/files/IcingTaskManager@json/3.4/utils.js

The Cinnamon 3.8 xlet importer fakes GJS module export compatibility by picking out modules from a file with regex, but it currently does not work if the declaration is on the very first line of the file. Internally it is taking these namespaces and adding them to the `exports` object, so it can be fixed by appending an exports assignment at the end of the file for scenarios like these.

Revert "IcingTaskManager@json: Fix exported variables (#1702)"

---

ScreenShot+RecordDesktop@tech71/README.md
ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/applet.js
ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/metadata.json

…
Same bug fixed in this applet as reported and fixed for Screenshot@tech71 - #1723 & #1727.
Also amended description slightly to reflect package names of dependencies rather than the command names.

Screenshot+Record Desktop@tech71 - fix icon resizing bug, allow multiple instances & clarify correct package names for dependencies.

---

netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/README.md

This is a holding action which adds warnings about issue #1647 to the README.md but makes no changes to the code to address the problem of the move from NMClient and NetworkManager libraries to NM in Fedora 27 at this point in time.
The changes required may take some time as I am going to be away without internet access for over a month. Assistance from those who have contributed to the changes on other applets would be welcome!

netusagemonitor@pdcurtis Update to version 3.2.4.1

---

vnstat@linuxmint.com/README.md

This is a holding action which adds warnings about issue #1647 to the README.md but makes no changes to the code to address the problem of the move from NMClient and NetworkManager libraries to NM in Fedora 27 at this point in time.
The original author of this applet was Clem but I made the most recent modifications in response to a bug which prevented it identifying the active device. The solution used code based on the code in netusagemonitor@pdcurtis so I feel responsible for eventually helping to sorti it out! In fact this is much simpler and shorter code so will be an ideal test of changes.

vnstat@linuxmint.com Update README.md only

---

vnstat@linuxmint.com/README.md
vnstat@linuxmint.com/files/vnstat@linuxmint.com/applet.js

This addresses issue #1647 where certain applet cannot be loaded on Fedora 27 (and possibly future versions of Linux Mint or other distros) due to the move from NMClient and NetworkManager libraries to NM.
* The version 2 fix uses the code for selecting the network manager for the multicore-sys-monitor@ccadeptic23 thanks to @jaszhix 
* A section has been added to README.md covering use on Distributions other than Mint and to note that @pdcurtis is currently providing support.
I have only been able to do a very basic checks on distributions other than Mint so I have initially marked this WIP in case anyone is prepared to check further on Fedora 27 or other Distros using the libnm library before it is merged.

vnstat@linuxmint.com Update to address issue 1647

---

netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/CHANGELOG.md
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/README.md
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/applet.js
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/changelog.txt
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/metadata.json

This addresses issue #1647 where certain applet cannot be loaded on Fedora 27 (and possibly future versions of Linux Mint or other distros) due to the move from NMClient and NetworkManager libraries to NM.
*  The fix uses the code for selecting the network manager for the multicore-sys-monitor@ccadeptic23 thanks to @jaszhix  
*  The use of xed has been changed to xdg-open to cover more distributions.
*  A section has been added to README.md covering use on Distributions other than Mint
I have only been able to do a very basic checks on distributions other than Mint so I have initially marked this WIP in case anyone is prepared to check further on Fedora 27 or other Distros using the libnm library before it is merged.

[WIP] netusagemonitor@pdcurtis Update to version 3.2.5

---

serviceLauncher@hulygun/files/serviceLauncher@hulygun/applet.js

Used a variable without declaration. This should not break older cinnamon versions (though I only tested with cinnamon 3.8).

[serviceLauncher@hulygun] Added fix for cinnamon 3.8

---

bash-sensors@pkkk/files/bash-sensors@pkkk/applet.js
bash-sensors@pkkk/files/bash-sensors@pkkk/po/bash-sensors@pkkk.pot
bash-sensors@pkkk/files/bash-sensors@pkkk/settings-schema.json

I wanted to have a custom tooltip for the bash-sensors@pkkk applet. Because I already touched the tooltip display I added the possibility to dynamically generate it.
I also noticed that the label is not automatically updated when the applet is (left-)clicked. This is fixed. Now it makes sense to add the option to disable the automatic updates, so that the label and tooltip only gets updated when the applet is clicked.
Is the pot file automatically updated?
- Refresh interval can be set to 0 to disable automatic updates (updates of the labels happen only if the applet is left-clicked).
- Tooltip can be dynamic using the output of a special command.
- Command output when left-clicking on the applet is trimmed on the right-hand side removing the trailing newline character which makes the …

bash-sensors@pkkk: Dynamic tooltips

---

vnstat@linuxmint.com/README.md
vnstat@linuxmint.com/files/vnstat@linuxmint.com/metadata.json
vnstat@linuxmint.com/info.json

* Changes author from none to @pdcurtis
* Adds a version number for convenience
* Minor edits to  README.md
Rationale for change in author:
* @pdcurtis has fixed all the issues since @clefebvre donated the applet
* Almost all the code is common to netusagemonitor@pdcurtis which also has the option of displaying vnstat output as part of  a more complex applet with alerts, actions and cumulative totals so most bug fixes will apply to both applets.

vnstat@linuxmint.com - Change author from none to pdcurtis

---

IcingTaskManager@json/CHANGELOG.md
IcingTaskManager@json/files/IcingTaskManager@json/3.4/applet.js
IcingTaskManager@json/files/IcingTaskManager@json/metadata.json

This reverts DND refactoring made in #1553. The original DND behavior was changed to ensure old, uninstalled apps in the favorites list got purged, but that should probably be attempted again later in a cleaner way.

IcingTaskManager@json: Fix DND

---

cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/settings-schema.json

This PR fixes an error with Cinnamon 3.6.7 with the applet Cryptocoin that causes the applet fails loading after Cinnamon restart when you have selected to not show the currency name or symbol:
* Install Cryptocoin applet
* Configure the applet option "Show Currency" to "None"
* Restart Cinnamon (`Ctrl + Alt + F2` write `r` and `enter`)
The applet fails loading with the next message on the log:
```
error t=2018-05-08T13:02:45Z this.settingsData[key].value is null
trace t=2018-05-08T13:02:45Z 
XletSettingsBase.prototype.bindWithObject@/usr/share/cinnamon/js/ui/settings.js:323:66
XletSettingsBase.prototype.bind@/usr/share/cinnamon/js/ui/settings.js:343:16
XletSettingsBase.prototype.bindProperty@/usr/share/cinnamon/js/ui/settings.js:362:16 …
```

[cryptocoin@guantanamoe] Fix 'value is null' error when no currency symbol or name is selected

---

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/3.4/applet.js

This made the buttons' vertical paddings to be different from the horizontal ones.
Let themes define the correct padding.
@NikoKrause

CinnVIIStarkMenu@NikoKrause: remove custom padding of favorite apps buttons

---

sysmonitor@orcus/files/sysmonitor@orcus/3.2/applet.js
sysmonitor@orcus/files/sysmonitor@orcus/3.2/graph.js
sysmonitor@orcus/files/sysmonitor@orcus/3.2/providers.js
sysmonitor@orcus/files/sysmonitor@orcus/3.2/settings-schema.json
sysmonitor@orcus/files/sysmonitor@orcus/metadata.json

I've fixed the rendering, where some lines were half pixel off and therefore a bit blurry. All graphs should now be pixel perfect.
I've also added an option to show decimal values in the tooltip for CPU usage, configurable in the applet settings. It closes  #1815.

Fixed rendering and added option to show decimal value in CPU usage.

---

IcingTaskManager@json/CHANGELOG.md
IcingTaskManager@json/files/IcingTaskManager@json/3.8/appGroup.js
IcingTaskManager@json/files/IcingTaskManager@json/3.8/specialMenus.js
IcingTaskManager@json/files/IcingTaskManager@json/metadata.json

* Fixed inability to see hover previews when thumbnails are disabled.
* Addressed an issue affecting apps that defer passing window metadata to Muffin, such as Spotify.

IcingTaskManager@json: 6.3.8

---

hideable-applets@cardsurf/files/hideable-applets@cardsurf/applet.js

Hide applets when panel edit mode is disabled in Cinnamon 3.8

[hideable-applets@cardsurf] Hide applets

---

redshift@marvel4u/files/redshift@marvel4u/applet.js

@Marvel4U This PR is for issue [1598.](https://github.com/linuxmint/cinnamon-spices-applets/issues/1598) I added logic that allows for the Brightness level to be remembered by whatever the user selected. Both the numeric value and the slider remember the setting. Also changed a "var" to "let".
If any of the code looks incorrect or needs to be changed, feel free to change whatever or let me know and I'll make adjusts accordingly.

Redshift: Fixed issue of Brightness level not being remembered.

---

download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js

Fixed an issue of not showing speed in bits in Cinnamon 3.8

[download-and-upload-speed@cardsurf] Show speed in bits

---

IcingTaskManager@json/files/IcingTaskManager@json/3.4/applet.js
IcingTaskManager@json/files/IcingTaskManager@json/3.8/applet.js

Adjusted for 3.4 and 3.8 branches of applet. PR accepted by applet
developer @jaszhix within the separate repo:
https://github.com/jaszhix/icingtaskmanager
Description:
When "Group apps" is activated and "Mouse wheel scroll behavior" is set
to "Cycle windows", scrolling over an app icon will now also present
the window if there exists only one window for the app icon.
Previously, only scrolling over icons that represented *multiple*
windows (grouped together) cycled through the app's existing windows,
presenting them (bringing them to foreground). If there was only one
window open, nothing happened upon scrolling on an icon, which is kind
of disruptive. You first had to move your finger and *click* the icon
to present the single window.
Now, scrolling an app's icon works the same on all …

IcingTaskManager@json: Present single window on scroll over app icon

---

Cinnamenu@json/CHANGELOG.md
Cinnamenu@json/files/Cinnamenu@json/applet.js
Cinnamenu@json/files/Cinnamenu@json/constants.js
Cinnamenu@json/files/Cinnamenu@json/metadata.json
Cinnamenu@json/files/Cinnamenu@json/settings-schema.json

* Lowered the minimum possible custom height to 360px.
* Lowered the minimum possible number of columns to 2.
* Reduced the widths of the columns so the menu is more compact.
Closes #1918, closes #1928

Cinnamenu@json: Support more compact layouts

---

mem-monitor-text@datanom.net/files/mem-monitor-text@datanom.net/applet.js
mem-monitor-text@datanom.net/files/mem-monitor-text@datanom.net/po/da.po
mem-monitor-text@datanom.net/files/mem-monitor-text@datanom.net/po/hr.po
mem-monitor-text@datanom.net/files/mem-monitor-text@datanom.net/po/mem-monitor-text@datanom.net.pot
mem-monitor-text@datanom.net/files/mem-monitor-text@datanom.net/po/sv.po
mem-monitor-text@datanom.net/files/mem-monitor-text@datanom.net/po/zh_CN.po
mem-monitor-text@datanom.net/files/mem-monitor-text@datanom.net/settings-schema.json

It really looks strange, that you've decided to remove prefix (in pr https://github.com/linuxmint/cinnamon-spices-applets/pull/1920) instead of adding the opportunity to customize (or just remove) prefix in applet settings (like we have in `cpu-monitor-text@gnemonix`).
**Related issue:** https://github.com/linuxmint/cinnamon-spices-applets/issues/1422
Sorry for weird diff. The second commit is just about using spaces instead of tabs. (https://github.com/linuxmint/cinnamon-spices-applets/pull/1936/commits/9d1c096d0bada41eebc6d142c56cee542f8075dd)

mem-monitor-text@datanom.net: add opportunity to customize label prefix

---

Cinnamenu@json/CHANGELOG.md
Cinnamenu@json/files/Cinnamenu@json/applet.js
Cinnamenu@json/files/Cinnamenu@json/buttons.js
Cinnamenu@json/files/Cinnamenu@json/metadata.json

This was caused by a regression in https://github.com/linuxmint/cinnamon-spices-applets/commit/57d7c4f2e4e03740289793e1f3e2cb9c8d185a37.
We actually do want to check for only null/undefined on `contextMenuIsOpen` because it stores the app index, which can be a falsey 0 value. This fixes up #1922 properly.
Closes #1958.

Cinnamenu@json: Fix being unable to select context menu options from the first app button in a group

---

temperature@fevimu/files/temperature@fevimu/applet.js

NaN was caused by division by zero while trying to calculate mean temp for all Packages/Cores. On my computer lm-sensors returns only 'CPU Temperature', no Package/Core temperatures.

temperature@fevimu: Resolved 'NaN' applet value when 'sensors' command returns no Package or Core temperature but shows 'CPU Temperature'

---

gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/applet.js

Passing context to the SignalManager constructor creates circular references, which makes memory management more complicated for the JS engine.
This is a fix for https://github.com/linuxmint/Cinnamon/pull/7868.
@Feuerfuchs

gpaste-reloaded@feuerfuchs.eu: Avoid passing xlet context to SignalManager

---

collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/applet.js

Passing context to the SignalManager constructor creates circular references, which makes memory management more complicated for the JS engine.
This is a fix for https://github.com/linuxmint/Cinnamon/pull/7868.
@Feuerfuchs

collapsible-systray@feuerfuchs.eu: Avoid passing xlet context to SignalManager

---

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/3.4/settings-schema.json

The desktop file for GNOME terminal in my system uses "utilities-terminal", not "terminal". That icon is not even in the hicolor theme nor in Adwaita on my system, so it is missing.

CinnVIIStarkMenu@NikoKrause: replace missing default terminal icon

---

bash-sensors@pkkk/files/bash-sensors@pkkk/applet.js

older Cinnamon versions do not have the setCustomStyleClass method and use actor.add_style_class_name instead

bash-sensors: fix stylesheet handling

---

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/ConfigSettings.js
multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/applet.js
multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json

- Fixes compatibility with cinnamon/new-panel-layout. This seems to be the only applet that attempted to assign to `this._panelHeight`, which is now a getter in ui/applet.
- Fixes the enabled state on devices not persisting after settings change.
Closes #2024

multicore-sys-monitor@ccadeptic23: 1.8.7

---

hwmonitor@sylfurd/files/hwmonitor@sylfurd/applet.js

Fixed an error where hwmonitor totally stoped working with Cinnamon 4.0.0
Example error :
```
[hwmonitor@sylfurd]: this.panel is null
[hwmonitor@sylfurd]: Failed to evaluate 'main' function on applet: hwmonitor@sylfurd/19
trace t=2018-11-07T10:40:08Z 
get _panelHeight@/usr/share/cinnamon/js/ui/applet.js:630:9
anonymous/GraphicalHWMonitorApplet.prototype._init@/home/d1ceward/.local/share/cinnamon/applets/hwmonitor@sylfurd/applet.js:80:9
GraphicalHWMonitorApplet@/home/d1ceward/.local/share/cinnamon/applets/hwmonitor@sylfurd/applet.js:58:5
main@/home/d1ceward/.local/share/cinnamon/applets/hwmonitor@sylfurd/applet.js:310:12
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:580:18
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:355:22 …
```

hwmonitor@sylfurd: Fixed this.panel is null

---

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js

Fixes an issue with the menu only opening on the primary monitor when activated with the Super key when only one instance is in use.

Cinnamenu: Fix multi-instance behavior

---

ShutdownApplet@DeathMD/files/ShutdownApplet@DeathMD/applet.js
ShutdownApplet@DeathMD/info.json

@jaszhix or @NikoKrause:
All of the commands, except 'log out', were not working. Fixed the broken commands. This PR should fix #1053. 
Also took ownership of this applet once I realized it was no longer being maintained.

Fixed broken commands in ShutdownApplet.

---

.gitignore
README.md
gulpfile.js
package-lock.json
package.json

This is adapted from the [same script](https://github.com/linuxmint/Cinnamon/commit/1dca47f323a38930e41dcdd32f2183eddbafd167) that was added to Cinnamon for the new panel layout PR. Previously I have been adding a similar script to applets I maintain individually, but it is easier and benefits more devs if it is available to use generically.
To use, install the [latest NodeJS LTS release](https://github.com/nodesource/distributions).
- Run `npm install -g gulp@^4.0.0`
- In the root of this repo's directory run `npm install`.
- To use the script, run ```gulp watch --uuid="<applet uuid>"```
For more info run ```gulp help```.

repo: Add a utility for reloading applets on code change

---

ShutdownApplet@shelley/files/ShutdownApplet@shelley/applet.js
ShutdownApplet@shelley/info.json

This is a fix for #1053. Fixed broken commands in applet. Removed Hibernate option since it requires swap to work correctly and would operate on a case-by-case basis for each user.
@jaszhix can you merge this whenever you have a moment? Thanks.

ShutdownApplet@shelley: Fixed broken commands

---

batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/CHANGELOG.md
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/applet.js
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/changelog.txt
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/metadata.json

* Use xdg-open in place of gedit or xed to allow use on more Linux distributions 
Closes #1985 as xdg-utils is available in all recent distributions that can support the Cinnamon Desktop

 batterymonitor@pdcurtis Update to version 1.3.3 

---

temperature@fevimu/files/temperature@fevimu/applet.js

Applet is supposed to find the temp from /proc or /sys if a reading isn't found from `sensors`, but it doesn't do this.

temperature@fevimu: Fix fall-back behavior when the temp can't be pulled from sensors

---

IcingTaskManager@json/CHANGELOG.md
IcingTaskManager@json/README.md
IcingTaskManager@json/files/IcingTaskManager@json/3.8/applet.js
IcingTaskManager@json/files/IcingTaskManager@json/3.8/settings-schema.json
IcingTaskManager@json/files/IcingTaskManager@json/metadata.json
IcingTaskManager@json/files/IcingTaskManager@json/po/bg.po
IcingTaskManager@json/files/IcingTaskManager@json/po/da.po
IcingTaskManager@json/files/IcingTaskManager@json/po/de.po
IcingTaskManager@json/files/IcingTaskManager@json/po/default.pot
IcingTaskManager@json/files/IcingTaskManager@json/po/es.po
IcingTaskManager@json/files/IcingTaskManager@json/po/fr.po
IcingTaskManager@json/files/IcingTaskManager@json/po/he.po
IcingTaskManager@json/files/IcingTaskManager@json/po/hr.po
IcingTaskManager@json/files/IcingTaskManager@json/po/hu.po
IcingTaskManager@json/files/IcingTaskManager@json/po/pl.po
IcingTaskManager@json/files/IcingTaskManager@json/po/ru.po
IcingTaskManager@json/files/IcingTaskManager@json/po/sv.po
IcingTaskManager@json/files/IcingTaskManager@json/po/tr.po
IcingTaskManager@json/files/IcingTaskManager@json/po/zh_CN.po

* Added a deprecation notice notification for Cinnamon 4.0 users.
* Added migration functionality for moving local pinned apps from ITM to Grouped Window List in Cinnamon 4.0. This can be accessed by clicking "Migrate Pinned Apps to Grouped Window List" from ITM's settings.

IcingTaskManager@json: Add migration functionality for moving pinned apps from ITM to GWL

---

ifstat@tagadan/files/ifstat@tagadan/applet.js

The applet changes sizes when network state is undefined, which is jarring. Changed it to show the empty arrows instead of nothing.

Make empty arrows appear if network state is undefined. (for  ifstat@tagadan)

---

vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/applet.js

VirtualBox changed their command line startup for VM images.
* Checks vbox major version
* Issues updated vboxmanage command for V6 and older --startvm for < V5
Fixes #2168 
@mockturtl 
@mhosse

Resolve VBox version and issue new startvm command

---

Cinnamenu@json/CHANGELOG.md
Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js
Cinnamenu@json/files/Cinnamenu@json/metadata.json

Cinnamenu: Fix "Add to desktop" context menu option

---

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/de.po

First translation was to literal, now it is more usual.
One off-topic suggestion: Why not set the default icon color in the case of updates to the Cinnamon Spices orange (like in icon.png) instead of blue?

SpicesUpdate@claudiux - refined German translation

---

SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/README.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/README.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/applet.js
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/fr.po
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/it.po

Hi @jaszhix,
This PR is an answer to the feature request #2213.
When new Spices are available, an option _Forget new Spices_ appears in the menu of this applet. Clicking it will clear these notifications of new spices, until others arrive.
French and Spanish translations: fr.po and es.po are updated.
Italian translation (new!): it.po.
SpicesUpdate@claudiux.pot updated.
Best regards.
Claudiux

SpicesUpdate@claudiux v1.1.1: Solves FR #2213

---

SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/README.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/README.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/applet.js
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json

Hi @jaszhix,
The `symbola` TrueType font is required to display certain characters in the menu of this applet. This has been added in the dependencies, because on Arch this font is not installed by default.
This PR also fixes #2219.
Can you merge this branch into your master one, please?
Best regards.
Claudiux

SpicesUpdate@claudiux: v1.1.3 Added dependency: Presence of symbola ttf. Fixes #2219.

---

Cinnamenu@json/CHANGELOG.md
Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js
Cinnamenu@json/files/Cinnamenu@json/metadata.json

Depends on https://github.com/linuxmint/Cinnamon/pull/8278
Cinnamon's docinfo module provides caching and sorting out of the box, among other performance improvements. From the PR comment:
>  - Results are limited to 20 (with RecentManager you can get a huge number of results)
>  - Results are sorted by timestamp (they're not sorted by RecentManager)
>  - Sorting and clamping of the results is done in C and only the 20 most recent results are stored in memory
>  - The "changed" signal sent by DocSystem is delayed via idle_timeout, so your applet doesn't rebuild immediately when Gtk.RecentManager sends its signal (which could potentially reduce the speed at which apps are launched)
>  - DocInfo provides decoded URIs and the ability to quickly create the icon so your applet doesn't need to …

Cinnamenu@json: Replace Gtk.RecentManager with docinfo

---

feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/applet.js
feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/check_feedparser.py

Provide a dependency check and install for Python's feedparser. Applet should work out of the box from now.

feeds@jonbrettdev: Add a dependency check and install for Python feedparser

---

SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/applet.js

Hi @jaszhix,
To do not flood the notifications area, the old ones concerning Spices Update are removed when the Refresh button is pressed, and new notifications arrive.
Best regards.
Claudiux

SpicesUpdate@claudiux: v2.0.1 - Delete old notifications when a new one arrives.

---

weather@mockturtl/README.md
weather@mockturtl/files/weather@mockturtl/3.6/applet.js
weather@mockturtl/files/weather@mockturtl/3.6/metadata.json
weather@mockturtl/files/weather@mockturtl/3.6/settings-schema.json
weather@mockturtl/files/weather@mockturtl/3.8/applet.js
weather@mockturtl/files/weather@mockturtl/3.8/darkSky.js
weather@mockturtl/files/weather@mockturtl/3.8/ipApi.js
weather@mockturtl/files/weather@mockturtl/3.8/openWeatherMap.js
weather@mockturtl/files/weather@mockturtl/3.8/stylesheet.css
weather@mockturtl/files/weather@mockturtl/metadata.json

Don't know how to do the versioning anymore.
**3.6**
* OpenWeatherMap using FOSS key and proper daily forecasts.
**3.8**
* Removed "require"-s, swapped them to imports
* Fixed bug when Cinnamon froze when the taskbar was manipulated when the applet was enabled on it.
* DarkSky was Getting the Forecast day names from sunrise time, fixed
* Humidity is rounded now.
* Location element is a button again, opens Data services webpages with more weather, or it can trigger a refresh if there was an error (there is no need anymore, but still).
@jaszhix Please check the readme on the Compatibility section, is that right?
I don't quite get it how the versioning works.
Basically from Cinnamon v3.2-3.6 the 3.6 folder is used, and Cinnamon v3.8< the 3.8 folder is used?
Right now 3.6 could support all …

Weather@mockturtl Update 2.1.2

---

weather@mockturtl/files/weather@mockturtl/3.8/applet.js
weather@mockturtl/files/weather@mockturtl/3.8/darkSky.js
weather@mockturtl/files/weather@mockturtl/metadata.json
weather@mockturtl/files/weather@mockturtl/po/hu.po
weather@mockturtl/files/weather@mockturtl/po/weather@mockturtl.pot

version 3.8 fixes:
* DarkSky short conditions contained words like 'and', 'until' at the end (used wrong function), this is now fixed
* Day names are now properly translated
* Update Translation template

weather@mockturtl Update 2.1.5

---

cinnamon-timer@jake1164/README.md
cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/3.4/applet.js
cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/3.4/settings-schema.json
cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/metadata.json
cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/po/cinnamon-timer@jake1164.pot

I always wanted to know the time, when the time will finish. I added this with this pull request. It is even possible to format the alarm time. Because some of the alarm times will be in the far future, I believe it's not necessary to show too much detail, hence two time formats can be specified.
I also changed the order of the default Preset Times to be strictly in descending order (the defaults of 2 and 3 hours were in the wrong order).
I still have one question: Is it possible to add a link in the label of a setting? It would be great to point the user to the website with the available format specifiers. At the moment this is included in the tooltip, but that is far from ideal.

Display the alarm time in menu and panel

---

sysmonitor@orcus/CHANGELOG.md
sysmonitor@orcus/files/sysmonitor@orcus/3.0/applet.js
sysmonitor@orcus/files/sysmonitor@orcus/3.0/graph.js
sysmonitor@orcus/files/sysmonitor@orcus/3.0/providers.js
sysmonitor@orcus/files/sysmonitor@orcus/3.0/settings-schema.json
sysmonitor@orcus/files/sysmonitor@orcus/3.2/applet.js
sysmonitor@orcus/files/sysmonitor@orcus/3.2/graph.js
sysmonitor@orcus/files/sysmonitor@orcus/3.2/providers.js
sysmonitor@orcus/files/sysmonitor@orcus/3.2/settings-schema.json
sysmonitor@orcus/files/sysmonitor@orcus/metadata.json

I've fixed the memory leak caused by garbage collector not destroying cairo surfaces automatically (fixes #2253). I've also simplified the rendering by using only one drawing area for all graphs now and backported the changes to the applet version 3.0.

sysmonitor@orcus: Fixed memory leak and optimized rendering

---

cryptocoin@guantanamoe/README.md

@philtyl
This PR just replaces the Getting Started section of the readme with instructions of how to install the current applet version hosted on Cinnamon Spices rather than from the author's original repo. 
Prompted by this forum thread documenting an attempt to install the applet https://forums.linuxmint.com/viewtopic.php?f=90&t=288713

cryptocoin@guantanamoe - fix install instructions for Spices hosted version

---

windowlist@cobinja.de/files/windowlist@cobinja.de/4.0/applet.js

This improves performance when opening the context menu by only fetching monitor names when the monitor configuration is actually changed

windowlist@cobinja.de Improve performance for monitor names

---

netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/3.2/CHANGELOG.md
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/3.2/README.md
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/3.2/applet.js
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/3.2/settings-schema.json
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/4.0/CHANGELOG.md
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/4.0/README.md
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/4.0/applet.js
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/4.0/settings-schema.json
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/4.0/stylesheet.css
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/CHANGELOG.md
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/README.md
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/applet.js
netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/metadata.json

* Further enhancement in styles to match Cinnamon 4.0
* Change selection of audible warning to use soundfilechooser widget in settings-schema.json for 3.2 and 4.0
* Correct code for style .numa-not-connected in applet.js

netusagemonitor@pdcurtis v 3.3.0 Enhancements to stylesheets and alert sound selection

---

calendar@simonwiles.net/files/calendar@simonwiles.net/applet.js

This change introduces honoring of the system clock settings 'use-24h' and 'show-seconds'. The changes are ported back from the current version of the system's calendar applet, see:
https://github.com/linuxmint/cinnamon/tree/ec6fb27452da571142bd39fccd8dbb5c64c066c6/files/usr/share/cinnamon/applets/calendar%40cinnamon.org
I usually don't code in JavaScript, so please someone have a quick look at the code for anti-patterns and such.
@simonwiles Thanks for the applet! Would you have a look at proposed changes and approve them if you agree?

 [calendar@simonwiles.net] Adds feature to let the applet check and apply system clock setting 'use-24h' and 'show-seconds'

---

gmail@lauritsriple/README.md

@lauritsriple 
Readme.md
Added alternative guidance for installing the dependencies via apt on Linux Mint.
Noted requirement for an app password if google account is set up with 2 factor-authentication.

gmail@lauritsriple - update readme with better instructions for set up on Mint Cinnamon

---

cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/applet.js

The value is not formatted if `Show currency` is set to `name`.
Values like `1234.5` are show as `1234.5 USD` instead of `1,234.50 USD`.

fix for unformated value

---

Cinnamenu@json/files/Cinnamenu@json/metadata.json
multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json
temperature@fevimu/files/temperature@fevimu/metadata.json

Version and Cinnamon Version bump for:
* multicore-sys-monitor
* Cinnamenu
* CPU Temperature indicator
All work the same under 4.2, only added 4.2 to the supported versions array in the metadata.

Compatibility with cinnamon 4.2

---

cpu-monitor-text@gnemonix/files/cpu-monitor-text@gnemonix/applet.js

In solution to #2462 Changes the width to the right of the applet to be more reasonable leaving less dead space. It still adapts to the max percentage length, there is just less buffer. It was 3.5em and is now 1.5em.
Old:
New:
I am sort of new to this using github pullrequests so let me know if I did anything wrong.

edited width of cpu-monitor-text@gnemonix

---

cpu-monitor-text@gnemonix/files/cpu-monitor-text@gnemonix/applet.js

Changelist:
- Fixed a bug where the width of the label of cpu monitor had a space at the beginning which pushed it outside the visual box of the applet.
@gnemonix
As it was, the label for the CPU monitor applet had an extra two white spaces that were making it override other applets, I simply removed those whitespaces and set the min-width to be more consistent with for example _[mem-monitor-text@datanom.net](https://github.com/linuxmint/cinnamon-spices-applets/tree/master/mem-monitor-text%40datanom.net)_

cpu-monitor-text@gnemonix: Fixed width of cpu monitor label

---

SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/README.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/applet.js
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/help/en/README.html
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/help/en/README.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/help/fr/README.html
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/help/fr/README.md

Hi @brownsr,
This version of SpicesUpdate@claudiux adds a Help button in its menu; this help (in html) can be translated and is loaded into the preferred browser.
A French translation of this help is available.
Other improvement: When only one Spice (by category: Applets, Desklets, ...) needs an update, its icon appears into the notification messages.
Best regards.
Claudiux

[SpicesUpdate@claudiux] v2.2.0

---

hwmonitor@sylfurd/files/hwmonitor@sylfurd/po/fr.po

New! This is the French translation for the last version of the Graphical hardware monitor applet.
@Hultan Here the pot file used to make this fr.po file. You can use it for a next PR, after rewriting the header.
[hwmonitor@sylfurd.pot.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/3464439/hwmonitor%40sylfurd.pot.zip)

[hwmonitor@sylfurd] French translation - fr.po

---

shutdown-timer@webum.by/files/shutdown-timer@webum.by/applet.js

dBus commands don't work on Debian Testing.
Replacing suspend/hibernate/reboot/shutdown with corresponding systemctl commands, this applet works on Debian. Lock-Screen still doesn't work (I don't know which dbus command is necessary).
@maintainers: I cannot verify if this works on Mint. According to https://forums.linuxmint.com/viewtopic.php?t=235654 , it should be necessary to change this applet for Mint as well.
Signed-off-by: Benjamin Aigner <aignerb@technikum-wien.at>

Replaced dbus commands by systemctl

---

SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/applet.js
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json

Hi @brownsr,
This version of SpicesUpdate@claudiux bypasses all caches to obtain the latest version of json files containing Spices data. This gives more responsiveness and more reliability to this applet.
Best regards.
Claudiux

[SpicesUpdate@claudiux] v2.3.0 - Bypass all caches downloading json files

---

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/2.8/applet.js

Fixes #2545. Just a typo that made this applet unusable with Cinnamon 2.8 to 3.6!
Hi @brownsr,
Best regards.
Claudiux

[SpicesUpdate@claudiux] Fixes #2545 (Cinnamon 2.8 to 3.6)

---

placesCenter@scollins/README.md
placesCenter@scollins/files/placesCenter@scollins/applet.js

@collinss 
Hi Stephen,
I propose this small change that improves the Recent Documents part of your applet.
A click on a recent doc opens it, as usual. A right-click opens the folder that contains this doc.
Regards.
Claudiux

[placesCenter@scollins] Now right-click on a recent document opens the forder containing it

---

placesCenter@scollins/files/placesCenter@scollins/applet.js
placesCenter@scollins/files/placesCenter@scollins/po/fr.po
placesCenter@scollins/files/placesCenter@scollins/po/placesCenter@scollins.pot
placesCenter@scollins/files/placesCenter@scollins/settings-schema.json

@collinss 
Hi Stephen,
I propose an option to show an help message about the Recent Files section (default value: true).
I did this because I manage the computers of several old people and some of them told me that they would not easily remember the use of the right click.
I also updated the .pot and fr.po. files
Best regards.
Claudiux

[placesCenter@scollins] Shows help in tooltip about Right click on a Recent File

---

placesCenter@scollins/files/placesCenter@scollins/applet.js
placesCenter@scollins/files/placesCenter@scollins/po/fr.po
placesCenter@scollins/files/placesCenter@scollins/po/placesCenter@scollins.pot
placesCenter@scollins/files/placesCenter@scollins/settings-schema.json

@collinss 
Hello Stephen,
I propose you some improvements to the Recent Files section.
1. No more files without an icon!
2. Whenever possible, replace the mime type icon with the icon of the last application that opened the file.
3. Do not show deleted files.
4. Do not show the Clear button when the list is empty.
5. Use default recentManager instead of a new recentManager, to be synchronized with  the `menu@cinnamon.org` applet.
6. In settings:
* the type of the `recentSizeLimit` parameter becomes `combobox` to avoid to call 10 times the `buildRecentDocumentsSection()` method when the user wants to display 10 more files in the Recent Files section.
* a new button appears, to open the Privacy window of Cinnamon Settings.
To see the differences:
1. Example of Recent Files section in …

placesCenter@scollins: Improvement of Recent Files section

---

SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/README.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/2.8/applet.js
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/3.8/applet.js
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/3.8/stylesheet.css
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.2/applet.js
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.2/stylesheet.css
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/help/en/README.html
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/help/en/README.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/help/fr/README.html
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/help/fr/README.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json

Hi @brownsr,
This version 4.0.2 of Spices Update removes unnecessary notifications like '(Refresh to see the description)' and have some minor CSS changes.
Can you merge this branch into your master one, please?
Best regards.
Claudiux

[SpicesUpdate@claudiux] v4.0.2 - Removes unnecessary notifications

---

SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/README.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/2.8/applet.js
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/3.8/applet.js
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.2/applet.js
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.2/constants.js
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.2/settings-schema.json
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/help/en/README.html
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/help/en/README.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/help/fr/README.html
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/help/fr/README.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/icons/spices-update-anim-symbolic.svg
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json

Hi @brownsr,
Now this applet allows users to renew the download of the latest version of a Spice (only with Cinnamon 4.2 and following).
EDIT: Now, the icon of this applet is animated during refresh.
Minor bugs have been fixed.
The .pot, fr.po and help files have been updated.
Best regards.
Claudiux

[SpicesUpdate@claudiux] v4.2.0 - Animated icon during refresh - Can renew the download of Spices (Cin. 4.2 and followings)

---

weather@mockturtl/files/weather@mockturtl/3.0/applet.js
weather@mockturtl/files/weather@mockturtl/3.0/darkSky.js
weather@mockturtl/files/weather@mockturtl/3.0/ipApi.js
weather@mockturtl/files/weather@mockturtl/3.0/openWeatherMap.js
weather@mockturtl/files/weather@mockturtl/3.8/applet.js
weather@mockturtl/files/weather@mockturtl/3.8/darkSky.js
weather@mockturtl/files/weather@mockturtl/metadata.json
weather@mockturtl/files/weather@mockturtl/po/fr.po
weather@mockturtl/src/applet.ts
weather@mockturtl/src/darkSky.ts

Opened Because https://github.com/linuxmint/cinnamon-spices-applets/issues/2603
Fixes: 
* DarkSky Conditions logic was inverted, it filtered out almost every word.
* SystemLanguage string was processed incorrectly (split by the wrong char)
* Updating French Translation to include Today and Tomorrow
The Rest of the changes are due to using new version of Typescript to build:
* Have to explicitly declare object what are used with for...in loops
* Async generator changed by them (version 3.0)

weather@mockturtl update 2.3.1 - Hotfixes

---

cpu-monitor-text@gnemonix/files/cpu-monitor-text@gnemonix/applet.js

After hibernating gtop resets its counter causing the delta to be negative for quite some while. Instead we update the last total on every iteration.
This fixes the cpu percentage not updating for a long time after hibernation.
This is in relation to issue #1744

Fix percentage not updating after hibernation

---

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/de.po

Hi claudiux,
even if I have to make a new Pot file - I think the forced reinstall of a spice is handled a bit illogical.
Why do I have to check the first box if I just want to repair/reinstall a spice? Perhaps I don't want it to be checked regularly? So I think checking the second box should be enough. What do you think?
Kind regards

SpicesUpdate@claudiux - Update de.po

---

sshlauncher@sumo/files/sshlauncher@sumo/applet.js

@sumo 
This PR removes noisy messages in `~/.xsession-errors`, using `Util.spawnCommandLine` instead of `Main.Util.spawnCommandLine`.
Best regards.
Claudiux

sshlauncher@sumo: Removes noisy messages in ~/.xsession-errors

---

radio@driglu4it/files/radio@driglu4it/applet.js

@brownsr 
This PR removes noisy messages in `~/.xsession-errors`, using `Util.spawnCommandLine` instead of `Main.Util.spawnCommandLine`.
The author of this applet seems inactive on Github since February 2019.
Best regards.
Claudiux

radio@driglu4it: Removes noisy messages in ~/.xsession-errors

---

hwmonitor@sylfurd/README.md

The link to issues was pointing to the "generic" issues page of the 'cinnamon-spices-applets' project. It makes life a bit easier when the same filter is applied as in the [Graphical hardware monitor project page](https://cinnamon-spices.linuxmint.com/applets/view/12)

README.md: Update link to hwmonitor@sylfurd issues

---

vpnLookOut@claudiux/files/vpnLookOut@claudiux/3.8/settings-schema.json

For Cinnamon 3.8+:
* Removes "dependency" option of "clientsList" (bug in Cinnamon 4.2).
* Changes all "checkbox" types to "switch".

[vpnLookOut] Update settings-schema.json - Bugfixes for Cinnamon 4.2

---

cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/2.6/applet.js
cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/3.4/applet.js

Hi @jake1164,
This PR removes noisy messages in `~/.xsession-errors`, such as: `TypeError: this._notification is null`.
Best regards.
Claudiux

[cinnamon-timer@jake1164] Remove noisy messages in .xsession-errors

---

sshlauncher@sumo/files/sshlauncher@sumo/applet.js

Hi @sumo,
This PR removes noisy messages  in `~/.xsession-errors` such as:
- `Cjs-Message: 13:44:51.265: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function 42]: reference to undefined property "_customCommand"`
- `Terminal opened with command...`. These latest messages can be displayed creating a DEBUG file in the same directory of the applet.js file (useful for developers).

[sshlauncher@sumo] Removes noisy messages in .xsession-errors

---

SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.2/constants.js
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/cs/4.2/bin/SUExtensionCore.py
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/cs/4.2/cinnamon-settings.py
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/cs/4.2/modules/cs_applets.py
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/cs/4.2/modules/cs_desklets.py
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/cs/4.2/modules/cs_extensions.py
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/cs/4.2/modules/cs_themes.py
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/cs/4.4/bin/SUExtensionCore.py
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/cs/4.4/cinnamon-settings.py
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/cs/4.4/modules/cs_applets.py
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/cs/4.4/modules/cs_desklets.py
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/cs/4.4/modules/cs_extensions.py
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/cs/4.4/modules/cs_themes.py
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json

Hi @brownsr,
This PR fixes a problem on Arch, which uses Python 3.8, making Spices Update unusable.
~~Work in progress. Do not merge now, please.~~
EDIT: The issue https://github.com/linuxmint/cinnamon/issues/8956 is not closed by this PR, but should be closed by https://github.com/linuxmint/cinnamon/issues/8959.
Best regards.
Claudiux

[SpicesUpdate] v5.1.1: Now compatible with Python 3.8 (used on Arch)

---

collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/metadata.json
multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json
weather@mockturtl/files/weather@mockturtl/metadata.json

I did this 1 month ago to prepare for the next version, then decided to write _4.3_ into the array.
I must be retarded.
Resolves this: https://github.com/linuxmint/cinnamon-spices-applets/issues/2698
Edit:
I Include some other Applets as well, as they work on 4.4

Update compatibility for 4.4

---

mem-monitor-text@datanom.net/files/mem-monitor-text@datanom.net/applet.js
mem-monitor-text@datanom.net/files/mem-monitor-text@datanom.net/settings-schema.json

My laptop has very little RAM (4Gb) I if I don't watch my browser tabs I end up with the system crashing on low memory. 
So I made this simple addition that the spice text start flashing red when the RAM usage is above a threshold specified in the spice settings. By default the feature is disabled. 
Have a nice day,
Luca

mem-monitor-text: added warning on wigh memory usage

---

turn-off-monitor@zablotski/files/turn-off-monitor@zablotski/applet.js
turn-off-monitor@zablotski/files/turn-off-monitor@zablotski/disable_mouse.sh
turn-off-monitor@zablotski/files/turn-off-monitor@zablotski/enable_mouse.sh
turn-off-monitor@zablotski/files/turn-off-monitor@zablotski/metadata.json
turn-off-monitor@zablotski/files/turn-off-monitor@zablotski/po/fr.po
turn-off-monitor@zablotski/files/turn-off-monitor@zablotski/po/turn-off-monitor@zablotski.pot
turn-off-monitor@zablotski/files/turn-off-monitor@zablotski/settings-schema.json

Hi @brownsr,
This PR closes #2719, adding some settings to prevent the monitor turning on too soon after turning off. Also, I added a keybinding management and fixed some bugs (this applet did not work with certain mouse).
The author of this applet, @zablotski, is inactive on Github since at least one year.
Best regards.
Claudiux

[turn-off-monitor@zablotski] Turn Off Monitor v2.0.0: Add Settings

---

cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/applet.js
cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/settings-schema.json

To refresh the countervalue of a ticker, calls are made every 5 seconds
to the cryptocompare API, which can lead to reaching the API rate free
tier limit.
To avoid that, a configuration field has been added to set a custom
interval and reduce the frequency of calls made to the API.
This configuration field default value is set to 5 seconds to avoid
behavior change.

cryptocoin@guantanamoe Add rates update interval configuration

---

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json

Hi @brownsr,
Just a minor change. Some users IRL told me that they were surprised that the version number displayed did not match that announced on the web page or in CHANGELOG.
Happy New Year!

[SpicesUpdate@claudiux] Update metadata.json: corrected version number: 5.2.1

---

SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/cs/4.2/bin/SUExtensionCore.py
SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json

@brownsr 
Hi Simon,
Minor change to bring Spices Update into line with [this mtwebster commit](https://github.com/linuxmint/cinnamon/commit/d57677b5ae306115139be98be62e3fb7cc6a27a8#diff-c4641b580bb45b188c5ae94c7f7a33cf).
Kind regards
Claudiux

v5.2.2 - Cinnamon 4.2: Let Gtk determine the right size of dialog window

---

sshlauncher@sumo/files/sshlauncher@sumo/applet.js
sshlauncher@sumo/files/sshlauncher@sumo/metadata.json

Changes:
* Fixes symbolic icon setting (my fuckup), now it actually sets as symbolic.
* Makes terminal argument handing a bit more bulletproof.
@sumo 
Let me know if there is anything I need to change.
I tried to show notifications on ssh errors on exiting, but its more complicated as I thought. :( I can only get terminal's status code and message, not what goes on inside the terminal even tough that's the only process keeping alive the terminal.

sshlauncher@sumo update 

---

ipindicator@matus.benko@gmail.com/README.md
ipindicator@matus.benko@gmail.com/files/ipindicator@matus.benko@gmail.com/applet.js
ipindicator@matus.benko@gmail.com/files/ipindicator@matus.benko@gmail.com/metadata.json

@PrimaMateria 
Primary change here is updating the endpoints the _services array includes. Two of the endpoints no longer exist so I replaced them with what seem like acceptable  alternatives.
Services removed:
http://geoip.nekudo.com/api/
-- Returns: 301 Moved Permanently
-- Migrated to ipapi.com and became a paid service
-- https://github.com/nekudocom/shiny_geoip
http://ip-json.rhcloud.com/json
-- rhcloud.com "301 Moved Permanently" to openshift. No longer appears to have ip address API
IP services added:
https://myexternalip.com/json
https://icanhazip.com
Looking at files changed shows changes to many lines because there was a mix of tabs and spaces being used for indentation. I standardized around spaces only because it's my preference, but tabs are fine too. Really only matters that …

IP Indicator: Update IP address API endpoints

---

temperature@fevimu/files/temperature@fevimu/po/de.po

@claudiux: This PR adds the last missing strings (German.po file didn't have all strings from pot file) to the German translation of the temperature applet

temperature@fevimu - Added missing translations to German translation

---

feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/applet.js

There are still two instances of Python version 2 in the applet.js code,
one of which is functional (calls `python` instead of `python3`), one is
only informational. Fix both.

fix missing python(2) appearances in feeds spice

---

feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/applet.js

Hi @brownsr,
Since #2891, each time this applet is started, a window appears indicating that a package is already installed. This PR fixes this bug.
Kind regards.
Claudiux

[feeds@jonbrettdev.wordpress.com] - Fixes a bug from #2891

---

feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/feedreader.js

Another two missing replacements of python -> python3, otherwise the
feedparser does not work on systems where python(2) is in the state of purge.

more python -> python3 fixes for the feedparser

---

cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/applet.js

cryptocompare.com seem to have changed their limits for number of api calls/month.
Currently the applet does one call every 5 seconds.
This makes the applet stop functioning after the quota is reached.
Change the value to make one call every 30 seconds to avoid hitting the limit and keep the applet working.

Lower number of API calls to data provider

---

windowlist@cobinja.de/CHANGELOG.md
windowlist@cobinja.de/files/windowlist@cobinja.de/4.0/applet.js
windowlist@cobinja.de/files/windowlist@cobinja.de/4.0/stylesheet.css

This switches styling to the one also used by the builtin window list and adds a flashing effect for attention-seeking windows for better theme integration.

windowlist@cobinja Switch styling to builtin grouped window list

---

windowlist@cobinja.de/CHANGELOG.md
windowlist@cobinja.de/README.md
windowlist@cobinja.de/files/windowlist@cobinja.de/4.0/applet.js

This adds support for launching actions declared in applications' desktop files
and support for places in nemo's context menu
https://github.com/Cobinja/CobiWindowList/issues/33

windowlist@cobinja.de Add support for desktop file actions

---

calendar@simonwiles.net/files/calendar@simonwiles.net/applet.js
calendar@simonwiles.net/files/calendar@simonwiles.net/world_clock_calendar_settings.py

The settings app for world calendar is built on python2, and is therefore obsolete which needs to modified to use python3.

world calendar is broken because uses python2 instead of python3

---

sound150@claudiux/files/sound150@claudiux/3.4/applet.js

Hi I use linux mint as my distro, and recently I started writing a music script when I realized that the cover art of music on sound applet was missing, so I tried fix by myself, its a little hard for me understand the code but I did it, sorry if I open this pull request just update one line of code, my skills with Gobject are weak yet.
This little fix just only update the url because spotify does not show cover art anymore by the old url.
**Additional notes:**
On old mode the artUrl could return a link like this for example: https://open.spotify.com/image/ab67616d00001e027ca89320e10bdc2bd343cdee and no image is returned.
Now with the change return something like this: https://i.scdn.co/image/ab67616d00001e027ca89320e10bdc2bd343cdee.
Ref to …

Fix missing images for Spotify Player

---

ShutdownApplet@shelley/files/ShutdownApplet@shelley/applet.js

@icarter09
gnome-session-quit is not part of cinnamon-core, but cinnamon-session-quit is

ShutdownApplet@shelley: Fixed broken Log Out command

---

temperature@fevimu/files/temperature@fevimu/applet.js
temperature@fevimu/files/temperature@fevimu/settings-schema.json

Simple change to add a customizable prefix to the temperate display in the panel.
Default included prefix (disabled by default) is the Unicode thermometer character (U+1F321). 
Triggering a notification to @claudiux

temperature@fevimu: Adding label prefix support to applet panel display

---

hwmonitor@sylfurd/README.md
hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.2/applet.js
hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.2/providers.js
hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.2/settings-schema.json
hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/applet.js
hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/providers.js
hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/settings-schema.json
hwmonitor@sylfurd/files/hwmonitor@sylfurd/metadata.json

This is a work in progress. I'm submitting this primarily for review/feedback. By the time I got this far, I realized that **there is a significant desktop performance impact when performing large transfers** to or from the device being monitored although I'm not sure if it is my crappy JS coding or something inherently wrong with the approach I'm taking here. Maybe if I were using async calls when reading the sysfs kernel exports it would perform better? **My plan is to rework this using the libgudev library** which I believe utilizes non-blocking, asynchronous I/O system calls which might be the ticket to speeding this up. Feedback and additional performance testing results welcome. Thanks.
* Enumerates block devices by reading directly from sysfs kernel exports.
* Provides combobox for …

[hwmonitor@sylfurd]: Workaround for glibtop disk I/O for LVM bug (#2801)

---

hwmonitor@sylfurd/README.md
hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/applet.js
hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/settings-schema.json
hwmonitor@sylfurd/files/hwmonitor@sylfurd/metadata.json

@Hultan 
This should do the trick. After enumerating the available devices on the system the applet now selects the first device in the list as the default storage device to monitor for disk IO stats.
I also managed to resolve a small redundancy issue, where the `getAvailableDisks()` class method was being called more often than it ought to be when the applet gets reloaded/restarted by changing from where in the code it gets called.
Fixes #3005

[hwmonitor@sylfurd] Fix disk settings defaults bug (#3005)

---

hwmonitor@sylfurd/README.md

GUdev was introduced in 802098c8 (via linuxmint/cinnamon-spices-applets#2983)
as a workaround for linuxmint/cinnamon-spices-applets#2801.
Without the GUdev package the applet crashes and can not be added to
the panel. The following error is shown in `~/.xsession-errors`:
```
Cjs-Message: 20:07:01.690: JS LOG: [LookingGlass/error]
[hwmonitor@sylfurd]: Requiring GUdev, version none: Typelib file for namespace 'GUdev' (any version) not found
[hwmonitor@sylfurd]: Error importing applet.js from hwmonitor@sylfurd
Cjs-Message: 20:07:01.690: JS LOG: [LookingGlass/trace]
anonymous@/home/jkirk/.local/share/cinnamon/applets/hwmonitor@sylfurd/3.8/applet.js:32:7
createExports@/usr/share/cinnamon/js/misc/fileUtils.js:210:31
requireModule/</<@/usr/share/cinnamon/js/misc/fileUtils.js:288 …
```

[hwmonitor@sylfurd]: Update requirements for hwmonitor

---

collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/4.0/CinnamonSystray.js

@Feuerfuchs 
"Fixes" the error message https://github.com/linuxmint/cinnamon-spices-applets/issues/3062, as indicatorManager was removed in Cinnamon 4.6.
I was too lazy to figure out what functionality was lost, so it just does a nullcheck.

collapsible-systray@feuerfuchs.eu - Handle exception for deprecated indicatorManager

---

force-quit@cinnamon.org/README.md
force-quit@cinnamon.org/files/force-quit@cinnamon.org/applet.js
force-quit@cinnamon.org/files/force-quit@cinnamon.org/po/de.po
force-quit@cinnamon.org/files/force-quit@cinnamon.org/po/force-quit@cinnamon.org.pot

Also fixes icon size memory:
If you use a custom height for your symbolic icons, the icon scales properly, but as soon as you restart Cinnamon, the icon gets back to its default size. (Fixes #2879)
Add instruction for Arch based distros (Closes https://github.com/linuxmint/cinnamon-spices-applets/issues/1294)

force-quit@cinnamon.org: Fix tooltip l10n & use symbolic icon

---

ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/recorder.sh
ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/screencapture.sh
ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/screencapturesound.sh
ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/screencapturesoundwindow.sh
ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/screencapturewindow.sh

* use DISPLAY environment variable instead of \:0
* resolves capture errors when DISPLAY is \:1 or other
* add mpdecimate as a video filter to significantly reduce recorded video sizes
* mpdecimate only removes duplicate frames
* mpdecimate has low overhead
* quote vars and convert parameters to an array to prevent potential whitespace issues

Screencapture+Recorder use DISPLAY for capture references, mpdecimate to reduce capture file sizes

---

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/appUtils.js
CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/applet.js
CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/metadata.json
CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/de.po

* mainly backporting the new improved search, i.e. apps are reordered on search
* but also backporting other improvements/commits to catch up with upstream
* scroll to top of cats/apps, when closing menu
* fixing mate-layout not remembering, if favs or cats were shown last
* fix app description on buttons switch
* use symbolic dropdown icon
* update German translations

CinnVIIStarkMenu: v1.29 (improved search)

---

weather@mockturtl/CHANGELOG.md
weather@mockturtl/files/weather@mockturtl/3.8/settings-schema.json
weather@mockturtl/files/weather@mockturtl/metadata.json
weather@mockturtl/files/weather@mockturtl/po/weather@mockturtl.pot

* Fixes [#3257](https://github.com/linuxmint/cinnamon-spices-applets/issues/3257), cinnamon-xlet-makepot can't handle `units` as section key

weather@mockturtl version 2.6.7 Settings schema fix

---

ddcci-monitor-control@andr35/files/ddcci-monitor-control@andr35/applet.js

The commit introduces only a minor fix.
Values of brightness and contrast are reset once menu is closed to avoid that old values are used when the menu is open again.

ddcci-monitor-control@andr35: reset display values when menu is closed

---

rust-menu@jerrywham/files/rust-menu@jerrywham/applet.js

Hi @jerrywham,
Thanks for the applet. The name used in the code didn't match the `svg` in the project folder. This PR fixes that.
Regards,

rust-menu@jerrywham: fix icon name

---

nightscout@ranneft/files/nightscout@ranneft/applet.js

When a user enables displaying the IOB, but one of the (sub-)properties isn't defined in `status.pump.iob.bolusiob`, the code silently stops execution and fails to update the applet label.
@ImmRanneft

nightscout: Bug fix - Handled IOB not defined

---

sysmonitor@orcus/CHANGELOG.md
sysmonitor@orcus/files/sysmonitor@orcus/3.2/providers.js
sysmonitor@orcus/files/sysmonitor@orcus/metadata.json

- Fixed crash in network provider when glibtop failed to retrieve network interface list and a fallback method was used, fixes #3432

sysmonitor@orcus: Fixed crash in network provider

---

Cinnamenu@json/files/Cinnamenu@json/3.2/applet.js
Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js

`entry.get_app_info()` can be null and make the menu appear empty.
```
(cinnamon:3641): Cjs-WARNING **: 17:27:11.412: JS ERROR: Exception in callback for signal: open-state-changed: TypeError: entry.get_app_info() is null
loadAppCategories@/home/user/.local/share/cinnamon/applets/Cinnamenu@json/4.0/applet.js:1687:28
initAppCategories/<@/home/user/.local/share/cinnamon/applets/Cinnamenu@json/4.0/applet.js:1664:22
initAppCategories@/home/user/.local/share/cinnamon/applets/Cinnamenu@json/4.0/applet.js:1660:14
getAppsByCategory@/home/user/.local/share/cinnamon/applets/Cinnamenu@json/4.0/applet.js:1735:18
update/<@/home/user/.local/share/cinnamon/applets/Cinnamenu@json/4.0/applet.js:1453:64
update@/home/user/.local/share/cinnamon/applets/Cinnamenu@json/4.0/applet.js:1450:14 …
```

Cinnamenu@json: check for null entry.get_app_info()

---

download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/compatibility.js
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/files.js
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/infos.js
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/shellUtils.js

Hi @NikoKrause
The changes works fine locally.
I have moved the method to a separate file for easier maintenance and porting the solution to other applets.
Also got an improvement idea to consider in the future while working on this. For such cases having a module with compatibility functions in Cinnamon would even further ease maintenance of all applets. Then developers could import such module and use the function directly like:
```
const Compatibility = imports.misc.compatibility;
...
let str = Compatibility.byte_array_to_string(byte_array);
```

[download-and-upload-speed@cardsurf] Moved method to separate file

---

scripts@paucapo.com/CHANGELOG.md
scripts@paucapo.com/files/scripts@paucapo.com/applet.js
scripts@paucapo.com/files/scripts@paucapo.com/metadata.json
scripts@paucapo.com/files/scripts@paucapo.com/po/localization-template.pot
scripts@paucapo.com/files/scripts@paucapo.com/settings-schema.json
scripts@paucapo.com/files/scripts@paucapo.com/stylesheet.css

- Ability to chose how to execute scripts, on right click and on left click.
Four possibilities: Execute silently, Execute in terminal, Edit the script, Ask what to do.
- Detection of default terminal.
- Ability to customize the terminal and editor to use.
- Not executable files can now only be opened with xdg-open.
- Dependency check: terminal, xdg-open and notify-send.
- Add of some icons to the menu.
This closes the ticket https://github.com/linuxmint/cinnamon-spices-applets/issues/3194
@paucapo Are you okay with this changes?

[scripts@paucapo.com] Manage how to execute scripts (#3194)

---

hamster@projecthamster.wordpress.com/files/hamster@projecthamster.wordpress.com/applet.js
hamster@projecthamster.wordpress.com/files/hamster@projecthamster.wordpress.com/stuff.js

Under Cinnamon 4.8.6 on Linux Mint 20.1, I tried to add the Project Hamster
applet to my Panel (task bar). The applet did not load, and the following error
appeared in Looking Glass:
error t=2021-02-01T21:11:01Z
[hamster2@projecthamster.wordpress.com]: missing ( after for
[hamster2@projecthamster.wordpress.com]: Error importing applet.js from hamster2@projecthamster.wordpress.com
trace t=2021-02-01T21:11:01Z
createExports@/usr/share/cinnamon/js/misc/fileUtils.js:211:59
requireModule/</<@/usr/share/cinnamon/js/misc/fileUtils.js:291:25
---------------->
The error is caused by the `for each (x in obj)` syntax in `applet.js` and
`stuff.js`. Using `for (x of obj)` syntax makes the error go away.
MDN says "JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 …

[hamster@projecthamster.wordpress.com] Fix crash: for-each-in syntax is not supported

---

validate-spice

valid string needs to be reset in for-loop

Fix validate-spice when used with --all flag

---

gputemperature@silentage.com/files/gputemperature@silentage.com/applet.js

Change U+1D3C (ᴼ) to U+00B0 (°) and added a space between degree value and degree symbol to make the format consistent with other applets (such as the weather or CPU temp applets).
**Current applet display:**
**Proposed applet display:**

[gputemperature@silentage.com] Changed unicode symbol U+1D3C (ᴼ) to U+00B0 (°) (minor aesthetic change)

---

radio@driglu4it/files/radio@driglu4it/4.6/applet.js
radio@driglu4it/files/radio@driglu4it/4.6/mpvPlayerHandler.js

Currently the volume it isn't shown at all in the applet which multiple users have criticized. So I changed the content shown in the tooltip from the radio channel to the volume.  In the long term I want to add an option in the settings so the users can decide what to show in the tooltip but for now I think it is more important to show the volume than the Channel as the channel can be shown in the panel and is indicated by a play/pause icon in the list. 
This PR has no conflicts to #3527 (although it would be great If this would be merged as well. Any reason why it hasn't get merged already? 😕)

[radio@driglu4it] Add volume to tooltip

---

weather@mockturtl/files/weather@mockturtl/po/nl.po

"Other options" would in my opinion be a better short generic tab name than "Units, Icons and Keys", so I've modified the Dutch translation for that string accordingly (thanks for the tip, @French77  ).

Update nl.po with nicer generic translation for "Units, Icons and Keys"

---

.github/workflows/main.yml
validate-spice

Use `msgfmt -c xx.po` command to verify po-files.
According to the man page (https://www.gnu.org/software/gettext/manual/html_node/msgfmt-Invocation.html), the command does the following:
`-c`, `--check`
Perform all the checks implied by `--check-format`, `--check-header`.
`--check-format`
Check language dependent format strings.
If the string represents a format string used in a `printf`-like function both strings should have the same number of `%` format specifiers, with matching types. If the flag c-format or possible-c-format appears in the special comment #, for this entry a check is performed. For example, the check will diagnose using `%.*s` against `%s`, or `%d` against `%s`, or `%d` against `%x`. It can even handle positional parameters.
Normally the xgettext program …

validate-spice: check po files for errors

---

bash-sensors@pkkk/files/bash-sensors@pkkk/po/bash-sensors@pkkk.pot
bash-sensors@pkkk/files/bash-sensors@pkkk/po/da.po
bash-sensors@pkkk/files/bash-sensors@pkkk/po/it.po
bash-sensors@pkkk/files/bash-sensors@pkkk/po/tr.po
bash-sensors@pkkk/files/bash-sensors@pkkk/settings-schema.json

The `cinnamon-spices-makepot` script crashes, if the settings-schema
contains a type called "title"

bash-sensors@pkkk: i18n should not contain \f escape sequence

---

.github/workflows/tst.yml
.translation-tables/LINGUAS
.translation-tables/translation-tables.py

This GitHub Action updates the Translation Status Tables (see
https://github.com/linuxmint/cinnamon-spices-applets/issues/3588) after
every push to the master branch by running the `translation-tables.py`
script. The generated tables are pushed to the
`translation-status-tables` branch.
The above mentioned issue is pinned and therefore shows up at the top of
the issues page for greater visibility.

Add GitHub Action "Update Translation Status Tables"

---

validate-spice

The msgfmt command created messages.mo files.
Stop it from doing this.

Validate spice: stop script from creating messages.mo files

---

radio@driglu4it/files/radio@driglu4it/4.6/applet.js
radio@driglu4it/files/radio@driglu4it/4.6/mpvPlayerHandler.js
radio@driglu4it/files/radio@driglu4it/4.6/utils.js

There has been some bugs in the MPV Handler which are fixed: 
- The volume of mpris and cvc (i.e. sound applet) haven't syncd when switching channel and changing volume afterwards
- The volume couldn't changed by scrolling after setting the cvc volume to zero
- When restarting cinnamon it could happen that volume N.A.N has been shown in toolitp or not rounded numbers
- Sometimes the volume in sound applet was shown +1 compared to the mpris volume
Unfortunately this will create some conflicts for my other open PR. I will update the other PR tomorrow to solve the conflicts. But it would be really useful when the other pr could be merged or rejected afterwards to prevent this circumstances in future ...

[radio@driglu4it] Fix bugs in mpv handler

---

calendar@ccprog/files/calendar@ccprog/po/calendar@ccprog.pot
calendar@ccprog/files/calendar@ccprog/po/da.po
calendar@ccprog/files/calendar@ccprog/po/de.po
calendar@ccprog/files/calendar@ccprog/po/fr.po
calendar@ccprog/files/calendar@ccprog/po/makepot
calendar@ccprog/files/calendar@ccprog/po/sv.po
calendar@ccprog/files/calendar@ccprog/settings-schema.json
calendar@ccprog/files/calendar@ccprog/settings_widgets.py

Add makepot to fix unicode characters in .pot file
Update .pot file
Update German translation
Update other l10n files against new .pot:
The other translation files did contain the broken unicode characters as
well. Fix by updating against new .pot file.
@ccprog

calendar@ccprog: Add gettext support to python script

---

sound150@claudiux/files/sound150@claudiux/3.4/applet.js
sound150@claudiux/files/sound150@claudiux/3.4/settings-schema.json

I think the function is pretty straightforward based on the description.
I can try to add corresponding changes for other Cinnamon versions if there's interest in merging it.

sound150@claudiux: add "Always show input controls" option

---

cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/3.4/applet.js
cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/3.4/settings-schema.json

setting-schema.json
- add an item "auto-loop-enable" to page "General" to select loop on/off.
applet.js
- add variable "timerDurationLoop" to keep current timeDuration for loop .
- modify function "doStartTimer" to save current timeDuration value to new variable "timeDurationLoop".
- modify function "doTimerExpired" to recall the function "doStartTimer".

Added function: automatically loop

---

hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/applet.js

This was added as part of this commit:
https://github.com/linuxmint/cinnamon-spices-applets/commit/0195a9d776d22b7cf4c6269a3edc7dcc6188179a
There is a danger to this, which manifests randomly and crashes cinnamon.  Scenario:
- Applet is in a timed loop (Mainloop.timeout_add_seconds)
- Each time the callback for this loop is called, the true update
is setup on an idle callback. Note: idle callbacks are never
guaranteed to run within any particular timeframe.
- The idle callback is made, and the graphs update.
When the system is not too busy, this is fine. But when there is a lot
of activity with the cpu, disk i/o, etc... those idle callbacks can
be delayed, and will end up accumulating until finally they all run
immediately one after the other.
The cpu provider uses libgtop to get cpu …

applet.js: Remove the idle callback when updating the graphs.

---

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/applet.js

The markup passed to the set_markup() method must be valid. For example,
the literal <>& characters must be escaped as &lt;, &gt;, and &amp;.
(https://developer.gnome.org/pygtk/stable/class-gtklabel.html)
Fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/3666

CinnVIIStarkMenu@NikoKrause: Fix search function bug

---

ShellTools@abgoyal/files/ShellTools@abgoyal/applet.js

A variable not being initialized stopped the applet from loading.
@brownsr @NikoKrause

ShellTools@abgoyal: Fixes error that causes applet not to load.

---

MessagingMenuV3@blub/files/MessagingMenuV3@blub/applet.js

Current version of Messaging Menu V3 is missing support for newer messaging applications, and older applications that used to be supported no longer show up in the menu (specifically Geary and Evolution). I've kept in the older geary and evolution ID's as well as the newer org.gnome.* versions in case this is used on older systems that might still support the older applications.

MessagingMenuV3@blub: Update Application Support, added support for unsupported and updated applications

---

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js
Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js
Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json
Cinnamenu@json/files/Cinnamenu@json/metadata.json

Limit file search folder recursion to 50 in order to avoid delays when searching home folder. This means that "search home folder" option will not find all files that match a search string when there are a large number of folders in the home directory.
fixes: #3742
and
fixes: #3759

[Cinnamenu@json] Fix search delay bug

---

cpufreq@mtwebster/files/cpufreq@mtwebster/applet.js

Based on useful comments on the [applet page](https://cinnamon-spices.linuxmint.com/applets/view/70), this is a fix for the applet not continually updating. Looks like all other places in code are properly using `Lang.bind` except here.
@mtwebster

[cpufreq@mtwebster] Fix applet update issues

---

.typescript-declarations/cinnamon/globals.d.ts
radio@driglu4it/files/radio@driglu4it/4.6/Config.js
radio@driglu4it/files/radio@driglu4it/4.6/lib/PopupMenu.js
radio@driglu4it/files/radio@driglu4it/4.6/lib/PopupSubMenu.js
radio@driglu4it/src/Config.ts
radio@driglu4it/src/lib/PopupMenu.ts

Fix for bugs reported on last commit: https://github.com/linuxmint/cinnamon-spices-applets/pull/3820#issuecomment-866357893. Thanks to @fredcw 
- In some unknown situation, it happens that the last volume is saved as null or undefined, which prevent radio from starting after restarting cinnamon. Added a fallback value of 50 as a workaround for this situation to prevent radio from stop working. 
- Fixing grey line on the screen when closing the popup menu on some themes

[radio@driglu4it] bugfix

---

ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/applet.js
ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/metadata.json

- display error messages if `ddcutil` is not installed
- display `InfoOSD` modal when running `ddcutil detect` (so the user knows the applet is doing something)

ddcci-multi-monitor@tim-we update 1.1.0

---

radio@driglu4it/files/radio@driglu4it/4.6/applet.js
radio@driglu4it/files/radio@driglu4it/4.6/lib/PopupMenu.js
radio@driglu4it/files/radio@driglu4it/4.6/mpv/MpvHandler.js
radio@driglu4it/files/radio@driglu4it/4.6/settings-schema.json
radio@driglu4it/files/radio@driglu4it/4.6/ui/Applet/Applet.js
radio@driglu4it/files/radio@driglu4it/4.6/ui/Applet/AppletLabel.js
radio@driglu4it/src/applet.ts
radio@driglu4it/src/lib/PopupMenu.ts
radio@driglu4it/src/mpv/MpvHandler.ts
radio@driglu4it/src/ui/Applet/Applet.ts

- In the past the mpv listeners haven't been deactivated when the applet has been moved or permanently removed from the panel which lead to the problem that the applet has been tried to access destroyed widgets which even could lead to cinnamon crashing. This has been fixed  
- add another default station
- prevent opening multiple installation windows when clicking on the applet while an installation is already in progress

[radio@driglu4it] Fix Problems when moving applet

---

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js
Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js
Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json
Cinnamenu@json/files/Cinnamenu@json/metadata.json

The emoji picker on search is an awesome feature, however, I was a bit annoyed that it didn't keep the skin tone, like chatting apps do. So I did this mod to at least allow selecting a default skin tone.
ping @fredcw 
Edit: adding some screenshots

[Cinnamenu@json] Allow selecting default skin tone

---

app-launcher@mchilli/files/app-launcher@mchilli/applet.js
app-launcher@mchilli/files/app-launcher@mchilli/settings-schema.json

Don't use symbolic-icons by default and use a local "replaceAll" function, for compatibility with cinnamon < 4.8

changes for backward compatibility

---

ipindicator@matus.benko@gmail.com/files/ipindicator@matus.benko@gmail.com/applet.js
ipindicator@matus.benko@gmail.com/files/ipindicator@matus.benko@gmail.com/getNetworkInterfaces.sh

The legacy tool ifconfig is not installed by default in many distributions and has been replaced by "ip".
Use that tool to get the list of network interfaces.

ipindicator@matus.benko: Use ip command to retrive list of interfaces.

---

radio@driglu4it/files/radio@driglu4it/4.6/radio-applet.js
radio@driglu4it/package.json

A user reported that the popup menu overlaps the panel when using cinnamox-themes. This should fix it (or at least make it much better. There still seems to be a very small overlap but not sure if this is the applets fault or the theme fault :-/)

[radio@driglu4it] improve cinnamox-theme support

---

qredshift@quintao/files/qredshift@quintao/applet.js
qredshift@quintao/files/qredshift@quintao/js/QUtils.js
qredshift@quintao/files/qredshift@quintao/js/to-string.js

Hi,
This PR removes this message from '.xsession-errors':
```
(cinnamon:1596): Cjs-WARNING **: 03:08:26.885: Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to explicitly call ByteArray.toString(array). (Note that array.toString() may have been called implicitly.)
ByteArray.toString(array) is *not* backward compatible with previous (< 4.8) versions of Cinnamon. You will have add versioning support to your applet if it does not already have it, so that compatibility can be maintained for users on older Cinnamon versions.
See: …
```

Qredshift toString() bugfixes

---

azan@fahri.nurul.id/files/azan@fahri.nurul.id/applet.js
azan@fahri.nurul.id/files/azan@fahri.nurul.id/metadata.json
azan@fahri.nurul.id/files/azan@fahri.nurul.id/settings-schema.json

This update will allow the user to choose the format for prayer times in the widget. The PrayTimes library already has this feature; this update lets the user adjust it.

feat(azan@fahri.nurul.id): add settings option to choose between 12 hour and 24 hour time

---

ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/applet.js

App can't be run on older versions on CJS.
This fix makes sure it is compatible from ES2017+ (cjs version 52 and up)
@tim-we

ddcci-multi-monitor@tim-we - Make sure code is es2017 compliant

---

screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/applet.js

Screensaver settings is a python module now.

screen-inhibit@mtwebster: Don't check for cinnamon-control-center when launching screensaver settings

---

darkMode@linuxedo.com/README.md
darkMode@linuxedo.com/files/darkMode@linuxedo.com/applet.js
darkMode@linuxedo.com/files/darkMode@linuxedo.com/metadata.json
darkMode@linuxedo.com/files/darkMode@linuxedo.com/po/darkMode@linuxedo.com.pot
darkMode@linuxedo.com/files/darkMode@linuxedo.com/settings-schema.json

A new option is added to change the wallpaper based on the light and dark modes from a given folder. If there are multiple images in the folder, a picture will be selected randomly. Currently supporting only .jpg, .jpeg, and .png files.

darkMode@linuxedo.com: Add option to change wallpaper with mode change

---

sysmonitor@orcus/files/sysmonitor@orcus/po/sv.po

This fixes a string where Up/Down where mixed up for network statistics in Swedish, as well as letting the "nice" stay untranslated as the string is about the Unix command, not the adjective.

sysmonitor@orcus: Update sv.po

---

octopussy@centurix/files/octopussy@centurix/applet.js

When opening the webcam stream or the octoprint page it will use the hardcoded url "octopi.local" even if a different url is set. This PR fixes it.
@Centurix

[octopussy@centurix] Use URL from settings instead of default

---

ipindicator@matus.benko@gmail.com/files/ipindicator@matus.benko@gmail.com/applet.js

Suggested improvements to fix #3800.
Delete line 356, which breaks the code. Its function is superfluous anyway.
Add trim() to all input strings at input.
Change code to enable partial ISP name match to make it far more robust.
@PrimaMateria, @PRSoftware

IP Indicator: fix #3800 Home icon not displayed 

---

Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js
Cinnamenu@json/files/Cinnamenu@json/4.0/mint-remove-application.py
Cinnamenu@json/files/Cinnamenu@json/metadata.json

Override mint-remove-application.py.
Don't allow uninstall of package if it has dependents and when removing a package, also remove autoremovable dependencies.

[Cinnamenu@json] Improvements to uninstall option

---

uiscaler@joka42/files/uiscaler@joka42/uiscaler

Fixed Issues:
* Scaling 200% and then 125% resulted in 225% increase which is now fixed
* Default panel height at 100% was not the cinnamon default, which is now fixed

uiscaler default 100% settings are actual default for Mint 20.2 + 20.3

---

calendar@simonwiles.net/files/calendar@simonwiles.net/world_clock_calendar_settings.py

Require Gtk 3.0 for world clocks setting window.
If Gtk 4.0 is installed, it is automatically picked as the highest
version and the settings window fails to open due to different API in
Gtk major versions.
Fixes #4118

calendar@simonwiles.net: require gtk 3.0 for settings window

---

radio@driglu4it/files/radio@driglu4it/4.6/radio-applet.js
radio@driglu4it/src/lib/AppletIcon.ts
radio@driglu4it/src/services/Config.ts
radio@driglu4it/src/ui/VolumeSlider.ts

Just  a small bugfix. Since the last update, it is initially shown "volume: undefined" in the tooltip of the volume slider. This fixes that bug.

[radio@driglu4it] Bugfix: Tooltip of volume slider showing undefined

---

radio@driglu4it/files/radio@driglu4it/4.6/radio-applet.js
radio@driglu4it/package.json
radio@driglu4it/src/lib/AppletContainer.ts
radio@driglu4it/src/ui/VolumeSlider.ts

Just another (and hopefully the last) fix for the last major update. Currently the volume slider is never showing 0 which is of course wrong (it is always a pain in javascript that 0 is "falsy").

[radio@driglu4it] fix volume-slider not showing zero

---

.typescript-declarations/Atk-1.0.d.ts
.typescript-declarations/CMenu-3.0.d.ts
.typescript-declarations/Caribou-1.0.d.ts
.typescript-declarations/Cinnamon-0.1.d.ts
.typescript-declarations/CinnamonDesktop-3.0.d.ts
.typescript-declarations/Clutter-1.0.d.ts
.typescript-declarations/ClutterX11-1.0.d.ts
.typescript-declarations/Cvc-1.0.d.ts
.typescript-declarations/GObject-2.0.d.ts
.typescript-declarations/Gdk-3.0.d.ts
.typescript-declarations/GdkPixbuf-2.0.d.ts
.typescript-declarations/Gio-2.0.d.ts
.typescript-declarations/Gst-1.0.d.ts
.typescript-declarations/Gtk-3.0.d.ts
.typescript-declarations/Meta-3.0.d.ts
.typescript-declarations/Pango-1.0.d.ts
.typescript-declarations/Soup-2.4.d.ts
.typescript-declarations/St-1.0.d.ts
.typescript-declarations/WebKit2-4.0.d.ts
.typescript-declarations/XApp-1.0.d.ts
.typescript-declarations/cinnamon/globals.d.ts
.typescript-declarations/cinnamon/ui/applet.d.ts
.typescript-declarations/cinnamon/ui/layout.d.ts
.typescript-declarations/cinnamon/ui/modalDialog.d.ts
.typescript-declarations/cinnamon/ui/settings.d.ts
.typescript-declarations/cinnamon/ui/tooltips.d.ts
.typescript-declarations/manual-overrides/St-1.0.d.ts
.typescript-declarations/xfixes-4.0.d.ts
.typescript-declarations/xrandr-1.3.d.ts

Changes:
* Fix `connect` signal keys for notify, it was using incorrectly formatted prop names (generated output)
* Remove readonly properties from class init options (generated output)
* Add few more generated declarations instead of dummy/handwritten ones
* Various fixes in JS side of the declarations

Update Typescript declarations with changes in npm package

---

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/prefs.js
multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/prefs.js
multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json

Applet preferences dialog does not open on systems with gtk4 installed because gtk version info should come before the import instruction.
Fixes: #3974

[multicore-sys-monitor@ccadeptic23] Bugfix: use gtk3 only

---

radio@driglu4it/files/radio@driglu4it/4.6/radio-applet.js
radio@driglu4it/files/radio@driglu4it/4.6/settings-schema.json
radio@driglu4it/files/radio@driglu4it/metadata.json
radio@driglu4it/src/services/Config.ts
radio@driglu4it/webpack.config.js

In the last pr I have accidentally used `ur` instead of `url`. This lead to a type Error each time the applet makes some changes in the settings for new users (which is very often the case and makes the applet almost useless for new users). 
@brownsr when possible please accept this soon. There are just very few changes.

[radio@driglu4it] HOT FIX - Fix config not working on fresh install

---

clean-show-desktop@filipetorresbr/files/clean-show-desktop@filipetorresbr/applet.js
clean-show-desktop@filipetorresbr/files/clean-show-desktop@filipetorresbr/settings-schema.json

Made the border to be left-only, and added an option for left-margin
it looks better if it's on the right side, but I'm sure that's where most people who come from windows are going to put it anyway

clean-show-desktop@filipetorresbr: Made the applet look more like Windows 10

---

Cinnamenu@json/README.md
Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js
Cinnamenu@json/files/Cinnamenu@json/4.0/appsview.js
Cinnamenu@json/files/Cinnamenu@json/4.0/browserBookmarks.js
Cinnamenu@json/files/Cinnamenu@json/4.0/browserHistory.js
Cinnamenu@json/files/Cinnamenu@json/4.0/getFavicons.py
Cinnamenu@json/files/Cinnamenu@json/4.0/searchHistory.py
Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json
Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js
Cinnamenu@json/files/Cinnamenu@json/metadata.json
Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot

Show favicons in browser search results.
Add browser history search.
Use search prefixes for unenabled search options. (Thanks to @McBruno712 & @quadransmuralis for the suggestion)
Limit number of some search results.
Horizontally center menu when in center zone of panel. fixes #4256

[Cinnamenu@json] Favicons, web history search and search prefixes.

---

cinnamon-multi-line-taskbar-applet/files/cinnamon-multi-line-taskbar-applet/applet.js

Add all the windows that currently exists to the taskbar.
This will ensure that the taskbar is not missing windows when
adding the applet to a panel or when cinnamon restarts.

[cinnamon-multi-line-taskbar-applet] Register windows on startup

---

cheaty@centurix/files/cheaty@centurix/applet.js
cheaty@centurix/files/cheaty@centurix/settings-schema.json

The default keybinding is `<super>m` which is allegedly not yet taken
by any other spice.
@Centurix

cheaty@centurix: Add keybinding for showing the cheaty menu

---

bluetooth-battery@zamszowy/README.md
bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/applet.js
bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/metadata.json
bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/override-select.js
bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/settings-schema.json

This patchset:
- removes usage od deleted Glib-Upower interface - this crashes applet if using latest upower. (fixes #4338)
- uses non-deprecated AppletSettings API.
- adds possibility to display user selected device (instead of one with lowest battery).
- changes name to match applet UUID
- take two at markdown newlines (to have them displayed at https://cinnamon-spices.linuxmint.com/)
- add notifications (closes #4345)

bluetooth-battery@zamszowy: notifications, manual device and fixes

---

Cinnamenu@json/files/Cinnamenu@json/po/fa.po

There two words are opposite in what they do. So when the system locale is set to Persian and everything is RTL, when you click left, the sidebar goes to right, and vice versa. This can possibly fix the issue.
Tested on:
LMDE 5.0 (Linux 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux)
Cinnamon 5.2.7
Here's a little proof:

Fix left and right being the opposite in Persian

---

bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/applet.js
bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/settings-schema.json

This patchset includes following changes:
- sort (by battery level) devices in menu
- hide applet entirely if no devices are monitored
- correctly skip unnamed devices: skip devices without model and serial property always, instead of just
when its type is "uncommon".
- notification filtering
This fixes: #4351

[bluetooth-battery@zamszowy]: notification, filtering, sorting and fixes

---

cheaty@centurix/files/cheaty@centurix/applet.js

Resolve errors in logs about Uint8Array errors when converting ByteArray data to strings when loading cheatsheets from disk using Gio.

cheaty@centurix: Resolve Uint8Array errors from Gio load_contents()

---

sshlauncher@sumo/files/sshlauncher@sumo/applet.js

Changed the Gio load file contents conversion to string so that it safely converts using ByteArray when reading Uint8Array
@sumo

sshlaucher@sumo: Resolve Uint8Array errors while loading SSH config file

---

darkMode@linuxedo.com/README.md
darkMode@linuxedo.com/files/darkMode@linuxedo.com/applet.js

Fix configuration dialog crash in pre cinnamon 5.4 versions due to no icon theme being found when ~/.local/share/icons folder doesn't exist and thus no icon theme options were available for the combobox causing xlet-settings.py to crash.
Fixes #4382
@slgobinath

[darkMode@linuxedo.com] Fix configuration dialog not opening

---

darkMode@linuxedo.com/files/darkMode@linuxedo.com/applet.js

@slgobinath Sorry. In fixing the last bug, I introduced another. I should have tested more thoroughly.
It turns out setOptions() doesn't do anything if passed the same object as previously even when the object has new properties, it must be passed a different object each time it's called.

[darkMode@linuxedo.com] Bug fix: incomplete theme options.

---

ipindicator@matus.benko@gmail.com/README.md

Updated the README image links to with full URLs so that the images will show up on both the README page (https://github.com/linuxmint/cinnamon-spices-applets/tree/master/ipindicator@matus.benko@gmail.com#screenshots) and on  https://cinnamon-spices.linuxmint.com/applets/view/300 (Right now they do not show up on the latter)
@PrimaMateria @brownsr

[ipindicator@matus.benko@gmail.com] Updated the README with full URLs to images

---

smallcalc_applet@lerc.sds/files/smallcalc_applet@lerc.sds/applet.js

Clutter.grab_pointer() no longer available in cinnamon 5.4.x

[Smallcalc_applet@lerc.sds] Fix for cinnamon 5.4.x

---

ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/applet.js

The applet has issues when running on laptops where displays do not support DDC/CI,
The parsing code for the command 'ddcutil detect' incorrectly identifies 'i2c-7' as the bus for my external monitor (which should be 'i2c-4') because there is no guard condition that prevents execution when it meets an 'invalid display'. 
This results in the applet crashing,
The proposed fix makes sure that the code does not continue execution and update values (currentDisplay.bus and currentDisplay.name) that have already been assigned. This effectively gets rid of 'invalid displays' with minimal changes to the codebase. Also, it preserves the existing display naming scheme (with an added fallbackName property).
**TL;DR - Applet can now be used with laptop displays and external monitors**
@tim-we

ddcci-multi-monitor@tim-we: Prevent the applet from crashing when invalid displays are present

---

nordvpn-indicator@nickdurante/files/nordvpn-indicator@nickdurante/applet.js

The new nordvpn app on linux prints about its meshnet feature any time a command is called. The breaks the connection status detection as is not as structured as before.
Instead of assuming a structured output for `nordvpn status` , we just a regex match for the word after `Status: ` and match it with Connected or Disconnected.

nordvpn-indicator@nickdurante : Fix connection status detection

---

radio@driglu4it/files/radio@driglu4it/4.6/radio-applet.js
radio@driglu4it/files/radio@driglu4it/4.6/settings-schema.json
radio@driglu4it/files/radio@driglu4it/metadata.json
radio@driglu4it/files/radio@driglu4it/po/de.po
radio@driglu4it/files/radio@driglu4it/po/es.po
radio@driglu4it/files/radio@driglu4it/po/hr.po
radio@driglu4it/files/radio@driglu4it/po/hu.po
radio@driglu4it/files/radio@driglu4it/po/is.po
radio@driglu4it/files/radio@driglu4it/po/it.po
radio@driglu4it/files/radio@driglu4it/po/radio@driglu4it.pot
radio@driglu4it/files/radio@driglu4it/po/sv.po
radio@driglu4it/files/radio@driglu4it/po/tr.po
radio@driglu4it/src/index.ts
radio@driglu4it/src/lib/AppletContainer.ts
radio@driglu4it/src/lib/PopupMenu.ts
radio@driglu4it/src/services/Config.ts
radio@driglu4it/src/services/mpv/MpvHandler.ts
radio@driglu4it/src/services/youtubeDownload/YoutubeDl.ts
radio@driglu4it/src/services/youtubeDownload/YoutubeDownloadManager.ts
radio@driglu4it/src/services/youtubeDownload/YtDlp.ts
radio@driglu4it/src/types.ts
radio@driglu4it/src/ui/RadioApplet/RadioAppletContainer.ts
radio@driglu4it/src/ui/RadioApplet/RadioAppletTooltip.ts
radio@driglu4it/src/ui/RadioApplet/YoutubeDownloadIcon.ts
radio@driglu4it/src/ui/RadioPopupMenu/MediaControlToolbar/DownloadButton.ts
radio@driglu4it/webpack.config.js

- Fixes #4479, 
- Fixes #4323
- Stop sticking the popup menu to the applet container. Previous the position of the popup menu has been updated as soon as the position of the applet in the panel has been changed. But this made it very difficult to use the seeker when the option "show song information on the panel" of the sound applet is selected

[radio@driglu4it] Version 2.2.1

---

redshift@marvel4u/files/redshift@marvel4u/applet.js

To @Marvel4U and all the related members,
Fixes #2747
Added `redshift -r -x` to invoke immediately reset,
and `-r` options to every redshift spawning so that the color transition won't cause issues.
These changes work well so far.
Test environment:
- Arch Linux 6.0.12-arch1-1
- Cinnamon 5.6.4
- redshift 1.12

redshift: Fixed flicker & darkening glitch

---

bettersettings@bownz/files/bettersettings@bownz/applet.js

Have the applet direct to using Cinnamons default startup manager instead of pursuing a gnome application thats not installed by default

bettersettings@bownz direct "Start up Applications" to Cinnamons

---

batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/5.4/applet.js
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/CHANGELOG.md
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/metadata.json
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/batterymonitor.pot
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/da.po
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/de.po
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/es.po
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/fr.po
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/hr.po
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/hu.po
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/it.po
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/ru.po
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/sv.po
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/tr.po
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/uk.po
batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/zh_CN.po

* Improved the logic for determining the default kernel path (some systems default to BAT1 instead of BAT0)
- Fixes "-- Warning" permanent message and removes the need for manual configuration in the single battery condition to address it
@pdcurtis (who is on vacation but gives his blessing)

[batterymonitor@pdcurtis] - BAMS 1.5.1 - Improving default battery path logic over hard-coding it

---

calendar@simonwiles.net/files/calendar@simonwiles.net/world_clock_calendar_settings.py

Applet manually edits .json config file but only looks in ~/.cinnamon/configs for file. Try looking for config file in ~/.config/cinnamon/applets/ first. fixes #4637, fixes #4638

[calendar@simonwiles.net] Fix for cinnamon 5.6

---

timer@Severga/files/timer@Severga/applet.js
timer@Severga/files/timer@Severga/po/fr.po
timer@Severga/files/timer@Severga/po/makepot
timer@Severga/files/timer@Severga/po/ru.po
timer@Severga/files/timer@Severga/po/ru_RU.po
timer@Severga/files/timer@Severga/po/timer@Severga.pot

@Severga @brownsr @mtwebster 
The purpose of this PR is to offer some improvements to the timer@Severga applet:
* Allow translations: In the `po/` folder, I created the `makepot` script used to build the `timer@Severga.pot` file. I used this .pot file to create the fr.po file (French translation).
* I fixed sound playback, because `global.play_sound_file()` is not a function (error notified in `~/.xsession-errors` - Cinnamon 5.6.7).
* The `applet.js` script was modified to use translations and the SoundManager.playSoundFile() function.
Using makepot:
* `cd ~/.local/share/cinnamon/applets/timer@Severga/po`
* `./makepot` to create timer@Severga.pot file
* Use timer@Severga.pot with poEdit to make translations
* `./makepot -i` to install translations
* Restart Cinnamon.

[timer@Severga] Allow translations - Fix sound playback

---

bettersettings@bownz/files/bettersettings@bownz/applet.js

change to open gnome-screenshot in interactive mode  since mode it was in isn't working

bettersettings@bownz changing how screenshot tool opens

---

kdecapplet@joejoetv/files/kdecapplet@joejoetv/applet.js
kdecapplet@joejoetv/files/kdecapplet@joejoetv/js/modules.js
kdecapplet@joejoetv/files/kdecapplet@joejoetv/metadata.json
kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/de.po
kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/kdecapplet@joejoetv.pot
kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/pot-additions.txt
kdecapplet@joejoetv/files/kdecapplet@joejoetv/settings-schema.json
kdecapplet@joejoetv/files/kdecapplet@joejoetv/settingsWidgets.py

I have updated the applet to version 2.1.0, which adds support for changing the order of modules for each device sub menu and changing the order of the devices themselves.
It also adds the ability to individually choose, which device sub menus should automatically expand.
Maybe @Drugwash2 could test, if the performance issues he observed with the app-launcher@mchilli applet are happening here too, as I have also used a custom SettingsWidget.
EDIT: I have also noticed, that the screenshot on the  cinnamon-spices page is still the old one, which I had reaplced in the 2.0.0 rewrite pull request. Do I have to do more than that to properly update it?

[kdecapplet@joejoetv] Version 2.1.0

---

sound150@claudiux/CHANGELOG.md
sound150@claudiux/files/sound150@claudiux/5.4/applet.js
sound150@claudiux/files/sound150@claudiux/CHANGELOG.md
sound150@claudiux/files/sound150@claudiux/metadata.json

Hi @brownsr @mtwebster 
This PR fixes https://github.com/linuxmint/cinnamon/issues/9919 just replacing the `sound@cinnamon.org` applet by `sound150@claudiux`.
I hope this is suitable.
Regards
Claudiux

[sound150@claudiux] v3.0.0 - Overwrite AudioRaiseVolume and AudioLowerVolume keysym

---

rwall@typicalfoobar/files/rwall@typicalfoobar/applet.js
rwall@typicalfoobar/files/rwall@typicalfoobar/metadata.json

The signal "Dangerous!" :warning: has now disappeared. 
Author of this applet: none.

[rwall@typicalfoobar] v1.0.2 - Make this applet not 'dangerous'

---

bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/applet.js

Don't clear manual device choice after e.g.: this device gets disconnected and reconnected.

[bluetooth-battery@zamszowy]: remember last manual device set

---

CommandRunner@appdevsw/files/CommandRunner@appdevsw/applet.js
CommandRunner@appdevsw/files/CommandRunner@appdevsw/settings-schema.json

This adds the possibility to define a command to run when left clicking the applet in the task bar.
When no command is defined the standard action (opening the settings) is executed.

CommandRunner@appdevsw: added setting to run command when left clicking applet

---

sysmonitor@orcus/files/sysmonitor@orcus/3.2/applet.js
sysmonitor@orcus/files/sysmonitor@orcus/3.2/settings-schema.json

Added a minimum scaling user setting for the network graph since it is the only graph that does not have a fixed maximum (like 100% CPU or known usable RAM value) so the user can set a "soft" maximum by specifying the minimum scaling of the graph.
If the value exceeds the specified minimum the graph is auto-scaled.
The standard setting of "0" produces the same behaviour as it does without this PR.

sysmonitor@orcus: added scaling functionality for network graph

---

desaturate-all@hkoosha/files/desaturate-all@hkoosha/applet.js

Each time the applet is clicked, an error message like the following appears in the ~/.xsession-errors file.
```
Gjs-Message: 08:49:39.664: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function 26]: Too many arguments to method Clutter.Actor.has_effects: expected 0, got 1
```
Addresses https://github.com/linuxmint/cinnamon-spices-applets/issues/4909
Tested on latest version of Manjaro-Cinnamon.

[desaturatea-all@hkoosha] replace call to `has_effects(this.effect)`

---

places-with-terminal@mtwebster/files/places-with-terminal@mtwebster/applet.js

Fixes #4566
When a place button (e.g. for your Home folder) was clicked `Cinnamon.get_event_state(event)` returned 0, so `activate` wasn't called and nothing happened.
I removed `_onButtonReleaseEvent` and now the parent class (PopupBaseMenuItem) correctly calls `activate`. I think the left mouse button check is unneeded as other applets with PopupMenus let you use any mouse button.
The applet has no author to ping.

places-with-terminal@mtwebster: Fix place buttons not working

---

CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot

1. Fixed the "Ungroup" action when the window-list was configured as "Grouped" so that it will actually un-group the application. Previously this option would only work when the window-list was configured as "pooled", "Automatic" or "one-to-one". Insert the new window-list buttons ahead of the original grouped button in the order they were in while grouped.
2. Fix some cases where the "one label per application pool" option was not behaving correctly.
3. When only two workspaces exist, replace the "Pin to other workspaces" context menu option to a toggle option for pinning to the other workspace. The "Pin to other workspaces" sub-menu now only appears when there are 3 or more workspaces
4. Added an option for the "Pooled"/"Automatic" configurations that allows users to decide if they want …

[CassiaWindowList@klangman] A bunch of fixes and new features

---

spices-notifier@germanfr/files/spices-notifier@germanfr/applet.js

Fix bug causing cinnamon to crash.
For some reason cinnamon is triggering make_uuidList() multiple times. For instance, with 3 applets in total to update, one in the uuid list and 2 from the owner name, make_uuidList() is called about 88 times on each timed update.
Not sure if this is caused by the applet or a bug in ui/settings.js, but I can't see any reason for it in the applet so it seems likely to be in settings.js. This fix works as a temporary solution until the real cause of the bug can be found.
The real issue with reload being called many times is that it seems to cause ui/settings.js's filemonitor to be repeatedly triggered, greatly increasing the chances of it occurring during spidermonkey's garbage collection phase. This causes the following errors and often causes cinnamon to …

spices-notifier@germanfr: Bug fix.

---

spices-notifier@germanfr/files/spices-notifier@germanfr/applet.js
spices-notifier@germanfr/files/spices-notifier@germanfr/metadata.json

Leave a delay of 1 second between two requests to the spices site, so we don't get blocked.
Add a 'Refresh' option to the contextual menu.

[spices-notifier@germanfr] v4.2 - Improves access to spices website

---

restart-cinnamon@kolle/files/restart-cinnamon@kolle/applet.js
restart-cinnamon@kolle/files/restart-cinnamon@kolle/metadata.json
restart-cinnamon@kolle/files/restart-cinnamon@kolle/po/fr.po
restart-cinnamon@kolle/files/restart-cinnamon@kolle/po/restart-cinnamon.pot
restart-cinnamon@kolle/files/restart-cinnamon@kolle/settings-schema.json

@icarter09 
Some changes:
- Using `Main.restartCinnamon()` instead of `global.reexec_self()`
- Add the 'Show OSD' option; true by default.
- Updated .pot file.
- Updated fr.po file.
Is that OK for you?

[restart-cinnamon@kolle] - Add 'Show OSD' option

---

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md
Radio3.0@claudiux/files/Radio3.0@claudiux/lib/checkDependencies.js
Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json

[Radio3.0@claudiux] v1.4.2 - Add mpv-mpris as a dependency

---

qredshift@quintao/files/qredshift@quintao/icons/redshift-status-off-symbolic.svg
qredshift@quintao/files/qredshift@quintao/icons/redshift-status-on-symbolic.svg

@raphaelquintao 
Curiously, the symbolic icons in /usr/share/icons are not used in Cinnamon 5.8. Hence the creation of an 'icons' folder containing the two symbolic icons required for this applet to function properly.

[qredshift@quintao] Add symbolic icons for Cinnamon 5.8

---

CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot

1. Changed the behaviour of pooled buttons so that new buttons are added to the right, rather then the left, of the pool. This makes it consistent with the behaviour of new buttons that are not part of a pool. My original decision to add new pool buttons to the left was to avoid odd animation behaviour but some animation improvements makes this less of an issue for me. If anyone really liked the old behaviour let me know and I can think about adding a configuration option to control this behaviour.
2. Introduced a window-list button removal label animation (shrink the label until it's 0 length before completely removing the button). This particularly helps with making the animation appear smoother when closing the trailing button of an application pool with only one label.
3. Fixed …

[CassiaWindowList@klangman] Add new buttons on the right of the pool

---

windowlist@cobinja.de/files/windowlist@cobinja.de/5.4/applet.js

This applies css class .grouped-window-list-box instead of .window-list-box. The .grouped...-names was already used for the contents, just not for the container.
This replaces #4953

[windowlist@cobinja.de] Align style for the container actor with the names used for the contents

---

CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js

Change the Workspace BoxLayout to use the CSS class grouped-window-list-box which is consistent with the classes used for other elements. This has the benefit of removing some padding at the start and end of the window-list as well as reduce the padding between buttons on the list when on a horizontal panel.

[CassiaWindowList@klangman] Use CSS class grouped-window-list-box

---

weather@mockturtl/files/weather@mockturtl/3.8/LogSaver.py

In more verbose languages this was forcing the minimum width of the settings window to be wider than our minimum supported display resolution.
Ref: linuxmint/cinnamon#11785

weather@mockturtl: Enable word wrap on custom LogSaver widget.

---

InternetTimeApplet@stefan/files/InternetTimeApplet@stefan/applet.js

Change the hour/minute/second variable assignments to explicitly be in UTC format. Also, add one hour to the "getUTCHours()" call, as "Biel Mean Time" (BMT), which Beat Time is based upon, is defined by Swatch as UTC+1.
Previously this was calling Date's getHours/getMinutes/getSeconds function family, which returns LOCAL time. This had the effect of the Beat time returned by this desklet always being incorrect unless your computer's time is set to the UTC+1 timezone.
This commit fixes that and ensures that the correct universal Beat Time will be displayed regardless of the user's timezone. It also incorporates the calculation changes from @nstoeckigt via his previously-merged PR [here.](https://github.com/linuxmint/cinnamon-spices-desklets/pull/784)
Original author of this applet is …

InternetTimeApplet@stefan: Fix timezone for accurate Beat Time calculation

---

CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot

1. Added an option in the "Hotkeys" setting tab (enabled by default) called "Smart numeric hotkeys" which allows you to switch to the first 9 windows of a specific application as ordered on the window list. Creating a Hotkey containing the "1" key will automatically be extended to 1-9. For example, using a key sequence of "Alt+1" with a "description" of "firefox.desktop" will register hotkeys Alt+1 through Alt+9. Using those hotkeys will switch to one of the first 9 firefox windows based on the order of the windows on the window-list.
2. Fix a number of issues with hotkey sequence text not being properly added to button tool-tips.
3. Fix a number of issues with hotkeys not working properly after deleting, rearranging or modifying hotkey entries.
4. Fixed some issue around deciding which …

[CassiaWindowList@klangman] Add new smart numeric hotkeys

---

calc-js@ptandler/files/calc-js@ptandler/applet.js

Fix enter/return key was not recognised meaning history didn't work.
Fixes: #4851
@ptandler

[calc-js@ptandler] Fix enter/return key not recognised + history.

---

CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot

1. Added a new pinning configuration option that allows the user to force pinned buttons to be synchronized across all workspaces. This means that any changes to the pinned buttons (adding, deleting or rearranging) in one workspace will effect all workspaces. This allows you to maintain a consistent set of pinned buttons, particularly useful for the "launcher" configuration where you might like to have a consistent set of launcher buttons for all workspaces.
2. Added a new mouse action option called "Pin to panel toggle" which allows you to assign the "pin to panel" action to any mouse button or Ctrl/Shift+Button action you define. This action will toggle the pinned setting status for the panel button you clicked on.
3. If an existing "launcher" applet exists on a panel (ether a 2nd …

[CassiaWindowList@klangman] improvements with button pinning

---

windowlist@cobinja.de/files/windowlist@cobinja.de/5.4/applet.js

This is in line with changes to ClutterButtonEvent listed at https://github.com/linuxmint/cinnamon-spices-applets/issues/4364
Applet author: @Cobinja 
The old version of the code no longer worked on my machine - the "Close window on mouse-wheel click" setting is on, but middle-clicking results in the same behaviour as left-clicking.
```
Linux Mint 21.1 Cinnamon
Cinnamon 5.6.8
Kernel 5.15.0-76-generic
newest version of the applet installed
```

windowlist@cobinja.de: Update middle click for Cinammon 5.4

---

cpufreq@mtwebster/files/cpufreq@mtwebster/applet.js
cpufreq@mtwebster/files/cpufreq@mtwebster/settings-schema.json

@mtwebster: please have a look at this.
I just added two sliders for setting a percentage for the lower and upper border and modified num_to_color() to use the values calculated from that. This is straight forward and works for me out of the box after reloading the applet.

cpufreq@mtwebster: adding settings for configuring the lower and upper border

---

CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot

1. Remember manual grouped/ungrouped setting: When you set a particular application to be grouped/ungrouped against the default behaviour set by the configuration option "Window list behaviour style", the application specific preference will be saved and reapplied after a reboot or cinnamon restart.
2. All Buttons special case hotkey: Added a special case hotkey description called "All Buttons" which will cause the modifier+1-9 hotkeys to be mapped to the first 9 windows in the window-list. Using this with the <Super> modifier will allow you to have Super+1-9 work the same way that the standard Grouped Window List works. I added a default hotkey for this new "All Buttons" description but that will only appear in new instances (existing instances will have to add one manually). Simply add …

[CassiaWindowList@klangman] 4 new features and some fixes

---

CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot

1. Fixed hotkey hit bubbles so that hints are shown for pinned buttons that have no running windows.
2. Changed the hotkey hint bubbles to use upper case letters which makes it a bit easier to see on high resolution displays.

[CassiaWindowList@klangman] Fix hotkey hint bubbles for pinned buttons

---

CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js

I accidentally removed the ability to start new windows using a hotkey when the hotkey description is a .desktop file name and there is no pinned button on the window list for that application.

[CassiaWindowList@klangman] Fix regression caused by my last commit

---

hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/settings-schema.json

Reduce number of tabbed pages by combining the NET and DISK tabs so that they appear when config dialog is first opened.
If the tab bar is too wide for the window, it doesn't show until the window is widened.
fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/5065
fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/4439
fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/3818

hwmonitor@sylfurd: Reduce number of pages in config dialog.

---

MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/applet.js

On some installations it is not enough to call 'amixer'. There an
additional parameter is needed: 'amixer -D pulse' for amixer to find the
proper channel. This PR checks, if it can find the 'Capture' channel
with 'amixer' and if not successful with 'amixer -D pulse'.

[MuteToggler@jebeaudet.com] Automatically decides which 'amixer' parameter to use (Closes #3979)

---

sound150@claudiux/files/sound150@claudiux/5.4/applet.js
sound150@claudiux/files/sound150@claudiux/CHANGELOG.md
sound150@claudiux/files/sound150@claudiux/metadata.json

This makes use of the PR
https://github.com/linuxmint/cinnamon/pull/11914.
@claudiux

[sound150@claudiux] Updates the contextual menu when flipping the 'Mute input' switch in the settings

---

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md
Radio3.0@claudiux/files/Radio3.0@claudiux/lib/checkDependencies.js
Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json

Updated dependencies.js for Soup3 on:
* Mint
* Debian
* Fedora
* Arch
* openSUSE

[Radio3.0@claudiux] v1.8.0 - Updated dependencies.js for Soup3

---

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md
Radio3.0@claudiux/files/Radio3.0@claudiux/lib/checkDependencies.js
Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json
Radio3.0@claudiux/files/Radio3.0@claudiux/scripts/update-yt-dlp.sh

and change location of yt-dlp: from `~/bin/` to `~/.local/bin/`.

[Radio3.0@claudiux] v1.9.0 - Use pipeware on Fedora Cinnamon 5.8+

---

CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot

1. Clear the window count bubbles before showing the hotkey-help bubbles so that only buttons with relevant hotkeys will have any bubbles shown when the hotkey-help hotkey is used, even when there is no hotkey-help to show. This is less confusing for the user when hitting the help hotkey.
2. Fixed the new window animation to only effect the window list button if that button is going to be the button tracking the new window.
3. Update the "Advanced" config tab help text box to document the cinnamon fix that is required in order for the "Ctrl/Shift + mouse button actions" list to correctly display the two middle column contents.
https://github.com/linuxmint/cinnamon/pull/11908

[CassiaWindowList@klangman] Fix hotkey-help and new window animations

---

timer@Severga/files/timer@Severga/applet.js
timer@Severga/files/timer@Severga/settings-schema.json

@Severga 
Hi,
When mintupdate updates xlets in use, Cinnamon restarts and the timer is reset.
This PR preserves timer (and "turn off" status) despite the applet restart.
Are these changes to your liking?
Regards
Claudiux

[timer@Severga] Preserves timer despite applet restart

---

MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/applet.js

@jebeaudet 
When the applet restarts or is "removed from the panel", the old loop continues. This PR fixes this bug.

[MuteToggler@jebeaudet.com] Stop loop when applet is removed from panel

---

healthyeyes@ipolozov/README.md
healthyeyes@ipolozov/files/healthyeyes@ipolozov/applet.js
healthyeyes@ipolozov/files/healthyeyes@ipolozov/metadata.json

Currently the icon automatically changes back within a minute of it first changing, meaning the change is easy to miss.

healthyeyes@ipolozov - Changed so that clicking the applet makes the colour change back

---

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md
Radio3.0@claudiux/files/Radio3.0@claudiux/lib/checkDependencies.js
Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json

Fixes the bug reported by @Neonteepee on https://cinnamon-spices.linuxmint.com/applets/view/360.

Remove libmpv1 or libmpv2 dependency for LM and Debian

---

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md
Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js
Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json
Radio3.0@claudiux/files/Radio3.0@claudiux/po/Radio3.0@claudiux.pot
Radio3.0@claudiux/files/Radio3.0@claudiux/po/fr.po
Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json

Moves the "Do not check dependencies" option from the Settings Behavior tab to the context menu. This avoids error messages.

v1.11.1 - Moves the 'Do not check dependencies' option from the Settings Behavior tab to the context menu

---

MonitorInputSource@klangman/files/MonitorInputSource@klangman/applet.js

Once the exitcode has been processed and the menu has been updated to show an error, reset the exitcode so that a refresh has a chance to succeed and populate the menu with new monitor input entries.

[MonitorInputSource@klangman] Reset exitcode after menu update

---

CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot

1. Added an option (General:Include windows from all workspaces) that will show windows from other workspaces on the current window list. Clicking on a window from another workspace will cause the current workspace to switch to that windows workspace. Rearranging the windows on one workspace will not affect the window arrangement on other workspaces window lists.
2. Window-list tooltips will now have bold window title text and smaller hotkey text to emphasize the window title and deemphasize the hotkey text.
3. Don't include transient windows in the window Thumbnails.This matches how the standard grouped-window-list handles thumbnail windows.
4. Fix focus tracking for windows with child transient windows that get the focus after its parent window had the focus.
5. Use …

[CassiaWindowList@klangman] Add option show windows from all workspaces

---

rswitcher@nixdev.com/files/rswitcher@nixdev.com/rswitcher

Added a reload of the Cinnamon menu applet after we change the resolution / scaling. 
This is so we get the correct scaling of the menu.

Reloading Cinnamon Menu to get correct dimentions

---

CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot

The "All Buttons" default hotkey entry uses an English "All Buttons" which can't be translated but the hard-coded "all buttons" string in the code is translated and therefore the default "All Buttons" entry would not work unless the description string was changed to a translation of "All Buttons". This fix allows both English and a translation to work.

[CassiaWindowList@klangman] Fix "All Buttons" hotkey with translations

---

download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletGui.js

Don't set the values for only the **text** or the **fixed_width** values if each is null or undefined. Also added a space to the fixed width string to give a small margin between the text and the icon, this was making the bytes not being shown correctly because they were too close to the icon.
cc @cardsurf

download-and-upload-speed@cardsurf: Made some small fixes

---

qredshift@quintao/files/qredshift@quintao/applet.js
qredshift@quintao/files/qredshift@quintao/metadata.json
qredshift@quintao/files/qredshift@quintao/po/es.po
qredshift@quintao/files/qredshift@quintao/po/fr.po
qredshift@quintao/files/qredshift@quintao/po/qredshift@quintao.pot
qredshift@quintao/files/qredshift@quintao/settings-schema.json

@raphaelquintao 
This PR adds an option "Activate QRedshift as soon as Cinnamon starts up".
This way, QRedshift can be activated even if it was previously deactivated.

[qredshift@quintao] v1.7.6 - Adds option 'Activate as soon as Cinnamon starts up'

---

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md
Sensors@claudiux/files/Sensors@claudiux/applet.js
Sensors@claudiux/files/Sensors@claudiux/metadata.json
Sensors@claudiux/files/Sensors@claudiux/stylesheet.css

Fixes #4986
From now on, the monospace font style is only used when size must be preserved.

[Sensors@claudiux] v3.3.0 - Fixes #4986

---

qredshift@quintao/files/qredshift@quintao/applet.js
qredshift@quintao/files/qredshift@quintao/settings-schema.json

Redshift is not supported yet by Wayland and running the applet while Cinnamon is running under Wayland may cause the system to completely freeze, even not initilizing successfuly. Some people also reported on Reddit having this same issue https://www.reddit.com/r/linuxmint/comments/195dsmu/blank_screen_on_experimental_wayland_session/
cc @raphaelquintao

qredshift@quintao: hotfix: disable by default under Wayland

---

sound150@claudiux/files/sound150@claudiux/5.4/applet.js
sound150@claudiux/files/sound150@claudiux/CHANGELOG.md
sound150@claudiux/files/sound150@claudiux/metadata.json
sound150@claudiux/files/sound150@claudiux/po/fr.po

* Use Ctrl-Middle-Click or Shift-Middle-Click to toggle mute as defined in settings.
* Takes into account an undefined input.
* Updates French translation.

sound150@claudiux - v5.1.1

---

CassiaWindowList@klangman/README.md
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot

1. Added an option to adjust the spacing between the window-list buttons
2. Added an option to disable the 'new window' icon animation effect
3. Process the window title text to make sure that the title text does not prevent the window-list button tooltips from formatting correctly.
4. Only apply tooltip formatting in Cinnamon 5+
5. Moved the "Hide window buttons of pinned buttons on other CassiaWindowList instances" option to the advanced tab to make space for the new options described above. I doubt anyone uses this option so it belongs under advanced anyhow.

[CassiaWindowList@klangman] Icon spacing and animation disable options

---

devbar@ludvigbostrom/files/devbar@ludvigbostrom/applet.js
duolingo-helper@nodeengineer.com/files/duolingo-helper@nodeengineer.com/applet.js
feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/feedreader.js
location-detection@heimdall/files/location-detection@heimdall/applet.js
nightscout@ranneft/files/nightscout@ranneft/applet.js
wakatimedisplay@inventor96/files/wakatimedisplay@inventor96/applet.js

We're hopefully going to switch Cinnamon to requiring soup 3 for 5.8 (distros are starting to drop soup 2), so I went thru and tried to update applets that hadn't been given soup 3 compatibility yet.
Most of these I couldn't test the actual http requests as they require accounts and api keys, but I hope to at least get the ball rolling so maybe the appropriate maintainers can cherry-pick from this, or I or they can open an individual PR for their applet.
@claudiux (VPN-Sentinel@claudiux)
@ludvigbostrom (devbar@ludvigbostrom)
@inventor96 (wakatimedisplay@inventor96)
@ImmRanneft (nightscout@ranneft)
not sure about others...
Thanks

Soup 3 cleanup

---

weather@mockturtl/CHANGELOG.md
weather@mockturtl/files/weather@mockturtl/3.8/settings-schema.json
weather@mockturtl/files/weather@mockturtl/3.8/weather-applet.js
weather@mockturtl/files/weather@mockturtl/metadata.json
weather@mockturtl/files/weather@mockturtl/po/weather@mockturtl.pot
weather@mockturtl/package.json
weather@mockturtl/src/3_8/config.ts
weather@mockturtl/src/3_8/lib/httpLib.ts
weather@mockturtl/src/3_8/lib/soupLib.ts
weather@mockturtl/src/3_8/location_services/geoip_services/geoclue.ts
weather@mockturtl/src/3_8/location_services/geoip_services/geoip.fedora.ts
weather@mockturtl/src/3_8/main.ts
weather@mockturtl/src/3_8/tsconfig.json
weather@mockturtl/src/3_8/types.ts

Changes:
* Fix https://github.com/linuxmint/cinnamon-spices-applets/issues/5212 
* Fix https://github.com/linuxmint/cinnamon-spices-applets/issues/5392
* Resolve https://github.com/linuxmint/cinnamon-spices-applets/issues/5355 - Use GeoClue as primary source for autolocation, fall back to Internet services
* Add description to Manual location entry
* Fix Saving Logs button not included the redacted config
* Update types for applet
* Use fedora geoip project for autolocation via the internet
TODO:

weather@mockturtl 3.4.0

---

directory-menu@torchipeppo/files/directory-menu@torchipeppo/applet.js
directory-menu@torchipeppo/files/directory-menu@torchipeppo/metadata.json
directory-menu@torchipeppo/files/directory-menu@torchipeppo/po/directory-menu@torchipeppo.pot
directory-menu@torchipeppo/files/directory-menu@torchipeppo/popup_menu.py
directory-menu@torchipeppo/files/directory-menu@torchipeppo/settings-schema.json

Add translation template
Add a terminal option for non-Debian-based distros
This addresses the execution functionality of the applet.
cc @torchipeppo

directory-menu@torchipeppo: Add execution to 'Open' functions

---

directory-menu@torchipeppo/files/directory-menu@torchipeppo/po/directory-menu@torchipeppo.pot
directory-menu@torchipeppo/files/directory-menu@torchipeppo/popup_menu.py

This will allow the texts "Open in folder" and "Open in terminal" on the popup menu to be translated into other languages.
cc @torchipeppo
Blocked by #5458

directory-menu@torchipeppo: Adapt popup menu for translation

---

CassiaWindowList@klangman/README.md
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot

1. Added a new Window-list button & Thumbnail menu item options that will cause a full size window preview to appear when hovering over a window-list button or a Thumbnail menu item.
2. Added new options to automatically active windows when leaving the panel/menu (no click focus changing). This allows the user to activate a window by simply moving to mouse over a window-list button or a Thumbnail menu item and then moving back towards the middle of the screen. The action can be cancelled by holding the Ctrl or Shift keys before leaving the panel/menu, or by leaving the panel/menu by moving the pointer off either end of the window-list/menu. The config option to enable this feature for the window-list is in the General tab and the option for the Thumbnail menu is in the Thumbnail tab.
3. …

[CassiaWindowList@klangman] Add hover-peek, no click activate, and fixes

---

ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/ABOUT.txt
ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/RELEASE.txt
ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/applet.js
ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/popupImageLeftMenuItem.js

While clicking for the first time on an item menu, the command is not executed and the following error is recorded on xsession-errors:
`JS ERROR: Exception in callback for signal: activate: TypeError: Main.Util is undefined`
fix #5444

Fix "Main.Util undefined" error

---

directory-menu@torchipeppo/README.md
directory-menu@torchipeppo/files/directory-menu@torchipeppo/applet.js
directory-menu@torchipeppo/files/directory-menu@torchipeppo/metadata.json
directory-menu@torchipeppo/files/directory-menu@torchipeppo/po/it.po
directory-menu@torchipeppo/files/directory-menu@torchipeppo/popup_menu.py
directory-menu@torchipeppo/files/directory-menu@torchipeppo/settings-schema.json

While using this applet I noticed I kept visiting a folder with files that need pretty long names, which made the menu exceedingly large and slowed down navigation to the next subdirectory.
So I just added a simple, completely optional functionality to truncate the displayed file names and thus limit the width of the menu. Maybe it'll be of use to someone else too.
While I was at it, I added an Italian translation too. I quickly switched my system language and all the strings appear to be in order.
A fabricated example of the new setting in action:

directory-menu@torchipeppo: add a new setting to truncate long file names, and an Italian translation

---

suspend@janax/files/suspend@janax/README.md
suspend@janax/files/suspend@janax/applet.js
suspend@janax/files/suspend@janax/metadata.json
suspend@janax/files/suspend@janax/po/da.po
suspend@janax/files/suspend@janax/po/de.po
suspend@janax/files/suspend@janax/po/es.po
suspend@janax/files/suspend@janax/po/fr.po
suspend@janax/files/suspend@janax/po/hr.po
suspend@janax/files/suspend@janax/po/hu.po
suspend@janax/files/suspend@janax/po/it.po
suspend@janax/files/suspend@janax/po/pt_BR.po
suspend@janax/files/suspend@janax/po/ru.po
suspend@janax/files/suspend@janax/po/suspend@janax.pot
suspend@janax/files/suspend@janax/po/sv.po
suspend@janax/files/suspend@janax/po/zh_CN.po
suspend@janax/files/suspend@janax/settings-schema.json
suspend@janax/info.json

I believe this applet has been abandoned, so I am offering the following changes. I could also submit this as a separate applet if you think that better given the extent of the changes?
1. Rewritten in Javascript EC6
2. Added an option to require a double-click to suspend (reducing accidental suspends).
3. Added a count-down option to allow the user some time to abort the suspend by clicking on the applet icon a second time. The count-down is displayed using a icon-overlay badge like the one used by the grouped-windowlist applet for showing the window count.
4. Added an option to configure the count-down duration
4. Added a README.md.
5. Made the applet allow multiple instances (mainly for people with multiple monitors).
6. Added an option to use a symbolic or full color icon on the …

[suspend@janax] Add  double-click and count-down options

---

color-picker@fmete/files/color-picker@fmete/cp.py

Fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/4711
The provided fix allows the color picker to also work when display scaling is used. Previously when using the color picker with display scaling, it would report either #000000 or an incorrect color (when picking a color somewhere in the upper left color of the screen).
Tested locally with a multi-monitor setup with different resolutions for each monitor and with multiple different scaling settings.

Fix color-picking when display scaling is used

---

ssm@Severga/files/ssm@Severga/applet.js

It turned out that the applet's list of net interfaces is shown incorrectly after turning off and on some connections in Network Manager. The signals I was able to find and use do not cover all changes that happen and the list sometimes doesn't change automatically, except after reloading the applet. Instead of signals I decided to use periodical net interfaces look-up every 30 sec.
I understand that this is not an efficient solution, and if somebody can help me with the signals, I would appreciate it very much.

[ssm@Severga] Improve net list update

---

directory-menu@torchipeppo/files/directory-menu@torchipeppo/metadata.json
directory-menu@torchipeppo/files/directory-menu@torchipeppo/popup_menu.py

cc @torchipeppo This adds support for terminals installed via Flatpak (e.g. [Black Box](https://flathub.org/apps/com.raggesilver.BlackBox))
Shout if you want to change the version too.

directory-menu@torchipeppo: Add support for Flatpak terminals

---

kdecapplet@joejoetv/files/kdecapplet@joejoetv/applet.js
kdecapplet@joejoetv/files/kdecapplet@joejoetv/metadata.json
kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/de.po

- Fixed bug that prevented the applet from showing the correct error message to the user, if KDE Connect was not installed or running
- Fixed spelling error in german language file

[kdecapplet@joejoetv] Version 2.1.1 - Small bug fix

---

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/de.po

It makes no sense to translate the proper name "Spice"/"Spices" literally to German as "Gewürz". This just adds confusion.

SpicesUpdate@claudiux: Update German translations

---

search-box@mtwebster/files/search-box@mtwebster/5.4/applet.js
search-box@mtwebster/files/search-box@mtwebster/metadata.json

Both Enter keys can be used.
Using a temporary search engine (such as "ddg linux mint iso", which uses DuckDuckGo to search for 'linux mint iso') does not change the search engine selected by the user prior to this query.
Ping #5666.

[search-box@mtwebster] v2.0.0

---

gpumonitor@axel358/files/gpumonitor@axel358/applet.js
gpumonitor@axel358/files/gpumonitor@axel358/settings-schema.json

@axel358
Add a setting to select a specific GPU to monitor in case there are multiple GPUs (including integrated graphics for example).
Uses `lshw -C display` to get a list of GPUs, but I am not sure how to get the full name of the GPU, so currently shows just the bus number which is passed on to radeontop.

gpumonitor@axel358: add setting to select GPU

---

azan@fahri.nurul.id/files/azan@fahri.nurul.id/applet.js

Set "expand" to "false" to address the issue of prayer times not being displayed correctly.

Fix prayer times appearance

---

ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/applet.js

Added ability to scroll on the applet icon to change the brightness without having to actually open it and move the slider. (With a lot of inspiration and code taken from the built-in [sound@cinnamon.org](https://github.com/linuxmint/cinnamon/tree/8214ed15927d59e4a7054404c2c584eeb4ba4a05/files/usr/share/cinnamon/applets/sound%40cinnamon.org)) 
I haven't tested it on a multi-monitor setup, but I think it would just increase or decrease the brightness of all the monitors.
I also changed a few quirks of the applet, such as not showing the real brightness of the monitor when opened, just the last brightness it was set to by the applet.

ddcci-multi-monitor@tim-we: Added changing brightness on scrolling applet icon.

---

pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/applet.js
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/metadata.json
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/ca.po
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/da.po
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/de.po
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/es.po
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/fi.po
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/fr.po
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/hr.po
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/hu.po
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/it.po
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/nl.po
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/pl.po
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/pomodoro@gregfreeman.org.pot
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/pt_BR.po
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/sv.po
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/tr.po
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/uk.po
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/zh_CN.po
pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/timer.js

* Adding a requested feature that allows the user to skip the current timer, useful if you want to end the current pomodoro or break early

pomodoro@greg.freeman.org: Add new feature to skip current timer

---

mylauncher@markbokil.com/files/mylauncher@markbokil.com/applet.js
mylauncher@markbokil.com/files/mylauncher@markbokil.com/mylauncher.properties

When updating the mylauncher@markbokil.com, it will overwrite any custom menu settings. This is due to the configuration file being present in the applets code directory. This change uses the applets files as a default configuration and copies the contents to the .config sub directory in the users home. This means that the configuration will survive applet updates in the future.
Fixed a hardcoded username in the default configuration for the home directory to the tilde shortcut
Fixed command line library references from Main.Util to Util.
@mbokil

mylauncher@markbokil.com: Fix issue where updating the applet will remove custom menu config

---

CassiaWindowList@klangman/CHANGELOG.md
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/metadata.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/da.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/es.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fr.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/hu.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/nl.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ru.po

1. Don't close the existing thumbnail menu and open a new one when the mouse hover moves between different buttons in the same application pool (as long as the menu does have an item for the currently hovered button's window). This removes the useless thumbnail menu close then open sequence when using the application pooling behaviour and the thumbnail menus are configured to show all pooled windows.
2. Print hotkeys in a pretty way for the button context menus "Assign window to a kotkey" sub-menu list.
3. Minor fixes and optimizations

[CassiaWindowList@klangman] Minor improvements, fixes and optimizations

---

placesCenter@scollins/files/placesCenter@scollins/applet.js
placesCenter@scollins/files/placesCenter@scollins/metadata.json
placesCenter@scollins/files/placesCenter@scollins/po/bg.po
placesCenter@scollins/files/placesCenter@scollins/po/da.po
placesCenter@scollins/files/placesCenter@scollins/po/de.po
placesCenter@scollins/files/placesCenter@scollins/po/es.po
placesCenter@scollins/files/placesCenter@scollins/po/eu.po
placesCenter@scollins/files/placesCenter@scollins/po/fi.po
placesCenter@scollins/files/placesCenter@scollins/po/fr.po
placesCenter@scollins/files/placesCenter@scollins/po/hr.po
placesCenter@scollins/files/placesCenter@scollins/po/hu.po
placesCenter@scollins/files/placesCenter@scollins/po/it.po
placesCenter@scollins/files/placesCenter@scollins/po/placesCenter@scollins.pot
placesCenter@scollins/files/placesCenter@scollins/po/sv.po
placesCenter@scollins/files/placesCenter@scollins/po/tr.po
placesCenter@scollins/files/placesCenter@scollins/po/uk.po
placesCenter@scollins/files/placesCenter@scollins/po/zh_CN.po
placesCenter@scollins/files/placesCenter@scollins/settings-schema.json

@collinss 
Hi Stephen,
This PR is to show the uri of each recent document in its tooltip.
This is useful when several documents have the same name (like `applet.js` - which applet is it?).
I hope you find these changes satisfactory.
Regards
claudiux

placesCenter@scollins v2.3 - Allows to show entire path in Recent Documents tooltips

---

CassiaWindowList@klangman/CHANGELOG.md
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/metadata.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/da.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/es.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fr.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/hu.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/nl.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ru.po

When in button pooling mode with a thumbnail menu open showing more then one window, highlight the thumbnail menu item matching the window of the windlow-list button that is currently being hovered by the mouse pointer.

[CassiaWindowList@klangman] Improve thumbnail menu Highlighting

---

color-picker@fmete/files/color-picker@fmete/cp.py

This fixes an issue where the color picker spice gets stuck when starting color picking while the mouse button is already pressed.
It was caused because xlib returned an error status (`AlreadyGrabbed`) that wasn't handled, subsequently waiting for a mouse release event will never succeed.
Fixes #6019.

color-picker@fmete: Fix stuck state when mouse already held down (#6019)

---

CassiaWindowList@klangman/CHANGELOG.md
CassiaWindowList@klangman/README.md
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/6.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/metadata.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/da.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/es.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fr.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/hu.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/nl.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ru.po

1. Added an option to configure what the "number label" content represents (Window count, Workspace index or Monitor number).
2. Added an option to show a vertical ellipsis character on grouped buttons to indicate a button represents a group of windows. Useful when the user decides to use the number label for Workspace/Monitor number and needs a new way to mark grouped buttons.
3. Added 4 new mouse action options that will activate windows 1-4 of a grouped button
4. Change the "2 or more window" option in the "Display number" drop-down to "Smart" so that it can apply to other number label options.
5. Removed the "Display number" "Never" option as now the "Number Style" option can disable the number label
6. In Launcher mode the "Number Style" option now appears but it's effects do not …

[CassiaWindowList@klangman] Three new features

---

weather@mockturtl/README.md
weather@mockturtl/files/weather@mockturtl/3.8/weather-applet.js
weather@mockturtl/src/3_8/utils.ts

Fixes \n, \\\\n or %n not inserting a line break in the Override label and Override tooltip.

Weather, Add line break {br} for Override label and Override tooltip

---

SpiceSpy@claudiux/files/SpiceSpy@claudiux/CHANGELOG.md
SpiceSpy@claudiux/files/SpiceSpy@claudiux/README.md
SpiceSpy@claudiux/files/SpiceSpy@claudiux/applet.js
SpiceSpy@claudiux/files/SpiceSpy@claudiux/metadata.json

* From now on, for each Spice row:
* clicking on the Spice name (or UUID) or on its icon or on its score opens its web page, at the top of this page.
* clicking on the Spice comments opens its web page, at the comments section.
* clicking on the Spice translations opens the web page showing the status of translations.
* Several bugfixes.

[SpiceSpy@claudiux] v2.0.0

---

bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/applet.js
bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/icons/headphones-000.svg
bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/icons/headphones-020.svg
bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/icons/headphones-030.svg
bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/icons/headphones-040.svg
bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/icons/keyboard-000.svg
bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/icons/keyboard-020.svg
bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/icons/keyboard-030.svg
bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/icons/keyboard-040.svg
bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/icons/mouse-000.svg
bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/icons/mouse-020.svg
bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/icons/mouse-030.svg
bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/icons/mouse-040.svg

bluetooth-battery@zamszowy: treat 'HEADSET' device as a headphones
Some headphones present themselves as a 'HEADSET' UPower device kind, so
treat them as a headphones, instead of a generic (blacklisted by
default) device.
bluetooth-battery@zamszowy: make icons more in line with the system
Show battery level icons just like the system is showing its icons for
the laptop battery:
- don't round percent values, use floor instead (e.g. instead of
showing icon for 30% when battery was 25-34, show 30% icon only
when battery is 30-39)
- show warning level only when between 20% - 29%
- show critical level when between 0% - 19%
- show now additionally exclamation mark when below 10%

bletooth-battery@zamszowy: headset and icons

---

CassiaWindowList@klangman/CHANGELOG.md
CassiaWindowList@klangman/README.md
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/6.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/metadata.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ca.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/da.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/es.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fr.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/hu.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/nl.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ru.po

1. Allow rearranging Thumbnail menu items using drag-and-drop
2. Allow drag-and-drop from the Thumbnail menu to the desktop, matching the behaviour of window-list button drag-and-drop
3. Add options for hiding button labels when the windows workspace/monitor is not the current workspace/monitor
4. Fixed how labels are hidden for grouped buttons so that it's solely based on the current windows state
5. Added an option to sort the Thumbnail menu for grouped buttons based on the Workspace & Monitor index
6. Fix a cases where Thumbnail menus can contain stale window titles or even contain windows that have been closed
7. Fix to show labels for application pools where some, but not all, windows in the pool don't qualify to have a label
8. Updated the tooltip for the "Hide labels for" option to …

[CassiaWindowList@klangman] Version 2.3.0

---

Cinnamenu@json/files/Cinnamenu@json/5.8/appsview.js
Cinnamenu@json/files/Cinnamenu@json/5.8/categoriesview.js
Cinnamenu@json/files/Cinnamenu@json/5.8/sidebar.js

Closes #6219
Ref: linuxmint/cinnamon#11123
cc @fredcw

Cinnamenu@json: Set clip_to_allocation to true

---

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/applet.js

Fix clicking on items outside of menu bug https://github.com/linuxmint/cinnamon/issues/11123
tested on cinnamon 6.2 and mint 19.3 (cinnamon 4.4)

CinnVIIStarkMenu@NikoKrause: bug fix

---

ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/applet.js

ddcci-multi-monitor@tim-we is not working after last update, gives an error Glib not found. Fixed this error.

ddcci-multi-monitor@tim-we: bugfix

---

placesCenter@scollins/files/placesCenter@scollins/applet.js
placesCenter@scollins/files/placesCenter@scollins/metadata.json

Due to changes in `js/ui/placesManager.js`, this applet was buggy in Cinnamon 6.2 (Mint 22).
This PR fixes that.

[placesCenter@scollins] v2.4 - Now compatible with Cinnamon 6.2 (Mint 22)

---

CassiaWindowList@klangman/CHANGELOG.md
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/metadata.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ca.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/da.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/es.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fr.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/hu.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/nl.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ru.po

1. Enable Cinnamon restore/minimize animation by setting window icon geometry
2. Fix (hopefully) an exception seen opening a context menu under Mint 22
3. Fix blurry icons caused by not respecting the panel setting for colored icon sizes

[CassiaWindowList@klangman] Version 2.3.2

---

shutdown-timer@webum.by/files/shutdown-timer@webum.by/applet.js

The "Shutdown" and "Log out" options in the menu are presented in English even if running with a non-English locale. This is because the strings don't match the ones available in cinnamon.mo.

shutdown-timer@webum.by: Changed "Shutdown" and "Log out" strings to the same ones used in cinnamon.mo to facilitate proper translation

---

Radio3.0@claudiux/files/Radio3.0@claudiux/po/de.po

Provide German translations for Radio3.0 applet.
@claudiux
I could not translate the button labels for shortcuts in the menu since they were not in the pot file:

Radio3.0@claudiux: Add German (de) translations

---

download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/metadata.json
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/bg.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/ca.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/da.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/de.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/download-and-upload-speed@cardsurf.pot
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/es.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/fi.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/fr.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/hr.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/hu.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/it.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/nl.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/pl.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/pt.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/sv.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/tr.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/zh_CN.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/settings-schema.json

@cardsurf 
Binary or decimal units can now be selected in settings.
'Decimal' is the default.
Also, units are now translatable. French translation is provided.
I hope you'll like these changes.
Claudiux
N.B. I can do the same for disk-read-and-write-speed@cardsurf if you wish.

[download-and-upload-speed@cardsurf] v1.6.6 - Binary or decimal units can now be selected

---

ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/applet.js

Add a retry mechanism to ddcci-multi-monitor@tim-we for setting the brightness and raise some timeouts.
For updating brightness, retry up to 16 times and increase timeout to 5000ms.
For querying, increase timeout to 500ms.
This should improve the DDC/CI brightness applet functionality with monitors which are slow/unreliable reading/updating DDC/CI brightness.
The way it is done (with the send/sent_brightness) also minimizes cascading of updates if the brightness is changed quickly in succession.
cc @GingerGigiCat @tim-we

ddcci-multi-monitor@tim-we: Retry setting brightness and raise timeouts

---

CassiaWindowList@klangman/CHANGELOG.md
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/metadata.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ca.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/da.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/es.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fr.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/hu.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/nl.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ru.po

1. Fix the number bubble showing up incorrectly after changing the UI scale settings in display setting application.
2. Add a 2nd setting of the "runWizard" to "0" (this time in the window-list Javascript code rather than just in the wizard python code) to try an ensure that the welcome wizard does not reappear after a restart (I had a report of this happening but couldn't get to the bottom of why it occurred).

[CassiaWindowList@klangman] 2.3.5 Fix for UI scale changes

---

screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/CHANGELOG.md
screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/applet.js
screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/metadata.json
screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/ca.po
screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/da.po
screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/de.po
screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/es.po
screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/fr.po
screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/hu.po
screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/it.po
screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/nl.po
screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/screen-inhibit@mtwebster.pot
screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/sv.po
screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/zh_CN.po
screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/settings-schema.json

As requested by @melomane63 on https://cinnamon-spices.linuxmint.com/applets/view/59.

[screen-inhibit@mtwebster] v2.2.0 - Add a timer to end screen saver inhibition

---

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.0/prefsui.glade

With 16+ cores, the value 100 is very low.

Allow higher width for cpu in multicore-sys-monitor

---

Sensors@claudiux/files/Sensors@claudiux/applet.js
Sensors@claudiux/files/Sensors@claudiux/lib/constants.js
Sensors@claudiux/files/Sensors@claudiux/lib/sensorsReaper.js

Use the nvidia-smi tool (https://developer.nvidia.com/system-management-interface) to read GPU temperatures 
Spice author: @claudiux 
References: #6078

Sensors@claudiux: add support for Nvidia SMI temperatures

---

sound150@claudiux/files/sound150@claudiux/5.4/applet.js
sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json
sound150@claudiux/files/sound150@claudiux/6.4/applet.js
sound150@claudiux/files/sound150@claudiux/6.4/settings-schema.json
sound150@claudiux/files/sound150@claudiux/CHANGELOG.md
sound150@claudiux/files/sound150@claudiux/metadata.json

Try to solve https://github.com/linuxmint/cinnamon/issues/12446
How it works: When new option is checked, the output is muted at shutdown.

[sound150@claudiux] v7.1.0 - Option to try to avoid loud cracking sound at shutdown

---

sound150@claudiux/files/sound150@claudiux/5.4/applet.js
sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json
sound150@claudiux/files/sound150@claudiux/6.4/applet.js
sound150@claudiux/files/sound150@claudiux/6.4/settings-schema.json
sound150@claudiux/files/sound150@claudiux/CHANGELOG.md
sound150@claudiux/files/sound150@claudiux/README.md
sound150@claudiux/files/sound150@claudiux/metadata.json
sound150@claudiux/files/sound150@claudiux/po/ca.po
sound150@claudiux/files/sound150@claudiux/po/da.po
sound150@claudiux/files/sound150@claudiux/po/es.po
sound150@claudiux/files/sound150@claudiux/po/fi.po
sound150@claudiux/files/sound150@claudiux/po/fr.po
sound150@claudiux/files/sound150@claudiux/po/hu.po
sound150@claudiux/files/sound150@claudiux/po/it.po
sound150@claudiux/files/sound150@claudiux/po/nl.po
sound150@claudiux/files/sound150@claudiux/po/ru.po
sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot
sound150@claudiux/files/sound150@claudiux/po/sv.po

This is now the default, with no options.
Related to https://github.com/linuxmint/cinnamon/issues/12446

[sound150@claudiux] v7.1.1 - Avoids loud cracking sound at shutdown

---

bash-sensors@pkkk/files/bash-sensors@pkkk/settings-schema.json

Every 60s is too frequent for many uses of bash-sensors. Increasing the max value allows for more options.

Increase refreshInterval max value to 3600 seconds

---

batterypower@joka42/files/batterypower@joka42/applet.js

I have changed the check for the folder of battery information to a list, so it should work for multiple batteries

Fix multiple batteries are not working (Issue #6480)

---

CassiaWindowList@klangman/CHANGELOG.md
CassiaWindowList@klangman/README.md
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/6.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/metadata.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ca.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/da.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/es.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fr.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/hu.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/nl.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ru.po

* Added scroll-wheel options, cycle all window-list windows and cycle group/pool windows
* The "active" class (window-list button underline in MintY theme) is now used as an active window highlight when pinning is disabled
* Fixed bug preventing pinned buttons from being removed after disabling the pinned buttons support ("Pinning of window list buttons" -> "Disabled")
* The window-list mouse scroll-wheel action will apply when the Thumbnail menu is open and the Thumbnail menu scroll-wheel setting is "Disabled"
* If the active window changes when the Thumbnail menu is open, the outlined Thumbnail menu item will change if the new active window is one of the menu items

[CassiaWindowList@klangman] 2.3.7 new scroll-wheel options and fixes

---

Exit@claudiux/files/Exit@claudiux/5.4/applet.js
Exit@claudiux/files/Exit@claudiux/5.4/settings-schema.json
Exit@claudiux/files/Exit@claudiux/CHANGELOG.md
Exit@claudiux/files/Exit@claudiux/README.md
Exit@claudiux/files/Exit@claudiux/metadata.json
Exit@claudiux/files/Exit@claudiux/po/Exit@claudiux.pot
Exit@claudiux/files/Exit@claudiux/po/ca.po
Exit@claudiux/files/Exit@claudiux/po/de.po
Exit@claudiux/files/Exit@claudiux/po/es.po
Exit@claudiux/files/Exit@claudiux/po/fi.po
Exit@claudiux/files/Exit@claudiux/po/fr.po
Exit@claudiux/files/Exit@claudiux/po/hu.po
Exit@claudiux/files/Exit@claudiux/po/it.po
Exit@claudiux/files/Exit@claudiux/po/nl.po

New option: Screen Off. Also you can set the duration of deactivation of the mouse to prevent the screen to turning on too soon after turning it off.
Idea from https://github.com/orgs/linuxmint/discussions/676.

[Exit@claudiux] v1.3.0 - New option: Screen Off

---

sound150@claudiux/files/sound150@claudiux/4.6/applet.js
sound150@claudiux/files/sound150@claudiux/5.4/applet.js
sound150@claudiux/files/sound150@claudiux/6.4/applet.js

fixes https://github.com/linuxmint/cinnamon/issues/9472
Users migrating from other operating systems might expect that changing the volume slider would play an audible tone to indicate how loud the volume is. Right now, the only ways to get this tone to play from the applet are to use the keyboard or mouse scroll wheel. This adds another option for users who prefer to use mouse/touch screen or don't have a mouse wheel to hear how loud the volume is.
@claudiux

sound150@claudiux: Play volume change sound after changing volume via dragging slider

---

calendar@ccprog/CHANGELOG.md
calendar@ccprog/files/calendar@ccprog/5.2/applet.js
calendar@ccprog/files/calendar@ccprog/5.2/eventView.js
calendar@ccprog/files/calendar@ccprog/5.2/holidays.js
calendar@ccprog/files/calendar@ccprog/5.2/settings-schema.json
calendar@ccprog/files/calendar@ccprog/metadata.json
calendar@ccprog/files/calendar@ccprog/po/ca.po
calendar@ccprog/files/calendar@ccprog/po/calendar@ccprog.pot
calendar@ccprog/files/calendar@ccprog/po/da.po
calendar@ccprog/files/calendar@ccprog/po/de.po
calendar@ccprog/files/calendar@ccprog/po/es.po
calendar@ccprog/files/calendar@ccprog/po/fi.po
calendar@ccprog/files/calendar@ccprog/po/fr.po
calendar@ccprog/files/calendar@ccprog/po/hu.po
calendar@ccprog/files/calendar@ccprog/po/it.po
calendar@ccprog/files/calendar@ccprog/po/nl.po
calendar@ccprog/files/calendar@ccprog/po/pt_BR.po
calendar@ccprog/files/calendar@ccprog/po/ru.po
calendar@ccprog/files/calendar@ccprog/po/sv.po
calendar@ccprog/files/calendar@ccprog/po/tr.po

- Thanks for multiple translations: blogdron for Russian, qadzek for Dutch, Odyssey for Catalan
- Multiple fixes merged from upstream calendar@cinnamon
- Included custom tooltip formatting from upstream calendar@cinnamon
- Bugfix: correctly check cache whenever data are needed
- Support for holidays in Cyprus, Montenegro and El Salvador, and for regional holidays in Belgium.  
**Users from Belgium will need to check their regional settings!**
Resolves #6587

Calender@ccprog version 1.3.0

---

test-spice

**Change:** 
Add automatic reload of applet after copying to DEVTEST path
**Rationale:** 
Currently, when a developer needs to test their applet, they need to run `./test-spice uuid`, followed up by explicitly entering the applet settings, and triggering a reload of the applet from the hamburger menu. In my tests, removing/re-adding the applet from the panel didn't trigger a reload in Cinnamon.
Now, when a developer runs `./test-spice uuid`, the script will tell Cinnamon to reload the applet using same method as the applet settings, making it easier for the developer to test their changes.
@rcalixte

[test-spice] Add applet reload after successful copy

---

MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/applet.js
MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/settings-schema.json

I am using a USB microphone (which is a soundcard by it's own).
The command 'amixer set Capture toggle' does not work in this environment.
In my case i need to select the soundcard as well and the control is not called 'Capture' but 'Mic'.
This extension let's you configure two strings that let you choose the device by a search string as it is displayed in 'cat /proc/asound/cards' and name control (Capture, Mic, ...).
Works fine for me, could also work fine for others...

[MuteToggler@jebeaudet.com] Added new parameters for soundcard and input choice

---

Radio3.0@claudiux/files/Radio3.0@claudiux/po/de.po

Add German translation strings for new Radio++ stations import feature.

Radio3.0@claudiux: Update German (de) translation

---

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md
Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js
Radio3.0@claudiux/files/Radio3.0@claudiux/lib/text-wrap.js
Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json
Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json

* Fixes #6689.
* Improved menu display.
* Reintroduces the "Display the Station list beside the Category list" option.
* If this option is not checked, the first category is not ♥︎.
* Favorite stations are marked with a ♥︎ in the menu.
Please note that this PR is a fix, but does not resolve all menu display issues. Improvements are on the way.

[Radio3.0@claudiux] v2.5.1: Fixes #6689

---

gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/applet.js
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/bg.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/ca.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/da.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/de.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/es.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/fi.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/fr.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/gpaste-reloaded@feuerfuchs.eu.pot
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/hr.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/hu.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/is.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/it.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/nl.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/pl.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/pt.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/ru.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/sv.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/tr.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/zh_CN.po
gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/settings-schema.json

Add option to hide tray icon while applet is not being used.
It would be shown when panel edit mode is on, or with key bindings.
Also added the respective .pot entry and included portuguese and spanish translations.

[gpaste-reloaded@feuerfuchs.eu] Add option to hide tray icon

---

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md
Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js
Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json

[Radio3.0@claudiux] v2.6.0: Improved functioning

---

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.0/Graphs.js

@claudiux
Memory, network and disk graphs were disappearing when the CPU graph was configured to use colors by activity level and the swap usage was above 20%.
Both the CPU and Swap graphs are bar charts and they share the same rendering function. That function was trying to get the colors configured by activity level for swap, but there's no such setting for swap, only for CPU. When swap usage reached 20%, the rendering function tried to get the color for the activity level >20%, but there's no color there. Swap has only 1 color configured.
The solution I applied is not very clean, but it works and has little impact. Let me know :+1:.

multicore-sys-monitor@ccadeptic23: Fix memory graph disappearing

---

desaturate-all@hkoosha/files/desaturate-all@hkoosha/applet.js
desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/ca.po
desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/da.po
desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/de.po
desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/desaturate-all@hkoosha.pot
desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/es.po
desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/fi.po
desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/fr.po
desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/hu.po
desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/it.po
desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/nl.po
desaturate-all@hkoosha/files/desaturate-all@hkoosha/settings-schema.json

I have this set in my local version of desaturate-all (in `~/.local/share/cinnamon/applets`). For some reason, when trying to use the `./test-spice` script, the settings menu would not open on the developer copy, and I'm not exactly sure why. However, this works for me locally so it might be an issue with me having both the developer copy and the main copy?

Add configurable keybinding for desaturate-all

---

radio@driglu4it/files/radio@driglu4it/6.4/radio-applet.js
radio@driglu4it/src/services/youtubeDownload/YoutubeDl.ts
radio@driglu4it/src/services/youtubeDownload/YoutubeDownloadManager.ts
radio@driglu4it/src/services/youtubeDownload/YtDlp.ts

This pull request focuses on enhancing error handling and logging for YouTube download functionality in the `radio@driglu4it` applet. The changes involve passing the `downloadCommand` to success and error callbacks, adding more detailed error messages, and providing users with options to view logs for troubleshooting.
Enhancements to error handling and logging:
* [`radio@driglu4it/files/radio@driglu4it/6.4/radio-applet.js`](diffhunk://#diff-7f93474cfcd4726c9386e197ed68ff727ff4c1e481abf1b1f80bef657afdda82L4188-R4188): Modified the `downloadWithYouTubeDl`, `downloadWithYtDlp`, and `downloadSongFromYouTube` functions to pass the `downloadCommand` to the `onSuccess` callback. This allows better tracking of the command used during the download process. …

radio@driglu4it: add more debug information when youtube download fails

---

mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/applet.js
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/bg.po
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/ca.po
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/da.po
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/de.po
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/es.po
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/fi.po
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/fr.po
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/hu.po
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/it.po
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/mailnagapplet@ozderya.net.pot
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/nl.po
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/pl.po
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/pt_BR.po
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/ru.po
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/sv.po
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/tr.po
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/zh_CN.po
mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/settings-schema.json

- The limit is now configurable on the applet settings page.
- Limit now applies to sender name, sender address and subject.
See #6810 and #5230 
Comments and suggestions are greatly appreciated.

Configurable char limit for mail sender and subject

---

Sensors@claudiux/files/Sensors@claudiux/po/de.po

Add German translations for untranslated strings.
@claudiux
Somehow the fan icon you are using is an unknown symbol here:
I also noticed this on a fresh Linux Mint 22.1 installation. It is rendered with the placeholder.

Sensors@claudiux: Update German (de) translation

---

PanelTranslator@klangman/CHANGELOG.md
PanelTranslator@klangman/files/PanelTranslator@klangman/applet.js
PanelTranslator@klangman/files/PanelTranslator@klangman/metadata.json
PanelTranslator@klangman/files/PanelTranslator@klangman/po/PanelTranslator@klangman.pot
PanelTranslator@klangman/files/PanelTranslator@klangman/po/ca.po
PanelTranslator@klangman/files/PanelTranslator@klangman/po/de.po
PanelTranslator@klangman/files/PanelTranslator@klangman/po/es.po
PanelTranslator@klangman/files/PanelTranslator@klangman/po/fi.po
PanelTranslator@klangman/files/PanelTranslator@klangman/po/fr.po
PanelTranslator@klangman/files/PanelTranslator@klangman/po/hu.po
PanelTranslator@klangman/files/PanelTranslator@klangman/po/it.po
PanelTranslator@klangman/files/PanelTranslator@klangman/po/nl.po
PanelTranslator@klangman/files/PanelTranslator@klangman/settings-schema.json

- Fixed the output for right-to-left language output by using the -no-bidi translation-shell parameter when translating text
- Removed the Hotkey1/2 options and replaced them with 8 unique hotkey options on a new Hotkeys configuration dialog page. This makes the hotkey support more versatile and allows the Cinnamon Keyboard->Shortcuts setting page to properly show Panel Translator Hotkeys in it's user interface
- Added support for allowing the popup dialog window to be resized
- Save and restore popup window size on window resize events and applet startup
- Fix handling of display scaling factors

[PanelTranslator@klangman] Fixes and improvements

---

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md
Sensors@claudiux/files/Sensors@claudiux/applet.js
Sensors@claudiux/files/Sensors@claudiux/metadata.json
Sensors@claudiux/files/Sensors@claudiux/settings-schema.json

[Sensors@claudiux] v5.3.1: Removed 'Only show positive values' option for fans

---

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md
Sensors@claudiux/files/Sensors@claudiux/applet.js
Sensors@claudiux/files/Sensors@claudiux/metadata.json
Sensors@claudiux/files/Sensors@claudiux/stylesheet.css

@claudiux 
1. Configure the applet to display more than 1 temperature on the panel
2. Set the separator:
1. If your panel is horizontal, set the separator to `(none)`
2. If your panel is vertical, set the separator to `blank`
3. Set a high and/or critical temperature for any of the temperatures that are displayed on the panel

[Sensors@claudiux] Fixes temperature highlighting when there are multiple temperatures

---

calendar@simonwiles.net/files/calendar@simonwiles.net/applet.js
calendar@simonwiles.net/files/calendar@simonwiles.net/stylesheet.css

- Added applet padding.
- Updated today label size and position, removed extra space between day and month.
- Added gap between world clock name and time.
Fixes #4216.

calendar@simonwiles.net: Fixed layout

---

NightLightSwitch@claudiux/files/NightLightSwitch@claudiux/6.4/applet.js
NightLightSwitch@claudiux/files/NightLightSwitch@claudiux/CHANGELOG.md
NightLightSwitch@claudiux/files/NightLightSwitch@claudiux/metadata.json
NightLightSwitch@claudiux/files/NightLightSwitch@claudiux/po/NightLightSwitch@claudiux.pot
NightLightSwitch@claudiux/files/NightLightSwitch@claudiux/po/ca.po
NightLightSwitch@claudiux/files/NightLightSwitch@claudiux/po/es.po
NightLightSwitch@claudiux/files/NightLightSwitch@claudiux/po/fr.po
NightLightSwitch@claudiux/files/NightLightSwitch@claudiux/po/nl.po

Sometimes I become confused if the icon shows the result of my click or the current state of the night light, so it would be useful to show current state when hovering the panel icon as a tooltip.
cc @claudiux

NightLightSwitch@claudiux: Add tooltips

---

CassiaWindowList@klangman/CHANGELOG.md
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/6.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/6.4/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/metadata.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ca.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/da.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/de.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/es.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fi.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fr.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/hu.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/nl.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ru.po

- Use the DesaturateEffect class rather than the saturate_and_pixelate() API to adjust the icon color saturation. This has as advantage in that it is able to desaturate the color for all icons where before it was limited in what type of icons it would work on. On the other hand, it has a disadvantage in that it can't oversaturate the icons. Hopefully no one was using the >100% saturation feature because it's not gone now.
- Fixed the option to hide windows for pinned buttons on other CassiaWindowList instances. Previously this option would only take into account pinned buttons on one other window list instance. Now it creates a super set of application that are present on all other CassiaWindowList instances that are setup to be in "Launcher" mode. Also changed the option name to make it …

[CassiaWindowList@klangman] V2.4.1 fixes

---

turn-off-monitor@zablotski/files/turn-off-monitor@zablotski/applet.js

* Added a touchpad to the list of disabled devices (fixes a bug where you had to click on the applet twice to turn off the monitor).
* Fixed the command to disable the keyboard when using a shortcut.

turn-off-monitor@zablotski:  fixing bugs

---

cpu-monitor-text@gnemonix/files/cpu-monitor-text@gnemonix/applet.js

cpu-monitor-text@gnemonix
When the CPU percentage changes number of digits the width of the applet changes and moves things around.
Improve the functionality by padding the percentage with Figure Space characters.
Issue #7080

cpu-monitor-text@gnemonix : Issue#7080 Improve percentage display so applet width does not change

---

sshlauncher@sumo/files/sshlauncher@sumo/applet.js
sshlauncher@sumo/files/sshlauncher@sumo/metadata.json

@sumo 
I removed in this PR all calls using Lang. It seems to me that works fine.
Ok for merging?
Best regards.

[sshlauncher@sumo] v0.1.2: Code cleanup (without Lang)

---

directory-menu@torchipeppo/files/directory-menu@torchipeppo/applet.js
directory-menu@torchipeppo/files/directory-menu@torchipeppo/metadata.json
directory-menu@torchipeppo/files/directory-menu@torchipeppo/po/ca.po
directory-menu@torchipeppo/files/directory-menu@torchipeppo/po/de.po
directory-menu@torchipeppo/files/directory-menu@torchipeppo/po/directory-menu@torchipeppo.pot
directory-menu@torchipeppo/files/directory-menu@torchipeppo/po/es.po
directory-menu@torchipeppo/files/directory-menu@torchipeppo/po/fi.po
directory-menu@torchipeppo/files/directory-menu@torchipeppo/po/fr.po
directory-menu@torchipeppo/files/directory-menu@torchipeppo/po/hu.po
directory-menu@torchipeppo/files/directory-menu@torchipeppo/po/it.po
directory-menu@torchipeppo/files/directory-menu@torchipeppo/po/nl.po
directory-menu@torchipeppo/files/directory-menu@torchipeppo/po/pt.po
directory-menu@torchipeppo/files/directory-menu@torchipeppo/popup_menu.py
directory-menu@torchipeppo/files/directory-menu@torchipeppo/settings-schema.json

A long overdue fulfillment of the request from @Kalo79 . The title says it all this time.
Fixes #6890

[directory-menu@torchipeppo] v0.9.0: Add option to hide "Open Folder" and "Open in Terminal"

---

jalalicalendar@mohammad-sn/files/jalalicalendar@mohammad-sn/jalalicalendar.js

از سال 1404 کدهای شما روزهارو شمسی یک روز بیشتر نشون میداد!
مثلا امروز 07/01/1404 ه ولی این کدها 08/01/1404 نشون میداد

[jalalicalendar@mohammad-sn] Fix incorrect Persian date calculation by adjusting Julian Day offset

---

notifications-enhanced@hilyxx/README.md
notifications-enhanced@hilyxx/files/notifications-enhanced@hilyxx/applet.js
notifications-enhanced@hilyxx/files/notifications-enhanced@hilyxx/metadata.json

- Fixed an issue when the “Show do not disturb icon” option is enabled. The icon may disappear if the “Show empty tray” option is enabled at the same time.
- Added rcalixte's fixe #12296
- Updated Readme and metadata

[notifications-enhanced@hilyxx] Fixed an issue with 'Show do not disturb icon' option.

---

cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/6.4/applet.js

In Distro: Linux Mint 22.1 Xia base: Ubuntu 24.04 noble the slider didn't work, gave 24 hours time-out regardless of the slide.
Turned out that 'value' passed with 'value-changed' into sliderChanged(slider, value) was undefined, the commit is fixing this.

Missing value in emit of  'value-changed' action of cinnamon-timer.

---

app-launcher@mchilli/README.md
app-launcher@mchilli/files/app-launcher@mchilli/dialogs.py
app-launcher@mchilli/files/app-launcher@mchilli/po/app-launcher@mchilli.pot
app-launcher@mchilli/files/app-launcher@mchilli/po/ca.po
app-launcher@mchilli/files/app-launcher@mchilli/po/da.po
app-launcher@mchilli/files/app-launcher@mchilli/po/de.po
app-launcher@mchilli/files/app-launcher@mchilli/po/es.po
app-launcher@mchilli/files/app-launcher@mchilli/po/fi.po
app-launcher@mchilli/files/app-launcher@mchilli/po/fr.po
app-launcher@mchilli/files/app-launcher@mchilli/po/hu.po
app-launcher@mchilli/files/app-launcher@mchilli/po/it.po
app-launcher@mchilli/files/app-launcher@mchilli/po/nl.po
app-launcher@mchilli/files/app-launcher@mchilli/po/ru.po
app-launcher@mchilli/files/app-launcher@mchilli/po/tr.po
app-launcher@mchilli/files/app-launcher@mchilli/po/zh_CN.po
app-launcher@mchilli/files/app-launcher@mchilli/po/zh_TW.po
app-launcher@mchilli/files/app-launcher@mchilli/ui/separator.glade
app-launcher@mchilli/files/app-launcher@mchilli/widgets.py

- rewrite the dialogs to make it easier to add new dialogs
- add possibility to add separators to groups
(Feature request by @don-dolarson on https://cinnamon-spices.linuxmint.com/applets/view/344)
- fix bug, if a group is deleted it remains in the selection
- fix bug, if a *.desktop file contains duplicates
- update readme and translations files

app-launcher@mchilli: separator in groups

---

app-launcher@mchilli/files/app-launcher@mchilli/dialogs.py

- fix: make sure that the icon path exists before open the dialog

app-launcher@mchilli: fix icon path validation

---

CassiaWindowList@klangman/CHANGELOG.md
CassiaWindowList@klangman/README.md
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/6.0/settings-schema.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/6.4/applet.js
CassiaWindowList@klangman/files/CassiaWindowList@klangman/SetupWizard.ui
CassiaWindowList@klangman/files/CassiaWindowList@klangman/metadata.json
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ca.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/da.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/de.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/es.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fi.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fr.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/hu.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/nl.po
CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ru.po

- Renamed the "Number label" to "Icon overlay label" since it no longer only shows numbers
- Added 5 new icon overlay label content options
- Changed the icon overlay "smart" option into a toggle switch rather than a drop-down list
- Hide the "smart" icon overlay options when it does not make sense for the type of icon overlay setting
- Move the Ellipsis group indicator option to the status indicator drop-down list
- Added 3 new status indicator types (app group count, monitor number, workspace number)
- Added window progress support, shown using the icon overlay label or button label prepend
- Added an "Hide status indicators when space is limited" option to replace the "Auto" drop-down list option
- Fixed the minimized indicator character to use the down arrow for all cases except when …

[CassiaWindowList@klangman] Version 2.4.2

---

ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/applet.js

Fix error when capabilities output has unknown characters by converting the output to UTF-8
As seen in #7425

ddcci-multi-monitor@tim-we: Fix error when capabilities output has unknown characters

---

ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/po/zh_TW.po

Copilot Summary:
> This pull request introduces a new translation file for Traditional Chinese (`zh_TW.po`) in the `ShutdownMenuWithIcons@LLOBERA` applet. The file provides localized strings for various menu options and settings descriptions related to system power management.
> 
> ### Localization for menu options:
> 
> * Added translations for menu items such as "Shutdown Menu With Icons," "Quit," "Suspend," "Hibernate," "Hybrid sleep," "Restart," "Switch users," "Log out," "Screen Lock," "Settings," "Help," and "About."
> 
> ### Localization for settings descriptions:
> 
> * Added translations for settings descriptions, including labels, icons, and commands for functionalities like "Quit," "Suspend," "Hibernate," "Hybrid sleep," "Restart," "Switch users," "Log out," and "Screen lock."

ShutdownMenuWithIcons@LLOBERA: Add Traditional Chinese translation

---

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/scripts/get-cpu-data3.sh

The script get-cpu-data3.sh was starting many awk processes, which made it slow and unnecessarily increased the CPU load.

multicore-sys-monitor@ccadeptic23: optimize the bash script get-cpu-data3.sh

---

bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/applet.js
mic-level@zamszowy/files/mic-level@zamszowy/applet.js
updates-notifier@zamszowy/files/updates-notifier@zamszowy/applet.js
updates-notifier@zamszowy/files/updates-notifier@zamszowy/metadata.json

This fixes subprocesses running in the background after applet removal.

bluetooth-battery/mic-level/updates-notifier@zamszowy: use correct method for detection of applet removal

---

mouse-keys-shortcut@GabrielCamara3526/files/mouse-keys-shortcut@GabrielCamara3526/applet.js
mouse-keys-shortcut@GabrielCamara3526/files/mouse-keys-shortcut@GabrielCamara3526/metadata.json
mouse-keys-shortcut@GabrielCamara3526/files/mouse-keys-shortcut@GabrielCamara3526/po/fr.po
mouse-keys-shortcut@GabrielCamara3526/files/mouse-keys-shortcut@GabrielCamara3526/po/mouse-keys-shortcut@GabrielCamara3526.pot

@GabrielCamara3526
Your applet is a real gem!
This PR improves the sliders:
- Setting a mark for each default value.
- Translating messages, adding current value and unit.
- Making magnetic each default value.
I hope you'll like this PR.

mouse-keys-shortcut@GabrielCamara3526: Improves sliders

---

updates-notifier@zamszowy/files/updates-notifier@zamszowy/info-window.js
updates-notifier@zamszowy/files/updates-notifier@zamszowy/metadata.json
updates-notifier@zamszowy/files/updates-notifier@zamszowy/updates.sh

looks like on cjs@4.4.0 TextDecoder is not yet available, but old-good String(byte[]) constructor works fine.
Implemented fallback to String ctor if TextDecoder is not available. Guess for such a simple output as pkcon produces String constructor should be good enough.
Bonus: moved updates count title calculation into the info-window.js and slightly simplified "view" script.
owner: @zamszowy

updates-notifier: fix TextDecoder error on old cjs

---

windowlist@cobinja.de/files/windowlist@cobinja.de/6.4/applet.js

This fixes a problem with how a monitor change for windows was handled. The previous method couldn't work, because CinnamonScreen::window-monitor-change doesn't always name the new monitor, but also the old one, without the listener being able to distinguish between those cases.

[windowlist@cobinja.de] Fix for windows changing the monitor

---

windowlist@cobinja.de/files/windowlist@cobinja.de/6.4/applet.js

This fixes an applet crash when adding a new instance of windowlist@cobinja.de

[windowlist@cobinja.de] Fix an issue that causes the applet to crash when adding a new instance to Cinnamon

---

download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletConstants.js
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletGui.js
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/metadata.json
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/bg.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/ca.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/da.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/de.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/download-and-upload-speed@cardsurf.pot
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/es.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/fi.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/fr.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/hr.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/hu.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/it.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/nl.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/pl.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/pt.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/sv.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/tr.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/zh_CN.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/zh_TW.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/settings-schema.json

This PR adds features that I found useful and I think would be nice additions to this applet:
- option to hide icons
- option to use fixed units (e.g. always MB) instead of auto choosing the unit
- option to display no traffic text ("0.00") in a different style, which would make it easier to notice when the traffic is active 
</br></br>
cc: @cardsurf @claudiux 
@claudiux I hope it's okay to add you here, since I saw that lately only you were making changes to this applet.

download-and-upload-speed@cardsurf: add options for hide icon, fixed units and inactive text style

---

download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/metadata.json
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/bg.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/ca.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/da.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/de.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/download-and-upload-speed@cardsurf.pot
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/es.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/fi.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/fr.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/hr.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/hu.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/it.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/nl.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/pl.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/pt.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/sv.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/tr.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/zh_CN.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/zh_TW.po
download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/settings-schema.json

Since one can have already change active text style, enforcing default
style for inactive text could break formatting of the labels.
Closes #7843 
cc @cardsurf @claudiux

download-and-upload-speed@cardsurf: disable inactive text by default

---

xsession@claudiux/files/xsession@claudiux/CHANGELOG.md
xsession@claudiux/files/xsession@claudiux/applet.js
xsession@claudiux/files/xsession@claudiux/metadata.json
xsession@claudiux/files/xsession@claudiux/po/ca.po
xsession@claudiux/files/xsession@claudiux/po/da.po
xsession@claudiux/files/xsession@claudiux/po/de.po
xsession@claudiux/files/xsession@claudiux/po/es.po
xsession@claudiux/files/xsession@claudiux/po/fr.po
xsession@claudiux/files/xsession@claudiux/po/hu.po
xsession@claudiux/files/xsession@claudiux/po/it.po
xsession@claudiux/files/xsession@claudiux/po/nl.po
xsession@claudiux/files/xsession@claudiux/po/tr.po
xsession@claudiux/files/xsession@claudiux/po/xsession@claudiux.pot
xsession@claudiux/files/xsession@claudiux/po/zh_CN.po
xsession@claudiux/files/xsession@claudiux/po/zh_TW.po

Developers often have to repeat the same action several times (reloading a Spice or opening its settings).
A “Repeat last action” option is now available in the menu when an action has been performed. This option disappears after one hour.
If you cannot remember what the action was, simply do not use this option.

xsession v5.1.0: Adds "Repeat last action" option in menu
