download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js
=> [download-and-upload-speed@cardsurf] Declared variable

vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/README.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/README.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/applet.js, vpnLookOut@claudiux/files/vpnLookOut@claudiux/metadata.json
Hi,
This is the version 2.3.0 of the vpnLookOut@claudiux applet.
A middle click on the icon of this applet is now a quick way to connect to the last VPN used (if it is off) or disconnect from VPN (if it is on).
Best regards.
Claudiux
=> [vpnLookOut@claudiux] v2.3.0 - Middle click to connect/disconnect VPN

vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/applet.js, vpnLookOut@claudiux/files/vpnLookOut@claudiux/metadata.json
Hi,
Can you merge this branch with your master one, please ?
Best regards.
Claudiux
=> [vpnLookOut@claudiux] v2.4.0 - Setting right permissions to script files

sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/3.4/applet.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
Hi,
Can you merge this branch with your master one, please ?
Best regards.
Claudiux
=> [sound150@claudiux] v1.5.0 - Setting right permissions to script files

IcingTaskManager@json/files/IcingTaskManager@json/3.4/appGroup.js, IcingTaskManager@json/files/IcingTaskManager@json/3.8/appGroup.js, IcingTaskManager@json/files/IcingTaskManager@json/metadata.json, IcingTaskManager@json/package.json, IcingTaskManager@json/yarn.lock
See https://github.com/jaszhix/icingtaskmanager/issues/199
=> [WIP] IcingTaskManager@json: Fix hover pseudo class not resetting on focus events

spices-notifier@germanfr/files/spices-notifier@germanfr/applet.js, spices-notifier@germanfr/files/spices-notifier@germanfr/po/es.po, spices-notifier@germanfr/files/spices-notifier@germanfr/po/spices-notifier@germanfr.pot, spices-notifier@germanfr/files/spices-notifier@germanfr/settings-schema.json
Changelog at: https://github.com/germanfr/spices-notifier/commits/master
=> Update Spices notifier v3.8 (spices-notifier@germanfr)

IcingTaskManager@json/CHANGELOG.md, IcingTaskManager@json/files/IcingTaskManager@json/3.4/appGroup.js, IcingTaskManager@json/files/IcingTaskManager@json/3.4/settings-schema.json, IcingTaskManager@json/files/IcingTaskManager@json/3.8/appGroup.js, IcingTaskManager@json/files/IcingTaskManager@json/3.8/settings-schema.json, IcingTaskManager@json/files/IcingTaskManager@json/metadata.json
* Addressed an issue with the focus pseudo class styling reverting on hover.
* Made the Mint X theme preset the default.
=> IcingTaskManager@json: 6.3.7

printers@linux-man/README.md, printers@linux-man/files/printers@linux-man/applet.js, printers@linux-man/files/printers@linux-man/metadata.json
=> printers@linux-man: Use pkexec to "Restart CUPS"

weather@mockturtl/files/weather@mockturtl/po/nl.po
I've translated a few missing strings and thus completed the Dutch translation again.
=> weather@mockturtl: Update nl.po

Cinnamenu@json/CHANGELOG.md, Cinnamenu@json/files/Cinnamenu@json/buttons.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
=> Cinnamenu@json: Fix inability to uninstall applications

IcingTaskManager@json/CHANGELOG.md, IcingTaskManager@json/README.md, IcingTaskManager@json/files/IcingTaskManager@json/3.8/appGroup.js, IcingTaskManager@json/files/IcingTaskManager@json/3.8/specialMenus.js, IcingTaskManager@json/files/IcingTaskManager@json/3.8/store.js, IcingTaskManager@json/files/IcingTaskManager@json/metadata.json
* Fixed scaling of thumbnails when removing windows.
* Updated readme.
Also thanks to @cardsurf for help in #1885.
=> IcingTaskManager@json: Fix thumbnail scaling on window removal

IcingTaskManager@json/CHANGELOG.md, IcingTaskManager@json/files/IcingTaskManager@json/3.8/appGroup.js, IcingTaskManager@json/files/IcingTaskManager@json/3.8/applet.js, IcingTaskManager@json/files/IcingTaskManager@json/3.8/specialMenus.js, IcingTaskManager@json/files/IcingTaskManager@json/3.8/store.js, IcingTaskManager@json/files/IcingTaskManager@json/metadata.json
* Fixed an issue with pinned applications becoming ordered incorrectly when uninstalled applications are present.
* Corrected a warning occurring during context menu initialization.
=> IcingTaskManager@json: 6.3.10

windowlist@cobinja.de/files/windowlist@cobinja.de/3.2/applet.js, windowlist@cobinja.de/files/windowlist@cobinja.de/3.2/settings-schema.json, windowlist@cobinja.de/files/windowlist@cobinja.de/3.2/stylesheet.css, windowlist@cobinja.de/files/windowlist@cobinja.de/po/bg.po, windowlist@cobinja.de/files/windowlist@cobinja.de/po/da.po, windowlist@cobinja.de/files/windowlist@cobinja.de/po/de.po, windowlist@cobinja.de/files/windowlist@cobinja.de/po/hr.po, windowlist@cobinja.de/files/windowlist@cobinja.de/po/pl.po, windowlist@cobinja.de/files/windowlist@cobinja.de/po/sv.po, windowlist@cobinja.de/files/windowlist@cobinja.de/po/windowlist@cobinja.de.pot, windowlist@cobinja.de/files/windowlist@cobinja.de/po/zh_CN.po
New setting for "open on hover"
=> windowlist@cobinja.de Improve popup menu settings

CommandRunner@appdevsw/files/CommandRunner@appdevsw/applet.js
@appdevsw
This PR is a fix for issue #1846. If anything looks out of place and needs to be edited, feel free to make the change or just let me know.
=> CommandRunner: Fixed issue with applet not starting

show-hide-applets@mohammad-sn/files/show-hide-applets@mohammad-sn/applet.js
@mohammad-sn 
This PR is a fix for issue #1801. If anything needs to be corrected or is wrong, feel free to change it or let me know and I'll make the change.
=> show-hide-applets: Fixed always showing on hover issue

color-picker@fmete/info.json
This applet has a score of 6 and is currently not maintained by anyone. I would like to take ownership of this applet and become the maintainer.
=> Taking ownership of unmaintained applet.

mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/es.po
Created Spanish .po file for the Mailnag applet.
=> mailnagapplet@ozderya.net: Spanish translation

ScreenShot+RecordDesktop@tech71/info.json
This applet has a score of 13 and is currently not maintained by anyone. I would like to take ownership of this applet and become the maintainer.
=>  ScreenShot+RecordDesktop@tech71: Taking ownership of applet.

restart-cinnamon@kolle/info.json
This applet has a score of 8 and is currently not maintained by anyone. I would like to take ownership of this applet and become the maintainer.
=> restart-cinnamon@kolle: Taking ownership of unmaintained applet.

mem-monitor-text@datanom.net/files/mem-monitor-text@datanom.net/applet.js, mem-monitor-text@datanom.net/info.json
This PR is a fix for issue #1422.
=> Mem-monitor-text: Removed label.

redshift@marvel4u/files/redshift@marvel4u/applet.js
@Marvel4U: This PR is s fix for issue #1597. Feel free to change/edit however you see fit or just let me know and I'll fix it.
=> redshift: Backlight not updating fix.

IcingTaskManager@json/CHANGELOG.md, IcingTaskManager@json/files/IcingTaskManager@json/3.8/applet.js, IcingTaskManager@json/files/IcingTaskManager@json/metadata.json, IcingTaskManager@json/yarn.lock
* Fixed an issue with the applet not initializing when an open app can't be resolved by wm_class.
=> IcingTaskManager@json: 6.3.11

batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/applet.js
@pdcurtis This PR is for issue #1913. Feel free to change however you see fit or let me know and I'll make the changes accordingly.
=> batterymonitor@pdcurtis: Updated warning message.

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json, multicore-sys-monitor@ccadeptic23/gulpfile.js, multicore-sys-monitor@ccadeptic23/package.json, multicore-sys-monitor@ccadeptic23/yarn.lock
=> multicore-sys-monitor@ccadeptic23: Fix hovering over the applet hiding the panel when auto hide is enabled

Cinnamenu@json/files/Cinnamenu@json/po/tr.po
=> Cinnamenu@json: Add Turkish translation

weather@mockturtl/files/weather@mockturtl/applet.js
=> weather@mockturtl: Fix up #53

weather@mockturtl/files/weather@mockturtl/po/tr.po
Hello
The language file is too old and missing
I translated the whole room
=> weather@mockturtl: Update tr.po

Cinnamenu@json/files/Cinnamenu@json/po/tr.po
Hi
Minor translation errors fixed
=> Cinnamenu@json: Update tr.po

CinnVIIStarkMenu@NikoKrause/CHANGELOG.md, CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/pt.po
* PT Translation:
- Fixed some errors.
- Updated some translations.
- Added missing translations of the last version.
=> CinnVIIStarkMenu@NikoKrause: Update pt.po

temperature@fevimu/files/temperature@fevimu/applet.js, temperature@fevimu/yarn.lock
Thanks to Peter M. for helping with reproducing the issue via email.
=> temperature@fevimu: Fix for Ryzen CPUs

pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/sound.js
Fix custom sound path in newer versions of cinnamon, filechooser returns a file uri
=> [pomodoro@gregfreeman.org] Fix custom sound path in newer versions of cinnamon

bash-sensors@pkkk/files/bash-sensors@pkkk/applet.js, bash-sensors@pkkk/files/bash-sensors@pkkk/stylesheet.css
I added a Stylesheet for the click menu to be able to change the font to something monospace like.
I think this fits the output of the plugin best, especially if someone is going for a bigger output which draws table etc.
=> [bash-sensors@pkkk] added stylesheet

CustomApplicationsMenu@LLOBERA/info.json
I am the original author of the applet `CustomApplicationsMenu` and I would like to take back the ownership of the applet to commit more easily the next modifications.
=> change author

CustomApplicationsMenu@LLOBERA/files/CustomApplicationsMenu@LLOBERA/applet.js
Fix bug: no icon is displayed because `get_names()` returns now an array of more than 1 element.
=> fix use get_names() as an array

Cinnamenu@json/CHANGELOG.md, Cinnamenu@json/files/Cinnamenu@json/applet.js, Cinnamenu@json/files/Cinnamenu@json/buttons.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/utils.js
* Fixed issues with invalid access of C objects occurring with CJS git master.
* Fixed the list view container width not filling the parent scroll container width, and the button widths not filling their parent container's width.
* Fixed the dot offsetting the vertical alignment of labels in the list view.
* Made the positioning of the running app indicator dot consistent between list and grid views.
=> Cinnamenu@json: 3.2.6

windowlist@cobinja.de/CHANGELOG.md, windowlist@cobinja.de/files/windowlist@cobinja.de/3.2/applet.js
=> windowlist@cobinja.de Fix preview size in HiDPI mode

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/3.4/applet.js
fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/1791
=> CinnVIIStarkMenu@NikoKrause: remove dead code

vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/README.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/2.8/applet.js, vpnLookOut@claudiux/files/vpnLookOut@claudiux/2.8/settings-schema.json, vpnLookOut@claudiux/files/vpnLookOut@claudiux/3.8/applet.js, vpnLookOut@claudiux/files/vpnLookOut@claudiux/3.8/settings-schema.json, vpnLookOut@claudiux/files/vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/README.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/metadata.json
Hi,
Can you merge this vpnLookOut251 branch with your master one, please?
Best regards.
Claudiux
=> vpnLookOut v2.5.1 - Adds a keyboard shortcut option to activate / deactivate the last VPN used.

Cinnamenu@json/files/Cinnamenu@json/buttons.js
Closes https://github.com/jaszhix/Cinnamenu/issues/24
=> Cinnamenu@json: Fix context menu positioning in list view mode

vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/2.8/settings-schema.json, vpnLookOut@claudiux/files/vpnLookOut@claudiux/3.8/settings-schema.json, vpnLookOut@claudiux/files/vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/metadata.json, vpnLookOut@claudiux/files/vpnLookOut@claudiux/po/es.po, vpnLookOut@claudiux/files/vpnLookOut@claudiux/po/fr.po, vpnLookOut@claudiux/files/vpnLookOut@claudiux/po/it.po, vpnLookOut@claudiux/files/vpnLookOut@claudiux/po/vpnLookOut@claudiux.pot
Hi,
Can you merge this vpnLookOut252 branch with your master one, please?
Best regards.
Claudiux
=> vpnLookOut v2.5.2 - Update translation files

placesCenter@scollins/files/placesCenter@scollins/po/fr.po
Hi,
This is the new version of fr.po for the placesCenter@scollins applet, with many improvements. (I am the author of the previous version of this file.)
Best regards.
Claudiux
=> placesCenter@scollins - fr.po updated

localipswithsettings@edaubert/files/localipswithsettings@edaubert/applet.js
As for #1993 this applet needs an update to respect the javascript strict mode.
=> localipswithsettings@edaubert: Fix strict mode errors

vpnLookOut@claudiux/files/vpnLookOut@claudiux/po/it.po
=> vpnLookOut@claudiux - Italian translation - New file it.po

vpnLookOut@claudiux/files/vpnLookOut@claudiux/po/es.po
=> vpnLookOut@claudiux - Spanish translation - New version of es.po

vpnLookOut@claudiux/files/vpnLookOut@claudiux/po/sv.po
=> vpnLookOut@claudiux: Update sv.po

workspace-name@willurd/files/workspace-name@willurd/po/tr.po
workspace-name@willurd: add tr.po
=> workspace-name@willurd: add tr.po

workspace-grid@hernejj/files/workspace-grid@hernejj/po/tr.po
workspace-grid@hernejj: add tr.po
=> workspace-grid@hernejj: add tr.po

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/tr.po
multicore-sys-monitor@ccadeptic23: add tr.po
=> multicore-sys-monitor@ccadeptic23: add tr.po

placesCenter@scollins/files/placesCenter@scollins/po/tr.po
placesCenter@scollins: add tr.po
=> placesCenter@scollins: add tr.po

pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/tr.po
pomodoro@gregfreeman.org: add tr.po
=> pomodoro@gregfreeman.org: add tr.po

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/tr.po
CinnVIIStarkMenu@NikoKrause: add tr.po
=> CinnVIIStarkMenu@NikoKrause: add tr.po

sessionManager@scollins/files/sessionManager@scollins/po/tr.po
sessionManager@scollins: add tr.po
=> sessionManager@scollins: add tr.po

vpnLookOut@claudiux/files/vpnLookOut@claudiux/po/tr.po
vpnLookOut@claudiux: add tr.po
=> vpnLookOut@claudiux: add tr.po

cheaty@centurix/files/cheaty@centurix/refdocs/Regex/icon.svg, cheaty@centurix/files/cheaty@centurix/refdocs/Regex/sheet.json
@Centurix 
Added a regular expressions cheatsheet with the characters classes, quantifiers, anchors, etc.
=> cheaty@centurix: Added Regex cheatsheet

batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/tr.po
batterymonitor@pdcurtis: add tr.po
=> batterymonitor@pdcurtis: add tr.po

CustomApplicationsMenu@LLOBERA/files/CustomApplicationsMenu@LLOBERA/po/tr.po
CustomApplicationsMenu@LLOBERA: add tr.po
=> CustomApplicationsMenu@LLOBERA: add tr.po

pa-equalizer@jschug.com/files/pa-equalizer@jschug.com/po/tr.po
pa-equalizer@jschug.com: add tr.po
=> pa-equalizer@jschug.com: add tr.po

graphicsCenter@scollins/files/graphicsCenter@scollins/po/tr.po
graphicsCenter@scollins: add tr.po
=> graphicsCenter@scollins: add tr.po

SW++@mohammad-sn/files/SW++@mohammad-sn/applet.js
=> SW++@mohammad-sn: Fix binding issue

color-picker@fmete/README.md, color-picker@fmete/files/color-picker@fmete/applet.js, color-picker@fmete/files/color-picker@fmete/cp.py
* port `cp.py` to python3
* replace xsel with xclip: xsel does not work with Java apps, e.g. phpStorm
@icarter09
=> color-picker@fmete: python3 and xclip

temperature@fevimu/files/temperature@fevimu/metadata.json
=> temperature@fevimu: Add 4.0 to supported versions

feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/po/tr.po
feeds@jonbrettdev.wordpress.com: add tr.po
=> feeds@jonbrettdev.wordpress.com: add tr.po

vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/3.8/assets/spawn.js, vpnLookOut@claudiux/files/vpnLookOut@claudiux/3.8/egSpawn.js, vpnLookOut@claudiux/files/vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/metadata.json
=> vpnLookOut@claudiux v3.2.1 - Improves display and management of Activity Log

spices-notifier@germanfr/files/spices-notifier@germanfr/po/fr.po
French translation for spices-notifier@germanfr, from .pot file.
=> spices-notifier@germanfr - French translation fr.po

sound150@claudiux/files/sound150@claudiux/po/sv.po
=> sound150@claudiux: add sv.po

back-up_state@natsakis.com/files/back-up_state@natsakis.com/applet.js
=> back-up_state@natsakis.com: Fix start-up errors

vpnLookOut@claudiux/files/vpnLookOut@claudiux/po/tr.po
vpnLookOut@claudiux: update tr.po
=> vpnLookOut@claudiux: update tr.po

stopwatch@pdcurtis/files/stopwatch@pdcurtis/CHANGELOG.md, stopwatch@pdcurtis/files/stopwatch@pdcurtis/applet.js, stopwatch@pdcurtis/files/stopwatch@pdcurtis/metadata.json
* Use xdg-open in place of gedit or xed to allow use on more distros
=> stopwatch@pdcurtis Update to version 2.1.1

bumblebee@pdcurtis/files/bumblebee@pdcurtis/CHANGELOG.md, bumblebee@pdcurtis/files/bumblebee@pdcurtis/applet.js, bumblebee@pdcurtis/files/bumblebee@pdcurtis/changelog.txt, bumblebee@pdcurtis/files/bumblebee@pdcurtis/metadata.json
* Use xdg-open in place of gedit or xed to allow use on more distros
=> bumblebee@pdcurtis Update to version 3.2.5

nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/CHANGELOG.md, nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/applet.js, nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/changelog.txt, nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/metadata.json
* Use xdg-open in place of gedit or xed to allow use on more distros
=> nvidiaprime@pdcurtis Update to version 3.3.4

bumblebee@pdcurtis/files/bumblebee@pdcurtis/po/tr.po
=> bumblebee@pdcurtis: add tr.po

nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/po/tr.po
nvidiaprime@pdcurtis: add tr.po
=> nvidiaprime@pdcurtis: add tr.po

github-projects@morgan-design.com/files/github-projects@morgan-design.com/applet.js
- Variable scope was stopping the repos from listing correctly
@jamesmorgan
=> github-projects@morgan-design.com: Fix variable scoping for CJS

commandLauncher@scollins/files/commandLauncher@scollins/po/tr.po
commandLauncher@scollins: add tr.po
=> commandLauncher@scollins: add tr.po

sshlauncher@sumo/files/sshlauncher@sumo/applet.js
Using `#GroupStart MyName` will create a group called "MyName".   `#GroupEnd` will close the group.  Used `#` since it is a comment character; so it won't have any negative effects on anything else that read SSH Config files.
So in this example image; `airey` and `story` are servers that are grouped inside the `Home` group.
Debating adding some spaces in front of the sub-menu-items...
=> sshlauncher@sumo: Add ability to have Server Groups in SSH Launcher.  

vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/applet.js
See [comment](https://github.com/linuxmint/cinnamon-spices-applets/commit/5751e8dd6fc92eb86c41da51b60f549d1117aff4#r31813483) on #2170.
=> vboxlauncher@mockturtl: fix version detection

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/SpicesUpdate@claudiux.pot, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/es.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/settings-schema.json
=> SpicesUpdate@claudiux v1.0.1 - Improves notifications. Added es.po.

netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/4.0/CHANGELOG.md, netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/4.0/applet.js, netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/4.0/stylesheet.css, netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/metadata.json
* Update stylesheet.css to better match Cinnamon 4.0 System Styles - less rounded and less intrusive.
* Add an initial mechanism to provide persistence for user edits of the stylesheet.
This replaces and closes #2152 where there has been a long and interesting discussion with @Mintulix who initial put forwards the need for change.
=> netusagemonitor@pdcurtis v 3.2.9 Refine stylesheet.css for 4.0

batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/CHANGELOG.md, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/applet.js, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/metadata.json, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/stylesheet.css
* Update stylesheet.css to better match Cinnamon 4.0 System Styles - less rounded.
* Add an initial mechanism to provide persistence for user edits of the stylesheet.
=> batterymonitor@pdcurtis v 1.3.5 Refine stylesheet

stopwatch@pdcurtis/files/stopwatch@pdcurtis/CHANGELOG.md, stopwatch@pdcurtis/files/stopwatch@pdcurtis/applet.js, stopwatch@pdcurtis/files/stopwatch@pdcurtis/metadata.json, stopwatch@pdcurtis/files/stopwatch@pdcurtis/stylesheet.css
* Update stylesheet
* Remove trailing spaces etc from code
=> stopwatch@pdcurtis v 2.1.2 Refine stylesheet

vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/3.8/applet.js, vpnLookOut@claudiux/files/vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/scripts/getTZ.sh
Hi,
Can you merge this branch in your master one, please?
Best regards.
Claudiux
=> vpnLookOut@claudiux v3.3.2 - Improves time zone detection

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/settings-schema.json
Hi @jaszhix,
In this version 1.0.4:
* The tooltip now contains the list of Spices to update.
* Undeclared variable errors are fixed.
Best regards.
Claudiux
=> SpicesUpdate@claudiux v1.0.4 - Tooltip now contains the list of Spices to update.

todo@threefi/files/todo@threefi/applet.js
The addon entered an infinite loop when the "todo.list" file had no entries to display effectively freezing itself and Cinnamon.
---
This bug has been reported in https://cinnamon-spices.linuxmint.com/applets/view/205
I'm unable find the author on GitHub so can't mention him/her either.
=> todo@threefi: Do not freeze when the input file has no entries.

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/SpicesUpdate@claudiux.pot, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/es.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/fr.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/settings-schema.json
Hi @jaszhix,
This version 1.1.0 of SpicesUpdate@claudiux is an answer to the feature request #2202.
Best Regards.
Claudiux
=> SpicesUpdate@claudiux v1.1.0 - Fixes #2202: Add support for new packages

restart-cinnamon@kolle/files/restart-cinnamon@kolle/po/nl.po
Dutch Translation off Restart Cinnamon
=> Restart cinnamon nl.po

ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/po/nl.po
=> Shutdown Menu with icons nl.po

vpnLookOut@claudiux/nl.po
Dutch Translation off VPN Look-Out Applet
=> VPN Look-Out nl _NL.po

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/3.4/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, MessagingMenuV3@blub/files/MessagingMenuV3@blub/applet.js
We want to remove these functions going forward as they are not needed.
=> Remove usage of old appsys functions

vpnLookOut@claudiux/files/vpnLookOut@claudiux/po/nl.po
Upload Dutch translation off VPN Look-Out Applet to the right file
=> VPN Look- Out Applet

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/nl.po
Improved translation and sentence structure
=> Update cinnamon-spices applet nl.po

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/fr.po
Hi @jaszhix,
I propose a French translation of the multicore-sys-monitor@ccadeptic23 messages.
Best regards.
Claudiux
=> multicore-sys-monitor@ccadeptic23: French translation fr.po

spices-notifier@germanfr/files/spices-notifier@germanfr/po/nl.po
=> Spices notifier nl.po

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/SpicesUpdate@claudiux.pot, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/es.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/fr.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/it.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/scripts/open_download_tab.py, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/settings-schema.json
Hi @jaszhix,
This code change is the response to the FR made by an user (https://cinnamon-spices.linuxmint.com/applets/view/309#count).
Can you merge this branch into your master one, please?
Best regards.
Claudiux
=> SpicesUpdate@claudiux: v1.2.1 - Can hide icon while nothing is to report

SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/README.md
Hi @jaszhix,
This PR is a response to the request of an user (https://cinnamon-spices.linuxmint.com/applets/view/309#count).
Best regards.
Claudiux
=> SpicesUpdate@claudiux: Update README.md files

weather@mockturtl/README.md, weather@mockturtl/files/weather@mockturtl/applet.js, weather@mockturtl/files/weather@mockturtl/darkSky.js, weather@mockturtl/files/weather@mockturtl/ipApi.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/files/weather@mockturtl/openWeatherMap.js, weather@mockturtl/files/weather@mockturtl/po/hu.po, weather@mockturtl/files/weather@mockturtl/po/weather@mockturtl.pot, weather@mockturtl/files/weather@mockturtl/settings-schema.json, weather@mockturtl/files/weather@mockturtl/stylesheet.css
* DarkSky API Support
* OpenWeatherMap Premium support
* Optional automatic location lookup based on IP
* Main loop separated from Refreshing weather, refreshing weather is purely time based 
* Improved logging
* Async functions instead of callbacks
* Hungarian translation added
* Improved stability
=> weather@mockurtl 2.1.0 Update

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/hr.po
@claudiux 
Can you add option to auto update spices?
=> SpicesUpdate@claudiux: Update Croatian language

weather@mockturtl/README.md, weather@mockturtl/files/weather@mockturtl/applet.js, weather@mockturtl/files/weather@mockturtl/darkSky.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/files/weather@mockturtl/openWeatherMap.js, weather@mockturtl/files/weather@mockturtl/settings-schema.json
By the courtesy and support of OpenWeatherMap.
Fixes and Changes: 
* Forcing mainloop to refresh when Weather update fails (it was not updating for a whole refresh interval when we had a successful update then the settings was changed right after and update failed)
* Using Regex against Location setting
* DarkSky error messages are displayed properly to the users now
* Fixed some OpenWeatherMap json response error handling (it was matching strings to numbers)
* Removed obsolete code
* Edited Readme
* Added some thanks to OpenWeatherMap at the bottom of the settings
=> weather@mockturtl 2.1.1 Update - OpenWeatherMap no longer requires key

weather@mockturtl/files/weather@mockturtl/po/nl.po
Complete and revised Dutch translation update for version 2.1.0 of weather@mockturtl.
=> Update nl.po for version 2.1.0

weather@mockturtl/files/weather@mockturtl/po/sv.po
Updated Swedish translation for weather@mockturtl update 2.0.1 with missing OpenWeatherMap Weather Conditions fount at https://openweathermap.org/weather-conditions
=> Update sv.po weather@mockturtl

spices-notifier@germanfr/files/spices-notifier@germanfr/po/nl.po
=> Update nl.po spices-notifier

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/nl.po
due to changes in the notification parts
=> Update Spices-Update nl.po

vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/3.8/applet.js, vpnLookOut@claudiux/files/vpnLookOut@claudiux/CHANGELOG.md
Hi @jaszhix,
This version improves the responsiveness of the icon when the status of the VPN changes.
Best regards.
Claudiux
=> vpnLookOut@claudiux: v3.3.3 - Improves responsiveness

SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/README.md
Hi @jaszhix,
The README.md files have been modified to describe the different types of notifications.
Best regards.
Claudiux
=> SpicesUpdate@claudiux: README.md - Description of notifications

InternetTimeApplet@stefan/README.md
Just did some formatting of the text. (Headline & Links)
=> InternetTimeApplet@stefan :  updated README.md

weather@mockturtl/files/weather@mockturtl/po/sv.po
Added new structure and strings for 2.1.2 and conditions from OpenWeatherMap
=> Update Swedish language weather@mockturtl 2.1.2

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/3.4/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js
API update for https://github.com/linuxmint/Cinnamon/commit/a65bf0e8a61dd9c8811eaee6613360bfb7779870.
=> Cinnamenu, CinnVIIStarkMenu: Use CinnamonAppSystem.get_tree

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/sv.po
=> SpicesUpdate@claudiux: add sv.po

weather@mockturtl/files/weather@mockturtl/po/sv.po
Changed one character from upper to lower case on condition that affect translation.
=> weather@mockturtl - Minimal update change sv.po

PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/po/sv.po
=> PDFManager@cinnamon.org: Update sv.po

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/sv.po
=> multicore-sys-monitor@ccadeptic23: Update sv.po

betterlock/files/betterlock/po/sv.po
=> betterlock: Update sv.po

temperature@fevimu/files/temperature@fevimu/po/sv.po
=> temperature@fevimu: Update sv.po

sysmonitor@orcus/files/sysmonitor@orcus/po/sv.po, sysmonitor@orcus/files/sysmonitor@orcus/po/sysmonitor@orcus.pot
=> sysmonitor@orcus: Update sv.po

Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot, Cinnamenu@json/files/Cinnamenu@json/po/sv.po
=> Cinnamenu@json: Update sv.po

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish updated language file for weather@mockturtl 2.1.5 rearranged from the latest template and some minor translation adjustments.
=> weather@mockturtl sv.po for Update 2.1.5

weather@mockturtl/files/weather@mockturtl/3.8/applet.js, weather@mockturtl/files/weather@mockturtl/metadata.json
Changes in 3.8:
* Fixed regression when location label override did not work if no City information was available
=> weather@mockturtl Update 2.1.6

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/applet.js
Hi @jaszhix,
The simple addition of a question mark at the end of the URL forces to send a new request to the server. Thus, the data received are as fresh as possible.
Best regards.
Claudiux
=> SpicesUpdate@claudiux: Force server to send fresh data

weather@mockturtl/files/weather@mockturtl/po/zh_CN.po
* Updates Simplified Chinese translations for version 2.1.5
* Update zh_CN.po
* Further tweaks
=> weather@mockturtl zh_CN.po for Update 2.1.5

weather@mockturtl/files/weather@mockturtl/3.6/applet.js, weather@mockturtl/files/weather@mockturtl/3.8/applet.js, weather@mockturtl/files/weather@mockturtl/applet.js, weather@mockturtl/files/weather@mockturtl/po/weather@mockturtl.pot
* Added condition descriptions for translations to support not supported languages on OpenWeatherMap, courtesy of @jorgenqv 
* Removed the Translations section from the older versions as one place is enough for the translations to work.
* Updated template
=> weather@mockturtl Update: Adding OpenWeatherMap Conditions

weather@mockturtl/files/weather@mockturtl/po/zh_CN.po
* Updates Simplified Chinese translations for version 2.1.0
* Update zh_CN.po
* Further tweaks
* Adding OpenWeatherMap conditions translations
=> weather@mockturtl zh_CN.po for Update 2.1.0

weather@mockturtl/files/weather@mockturtl/po/sv.po
New Swedish translate update from template file update #2331 weather@mockturtl/files/weather@mockturtl/po/weather@mockturtl.pot with POT-Creation-Date: 2019-02-24 10:42+0000.
=> weather@mockturtl Update sv.po from latest potfile

cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/po/fr.po
=> cinnamon-timer@jake1164: Update fr.po

weather@mockturtl/files/weather@mockturtl/3.8/applet.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/files/weather@mockturtl/po/hu.po
* Fixed issue that OpenWeatherMap forecast conditions were always translated
* Updated Hungarian translation
* Version bump
=> Weather@mockturtl Update 2.1.7

redshift@marvel4u/files/redshift@marvel4u/po/sv.po
=> redshift@marvel4u: add sv.po

workspace-grid@hernejj/files/workspace-grid@hernejj/po/nl.po
Dutch translation off Workspace-grid @hernejj
=> Workspace-grid @hernejj nl.po

radio@driglu4it/files/radio@driglu4it/applet.js, radio@driglu4it/files/radio@driglu4it/icons/radio.svg
Hi @Driglu4it,
I offer you a new icon for your great applet.
I hope it will suit you. It solves #2355.
Best regards.
Claudiux
=> radio@driglu4it: Symbolic icon added

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/sv.po
=> CinnVIIStarkMenu@NikoKrause: Update sv.po

vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/applet.js
This pull request change the display to allow to start Virtualbox VMs using the headless mode
@mockturtl
=> vboxlauncher@mockturtl: add headless mode for VirtualBox machines

color-picker@fmete/files/color-picker@fmete/po/sv.po
=> color-picker@fmete: Update sv.po

github-projects@morgan-design.com/files/github-projects@morgan-design.com/po/sv.po
=> github-projects@morgan-design.com: Update sv.po

bash-sensors@pkkk/files/bash-sensors@pkkk/po/sv.po
=> bash-sensors@pkkk: Update sv.po

windowlist@cobinja.de/files/windowlist@cobinja.de/4.0/applet.js
This improves monitor names for "Move to another monitor" in the context menu.
Example:
Old style: `Monitor 0`
New Style: `Monitor 0 (LG Electronics 23")`
=> windowlist@cobinja.de Improve monitor names

brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/metadata.json, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/shellUtils.js
=> [brightness-and-gamma-applet@cardsurf] Use mktemp command

disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/metadata.json, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/shellUtils.js
=> [disk-read-and-write-speed@cardsurf] Use mktemp command

download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/metadata.json, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/shellUtils.js
=> [download-and-upload-speed@cardsurf] Use mktemp command

text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/metadata.json, text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/shellUtils.js
=> [text-to-speech-applet@cardsurf] Use mktemp command

website-notifier@cardsurf/files/website-notifier@cardsurf/metadata.json, website-notifier@cardsurf/files/website-notifier@cardsurf/shellUtils.js
=> [website-notifier@cardsurf] Use mktemp command

download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletConstants.js, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletGui.js, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/settings-schema.json, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/shellUtils.js
Added an option to select order of values shown in a panel and in a hover popup.
=> [download-and-upload-speed@cardsurf] Value order

printers@linux-man/files/printers@linux-man/nl.po
Dutch translation Applet printer@linux-man
=> printer@linux-man nl.po

printers@linux-man/files/printers@linux-man/po/nl.po
Dutch translation placed in the po folder.
=> printers@linux-man: nl.po

sound150@claudiux/files/sound150@claudiux/metadata.json
Just changing the metadata.json contents.
=> sound150@claudiux v1.5.2 - Now compatible with Cinnamon 4.0.10

printers@linux-man/files/printers@linux-man/po/pl_PL.po
=>  printers@linux-man Added polish translation

weather@mockturtl/cs.po
Completed translation for new version of the Weather applet.
=>  weather@mockturtl: Updated Czech Translation for v 2.1.2

spices-notifier@germanfr/files/spices-notifier@germanfr/applet.js
Changelog at: https://github.com/germanfr/spices-notifier/commits/master
=> Update Spices notifier v4.0~20190105 (spices-notifier@germanfr)

MessagingMenuV3@blub/files/MessagingMenuV3@blub/applet.js
- Spice name: Messaging Menu V3
- Author: @clefebvre (I think is the author, sorry if I'm mistaken)
- Description: I just added more apps to the array so the applet would have more apps compatible with.
=> spice name: MessagingMenuV3@blub, added more apps

vpnLookOut@claudiux/files/vpnLookOut@claudiux/3.8/applet.js
=> vpnLookOut@claudiux: Fix to display correct icons in Mint-Y-{colorVariant} icon-themes

vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/metadata.json
=> [vpnLookOut@claudiux] v3.3.4 - Now compatible with Cinnamon 4.2

temperature@fevimu/files/temperature@fevimu/metadata.json
Added new cinnamon version in `metadata.json`
Current maintainer @jaszhix
=> temperature@fevimu: Add support for cinnamon 4.2

cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/applet.js, cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/settings-schema.json
Added price alerts
@philtyl @jaszhix
=> cryptocoin@guantanamoe: Price alerts

rwall@typicalfoobar/files/rwall@typicalfoobar/bin/rwall
* update wallheaven URLs
* update to work with new cinnamon version
=> Update rwall applet

ScreenLocker@tuuxx/files/ScreenLocker@tuuxx/applet.js, ScreenLocker@tuuxx/files/ScreenLocker@tuuxx/po/de.po
Use vector icon instead of png file. 
Update on the german translation.
=> Changed icon and german translation

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
Hi @brownsr,
Thank you.
Best regards.
Claudiux
=> [SpicesUpdate@claudiux] v2.1.0 - Lets updatable even xlets downloaded from the Download button

window-list@zeripath.sdf-eu.org/files/window-list@zeripath.sdf-eu.org/README.md, window-list@zeripath.sdf-eu.org/files/window-list@zeripath.sdf-eu.org/applet.js, window-list@zeripath.sdf-eu.org/files/window-list@zeripath.sdf-eu.org/settings-schema.json
Hi!
This PR updates the window-list@zeripath.sdf-eu.org applet to work with cinnamon 4.
=> [window-list@zeripath.sdf-eu.org]: Update to cinnamon-4

batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/metadata.json
Added "4.2" to cinnamon-version in metadata.json to allow use with Cinnamon 4.2
=> batterymonitor@pdcurtis - Update for Cinnamon 4.2

netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/metadata.json
Added "4.2" to cinnamon-version in metadata.json to allow use with Cinnamon 4.2
=> netusagemonitor@pdcurtis - Update for Cinnamon 4.2

vnstat@linuxmint.com/files/vnstat@linuxmint.com/metadata.json
Added "4.2" to cinnamon-version in metadata.json to allow use with Cinnamon 4.2
=> vnstat@linuxmint.com - Update for Cinnamon 4.2

uptime@vatanuki.kun/files/uptime@vatanuki.kun/applet.js, uptime@vatanuki.kun/files/uptime@vatanuki.kun/settings-schema.json, uptime@vatanuki.kun/readme.md
Added a minimal mode, with no text, just a tooltip.
=> uptime@vatanuki.kun - Uptime minimal mode

hwmonitor@sylfurd/files/hwmonitor@sylfurd/applet.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/settings-schema.json, hwmonitor@sylfurd/readme.md
Added a setting that allows the user to control the applet width.
Applet width = {scale factor} * {panel height}
=> hwmonitor@sylfurd - Added a setting for applet width

hwmonitor@sylfurd/files/hwmonitor@sylfurd/applet.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/settings-schema.json, hwmonitor@sylfurd/readme.md
Added a setting for update frequency...
=> hwmonitor@sylfurd - Added a setting so that the user can change the update frequency.

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
Update metadata.json. I forgot to change the version number. Sorry for the inconvenience.
=> [SpicesUpdate@claudiux] v2.2.0

hwmonitor@sylfurd/files/hwmonitor@sylfurd/po/sv.po
hwmonitor@sylfurd - Swedish translation
=> hwmonitor@sylfurd - Swedish translation

hwmonitor@sylfurd/readme.md
hwmonitor@sylfurd - Updated readme.md
=> hwmonitor@sylfurd - Updated readme.md

text-to-speech-applet@cardsurf/README.md, text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/applet.js, text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/metadata.json, text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/settings-schema.json
Removed check if `espeak` text-to-speech engine is installed. More detailed issue description is [here](https://github.com/linuxmint/cinnamon-spices-applets/issues/2500).
=> [text-to-speech-applet@cardsurf] Removed espeak dependency

hwmonitor@sylfurd/files/hwmonitor@sylfurd/applet.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/po/sv.po
Added a restart function to help with and possibly close issue #2371 .
=> hwmonitor@sylfurd - Added restart-function for issue #2371

hwmonitor@sylfurd/files/hwmonitor@sylfurd/applet.js
Fixed bug : Applet now resizes correctly when panel height is changed.
=> hwmonitor@sylfurd - Applet resize bug fixed

text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/applet.js, text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/metadata.json
=> [text-to-speech-applet@cardsurf] Left mouse click resumes reading

hwmonitor@sylfurd/files/hwmonitor@sylfurd/po/hwmonitor@sylfurd.pot
hwmonitor@sylfurd.pot now contains all new strings.
=> [hwmonitor@sylfurd] Update hwmonitor@sylfurd.pot

hwmonitor@sylfurd/files/hwmonitor@sylfurd/po/fr.po
Update containing the translation of the new strings.
=> [hwmonitor@sylfurd] French translation - Update fr.po

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
Hi @brownsr,
This version includes minor changes requested by an user on [https://cinnamon-spices.linuxmint.com/applets/view/309#count](https://cinnamon-spices.linuxmint.com/applets/view/309#count).
Best regards.
Claudiux
=> [SpicesUpdate@claudiux] v2.3.1 - Minor improvements (tooltip and notifications)

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/2.8/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md
Hi @brownsr,
This version 3.0.1 of Spices Update fixes the issue reported in https://github.com/linuxmint/cinnamon-spices-applets/issues/2360#issuecomment-520369040.
Best regards.
Claudiux
=> [SpicesUpdate@claudiux] v3.0.1 - Fixes notification button issue (#2360)

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/metadata.json
Fixes #2507
@NikoKrause: Just added cinnamon 4.2 to the compatible version, test showed no problem
=> CinnVIIStarkMenu@NikoKrause: Fix for compability to cinnamon 4.2

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/2.8/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/3.8/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
Hi @brownsr,
This is just a minor change. Can you merge this branch with your master one, please?
Best regards.
Claudiux
=> [SpicesUpdate@claudiux] v3.0.2 - Show version of Spices Update in tooltip

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
Hi @brownsr,
This is just a version change to take into account the latest improvements: Finnish translation and bug fixed.
Best regards.
Claudiux
=> [SpicesUpdate@claudiux] - v3.0.4

temperature@fevimu/files/temperature@fevimu/applet.js
Hi @brownsr,
Now, this applet can also be used on vertical panels (with ° C or ° F under the value). No changes for horizontal panels.
Best regards.
Claudiux
=> [temperature@fevimu] Make compatible with vertical panels

temperature@fevimu/files/temperature@fevimu/applet.js, temperature@fevimu/files/temperature@fevimu/settings-schema.json
Also fixes a display issue.
@brownsr Can you merge this branch with your master one, please?
Best regards.
Claudiux
=> [temperature@fevimu] Option added: Change color when the temperature becomes High or Critical

mem-monitor-text@datanom.net/files/mem-monitor-text@datanom.net/applet.js
This is relative to issue #2476 
Thanks @brownsr for the hints
This my first pull request to an open source project, this feels nice!
=> mem-monitor-text: issue #2476, fix RAM occupation calculation

temperature@fevimu/files/temperature@fevimu/applet.js, temperature@fevimu/files/temperature@fevimu/po/fr.po, temperature@fevimu/files/temperature@fevimu/po/temperature@fevimu.pot, temperature@fevimu/files/temperature@fevimu/settings-schema.json
Hi @brownsr,
On [the page of this applet](https://cinnamon-spices.linuxmint.com/applets/view/106#count), an user (Fifis) would like an option to stop seeing annoying text alerts, and another (Valyaev ilya) seems to not know what are the High and Critical Temperature thresholds.
This PR responds to their requests.
Best regards.
Claudiux
=> [temperature@fevimu] - Responds to user requests

hwmonitor@sylfurd/files/hwmonitor@sylfurd/applet.js
=> [hwmonitor@sylfurd] Fixes #2371

sessionManager@scollins/files/sessionManager@scollins/po/fr.po
Hi @brownsr,
This is a simple update of the fr.po file.
Best regards.
Claudiux
=> [sessionManager@scollins] French translation - Updated fr.po

radio@driglu4it/files/radio@driglu4it/po/sv.po
=> radio@driglu4it: add sv.po

hwmonitor@sylfurd/files/hwmonitor@sylfurd/graph.js
Minor bug fix that corrects the label position when changing the label font size
=> hwmonitor@sylfurd - Bug fix - label font size

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/de.po
Hi Claudiux, I thought it was time to rework some sentences.
Greetings
=> SpicesUpdate@claudiux: Update German translation

download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/metadata.json, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/settings-schema.json
Set minimum calculation interval to 0.1s.
Closes #2590.
=> [download-and-upload-speed@cardsurf] Set minimum calculation interval

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.2/constants.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.2/settings-schema.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/SpicesUpdate@claudiux.pot, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/es.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/fr.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/it.po
Hi @brownsr,
Best regards.
Claudiux
=> Updates some messages and .pot, fr.po, es.po, it.po files

disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/applet.js, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/appletConstants.js, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/metadata.json, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/settings-schema.json
[Issue description.](https://github.com/linuxmint/cinnamon-spices-applets/issues/2589)
=> [disk-read-and-write-speed@cardsurf] Added support for kernel 4.18+

temperature@fevimu/files/temperature@fevimu/applet.js
Hi @brownsr 
This PR fixes #2591.
Can you merge this branch with you master one, please?
Best regards.
Claudiux
=> [temperature@fevimu] Fixes #2591

temperature@fevimu/files/temperature@fevimu/applet.js
Replaced all synchronous calls (`GLib.spawn_command_line_sync()`) with asynchronous calls (`Util.spawn_async()`).
=> * Replaced all calls to GLib.spawn_command_line_sync() with Util.spawn_async()

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/sv.po
=> SpicesUpdate@claudiux: Update sv.po

weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/files/weather@mockturtl/po/sr.po, weather@mockturtl/src/applet.ts
Courtesy of @Knezev
Issue: https://github.com/linuxmint/cinnamon-spices-applets/issues/2551
=> weather@mockturtl Update 2.3.2:  Add Serbian Translation

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/2.8/settings-schema.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/3.8/settings-schema.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.2/settings-schema.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
=> Adds the ability to increase up to 30 days the time between two checks

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.0/prefsui.glade, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.2/prefsui.glade, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/prefsui.glade, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/prefsui.glade, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/bg.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/da.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/de.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/fi.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/fr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/hr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/multicore-sys-monitor.pot, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/pl.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ru.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/sv.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/tr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/zh_CN.po
Fix the spelling of the word "Refresh".
=> Fix typographical errors

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/fr.po
@NikoKrause 
Hi,
Here is a complete review of the French translation.
Best regards.
Claudiux
=> [CinnVIIStarkMenu@NikoKrause] Updated fr.po - French translation

WindowListGroup@jake.phy@gmail.com/files/WindowListGroup@jake.phy@gmail.com/locale/sv.po
=> WindowListGroup@jake.phy@gmail.com: add sv.po

spices-notifier@germanfr/files/spices-notifier@germanfr/po/sv.po
=> spices-notifier@germanfr: add sv.po

temperature@fevimu/files/temperature@fevimu/applet.js, temperature@fevimu/files/temperature@fevimu/metadata.json, temperature@fevimu/files/temperature@fevimu/po/fr.po, temperature@fevimu/files/temperature@fevimu/po/temperature@fevimu.pot, temperature@fevimu/files/temperature@fevimu/settings-schema.json
Hi @brownsr,
This PR fixes #2633 and also fixes #2642. 
EDIT: It also improves temperature unit display and settings reaction delay.
Best regards.
Claudiux
=> [temperature@fevimu] Fixes #2633 and #2642 + some improvements

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/3.8/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
Hi @brownsr,
This is the version 4.5.0 of Spices Update, which extends to Cinnamon 3.8 and 4.0 the feature previously reserved for Cinnamon 4.2: icon animation during refresh.
Best regards.
Claudiux
=> [SpicesUpdate@claudiux] v4.5.0 - Animated icon during refresh (Cinnamon 3.8+)

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.0/DataProviders.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.0/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.2/DataProviders.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.2/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/DataProviders.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/DataProviders.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/bg.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/da.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/de.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/fi.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/fr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/hr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/it.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/multicore-sys-monitor.pot, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/pl.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ru.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/sv.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/tr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/zh_CN.po
Hi @brownsr,
I made some bug fixes:
- noisy messages in `~/.xsession-errors` are removed; 
- no more memory leak.
I also made some improvements to the tooltip, which is now more readable without any shake.
Before changes  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  After changes
~~This work is in progress. Please do not merge now.~~
**All is OK, tested on all versions of Cinnamon, from 3.0 to 4.2.**
Best regards.
Claudiux
=> [multicore-sys-monitor@ccadeptic23] Tooltip improvements + bug fixes

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/nl.po
Revision Dutch language Version 4.5.0
=> Update SpicesUpdate@claudiux nl.po

stopwatch@pdcurtis/files/stopwatch@pdcurtis/CHANGELOG.md, stopwatch@pdcurtis/files/stopwatch@pdcurtis/README.md, stopwatch@pdcurtis/files/stopwatch@pdcurtis/applet.js, stopwatch@pdcurtis/files/stopwatch@pdcurtis/metadata.json, stopwatch@pdcurtis/files/stopwatch@pdcurtis/settings-schema.json, stopwatch@pdcurtis/files/stopwatch@pdcurtis/stylesheet.css
* Adds an option in Configure... to display Counter Heading in Panel.
* New single line layout for Start, Pause, Reset, Continue and Continue from Start Time in Context Menu
* Adds ability to edit Counter Heading in Context menu as well as Configure..
* Adds option in Configure... to add experimental functions such as an ability to modify time by buttons in Context (right click) Menu - a possible precursor to a flexible timer function
* Implements changes proposed by @100k (Łukasz Dobrowolski)in #2648 and uses code provided by him to implement his suggestions.
* Minor changes in stylesheet.css to match the other applets in the suite..
* Closes #2648
=> stopwatch@pdcurtis v 2.2.0 Add new functionality and flexibility

feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/applet.js
=> [feeds@jonbrettdev.wordpress.com] Update applet.js: only adds a 'let'

clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/po/clipboard-qr@wrouesnel.pot
Hi @brownsr,
The .pot file was removed by #2666. It is recreated by this PR.
Best regards.
Claudiux
=> [clipboard-qr@wrouesnel] .pot file recreated (was removed by #2666)

temperature@fevimu/files/temperature@fevimu/po/temperature@fevimu.pot
Hi @brownsr,
The .pot file was removed by #2667. It is recreated by this PR.
Best regards.
Claudiux
=> [temperature@fevimu] .pot file recreated (was removed by #2667)

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/de.po
=> SpicesUpdate@claudiux: Update de.po

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/2.8/settings-schema.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/3.8/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/3.8/settings-schema.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.2/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.2/settings-schema.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/SpicesUpdate@claudiux.pot, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/de.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/es.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/fi.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/fr.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/hr.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/it.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/nl.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/sv.po
Hi @brownsr,
This PR closes #2679, closes #2680, closes #2681.
Best regards.
Claudiux
=> [SpicesUpdate] v5.1.0: Fixes #2679 #2680 #2681

SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/SpicesUpdate@claudiux.pot, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/es.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/fr.po
Hi @brownsr,
Best regards.
Claudiux
=> [SpicesUpdate] Translations - Updated files: .pot, fr.po and es.po

vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/po/fr.po, vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/po/vboxlauncher@mockturtl.pot
@mockturtl 
This PR updates the .pot file and creates fr.po.
Regards.
Claudiux
=> [vboxlauncher@mockturtl] Update .pot file. Create fr.po - French translation

printers@linux-man/files/printers@linux-man/po/sv.po
=> printers@linux-man: Update sv.po

temperature@fevimu/files/temperature@fevimu/metadata.json
Hi @brownsr,
This PR closes #2700.
Best Regards.
Claudiux
=> [temperature@fevimu] Add ability to use it on Cinnamon 4.4

SW++@mohammad-sn/files/SW++@mohammad-sn/applet.js
...which spammed the Looking Glass log.
No one answered on [https://github.com/linuxmint/cinnamon-spices-applets/issues/2209#issuecomment-533341096](url)  (#2209), but other users mentioned it, too [https://cinnamon-spices.linuxmint.com/applets/view/165](url)
=> [SW++@mohammad-sn] Correct three types of errors

netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/4.0/CHANGELOG.md, netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/4.0/stylesheet.css, netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/metadata.json
* Changes to syleshhet.css to improve colour contrast with wider range of Themes
* Update to allow use with Cinnamon 4.4
=> netusagemonitor@pdcurtis v 3.3.1 Update for 4.4 and stylesheet changes

vnstat@linuxmint.com/files/vnstat@linuxmint.com/metadata.json
=> vnstat@linuxmint.com v 1.0.2.2 Update for 4.4 only

radio@driglu4it/files/radio@driglu4it/settings-schema.json
=> [radio@driglu4it] Increase height of list in settings

ShutdownApplet@DeathMD/files/ShutdownApplet@DeathMD/po/de.po
Hope, you can use that, my dad would be happy with that i guess :smile:
=> Added german translation to the shutdown applet

vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/4.2/applet.js, vpnLookOut@claudiux/files/vpnLookOut@claudiux/4.2/settings-schema.json, vpnLookOut@claudiux/files/vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/metadata.json, vpnLookOut@claudiux/files/vpnLookOut@claudiux/po/es.po, vpnLookOut@claudiux/files/vpnLookOut@claudiux/po/fr.po, vpnLookOut@claudiux/files/vpnLookOut@claudiux/po/vpnLookOut@claudiux.pot
Hi @brownsr,
Best regards.
Claudiux
=> [vpnLookOut@claudiux] v3.4.1 - Add option to be able to start in deactivated state

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/de.po
Hi @claudiux , I waited for further po-changes, but there are none... ;-)
To update this applet in a lower frequency - would it be possible to combine all po-updates at once and merge/release it only then? But I don't know how to manage that, and I fear it creates too much extra work.
=> [SpicesUpdate@claudiux] Update de.po

vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/README.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/4.2/applet.js, vpnLookOut@claudiux/files/vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/metadata.json, vpnLookOut@claudiux/files/vpnLookOut@claudiux/po/es.po, vpnLookOut@claudiux/files/vpnLookOut@claudiux/po/fr.po, vpnLookOut@claudiux/files/vpnLookOut@claudiux/po/vpnLookOut@claudiux.pot
Hi @brownsr,
Best regards.
Claudiux
=> [vpnLookOut@claudiux] v3.4.2: Activate with middle-click or keyboard shortcut

sshlauncher@sumo/files/sshlauncher@sumo/po/sv.po
=> sshlauncher@sumo.mo: Update sv.po

hwmonitor@sylfurd/files/hwmonitor@sylfurd/metadata.json
=> hwmonitor@sylfurd : Wrong version number in metadata.json

weather@mockturtl/files/weather@mockturtl/3.0/applet.js, weather@mockturtl/files/weather@mockturtl/3.0/darkSky.js, weather@mockturtl/files/weather@mockturtl/3.0/openWeatherMap.js, weather@mockturtl/files/weather@mockturtl/3.0/utils.js, weather@mockturtl/files/weather@mockturtl/3.8/applet.js, weather@mockturtl/files/weather@mockturtl/3.8/darkSky.js, weather@mockturtl/files/weather@mockturtl/3.8/openWeatherMap.js, weather@mockturtl/files/weather@mockturtl/3.8/utils.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/files/weather@mockturtl/po/weather@mockturtl.pot, weather@mockturtl/src/applet.ts, weather@mockturtl/src/darkSky.ts, weather@mockturtl/src/openWeatherMap.ts, weather@mockturtl/src/utils.ts
* Various small bugfixes
* Change repeated error handling (increases time between retries, tops up at 15 mins)
* Add last refreshed time to the tool-tip next to location.
Tested and ready.
=> weather@mockturtl Update 2.3.4

qredshift@quintao/README.md, qredshift@quintao/files/qredshift@quintao/applet.js, qredshift@quintao/files/qredshift@quintao/metadata.json, qredshift@quintao/files/qredshift@quintao/settings-schema.json, qredshift@quintao/files/qredshift@quintao/stylesheet.css
I forgot to push the commit on last pull request.
~~The drugs are not doing me good.~~
* 1.4
- Fixed icon scale.
- Added support to version 4.3 and 4.4
=> Fixed some issues reported by the users. 

weather@mockturtl/files/weather@mockturtl/po/bg.po
Updated Bulgarian Translation using the latest translation template.
=> Updated Bulgarian Translation

cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/metadata.json
=> [cinnamon-timer@jake1164] Now compatible with Cinnamon 4.4

cpufreq@mtwebster/files/cpufreq@mtwebster/applet.js
Still needs some menu stuff overhauled.
Fixes #2676
=> cpufreq@mtwebster: Fix, cleanup, make it work again.

betterlock/files/betterlock/po/tr.po
=> betterlock: add tr.po

search-box@mtwebster/files/search-box@mtwebster/po/tr.po
search-box@mtwebster: add tr.po
=> search-box@mtwebster: add tr.po

gnote@brett-smith/README.md, gnote@brett-smith/files/gnote@brett-smith/applet.js, gnote@brett-smith/files/gnote@brett-smith/icons/gnote-panel-symbolic.svg, gnote@brett-smith/files/gnote@brett-smith/icons/gnote-panel.svg, gnote@brett-smith/files/gnote@brett-smith/metadata.json
* Different icon.
* Symbolic icon.
* Got rid of debug output and other error messages.
* Changed how menu is rebuilt on changes.
=> gnote@brett-smith: Fixes #2775 and other comments from initial merge.

gnote@brett-smith/files/gnote@brett-smith/po/tr.po
gnote@brett-smith: added tr.po
=> gnote@brett-smith: added tr.po

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/DataProviders.js
=> [multicore-sys-monitor@ccadeptic23] Fixes #2768

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/DataProviders.js
DataProvider.js: bug fixed!
Corrects a value calculation error due to a confusion between decimal log and neperian log.
@brownsr Can you merge this branch urgently, please? Sorry for the inconvenience.
Bonne fin d'année ! (Happy end of the year!)
Best regards.
Claudiux
=> [multicore-sys-monitor@ccadeptic23] Corrects a value calculation error

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/2.8/settings-schema.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/3.8/settings-schema.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/cs/4.4/modules/cs_themes.py, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/SpicesUpdate@claudiux.pot, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/es.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/fr.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/it.po
Hi @brownsr,
When trying to install this applet under Debian 10 (Cinnamon 3.8), I noticed that the settings-schema.json file should not contain a "units" field. This is fixed.
Best regards.
Claudiux
=> [SpicesUpdate@claudiux] v5.2.1: Make it configurable (Cinnamon 2.8 -> 4.0)

download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/metadata.json, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/settings-schema.json
Added a setting that determines how often to update a list of available network interfaces
=> [download-and-upload-speed@cardsurf] Update list of available interfaces

gnote@brett-smith/files/gnote@brett-smith/po/sv.po
=> gnote@brett-smith: add sv.po

qredshift@quintao/files/qredshift@quintao/applet.js, qredshift@quintao/files/qredshift@quintao/po/qredshift@quintao.pot, qredshift@quintao/files/qredshift@quintao/po/tr.po
Add locale support
Add pot file
Add tr.po file
@raphaelquintao
=>  qredshift@quintao: Add locale support

qredshift@quintao/files/qredshift@quintao/po/fr.po
French translation using pot file from #2772.
=> [qredshift@quintao] Create fr.po - French translation

qredshift@quintao/files/qredshift@quintao/po/sv.po
Add Swedish translation using pot file from [#2772](https://github.com/linuxmint/cinnamon-spices-applets/pull/2772).
=> qredshift@quintao: add sv.po

ratecurrency@magner/files/ratecurrency@magner/po/sv.po
=> ratecurrency@magner: add sv.po

search-box@mtwebster/files/search-box@mtwebster/po/sv.po
=> search-box@mtwebster: Update sv.po

brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/sv.po
=> brightness-and-gamma-applet@cardsurf: Update sv.po

qredshift@quintao/README.md, qredshift@quintao/files/qredshift@quintao/applet.js, qredshift@quintao/files/qredshift@quintao/js/QUtils.js, qredshift@quintao/files/qredshift@quintao/metadata.json, qredshift@quintao/files/qredshift@quintao/po/pt.po, qredshift@quintao/files/qredshift@quintao/po/qredshift@quintao.pot, qredshift@quintao/files/qredshift@quintao/po/sv.po, qredshift@quintao/files/qredshift@quintao/po/tr.po, qredshift@quintao/files/qredshift@quintao/settings-schema.json
* 1.5
- Added keyboard shortcut to toggle On/Off `<Control>End`
- Added localization support.
- Added Portuguese translation.
- Improved some texts.
=> [qredshift@quintao] - Version 1.5

qredshift@quintao/files/qredshift@quintao/po/sv.po
=> qredshift@quintao: Update sv.po

ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/po/de.po
Full german translation of the applet, tested.
=> ShutdownMenuWithIcons@LLOBERA: German translations (de.po)

qredshift@quintao/files/qredshift@quintao/po/tr.po
qredshift@quintao: update tr.po
=> qredshift@quintao: update tr.po

windowlist@cobinja.de/files/windowlist@cobinja.de/4.0/applet.js, windowlist@cobinja.de/files/windowlist@cobinja.de/4.0/stylesheet.css
This fixes https://github.com/Cobinja/CobiWindowList/issues/29
=> windowlist@cobinja.de: Make numbers more readable

download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/metadata.json, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/settings-schema.json
Added settings that determine minimum download and upload values displayed in the panel.
=> [download-and-upload-speed@cardsurf] Minimum value thresholds

cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/applet.js, cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/metadata.json, cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/settings-schema.json
=> cryptocoin@guantanamoe: Custom currency format

weather@mockturtl/files/weather@mockturtl/3.0/applet.js, weather@mockturtl/files/weather@mockturtl/3.8/applet.js, weather@mockturtl/src/applet.ts
Wind units and direction were not translated, so it needs fix. Line was too long to read, so I formatted with prettier
=> Weather wind text translation fix

cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/applet.js, cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/metadata.json, cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/settings-schema.json
This makes easy to check you current balance.
@philtyl @jaszhix
=> cryptocoin@guantanamoe: Allow to define balance to multiply the price

web-developer-menu@infiniteshroom/files/web-developer-menu@infiniteshroom/applet.js
Bug fix. This PR fixes #2760 (undeclared variables).
The author of this applet, @infiniteshroom, has not had public activity on Github since December 2018.
=> [web-developer-menu@infiniteshroom] Fix issue #2760

mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/fr.po
=> [mailnagapplet@ozderya.net] Add French translation

clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/QR.js, clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/QRLib.js, clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/applet.js, clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/metadata.json
Fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/2295 applet scaling
Fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/1718
QR code generation for numbers
=> clipboard-qr@wrouesnel: Version 1.13

weather@mockturtl/files/weather@mockturtl/po/sv.po
Update sv.po from the latest template pot-file
=> Update Swedish language weather@mockturtl

bing-wallpaper@starcross.dev/files/bing-wallpaper@starcross.dev/applet.js
Hi Alex,
this fixes #2825 
Two remarks:
- I personally set the loop to 10 minutes - a wallpaper that changes once a day isn't so important. But I don't know if that makes any tiny bit of difference; may be the 5 min. loop is "the same" related to CPU power, so I let it unchanged in the pull request.
- _done_ [GLib.get_user_special_dir(GLib.UserDirectory.DIRECTORY_PICTURES) doesn't work, at least in Linux Mint 19.3. The picture is saved in $HOME. I don't know how to fix that. Do you have a clue?]
=> Update bing-wallpaper@starcross.dev: recover image name

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language update from latest pot file.
=> weather@mockturtl update sv.po

temperature@fevimu/files/temperature@fevimu/po/de.po
This PR adds the last missing strings to the German translation of the temperature applet
=> temperature@fevimu - Update german translation

vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/4.2/applet.js, vpnLookOut@claudiux/files/vpnLookOut@claudiux/4.2/settings-schema.json, vpnLookOut@claudiux/files/vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/metadata.json
~~Work in progress.~~
Hi @brownsr,
This is certainly the latest version of this applet (with the exception of bug fixes). I completely rewrite its code to create a new applet, which I will offer soon.
Kind regards.
Claudiux
=> [vpnLookOut@claudiux] v3.5.0: Some bug fixes and code cleanup

web-developer-menu@infiniteshroom/files/web-developer-menu@infiniteshroom/applet.js
gksu is not supporting in newer mints. so changed gksu to sudo.
=> Add Support for new Mint's sudo

ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/po/fr.po
=> [ScreenShot+RecordDesktop] Add French support

weather@mockturtl/CHANGELOG.md, weather@mockturtl/files/weather@mockturtl/3.0/settings-schema.json, weather@mockturtl/files/weather@mockturtl/3.8/settings-schema.json, weather@mockturtl/files/weather@mockturtl/metadata.json
Changes:
* Fixes [#2853](https://github.com/linuxmint/cinnamon-spices-applets/issues/2853)
=> weather@mockturtl Update 2.4.2

ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/po/fr.po
Initial version is not take in account, on a french environment.
This change seen to fix the issue:
```
"Plural-Forms: nplurals=2; plural=(n != 1);\n" 
```
=> [ScreenShot+RecordDesktop@tech71] fix french translation

weather@mockturtl/CHANGELOG.md, weather@mockturtl/files/weather@mockturtl/3.0/applet.js, weather@mockturtl/files/weather@mockturtl/3.0/darkSky.js, weather@mockturtl/files/weather@mockturtl/3.0/met_norway.js, weather@mockturtl/files/weather@mockturtl/3.0/openWeatherMap.js, weather@mockturtl/files/weather@mockturtl/3.0/settings-schema.json, weather@mockturtl/files/weather@mockturtl/3.8/applet.js, weather@mockturtl/files/weather@mockturtl/3.8/darkSky.js, weather@mockturtl/files/weather@mockturtl/3.8/met_norway.js, weather@mockturtl/files/weather@mockturtl/3.8/openWeatherMap.js, weather@mockturtl/files/weather@mockturtl/3.8/settings-schema.json, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/files/weather@mockturtl/po/hu.po, weather@mockturtl/files/weather@mockturtl/po/weather@mockturtl.pot, weather@mockturtl/src/applet.ts, weather@mockturtl/src/darkSky.ts, weather@mockturtl/src/declarations/cinnamon.d.ts, weather@mockturtl/src/openWeatherMap.ts
Changes:
* Fixes [#2861](https://github.com/linuxmint/cinnamon-spices-applets/issues/2861)
* Fixes [#2860](https://github.com/linuxmint/cinnamon-spices-applets/issues/2860)
* Minor condition text fixes for MET Norway
* One setting was in the wrong category in settings, moved.
=> weather@mockturtl update 2.4.3

weather@mockturtl/files/weather@mockturtl/po/sv.po
Update Swedish language from latest pot-file
=> weather@mockturtl Update sv.po 2.4.3

jenkins@backuity.org/files/jenkins@backuity.org/applet.js
folders of Jenkins showed up as failure.
I removed them completely from the view. Not the best solution, but the easiest and fastest for now.
Its really annoying to see the read icon even when its all building correctly.
=> jenkins@backuity.org: Jenkins Folders showed up as failure

windowlist@cobinja.de/CHANGELOG.md, windowlist@cobinja.de/files/windowlist@cobinja.de/4.0/applet.js
This fixes https://github.com/Cobinja/CobiWindowList/issues/30
=> windowlist@cobinja.de: Fix number badge growing

weather@mockturtl/CHANGELOG.md, weather@mockturtl/files/weather@mockturtl/3.0/applet.js, weather@mockturtl/files/weather@mockturtl/3.0/darkSky.js, weather@mockturtl/files/weather@mockturtl/3.0/openWeatherMap.js, weather@mockturtl/files/weather@mockturtl/3.0/settings-schema.json, weather@mockturtl/files/weather@mockturtl/3.0/weatherbit.js, weather@mockturtl/files/weather@mockturtl/3.8/applet.js, weather@mockturtl/files/weather@mockturtl/3.8/darkSky.js, weather@mockturtl/files/weather@mockturtl/3.8/openWeatherMap.js, weather@mockturtl/files/weather@mockturtl/3.8/settings-schema.json, weather@mockturtl/files/weather@mockturtl/3.8/weatherbit.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/src/applet.ts, weather@mockturtl/src/darkSky.ts, weather@mockturtl/src/openWeatherMap.ts, weather@mockturtl/src/weatherbit.ts
Changes:
* Fixes [#2782](https://github.com/linuxmint/cinnamon-spices-applets/issues/2872)
* Add ability to override applet label with injecting values (customise and fit text on horizontal and vertical panels as well)
=> weather@mockturtl Update 2.4.4

sshlauncher@sumo/files/sshlauncher@sumo/po/fr.po
Po file for the French translation.
=> French translation for SSH Launcher

hwmonitor@sylfurd/README.md, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.2/applet.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.2/providers.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.2/settings-schema.json, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/applet.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/providers.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/settings-schema.json, hwmonitor@sylfurd/files/hwmonitor@sylfurd/metadata.json
=> hwmonitor@sylfurd : Version 1.1.1

scripts@paucapo.com/files/scripts@paucapo.com/po/fr.po
Add French translation to the scripts@paucapo.com applet
=> Add French translation

weather@mockturtl/nl.po
updated Dutch translation Version 2.4.5 (2020-03-05 08:38:14)
=> Weather (weather@mockturtl) nl.po

weather@mockturtl/files/weather@mockturtl/po/nl.po
Improvements Dutch translation
=> Weather (weather@mockturtl) update nl.po

weather@mockturtl/CHANGELOG.md, weather@mockturtl/README.md, weather@mockturtl/files/weather@mockturtl/3.0/utils.js, weather@mockturtl/files/weather@mockturtl/3.8/utils.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/files/weather@mockturtl/po/hu.po, weather@mockturtl/src/applet.ts, weather@mockturtl/src/utils.ts
Changes:
* Fixes [#2907](https://github.com/linuxmint/cinnamon-spices-applets/issues/2907)
* Update Hungraian translation
=> weather@mockturtl Update 2.4.6

bash-sensors@pkkk/files/bash-sensors@pkkk/applet.js, bash-sensors@pkkk/files/bash-sensors@pkkk/metadata.json, bash-sensors@pkkk/files/bash-sensors@pkkk/po/bash-sensors@pkkk.pot, bash-sensors@pkkk/files/bash-sensors@pkkk/settings-schema.json
Just had the need to execute a command, whenever the applet is started, so I added the possibility to add one.
=> Added a start-up command, which is executed when the applet is started.

windowlist@cobinja.de/CHANGELOG.md, windowlist@cobinja.de/files/windowlist@cobinja.de/4.0/applet.js
This fixes https://github.com/Cobinja/CobiWindowList/issues/35
=> windowlist@cobinja.de Don't show "Visible on all workspaces" if there is only one workspace

disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/applet.js, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/metadata.json
Added support to read partition names which contain special characters
=> [disk-read-and-write-speed@cardsurf] Read partition names

ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/po/is.po
New Icelandic translation based on ScreenShot+RecordDesktop@tech71.pot as of today
=> New Icelandic translation

ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/po/is.po, weather@mockturtl/files/weather@mockturtl/po/is.po
Updated Icelandic translation of weather@mockturtl applet for Cinnamon.
=> Updated Icelandic translation of weather@mockturtl

ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/po/is.po, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/applet.js, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/metadata.json, weather@mockturtl/files/weather@mockturtl/po/is.po
New Icelandic translation of color-picker@fmete applet.
Still learning the basics of GitHub, hopefully this is the way to do this.
=> Icelandic translation of color-picker@fmete applet

weather@mockturtl/CHANGELOG.md, weather@mockturtl/files/weather@mockturtl/3.0/settings-schema.json, weather@mockturtl/files/weather@mockturtl/3.0/stylesheet.css, weather@mockturtl/files/weather@mockturtl/3.8/settings-schema.json, weather@mockturtl/files/weather@mockturtl/3.8/stylesheet.css, weather@mockturtl/files/weather@mockturtl/metadata.json
Changes:
* Fixes [#2929](https://github.com/linuxmint/cinnamon-spices-applets/issues/2929)
* Fix styling issues with forecasts box - There wasn't enough margin on the bottom when the icon's height were bigger than the text, neither when the forecasts were wider than the current weather box.
=> weather@mockturtl Update 2.4.7

weather@mockturtl/files/weather@mockturtl/po/nl.po
Adjusted due to update weather@mockturtl.pot
=> Update nl.po Weather (weather@mockturtl) 2.4.7

weather@mockturtl/files/weather@mockturtl/po/sv.po
Update Swedish language file from latest pot-file.
=> weather@mockturtl Update sv.po 2.4.7

hwmonitor@sylfurd/README.md, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.2/applet.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.2/graph.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.2/providers.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.2/settings-schema.json, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/applet.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/graph.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/providers.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/settings-schema.json, hwmonitor@sylfurd/files/hwmonitor@sylfurd/metadata.json
Added a new battery graph for laptop users.
=> hwmonitor@sylfurd : Battery graph

Cinnamenu@json/files/Cinnamenu@json/3.2/CREDITS, Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/constants.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json
+removed an unneeded file and some minor changes.
=> Cinnamenu@json: Increased maximum number of columns

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/ro.po
@claudiux here is a Romanian translation.
=> Adding Romanian translation for SpicesUpdate@claudiux

weather@mockturtl/CHANGELOG.md, weather@mockturtl/README.md, weather@mockturtl/files/weather@mockturtl/3.0/applet.js, weather@mockturtl/files/weather@mockturtl/3.0/darkSky.js, weather@mockturtl/files/weather@mockturtl/3.0/met_norway.js, weather@mockturtl/files/weather@mockturtl/3.0/openWeatherMap.js, weather@mockturtl/files/weather@mockturtl/3.0/settings-schema.json, weather@mockturtl/files/weather@mockturtl/3.0/stylesheet.css, weather@mockturtl/files/weather@mockturtl/3.0/utils.js, weather@mockturtl/files/weather@mockturtl/3.0/weatherbit.js, weather@mockturtl/files/weather@mockturtl/3.0/yahoo.js, weather@mockturtl/files/weather@mockturtl/3.8/applet.js, weather@mockturtl/files/weather@mockturtl/3.8/darkSky.js, weather@mockturtl/files/weather@mockturtl/3.8/met_norway.js, weather@mockturtl/files/weather@mockturtl/3.8/openWeatherMap.js, weather@mockturtl/files/weather@mockturtl/3.8/settings-schema.json, weather@mockturtl/files/weather@mockturtl/3.8/stylesheet.css, weather@mockturtl/files/weather@mockturtl/3.8/utils.js, weather@mockturtl/files/weather@mockturtl/3.8/weatherbit.js, weather@mockturtl/files/weather@mockturtl/3.8/yahoo.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/files/weather@mockturtl/po/weather@mockturtl.pot, weather@mockturtl/files/weather@mockturtl/yahoo-bridge.py, weather@mockturtl/src/applet.ts, weather@mockturtl/src/darkSky.ts, weather@mockturtl/src/met_norway.ts, weather@mockturtl/src/openWeatherMap.ts, weather@mockturtl/src/utils.ts, weather@mockturtl/src/weatherbit.ts, weather@mockturtl/src/yahoo.ts
Changes:
* Update Openweathermap to their unified API call
* Add information on DarkSky aquisition to Readme
* Fix translation issues in files other than applet.js
* Add Yahoo Weather to the available services
* Fix issue when system time is changed backwards, the applet stops updating until time gets to the time previously set
* Change 'Updated' to 'As of' to have a clearer meaning.
Tested on Cinnamon version 3.0 as well.
=> weather@mockturtl Update 2.4.8

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/tr.po
Hi @brownsr,
This is a Turkish translation offered by @serkan-maker.
Kind regards.
Claudiux
=> [SpicesUpdate@claudiux] Turkish translation by Serkan Önder

hwmonitor@sylfurd/README.md, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.2/applet.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.2/graph.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.2/settings-schema.json, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/applet.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/graph.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/settings-schema.json, hwmonitor@sylfurd/files/hwmonitor@sylfurd/metadata.json
A new setting for hwmonitor@sylfurd :
* Don't draw grid lines
* Draw grid lines over graphs
* Draw graphs over grid lines
=> hwmonitor@sylfurd : New setting, grid lines

weather@mockturtl/files/weather@mockturtl/po/nl.po
=> Weather (weather@mockturtl) Version 2.4.8  nl.po

weather@mockturtl/files/weather@mockturtl/po/nl.po
=> Weather (weather@mockturtl) V2.4.8 Updated nl.po

weather@mockturtl/files/weather@mockturtl/po/sv.po
Translation update Swedish language from latest pot-file.
=> weather@mockturtl Update sv.po 2.4.8

weather@mockturtl/CHANGELOG.md, weather@mockturtl/files/weather@mockturtl/3.0/applet.js, weather@mockturtl/files/weather@mockturtl/3.8/applet.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/src/applet.ts
Fixes [#2970](https://github.com/linuxmint/cinnamon-spices-applets/issues/2970)
=> weather@mockturtl Update 2.4.9

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/applet.js, CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/settings-schema.json
Resolves #2565
Update:
@NikoKrause tag is added.
=> [CinnVIIStarkMenu@NikoKrause] New option to switch order of shutdown buttons

weather@mockturtl/CHANGELOG.md, weather@mockturtl/README.md, weather@mockturtl/files/weather@mockturtl/3.0/openWeatherMap.js, weather@mockturtl/files/weather@mockturtl/3.0/settings-schema.json, weather@mockturtl/files/weather@mockturtl/3.0/utils.js, weather@mockturtl/files/weather@mockturtl/3.0/weatherbit.js, weather@mockturtl/files/weather@mockturtl/3.8/openWeatherMap.js, weather@mockturtl/files/weather@mockturtl/3.8/settings-schema.json, weather@mockturtl/files/weather@mockturtl/3.8/utils.js, weather@mockturtl/files/weather@mockturtl/3.8/weatherbit.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/files/weather@mockturtl/po/weather@mockturtl.pot, weather@mockturtl/src/openWeatherMap.ts, weather@mockturtl/src/utils.ts, weather@mockturtl/src/weatherbit.ts
Changes:
* Fixes [#2980](https://github.com/linuxmint/cinnamon-spices-applets/issues/2980) and [#2979](https://github.com/linuxmint/cinnamon-spices-applets/issues/2979) by implementing checks for OpenWeatherMap and change Readme.
* Hopefully Fixes [#2977](https://github.com/linuxmint/cinnamon-spices-applets/issues/2977) in most cases. You can never know with JSs flimsy timezone support.
=> weather@mockturtl Update 2.5.0

weather@mockturtl/files/weather@mockturtl/po/nl.po
=> Weather (weather@mockturtl) 2.5.0 update nl.po

clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/QR.js, clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/metadata.json
=> clipboard-qr@wrouesnel: (v1.14) create qr-code.svg file

timeshift-spy@nicog60/CHANGELOG.md, timeshift-spy@nicog60/files/timeshift-spy@nicog60/applet.js, timeshift-spy@nicog60/files/timeshift-spy@nicog60/po/en.po, timeshift-spy@nicog60/files/timeshift-spy@nicog60/po/fr.po, timeshift-spy@nicog60/files/timeshift-spy@nicog60/po/timeshift-spy@nicog60.pot
Fix that crash if timeshift is not installed or not configured
=> timeshift-spy@nicog60: fix crash when timeshift is not installed

timeshift-spy@nicog60/files/timeshift-spy@nicog60/applet.js
Fixed an issue. The applet was not working if the timeshift was configured in the root filesystem.
=> timeshift-spy@nicog60: fixed not working in root

weather@mockturtl/files/weather@mockturtl/po/sv.po
Translation update Swedish language from latest pot template file.
=> weather@mockturtl Update sv.po 2.5.0

cs.po, weather@mockturtl/cs.po
weather@mockturtl: Updated  Czech translation for Weather 2.5
=> weather@mockturtl

cheaty@centurix/files/cheaty@centurix/refdocs/Tmux/icon.svg, cheaty@centurix/files/cheaty@centurix/refdocs/Tmux/sheet.json
There is a basic cheat sheet for tmux terminal tool.
@Centurix
=> cheaty@centurix: Added tmux cheatsheet

weather@mockturtl/files/weather@mockturtl/po/fr.po
-improve some translation, wording
=> weather@mockturtl Update fr.po

temperature@fevimu/files/temperature@fevimu/po/fr.po, temperature@fevimu/files/temperature@fevimu/po/temperature@fevimu.pot
In response to https://github.com/linuxmint/cinnamon-spices-applets/commit/e9ca8506672bbc0f357003e46616098ccbf090c7#commitcomment-38901965
=> [temperature@fevimu] Updated .pot and fr.po files

temperature@fevimu/files/temperature@fevimu/po/nl.po
=> Update nl.po CPU Temperature Indicator

calendar@ccprog/files/calendar@ccprog/po/fr.po
French translation for the calendar@ccprog applet
=> Calendar@ccprog: French translation

tor-button@shatur/files/tor-button@shatur/applet.js
Fix error "Assignment to undeclared variable result.", mentioned in issue #2197
=> Fix Tor Button syntax error

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/applet.js, CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/metadata.json
fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/3037: Cinnamon freezes while dragging applications
=> CinnVIIStarkMenu@NikoKrause: v1.23

hwmonitor@sylfurd/files/hwmonitor@sylfurd/metadata.json
Added support for version 4.6 of Cinnamon.
=> hwmonitor@sylfurd : Cinnamon 4.6

qredshift@quintao/README.md, qredshift@quintao/files/qredshift@quintao/applet.js, qredshift@quintao/files/qredshift@quintao/metadata.json, qredshift@quintao/files/qredshift@quintao/po/bg.po
* 1.5.1
- Added support to version 4.6.
- Update night brightness on scrolling.
- Added translations:
- Bulgarian
=> Version 1.5.1

calendar@ccprog/files/calendar@ccprog/po/fr.po
=> Update French translation of calendar@ccprog

temperature@fevimu/files/temperature@fevimu/metadata.json
=> [temperature@fevimu] Now compatible with Cinnamon 4.6

weather@mockturtl/files/weather@mockturtl/po/nl.po
=> Update nl.po Weather (weather@mockturtl) v2.6.0

weather@mockturtl/CHANGELOG.md, weather@mockturtl/files/weather@mockturtl/3.0/applet.js, weather@mockturtl/files/weather@mockturtl/3.8/applet.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/src/applet.ts
Fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/3059
=> weather@mockturtl Hotfix 2.6.1

weather@mockturtl/files/weather@mockturtl/po/fr.po
Update French translation of weather@mockturtl
=> Update weather@mockturtl French translation

kdeccc@Severga/files/kdeccc@Severga/applet.js
Applet for any layout, including vertical
=> KDE Connect - Applet for ANY layout

temperature@fevimu/files/temperature@fevimu/po/ro.po
=> [temperature@fevimu] Added ro.po

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.2/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.2/constants.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.2/settings-schema.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
Hi @brownsr,
This is the v5.4.1 of Spices Update. Just a code clean-up and some minor changes.
Kind regards.
Claudiux
=> [SpicesUpdate@claudiux] v5.4.1 - Code clean-up

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/metadata.json
-Swapped user-info button with system-settings button.
-Removed ability to change order of categories.
-A few bug fixes.
=> [Cinnamenu@json] Replaced user-info icon + bug fixes.

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.2/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
Hi @brownsr,
This PR fixes #3071.
Kind regards.
Claudiux
=> [SpicesUpdate@claudiux] v5.4.2 - Fixes issue #3071

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/fuzzy.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/metadata.json
search now prioritises beginning of word matches
=> [Cinnamenu@json] Reinstated category reordering + improved search

stopwatch@pdcurtis/files/stopwatch@pdcurtis/metadata.json
* Additions to cinnamon-version in metadata.json for Mint 20 series
=> stopwatch@pdcurtis Version 2.3.1 Fix for use in Cinnamon 4.6 to 5.2

netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/metadata.json
* Additions to cinnamon-version in metadata.json for Mint 20 series
=> netusagemonitor@pdcurtis Version 3.3.2 Fix for use in Cinnamon 4.6 to 5.2

batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/metadata.json
* Additions to cinnamon-version in metadata.json for Mint 20
=> batterymonitor@pdcurtis Version 1.4.0.1 Fix for Cinnamon 4.6 to 5.2

vnstat@linuxmint.com/files/vnstat@linuxmint.com/metadata.json
* Addition to cinnamon-version in metadata.json for Cinnamon 4.6 (Mint 20)
=> vnstat@linuxmint.com Version 1.0.3 Fix for Cinnamon 4.6

weather@mockturtl/files/weather@mockturtl/po/sv.po
Update Swedish language from latest pot template file.
=> weather@mockturtl Update sv.po 2.6.0

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
-new option to include fav apps with session buttons + choice of placement.
-bug fixes
known issue: keyboard navigation needs fixing.
=> [Cinnamenu.json] New feature: session+fav buttons placement choice.

weather@mockturtl/files/weather@mockturtl/po/nl.po
=> Update nl.po <> Weather (weather@mockturtl)V 2.6.2

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
=> [Cinnamenu@json] Bug fix.

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language update for the latest pot template file.
=> weather@mockturtl Update sv.po 2.6.2

timeshift-spy@nicog60/files/timeshift-spy@nicog60/applet.js, timeshift-spy@nicog60/files/timeshift-spy@nicog60/po/fr.po, timeshift-spy@nicog60/files/timeshift-spy@nicog60/po/timeshift-spy@nicog60.pot
@NicoG60 
This PR fixes #3095. (Changes in applet.js.)
It also contains a new .pot file and the fr.po is updated.
Regards.
Claudiux
=> [timeshift-spy@nicog60] Translation bug fixes

Cinnamenu@json/files/Cinnamenu@json/3.2/applet.js, Cinnamenu@json/files/Cinnamenu@json/3.2/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Added 'Run with Nvidia' option to application right click menu, similar to Mint menu.
=> [Cinnamenu@json] Add option run application on Nvidia GPU when render offload is available.

force-quit@cinnamon.org/files/force-quit@cinnamon.org/po/fr.po
=> [force-quit@cinnamon.org] French translation

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/DataProviders.js
Now testing whether i is NaN in formatBytes. (Sometime it is the case at startup; so, this applet freezed.)
=> [multicore-sys-monitor@ccadeptic23] Bug fix: this applet no longer freezes on startup

windowlist@cobinja.de/CHANGELOG.md, windowlist@cobinja.de/files/windowlist@cobinja.de/4.0/applet.js
- Remove some leftover development output
- Improve urgent/attention handling
- Make app buttons squared in all themes
- Improve number placement
=> windowlist@cobinja.de Multiple patches

weather@mockturtl/files/weather@mockturtl/po/nl.po
=> weather@mockturtl Update nl.po

weather@mockturtl/files/weather@mockturtl/po/fr.po
=> Weather@mockturtl : Update French translation

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot, Cinnamenu@json/files/Cinnamenu@json/po/da.po, Cinnamenu@json/files/Cinnamenu@json/po/de.po, Cinnamenu@json/files/Cinnamenu@json/po/fr.po, Cinnamenu@json/files/Cinnamenu@json/po/sv.po
+ option to open menu on fav apps category
+ fixed category hover unresponsiveness bug
=> [Cinnamenu@json] New option to open menu on favorite apps

weather@mockturtl/files/weather@mockturtl/po/fr.po
Update French translation for weather@mockturtl
=> weather@mockturtl : update fr.po

Cinnamenu@json/README.md, Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot, Cinnamenu@json/files/Cinnamenu@json/po/da.po, Cinnamenu@json/files/Cinnamenu@json/po/de.po, Cinnamenu@json/files/Cinnamenu@json/po/es.po, Cinnamenu@json/files/Cinnamenu@json/po/et.po, Cinnamenu@json/files/Cinnamenu@json/po/sv.po
+ a bug fix - dragging categories/app when icon size is 0 now works
=> [Cinnamenu@json] Updated translations.

mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/applet.js
Fix time difference string error when time > 2 hours and < 1 day
Add more time constants
=> [mailnagapplet@ozderya.net]: Fix time difference error

SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/README.md
Hi @brownsr,
Just some changes in the README.md file.
Kind regards.
Claudiux
=> [SpicesUpdate@claudiux] v6.0.1 - Symbola font no longer included. README.md updated.

weather@mockturtl/files/weather@mockturtl/po/fr.po
[weather@mockturtl] Update fr.po
=> [weather@mockturtl] Update the French translation to the last version

weather@mockturtl/files/weather@mockturtl/po/nl.po
Vertaling - [x] Bijgewerkt :page_facing_up: Versie 2.6.5
=> Update nl.po weather@mockturtl Versie 2.6.5

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/nl.po
=> Update nl.po Spices Update (SpicesUpdate@claudiux)

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language update from the latest pot template file.
=> weather@mockturtl Update sv.po 2.6.5

vpnLookOut@claudiux/files/vpnLookOut@claudiux/CHANGELOG.md, vpnLookOut@claudiux/files/vpnLookOut@claudiux/metadata.json, vpnLookOut@claudiux/files/vpnLookOut@claudiux/scripts/vpn_iface_detect.sh
@brownsr 
Hi Simon,
There are some minor changes in vpnLookOut@claudiux.
Kind regards.
Claudiux
=> [vpnLookOut@claudiux] v3.5.1 - Now detects Wireguard links (but not manage them)

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.2/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.2/constants.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.6/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.6/constants.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
@brownsr 
Hi Simon,
Just some minor changes.
Kind regards.
Claudiux
=> [SpicesUpdate@claudiux] v6.0.2 - Remove all notifications when reloading this applet

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserBookmarks.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/da.po
+ fixed bug causing list view scrolling slow down.
+ da.po update
=> [Cinnamenu@json] Bug fix + translation

kdecapplet@joejoetv/files/kdecapplet@joejoetv/applet.js, kdecapplet@joejoetv/files/kdecapplet@joejoetv/metadata.json, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/de.po, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/de_de.po, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/kdecapplet.pot
- Added support for new features in KDE Connect 1.4
- SMS App
- Photo Plugin
- Added support for checking KDE Connect version and version differenced between 1.3 and 1.4
- Added more error messages
I think I got it right with the pull request.
=> [kdecapplet@joejoetv] KDE Connect 1.4 support

batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/metadata.json
* Update version number in metadata.json to 1.4.1
=> batterymonitor@pdcurtis Correction to v 1.4.1 

SettingsPlus@lusito.info/files/SettingsPlus@lusito.info/applet.js, SettingsPlus@lusito.info/files/SettingsPlus@lusito.info/config.json
Fixes #3208
* JSON file had syntax errors
* using ```xdg-open``` instead of ```gnome-open```
=> SettingsPlus@lusito.info: Fix for Cinnamon 4.6

Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/po/Sensors@claudiux.pot, Sensors@claudiux/files/Sensors@claudiux/po/fr.po
@brownsr 
Hi Simon,
Just a code cleanup and an update of the .pot and fr.po files.
Kind regards.
Claudiux
=> [Sensors@claudiux] Update .pot and fr.po files and code cleanup

kdecapplet@joejoetv/files/kdecapplet@joejoetv/applet.js, kdecapplet@joejoetv/files/kdecapplet@joejoetv/metadata.json
- FEATURE: Automatically expand device menu if there is only one device. (hacker1024)
=> [kdecapplet@joejoetv] Version 1.1.1

kdecapplet@joejoetv/files/kdecapplet@joejoetv/applet.js, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/de.po, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/de_de.po, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/kdecapplet.pot
- Fix Menu Bug
- Update Language Files
=> [kdecapplet@joejoetv] Version 1.1.2

Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/README.md, Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/README.md, Sensors@claudiux/files/Sensors@claudiux/settings-schema.json
@brownsr 
Hi Simon,
Maybe updating these files?
Otherwise, I don't know what to do.
Regards.
Claudiux
=> [Sensors@claudiux] Update settings-schema.json and all .md files

Sensors@claudiux/README.md, Sensors@claudiux/files/Sensors@claudiux/README.md
@brownsr,
Hi Simon,
Just an update of the README.md file.
Kind regards.
Claudiux
=> Sensors@claudiux: v1.1.0: Update README.md

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Reverse order of session buttons when at top or bottom.
Choose alternative "favorites" and "recents" category icons if defaults are not available in icon theme.
=> [Cinnamenu@json] Bug fix update

Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/README.md, Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/README.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/checkDependencies.js, Sensors@claudiux/files/Sensors@claudiux/constants.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/sensorsReaper.js, Sensors@claudiux/files/Sensors@claudiux/settings-schema.json, Sensors@claudiux/files/Sensors@claudiux/util.js
@brownsr 
Hi Simon,
This version aims to fix some user reported issues (but I'm not sure it fixes them permanently).
Kind regards.
Claudiux
=> Sensors@claudiux: v1.2.0

weather@mockturtl/files/weather@mockturtl/po/de.po
I did a complete rework of the DE translations and used @jorgebadad 's Translation as benchmark. Thanks for your great work @jorgebadad !
=> weather@mockturtl: update de.po

Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/README.md, Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/README.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json
@brownsr 
Hi Simon,
Sorry for the extra work I'm making you do. This version 1.2.1 still attempts to resolve the same issues.
Kind regards.
Claudiux
=> Sensors@claudiux: v1.2.1

Sensors@claudiux/files/Sensors@claudiux/po/nl.po
Dutch translation of Sensors Monitor (Sensors@claudiux)
=> Sensors Monitor (Sensors@claudiux) nl.po

Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/README.md, Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/README.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/sensorsReaper.js
Hi @brownsr,
This is the latest version of Sensors@claudiux.
Kind regards.
Claudiux
=> Sensors@claudiux: v1.3.0 - Avoid wasted processor time and memory leaks.

sysmonitor@orcus/files/sysmonitor@orcus/po/pt_PT.po
Hello @OrcusCZ @NikoKrause. I'm opening this PR to submit the European Portuguese translation for sysmonitor@orcus extension. Please let me know if it needs any additional change.
=> sysmonitor@orcus: added pt-PT translation file

Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/README.md, Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/README.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/constants.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/scripts/xs.py, Sensors@claudiux/files/Sensors@claudiux/sensorsReaper.js
@brownsr 
Hi Simon,
Kind regards.
Claudiux
=> Sensors@claudiux: v1.4.0 - Compatible with versions 3.8 to 4.6 of Cinnamon

cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/metadata.json
=> cinnamon-timer@jake1164: Now compatible with Cinnamon 4.6

Sensors@claudiux/README.md, Sensors@claudiux/files/Sensors@claudiux/README.md, Sensors@claudiux/files/Sensors@claudiux/scripts/xs.py
@brownsr 
Hi Simon,
Just some little changes.
Can you merge this branch with you master one, please?
Kind regards.
Claudiux
=> Sensors@claudiux: (v1.4.0) Update xs.py

weather@mockturtl/files/weather@mockturtl/po/cs.po
Czech translation. New strings translated and changes updated
=> weather@mockturtl: update cs.po

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.6/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.6/settings-schema.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.6/utils.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
@brownsr 
Hi Simon,
This is the new version of SpicesUpdate.
Kind regards.
Claudiux
=> SpicesUpdate@claudiux: v6.1.0 - Now detects when the Cinnamon server is down (Cinnamon 4.6 only)

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.6/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/README.md
@brownsr 
Hi Simon,
This PR fixes #3253.
Kind regards.
Claudiux
=> SpicesUpdate@claudiux: (v6.1.0) Fix #3253

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language update from the latest pot template file.
=> weather@mockturtl Update sv.po 2.6.6

SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.6/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/4.6/settings-schema.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
@brownsr 
Hi Simon,
Kind regards.
Claudiux
=> SpicesUpdate@claudiux: v6.2.0 - Improved settings, tooltips, animations and notifications.

PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/po/hu.po, ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/po/hu.po, betterlock/files/betterlock/po/hu.po, graphicsCenter@scollins/files/graphicsCenter@scollins/po/hu.po, officeCenter@scollins/files/officeCenter@scollins/po/hu.po, placesCenter@scollins/files/placesCenter@scollins/po/hu.po, sticky@scollins/files/sticky@scollins/po/hu.po, suspend@janax/files/suspend@janax/po/hu.po
I added the Hungarian translation to some applets.
=> New Hungarian translations

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserBookmarks.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot
+ Add context menu to recent items.
+ Add context menu to fav apps in sidebar.
+ update .pot file.
=> [Cinnamenu@json] Added context menus.

weather@mockturtl/files/weather@mockturtl/3.8/settings-schema.json
Fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/3268, an unfortunate oversight from my end.
=> weather@mockturtl hotfix - Update settings-schema.json to fix wrong key in pages array

weather@mockturtl/files/weather@mockturtl/po/fr.po
Update fr.po to the newer .pot file version.
=> weather@mockturtl Update French translation

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language update for Weather version 2.6.7 from latest POT template with some minor translation adjustments.
=> weather@mockturtl Update sv.po 2.6.7

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/pl.po
=> Polish translation

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserBookmarks.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/4.0/stylesheet.css, Cinnamenu@json/files/Cinnamenu@json/metadata.json
+ fixed a problem reading firefox bookmarks
+ slight performance improvement.
+ updated .css file
=> [Cinnamenu@json] Bug fixes.

better-backgrounds@simonmicro/files/better-backgrounds@simonmicro/applet.js, better-backgrounds@simonmicro/files/better-backgrounds@simonmicro/metadata.json
=> Update to 6fd71283b4ff6fbe6806ea642c7fa649db357c53

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language update for the Weather applet from latest POT template.
=> weather@mockturtl Update sv.po 2.6.8

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/nl.po
=> Spices Update Versie 6.3.1 update nl.po

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Ctrl-enter now opens app context menu.
fixed theme bug with category hover.
=> [Cinnamenu@json] Add key to open context menu.

weather@mockturtl/files/weather@mockturtl/po/cs.po
=> weather@mockturtl: Czech translation update

cheaty@centurix/files/cheaty@centurix/stylesheet.css
- Replace `Courier` with `sans-serif` in `stylesheet.css`. (Closes #3279)
- Remove duplicate `.sheet-item-code` block in `stylesheet.css`.
=> Use system-wide sans-serif font

Sensors@claudiux/files/Sensors@claudiux/po/cs.po, weather@mockturtl/files/weather@mockturtl/po/cs.po
Czech translation for Sensors monitor applet
=> Sensors@claudiux: Czech translation

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/applet.js, CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/settings-schema.json, CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/metadata.json, CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/CinnVIIStarkMenu.pot, CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/de.po
Add web search feature based on the applet "Internet Search Box" (https://cinnamon-spices.linuxmint.com/applets/view/57)
=> CinnVIIStarkMenu: v1.31 (web search)

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/stylesheet.css, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
+ sidebar favs dnd
+ left/right sidebar scrollable.
+ slight performance improvement.
=> [cinnamenu@json] can now move favs on sidebar

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/applet.js
Fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/3309
=> CinnVIIStarkMenu@NikoKrause: fix search in Mint 19.2

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
+ fix menu not opening in some cases bug
=> [Cinnamenu@json] bug fix

calendar@ccprog/files/calendar@ccprog/settings_widgets.py
Includes uncategorized timezones in the list of World Clocks. (Issue #3314)
=> Puts uncategorized timezones into the list of World Clocks

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot, Cinnamenu@json/files/Cinnamenu@json/po/da.po
+ Add "Open containing folder" to context menu of recent items
+ Change separator from dot to line on sidebar
+ fix search bug
+ removed search provider toggle, now always on.
=> [Cinnamenu@json] Add context menu item + bug fix

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/4.0/stylesheet.css, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot
+ support for Nemo favorites
+fix for ":flatpak" suffix in app ids.
=> [Cinnamenu@json] Bug fixes

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot
+ add "move to trash" context menu item.
+ add favorites files to sidebar (cinnamon 4.8 only)
+ update .pot file.
=> [Cinnamenu@json] Various.

mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/applet.js
Fixes syntax errors in JS code for #3340 and #3339
=> mailnag@ozderya.net Fix syntax errors

Cinnamenu@json/README.md, Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot
+ shift tab now works.
+ recent files category icon changed.
+ update .pot file
=> [Cinnamenu@json] Some minor fixes

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
+ remove "move to trash" from context menu of favorite.
=> [Cinnamenu@json] Change favorites category icon.

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language file update for the Weather applet from latest POT template.
=> weather@mockturtl Update sv.po 2.6.9

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/emoji.js, Cinnamenu@json/files/Cinnamenu@json/4.0/resizer.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/metadata.json
+ resize menu by dragging on edges.
=> [Cinnamenu@json] Menu resizing.

radio@driglu4it/README.md, radio@driglu4it/files/radio@driglu4it/4.6/applet.js
I refactored the code for cinnamon 4.6 a little bit to make it simpler to add new features in future. In particular I made some functions shorter, added more comments and renamed some variables. So I hope the code is now a little bit easier to read. Also I fixed the minor bugs: 
- The current channel is now correctly indicated with a point, the icon changes and the channel is now shown in the tooltip when refreshing cinnamon
- The color of the symbolic icon is now changed immediately after changing the color in the applet settings. Previously cinnamon had to be restarted to apply the changes
- There are no errors in the log anymore
I also updated the readme. 
Merry Christmas @NikoKrause
=> radio@driglu4it: Minor Bug fixes, readme addition and code clean up

nightscout@ranneft/files/nightscout@ranneft/applet.js
Same bug that was fixed in #3395, just in another area I didn't think about when I worked on that PR.
@ImmRanneft
=> Nightscout: Bug fix - Handled undefined values in tooltip

localipswithsettings@edaubert/README.md
changing the img dir at the readme file at file [https://github.com/linuxmint/cinnamon-spices-applets/tree/master/localipswithsettings%40edaubert/README.md](https://github.com/linuxmint/cinnamon-spices-applets/tree/master/localipswithsettings%40edaubert/README.md)
=> changing the img dir at the readme file

nightscout@ranneft/files/nightscout@ranneft/applet.js, nightscout@ranneft/files/nightscout@ranneft/metadata.json
The Nightscout web app reports sloped arrows, too.
@ImmRanneft
=> nightscout: Handled 45 degree arrows

download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/tr.po
=> New  translation tr.po

calendar@ccprog/files/calendar@ccprog/po/calendar@ccprog.pot, calendar@ccprog/files/calendar@ccprog/po/sv.po
=> calendar@ccprog: add sv.po

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/resizer.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
+ fix intermittent bug causing cinnamon to crash when resizing.
+ Allow fav files to be unfaved even when no longer on disk.
=> [Cinnamenu@json] resizing bug fix

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/resizer.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Monitor mouse movements to prevent accidental selection of other categories when moving mouse from selected category button to app button.
=> [Cinnamenu@json] Prevent category mis-selection

radio@driglu4it/README.md, radio@driglu4it/files/radio@driglu4it/4.6/applet.js, radio@driglu4it/files/radio@driglu4it/4.6/mpvPlayerHandler.js, radio@driglu4it/files/radio@driglu4it/4.6/settings-schema.json, radio@driglu4it/files/radio@driglu4it/po/de.po, radio@driglu4it/files/radio@driglu4it/po/radio@driglu4it.pot
Added the following improvements: 
- It is only shown a notification when there has been't a  notification with the same text in the last 10 seconds. Previously it could easily happen to get multiple notifications when scrolling above the maximum volume
- Added option to copy the current song title from the context menu
- Added option to show radio channel on the panel
- Updated German translation
- Removed Max volume (see: https://github.com/linuxmint/cinnamon-spices-applets/issues/3402#issuecomment-756430754 for explanation)
@NikoKrause
=> [radio@driglu4it] Update radio applet

mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/applet.js
Fix javascript code syntax for #3352
=> mailnag@ozderya.net : Fix code syntax

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserBookmarks.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/resizer.js, Cinnamenu@json/files/Cinnamenu@json/4.0/stylesheet.css, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
+ Addition fix for bug causing cinnamon to crash while resizing
=> [Cinnamenu@json] Also highlight category when new app installed.

clipboard-qr@wrouesnel/README.md, clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/applet.js, clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/clipboard-qr.py
and fix `toString` for Cinnamon 4.8
=> clipboard-qr@wrouesnel: python3 update

places-with-terminal@mtwebster/files/places-with-terminal@mtwebster/applet.js
Fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/2597
=> places-with-terminal@mtwebster: remove gksudo

Sensors@claudiux/README.md, Sensors@claudiux/files/Sensors@claudiux/README.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/checkDependencies.js, Sensors@claudiux/files/Sensors@claudiux/lib/to-string.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/sensorsReaper.js
Hi @brownsr,
This is the v1.5.0 of Sensors. It solves the problem of array.toString(). Thus, no more messages about this applet come polluting the `.xsession-errors` file.
Kind regards.
Claudiux
=> [Sensors@claudiux] v1.5.0: Now fully compatible with Cinnamon 4.8

better-backgrounds@simonmicro/files/better-backgrounds@simonmicro/applet.js
This fixes the broken Himawari 8 during January. Typical off-by-one.
=> Update to 699fa2d2d243beb7dac0cd1e3900b0c988e58325 (BUGFIX)

radio@driglu4it/files/radio@driglu4it/4.6/applet.js, radio@driglu4it/files/radio@driglu4it/4.6/mpvPlayerHandler.js
Currently we use playerctl for stopping the radio and increasing/decreasing the volume. This has several disadvantages - users have to install the package and it is very difficult to trigger actions when the volume is changed or the radio player paused from outside of the applet (e.g the sound applet). This pull request removes the playerctl dependency by using the D-Bus interface instead (similar to the sound applet). 
@NikoKrause
=> [radio@driglu4it] Remove Playerctl

radio@driglu4it/info.json
=> radio@driglu4it: Add new maintainer

weather@mockturtl/files/weather@mockturtl/po/nl.po
=> Update nl.po weather@mockturtl Versie 2.7.0

Cinnamenu@json/README.md, Cinnamenu@json/files/Cinnamenu@json/4.0/CREDITS, Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/search.py, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot
=> [Cinnamenu@json] Add search function to applet context menu.

hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.2/providers.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/providers.js
Minor additional fix for #3350
(wrote the wrong number (#3432) in my commits, ignore that)
=> [hwmonitor@sylfurd] Bug fix #3350

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language file update for the Weather applet from latest POT template and minor adjustments.
=> weather@mockturtl Update sv.po 2.7.0

weather@mockturtl/files/weather@mockturtl/po/nl.po
Remove colon : punctuation mark and dots
=> Update po.nl weather@mockturtl Versie 2.7.0

radio@driglu4it/README.md, radio@driglu4it/files/radio@driglu4it/4.6/applet.js, radio@driglu4it/files/radio@driglu4it/4.6/mpvPlayerHandler.js, radio@driglu4it/files/radio@driglu4it/4.6/settings-schema.json, radio@driglu4it/files/radio@driglu4it/po/de.po, radio@driglu4it/files/radio@driglu4it/po/radio@driglu4it.pot
- Fixed: The volume shown in the sound applet is now synchronized with the MPRIS volume 
- Added: The volume can now be saved after stopping/closing the applet
=> [radio@driglu4it] Improve volume settings

radio@driglu4it/files/radio@driglu4it/4.6/applet.js, radio@driglu4it/files/radio@driglu4it/4.6/settings-schema.json
Added a scrollbar as Fix for #3475
=> [radio@driglu4it] Fix #3475

weather@mockturtl/files/weather@mockturtl/po/tr.po
=> update 2.7.0 tr.po

weather@mockturtl/files/weather@mockturtl/po/nl.po
=> weather@mockturtl Versie 3.0.0 nl.po

weather@mockturtl/files/weather@mockturtl/po/fr.po
Update french translation to the 3.0.0 version
=> weather@mockturtl: update french translation to the 3.0.0 version

weather@mockturtl/CHANGELOG.md, weather@mockturtl/README.md, weather@mockturtl/files/weather@mockturtl/3.0/climacell.js, weather@mockturtl/files/weather@mockturtl/3.8/climacell.js, weather@mockturtl/files/weather@mockturtl/3.8/climacellV4.js, weather@mockturtl/files/weather@mockturtl/3.8/config.js, weather@mockturtl/files/weather@mockturtl/3.8/httpLib.js, weather@mockturtl/files/weather@mockturtl/3.8/main.js, weather@mockturtl/files/weather@mockturtl/3.8/settings-schema.json, weather@mockturtl/files/weather@mockturtl/3.8/types.js, weather@mockturtl/files/weather@mockturtl/3.8/uiCurrentWeather.js, weather@mockturtl/files/weather@mockturtl/3.8/utils.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/files/weather@mockturtl/po/hu.po, weather@mockturtl/files/weather@mockturtl/po/weather@mockturtl.pot, weather@mockturtl/src/3_0/climacell.ts, weather@mockturtl/src/3_8/climacell.ts, weather@mockturtl/src/3_8/climacellV4.ts, weather@mockturtl/src/3_8/config.ts, weather@mockturtl/src/3_8/httpLib.ts, weather@mockturtl/src/3_8/main.ts, weather@mockturtl/src/3_8/tsconfig.json, weather@mockturtl/src/3_8/uiCurrentWeather.ts, weather@mockturtl/src/3_8/utils.ts
Fixes:
* Fix issue where Symbolic icons setting was not reflected in the app when changed
* Fix [#3486](https://github.com/linuxmint/cinnamon-spices-applets/issues/3486), now wind icons point to the right direction
* Fix wind icon color when non-symbolic icons are used in the applet popup menu
* Fix [#3488](https://github.com/linuxmint/cinnamon-spices-applets/issues/3488), add Climacell V4 as a new provider because Climacell v3 is deprecated and dosen't accept new signups.
* Make network and DNS related errors soft errors again
=> weather@mockturtl Update 3.0.1 - hotfixes

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language file update for the Weather applets latest POT template file.
=> weather@mockturtl Update sv.po 3.0.1

radio@driglu4it/files/radio@driglu4it/4.6/applet.js, radio@driglu4it/files/radio@driglu4it/4.6/mpvPlayerHandler.js, radio@driglu4it/files/radio@driglu4it/4.6/playPauseIconMenuItem.js
In Radio List now shown a play icon when radio channel is played and a pause icon when paused.
=> [radio@driglu4it] Add pause handling

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot
+ always show (auto-hidden) panel when menu is opened.
=> [Cinnamenu@json] Add option to change panel icon size.

radio@driglu4it/files/radio@driglu4it/4.6/applet.js
- fixed white icon color shown in white Desktop Themes
- fixed radio kept playing when removed from panel
=> fixed #3512

notification-mute@jgillula/info.json
The "author" flag has to contain the GitHub user name
@jgillula
=> notification-mute@jgillula: Fix info.json

BgRadio@spacy01/files/BgRadio@spacy01/metadata.json, SW++@mohammad-sn/files/SW++@mohammad-sn/metadata.json, back-up_state@natsakis.com/files/back-up_state@natsakis.com/metadata.json, better-backgrounds@simonmicro/files/better-backgrounds@simonmicro/metadata.json, cheaty@centurix/files/cheaty@centurix/metadata.json, dgs-bpivaty@gmail.com/files/dgs-bpivaty@gmail.com/metadata.json, expressvpn@Hukuta/files/expressvpn@Hukuta/metadata.json, gnote@brett-smith/files/gnote@brett-smith/metadata.json, kdecapplet@joejoetv/files/kdecapplet@joejoetv/metadata.json, kdeccc@Severga/files/kdeccc@Severga/metadata.json, location-detection@heimdall/files/location-detection@heimdall/metadata.json, rancher@centurix/files/rancher@centurix/metadata.json, scripts@paucapo.com/files/scripts@paucapo.com/metadata.json, show-hide-applets@mohammad-sn/files/show-hide-applets@mohammad-sn/metadata.json, suspend@janax/files/suspend@janax/metadata.json, timeshift-spy@nicog60/files/timeshift-spy@nicog60/metadata.json, uptime@vatanuki.kun/files/uptime@vatanuki.kun/metadata.json, validate-spice
- Add some checks to validate-spice script
- Some applets: Remove last-edited flag in metadata
=> Validate-spice script and last-edited flag

betterlock/files/betterlock/applet.js, betterlock/files/betterlock/settings-schema.json
and disable notifications by default
=> betterlock: Fix error spam in log

CustomApplicationsMenu@LLOBERA/files/CustomApplicationsMenu@LLOBERA/RELEASE.txt, CustomApplicationsMenu@LLOBERA/files/CustomApplicationsMenu@LLOBERA/applet.js, CustomApplicationsMenu@LLOBERA/files/CustomApplicationsMenu@LLOBERA/applications.json, CustomApplicationsMenu@LLOBERA/files/CustomApplicationsMenu@LLOBERA/metadata.json
Remove the "const _ = Gettext.gettext" which causes the following error "redeclaration of const _"
=> [CustomApplicationsMenu@LLOBERA] Fix not loading of the applet

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/stylesheet.css, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
+ Improved fav box styling.
+ Fixed context menu styling.
+ Don't allow uninstalling of items in preferences category
+ Populate menu synchronously.
+ Fix search box padding/margin
=> [Cinnamenu@json] Various fixes.

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/stylesheet.css, Cinnamenu@json/files/Cinnamenu@json/metadata.json
+ Removed "uninstall" context menu option.
=> [Cinnamenu@json] Theming adjustments.

ratecurrency@magner/files/ratecurrency@magner/po/ratecurrency@magner.pot
The comment has to be above the msgid
@AleksiMagner fyi
=> ratecurrency@magner: Fix pot file

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/search.py, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot
+ update .pot file
+ fix ellipsized labels in context menu.
=> [Cinnamenu@json] Add option to set "open on" category.

ddcci-monitor-control@andr35/files/ddcci-monitor-control@andr35/applet.js
Just and update of icon name of applet "ddcci-monitor-control@andr35".
=> ddcci-monitor-control@andr35: update applet icon name

weather@mockturtl/files/weather@mockturtl/po/nl.po
Translation updated due to changes in Version 3.0.3
=> weather@mockturtl V 3.0.3 Update nl.po

cryptocoin@guantanamoe/README.md, cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/po/de.po, cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/settings-schema.json
change default update intervall from 5 seconds to 5 minutes
- The used website allows certain calls per month. Expand the default update intervall to prevent hitting the rate limit (closes https://github.com/linuxmint/cinnamon-spices-applets/issues/3453)
Closes https://github.com/linuxmint/cinnamon-spices-applets/issues/3545
@imDeprecated fyi
=> cryptocoin@guantanamoe: Update l10n template, add German translation

Cinnamenu@json/files/Cinnamenu@json/4.0/search.py, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot, Cinnamenu@json/files/Cinnamenu@json/po/de.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/de.po, ThemeRefresh@JosephM/files/ThemeRefresh@JosephM/po/de.po, placesCenter@scollins/files/placesCenter@scollins/po/de.po, placesCenter@scollins/files/placesCenter@scollins/po/placesCenter@scollins.pot, placesCenter@scollins/files/placesCenter@scollins/search.py
@fredcw See the first commit. I fixed some translation issues in Cinnamenu. Fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/3623 and fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/3203
=> Some Appelts: Update German l10n

qredshift@quintao/README.md, qredshift@quintao/files/qredshift@quintao/applet.js, qredshift@quintao/files/qredshift@quintao/metadata.json, qredshift@quintao/files/qredshift@quintao/po/pt.po, qredshift@quintao/files/qredshift@quintao/po/qredshift@quintao.pot
* 1.5.4
- Implemented asynchronous command calls, this fixes: "This applet contains function calls that could potentially cause Cinnamon to crash or freeze."
- Reverted description, to avoid loss of translations.
=> qredshift@quintao: Version 1.5.4

asl@santiago/files/asl@santiago/applet.js, asl@santiago/files/asl@santiago/po/de.po
@SamBurgos I've changed the translation strings. We don't need to change
the letters themselves, we just need to translate the word "Letter".
This reduces the work for translators immensely.
=> asl@santiago: Reduce strings in l10n template by a lot

BgRadio@spacy01/files/BgRadio@spacy01/applet.js, BgRadio@spacy01/files/BgRadio@spacy01/po/bg.po, BgRadio@spacy01/files/BgRadio@spacy01/po/de.po
Update translation files and add German l10n
@spacy01
=> BgRadio@spacy01: Simplify code and improve l10n string

weather@mockturtl/files/weather@mockturtl/po/is.po
Some fixes and finishing the Icelandic translation.
=> weather@mockturtl - update is.po

weather@mockturtl/CHANGELOG.md, weather@mockturtl/files/weather@mockturtl/3.0/applet.js, weather@mockturtl/files/weather@mockturtl/3.8/config.js, weather@mockturtl/files/weather@mockturtl/3.8/danishMI.js, weather@mockturtl/files/weather@mockturtl/3.8/locationstore.js, weather@mockturtl/files/weather@mockturtl/3.8/main.js, weather@mockturtl/files/weather@mockturtl/3.8/nominatim.js, weather@mockturtl/files/weather@mockturtl/3.8/uiForecasts.js, weather@mockturtl/files/weather@mockturtl/3.8/uiHourlyForecasts.js, weather@mockturtl/files/weather@mockturtl/3.8/utils.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/src/3_8/config.ts, weather@mockturtl/src/3_8/danishMI.ts, weather@mockturtl/src/3_8/locationstore.ts, weather@mockturtl/src/3_8/main.ts, weather@mockturtl/src/3_8/nominatim.ts, weather@mockturtl/src/3_8/uiForecasts.ts, weather@mockturtl/src/3_8/uiHourlyForecasts.ts, weather@mockturtl/src/3_8/utils.ts
Changes:
* Fixes #3654 
* Fixes #3659
=> weather@mockturtl Update 3.0.5

tzclock@lhriley/files/tzclock@lhriley/applet.js
This PR fixes an issue where Cinnamon would experience performance issues (high CPU use) and the clock itself would become desynced from real time. This would typically happen when the machine would be in a `suspend` state, but would also occur over time even when the machine had power saving functions disabled.
The primary cause was using a naive periodic timeout rather than relying on notifications from `notify::clock`.
This problem likely also occurs in [calendar@simonwiles.net](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/calendar@simonwiles.net/files/calendar@simonwiles.net/applet.js) as this was one of the original sources of code that I borrowed: https://github.com/linuxmint/cinnamon-spices-applets/blob/d172c5008c324212e258952964f28e3607bc90f5/calendar%40simonwil …
=> tzclock@lhriley: fix performance / timing issues

Cinnamenu@json/files/Cinnamenu@json/po/tr.po
Cinnamenu@json: updated tr.po file
=> Cinnamenu@json: updated tr.po file

PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/po/tr.po
PDFManager@cinnamon.org: Added tr.po file
=> PDFManager@cinnamon.org: Added tr.po file

Cinnamenu@json/files/Cinnamenu@json/3.2/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserBookmarks.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/4.0/stylesheet.css, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot
+ fix search bug in 3.2 version. fixes #3643
+ Remove option to disable emoji search.
+ remove option to hide "recent files" category. category can still be disabled in cinnamon settings -> privacy
=> [Cinnamenu@json] Fix search bug

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/tr.po
CinnVIIStarkMenu@NikoKrause: update tr.po
=> CinnVIIStarkMenu@NikoKrause: update tr.po

temperature@fevimu/files/temperature@fevimu/po/tr.po
temperature@fevimu: Added tr.po
=> temperature@fevimu: Added tr.po

Cinnamenu@json/files/Cinnamenu@json/3.2/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/search.py, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot
Thanks to @spsf64 for the suggestion.
+some bug fixes.
=> [Cinnamenu@json] Add some recent apps to recent category.

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Oops, list view disappeared in last update.
=> [Cinnamenu@json] Fix bug causing missing list view.

calendar@simonwiles.net/files/calendar@simonwiles.net/applet.js
Quick PR to update `calendar@simonwiles.net` to use the notification interface for updating the clock rather than relying on a naive timer.
While I did not directly experience performance issues with this applet, I had originally used this code as a starting point for `tzclock@lhriley` where I did experience issues with high CPU usage and clocks becoming desynced. As a result, this patch is an attempt to proactively avoid similar issues by using the update methodology from `calendar@cinnamon.org`.
These changes are proposed with the blessing of the original author @simonwiles.
Related PR for additional context: https://github.com/linuxmint/cinnamon-spices-applets/pull/3667
=> calendar@simonwiles.net: fix potential performance / timing issues

bash-sensors@pkkk/files/bash-sensors@pkkk/po/fr.po
Upload the fr.po provided by @uapv1702675
Closes https://github.com/linuxmint/cinnamon-spices-applets/issues/3670
=> bash-sensor@pkkk: Add French l10n

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/applet.js
The function replaceAll is not available in Cinnamon versions lower 4.8
=> CinnVIIStarkMenu@NikoKrause: Use replace instead of replaceAll

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/stylesheet.css, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot
+ created new class for header text (.menu-applications-header-text)
=> [Cinnamenu@json] Performance improvements

systray-collapsible@koutch/files/systray-collapsible@koutch/applet.js
This helps to at least get the applet up and running.
@koutch
@brownsr @NikoKrause
=> Fixes issues with variable initialization in for loops

qredshift@quintao/files/qredshift@quintao/applet.js, qredshift@quintao/files/qredshift@quintao/metadata.json
* 1.5.5
- Fixed icon blinking when using symbolic icon.
- Reverting metadata text to avoid loss of translations.
=> [qredshift@quintao] Version 1.5.5

cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/3.4/applet.js, cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/3.4/settings-schema.json
applet.js
Add a parameter to spawnCommandLine.
settings-schema.json
Add scale for specify volume.
=> Add function: You can specify sound volume.

cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/metadata.json
Add function: Automatically loop. (Restart the timer at same duration)
Add function: Specify sound volume for timer has elapsed.
=> Added 2 functions

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserBookmarks.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/4.0/stylesheet.css, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Non-latin characters were being ignored when searching.
=> [Cinnamenu@json] Fix non-latin character search bug

qredshift@quintao/README.md, qredshift@quintao/files/qredshift@quintao/applet.js, qredshift@quintao/files/qredshift@quintao/js/QUtils.js, qredshift@quintao/files/qredshift@quintao/metadata.json, qredshift@quintao/files/qredshift@quintao/settings-schema.json
* 1.6.0
- Added manual night-time option.
- Fixed some issues with Debian.
=> [qredshift@quintao] Version 1.6.0

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserBookmarks.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/4.0/stylesheet.css, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot
=> [Cinnamenu@json] Add home folder search function

BgRadio@spacy01/files/BgRadio@spacy01/po/hu.po, asl@santiago/files/asl@santiago/po/hu.po, back-up_state@natsakis.com/files/back-up_state@natsakis.com/po/hu.po, bash-sensors@pkkk/files/bash-sensors@pkkk/po/hu.po, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/hu.po, bettersettings@bownz/files/bettersettings@bownz/po/hu.po, binaryclock@entelechy/files/binaryclock@entelechy/po/hu.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/hu.po, bumblebee@pdcurtis/files/bumblebee@pdcurtis/po/hu.po
Hello Team,
this is my first pull request. I started to contribute to the Hungarian translation of the Linux mint applets and desklets.
=> Hungarian translation for various applets

MessagingMenuV3@blub/files/MessagingMenuV3@blub/po/tr.po
MessagingMenuV3@blub: Added tr.po
=> MessagingMenuV3@blub: Added tr.po

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserBookmarks.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/resizer.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings.js, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
+ remove duplicate search results.
=> [Cinnamenu@json] Fix tweaks for some themes.

mybookmarks@markbokil.com/files/mybookmarks@markbokil.com/applet.js, mybookmarks@markbokil.com/files/mybookmarks@markbokil.com/config.js, mybookmarks@markbokil.com/files/mybookmarks@markbokil.com/mybookmarks.properties
Fixed, tested, and checked the paths, which are correct now, but don't seem to open. But applet does work when downloaded and added.
@brownsr @NikoKrause tagging you guys since there doesn't appear to be an author for this applet any more.
=> Applies object check so applet will start.

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/resizer.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
+ remove unneeded code from settings.js
=> [Cinnamenu@json] Add trash to places category.

azan@fahri.nurul.id/README.md, azan@fahri.nurul.id/files/azan@fahri.nurul.id/applet.js, azan@fahri.nurul.id/files/azan@fahri.nurul.id/metadata.json, azan@fahri.nurul.id/files/azan@fahri.nurul.id/settings-schema.json
feat(azan@fahri.nurul.id): add settings options to select juristic method
This update will add the option to select the juristic method in settings menu.
Juristic method allows to adjust time calculation for Asr Prayer.
The library Prayer.js already has this option, now it is hooked to the settings menu allowing for users to adjust this setting.
=> azan@fahri.nurul.id: Add settings options to select juristic method

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Make applet more responsive when searching home folder.
=> [Cinnamenu@json] Fix slow folder search bug

radio@driglu4it/files/radio@driglu4it/4.6/RadioSearchWidget.py
- make "add to my stations" button context-sensitive (only activated when a station is selected in list)
- prevent adding stations to "my stations" from the search widget when a station with same name or same url already exist (it is still possible to add duplicates by manually adding stations but at least it is now less likely to happen)
- show an infobar after clicking on "add to my stations" button (which is either positive or negative when trying to add a station with an already existing name/url)
=> [radio@driglu4it] Improve search widget

radio@driglu4it/files/radio@driglu4it/po/sv.po
=> radio@driglu4it: Update sv.po

scripts@paucapo.com/files/scripts@paucapo.com/po/sv.po
=> scripts@paucapo.com: Update sv.po

qredshift@quintao/README.md, qredshift@quintao/files/qredshift@quintao/applet.js, qredshift@quintao/files/qredshift@quintao/metadata.json, qredshift@quintao/files/qredshift@quintao/po/es_MX.po, qredshift@quintao/files/qredshift@quintao/settings-schema.json
* 1.7.0
- Fixed issues with asynchronous command calls.
- Main redshift call reverted to synchronous, so the cinnamon will show the annoying message again: ***This applet contains function calls that could potentially cause Cinnamon to crash or freeze***.
- I noticed that on some (slow?) computers many asynchronous calls cause the application to stop work in some mysterious way.
- Added translations:
- Spanish by [RichLuna](https://github.com/RichLuna "@RichLuna on Github")
=> [qredshift@quintao] Version 1.7.0

.typescript-declarations/cinnamon/cinnamon.d.ts, .typescript-declarations/cinnamon/ui/popupMenu.d.ts, .typescript-declarations/cinnamon/ui/slider.d.ts
@Gr3q  I added/updated some declarations I need for the radio applet. Best regards
=> [.typescript-declarations] add/update declarations

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/metadata.json
and put back settings option to hide recents category.
=> [Cinnamenu@json] Put time limit on file home folder search

wireguard@nicoulaj.net/files/wireguard@nicoulaj.net/applet.js, wireguard@nicoulaj.net/files/wireguard@nicoulaj.net/metadata.json, wireguard@nicoulaj.net/files/wireguard@nicoulaj.net/po/da.po, wireguard@nicoulaj.net/files/wireguard@nicoulaj.net/po/hu.po, wireguard@nicoulaj.net/files/wireguard@nicoulaj.net/po/it.po, wireguard@nicoulaj.net/files/wireguard@nicoulaj.net/po/wireguard@nicoulaj.net.pot
https://github.com/nicoulaj/cinnamon-applet-wireguard/releases/tag/1.0.3
Fixes:
- https://github.com/nicoulaj/cinnamon-applet-wireguard/issues/2
- https://github.com/nicoulaj/cinnamon-applet-wireguard/issues/3
=> update wireguard plugin to version 1.0.3

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Now searches home folder for files without blocking UI.
=> [Cinnamenu@json] Fix home folder search.

ipindicator@matus.benko@gmail.com/files/ipindicator@matus.benko@gmail.com/applet.js, ipindicator@matus.benko@gmail.com/files/ipindicator@matus.benko@gmail.com/settings-schema.json
- added appearance settings to choose between icon, ip, and icon and ip
- fixed margins in the tooltip
=> Ip Indicator: appearance settings

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserBookmarks.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
+ Don't follow symlinks in search.
+ improve app_id search
=> [Cinnamenu@json] Improved search results

better-backgrounds@simonmicro/files/better-backgrounds@simonmicro/applet.js, better-backgrounds@simonmicro/files/better-backgrounds@simonmicro/settings-schema.json
=> Allow choice of save location

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserBookmarks.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot
Make web bookmarks search only.
Update .pot file.
=> [Cinnamenu@json] Don't show web bookmarks category (search only)

color-picker@fmete/files/color-picker@fmete/applet.js, color-picker@fmete/files/color-picker@fmete/cp.py
Removes redundant code "import numpy" in one file and the corresponding part in another that triggers checking if an error occurred while importing.
=> [ color-picker@fmete ] : Removes redundant code which may ask the user to install a lib.

weather@mockturtl/CHANGELOG.md, weather@mockturtl/files/weather@mockturtl/3.8/providers/met_uk.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/src/3_8/providers/met_uk.ts
=> weather@mockturtl update 3.0.10

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language file update for the Weather applet latest POT template file from 2021-06-15.
=> weather@mockturtl Update sv.po 3.0.9

Cinnamenu@json/README.md, Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot
+ show calculator result at top of results
+ make "clear list" bold
+ update .pot file
=> [Cinnamenu@json] fix file search inconsistency bug. 

weather@mockturtl/CHANGELOG.md
Corrected link to point to right issue under 3.0.8.
=> Update CHANGELOG.md typo

weather@mockturtl/files/weather@mockturtl/po/cs.po
Thx to Marek Hladík for addresing it.
=> wearther@mockturtl: fixed errors in Czech weather translation

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/applet.js
..to avoid label sometimes being ellipsized.
Same issue as menu applet https://github.com/linuxmint/cinnamon/pull/10178
=> [CinnVIIStarkMenu@NikoKrause] Change method of making "Clear list" label bold..

gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/GPasteHistoryItem.js
Apply fix for #3288
Author: @bazuchan
He did not open a PR. After waiting for that, it started to annoy me.
So -> All hail to bazuchan.
I'm not sure if this applet is maintained actively any more?
=> fix #3288 by applying the solution of bazuchan

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/buttons.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/metadata.json
=> [Cinnamenu] Add more theme tweaks.

weather@mockturtl/files/weather@mockturtl/po/fr.po
=> weather@mockturtl: Update French translation

color-picker@fmete/README.md
After discussion https://github.com/linuxmint/cinnamon-spices-applets/commit/1838b273a5ec179b6273881197a682da4021336a#commitcomment-53706181 it was suggested that README file needs to be corrected too.
=> a follow-up patch to #3803 : a small correction to the README file

weather@mockturtl/files/weather@mockturtl/po/sl.po
Updated Slovenian translation for weather@mockturtl (3.1.2)
=> weather@mockturtl: Update Slovenian translation

Cinnamenu@json/files/Cinnamenu@json/po/de.po
=> [Cinnamenu@json] update de.po

Cinnamenu@json/files/Cinnamenu@json/3.2/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot, Cinnamenu@json/files/Cinnamenu@json/po/de.po
=> [Cinnamenu@json] Update .pot file

weather@mockturtl/files/weather@mockturtl/po/sk.po
By Radoslav Matasovsky <matasovsky.radoslav@gmail.com>
=> weather@mockturtl - update sk.po

app-launcher@mchilli/files/app-launcher@mchilli/applet.js
- symbolic application icons are working again
- possibility to use a path for applet icon
=> app-launcher@mchilli: icon fixes

radio@driglu4it/files/radio@driglu4it/po/radio@driglu4it.pot, radio@driglu4it/files/radio@driglu4it/po/sv.po
Fix some missing translation strings and errors
=> radio@driglu4it: Update pot file

Cinnamenu@json/files/Cinnamenu@json/po/pt_BR.po
I corrected the translation file, using poedit, as directed by @fredcw  in  #3894 .
=> Cinnamenu@json: Update pt_BR.po

app-launcher@mchilli/files/app-launcher@mchilli/applet.js
- use exec command from dropped apps, instead of using "gtk-launch"
- possibility to drag apps from "Cinnamenu@json"
=> app-launcher@mchilli: updated getAppInfo behaviour

calendar@ccprog/files/calendar@ccprog/po/fr.po
=> calendar@ccprog: Update French translation

weather@mockturtl/README.md
Minor update tuneup of providers and Language translation section regarding new menu name in latest version of poedit.
=> weather@mockturtl Update README.md provider + lang

app-launcher@mchilli/files/app-launcher@mchilli/po/tr.po
app-launcher@mchilli: update tr.po
=> app-launcher@mchilli: update tr.po

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language file update for the Weather applet latest pot template file from 2021-09-23.
=> weather@mockturtl Update sv.po 3.1.4

weather@mockturtl/CHANGELOG.md, weather@mockturtl/build.sh, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/files/weather@mockturtl/po/weather@mockturtl.pot, weather@mockturtl/weather@mockturtl.code-workspace
* Resolves https://github.com/linuxmint/cinnamon-spices-applets/issues/3935 Update translations file
* Make sure translation generation is not missed again, now included as a build step
* Add VSCode workspace
=> weather@mockturtl Update 3.1.4

temperature@fevimu/files/temperature@fevimu/po/pt.po
=> temperature@fevimu update pt.po file translation

CustomApplicationsMenu@LLOBERA/files/CustomApplicationsMenu@LLOBERA/po/tr.po
CustomApplicationsMenu@LLOBERA: Update tr.po
=> CustomApplicationsMenu@LLOBERA: Update tr.po

qredshift@quintao/README.md
* Update README.md
* Updated Changelog 
I forgot that on my last pull request.
=> Version 1.7.1 - Updated changelog

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language file update for the Weather applet latest pot template file from 2021-10-19.
=> weather@mockturtl Update sv.po 3.1.5

Cinnamenu@json/files/Cinnamenu@json/po/pt.po
=> Cinnamenu@json portuguese translation update

weather@mockturtl/files/weather@mockturtl/po/is.po
weather@mockturtl: Icelandic translation updated from latest POT-file
=> weather@mockturtl: Update is.po

qredshift@quintao/files/qredshift@quintao/pt.po, qredshift@quintao/files/qredshift@quintao/pt_BR.po
Correct translation of the portuguese (pt.po file)
Brazilian Portuguese translation added (pt_BR.po file) Original translation reused from previous pt.po version
=> qredshift@quintao: Update pt.po file and add pt_BR.po file

weather@mockturtl/files/weather@mockturtl/po/cs.po
=> Weather@mockturtl Update 3.1.5 Czech

darkMode@linuxedo.com/files/darkMode@linuxedo.com/po/tr.po
darkMode@linuxedo.com: Re-add and update tr.po
https://github.com/linuxmint/cinnamon-spices-applets/pull/3990
=> darkMode@linuxedo.com: Re-add and update tr.po

darkMode@linuxedo.com/files/darkMode@linuxedo.com/po/es.po
The translation was sent by a user and I am creating the PR for him.
=> darkMode@linuxedo.com: Add Spanish translation

app-launcher@mchilli/README.md, app-launcher@mchilli/files/app-launcher@mchilli/applet.js
- added possibility to use middleclick to run an application and hold the menu open
=> app-launcher@mchilli: hold menu open with middleclick

weather@mockturtl/files/weather@mockturtl/po/es.po
=> Update Spanish translations for weather@mockturtl 3.1.5 

app-launcher@mchilli/files/app-launcher@mchilli/widgets.py
- dont use markup for command column
=> app-launcher@mchilli: bugfix command not visible

app-launcher@mchilli/files/app-launcher@mchilli/applet.js, app-launcher@mchilli/files/app-launcher@mchilli/po/app-launcher@mchilli.pot, app-launcher@mchilli/files/app-launcher@mchilli/po/de.po, app-launcher@mchilli/files/app-launcher@mchilli/po/es.po, app-launcher@mchilli/files/app-launcher@mchilli/settings-schema.json
- added functionality to use hotkey to show the menu. closed #4055
- added spanish translation, thanks to @haggen88. closed #4046
=> app-launcher@mchilli: added hotkey, spanish tranlation

darkMode@linuxedo.com/files/darkMode@linuxedo.com/po/tr.po
darkMode@linuxedo.com: Update tr.po
=> darkMode@linuxedo.com: Update tr.po

weather@mockturtl/files/weather@mockturtl/po/fr.po
Fix the variable in fr.po.
Regards.
=> Fix: fr.po weather@mockturtl

radio@driglu4it/files/radio@driglu4it/4.6/radio-applet.js, radio@driglu4it/package.json, radio@driglu4it/src/lib/ActivWidget.ts, radio@driglu4it/src/lib/Slider.ts, radio@driglu4it/src/mpv/MpvHandler.ts, radio@driglu4it/src/ui/Applet/Applet.ts, radio@driglu4it/src/ui/VolumeSlider.ts
just a small update to apply the new types
=> [radio@driglu4it] update types

cpufreq@mtwebster/files/cpufreq@mtwebster/po/es.po
=> cpufreq@mtwebster - add spanish translation

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language file update for the Weather applet latest pot template file from 2021-11-14.
=> weather@mockturtl Update sv.po 3.1.6

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/es.po
=> multicore-sys-monitor@ccadeptic23 - add spanish translation

pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/es.po
=> pomodoro@gregfreeman.org - Update es.po

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/es.po
=> CinnVIIStarkMenu@NikoKrause - Update es.po

windowlist@cobinja.de/files/windowlist@cobinja.de/po/es.po
=> windowlist@cobinja.de - add spanish translation

sticky@scollins/files/sticky@scollins/po/es.po
=> sticky@scollins - Update es.po

ipindicator@matus.benko@gmail.com/files/ipindicator@matus.benko@gmail.com/applet.js
Updating IP services
https://bot.whatismyipaddress.com/ has been discontinued.
Replaced it, plus added two other good services.
@PrimaMateria
=> IP-Indicator: updating IP services 

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language file update for the Weather applet latest pot template file from 2021-12-12.
=> weather@mockturtl Update sv.po 3.1.7

weather@mockturtl/CHANGELOG.md, weather@mockturtl/files/weather@mockturtl/3.8/LogSaver.py, weather@mockturtl/files/weather@mockturtl/3.8/weather-applet.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/files/weather@mockturtl/po/weather@mockturtl.pot, weather@mockturtl/src/3_8/utils.ts
Changes:
* Fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/4136 - Fix custom widget not applying translations
* Fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/4147
=> weather@mockturtl hotfix 3.1.8

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language file update for the Weather applet latest pot template file from 2021-12-19.
=> weather@mockturtl Update sv.po 3.1.8

qredshift@quintao/files/qredshift@quintao/po/es.po
=> qredshift@quintao - Update es.po

radio@driglu4it/files/radio@driglu4it/4.6/radio-applet.js, radio@driglu4it/files/radio@driglu4it/metadata.json, radio@driglu4it/src/services/mpv/MpvHandler.ts, radio@driglu4it/webpack.config.js
This fixes #4201. Additionally I started now using a version number as that way it is easier to provide support.
=> [radio@driglu4it] fix gui opening in some circumstances

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/applet.js
Closes https://github.com/linuxmint/cinnamon-spices-applets/issues/4199
=> CinnVIIStarkMenu@NikoKrause: Correctly colour symbolic icons in quicklauncher

weather@mockturtl/files/weather@mockturtl/po/pt_BR.po
Successfully tested on Linux Mint 20.3 Una with Cinnamon.
=> weather@mockturtl: Brazilian Portuguese (pt-BR) update

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/appsview.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserBookmarks.js, Cinnamenu@json/files/Cinnamenu@json/4.0/stylesheet.css, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot, Cinnamenu@json/files/Cinnamenu@json/po/de.po, Cinnamenu@json/files/Cinnamenu@json/po/es.po, Cinnamenu@json/files/Cinnamenu@json/po/uk.po, Cinnamenu@json/files/Cinnamenu@json/po/ur.po, Cinnamenu@json/files/Cinnamenu@json/po/zh_CN.po
Separate recent files category into sections based on file type. Thanks to @naoseimaisquenomeusar for the idea.
Also separate search results into 2 sections.
update .pot and some .po files.
=> [Cinnamenu@json] Separate recents into categories

Cinnamenu@json/files/Cinnamenu@json/po/tr.po
=>  Cinnamenu@json: Update tr.po

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/appsview.js, Cinnamenu@json/files/Cinnamenu@json/4.0/categoriesview.js, Cinnamenu@json/files/Cinnamenu@json/4.0/contextmenu.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/4.0/sidebar.js, Cinnamenu@json/files/Cinnamenu@json/4.0/stylesheet.css, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/fr.po
\+ show web search option before bookmarks in search results.
=> [Cinnamenu@json] Show fewer recents

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language file update for the Weather applet latest pot template file from 2022-01-30.
=> weather@mockturtl Update sv.po 3.2.0

weather@mockturtl/README.md
Some suggestions adjusting and adding info for new weather provider AccuWeather, general fine-tuning and a new sub section for report a new issue.
ping @Gr3q  :)
=> weather@mockturtl readme fine-tuning

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/appsview.js, Cinnamenu@json/files/Cinnamenu@json/4.0/contextmenu.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/4.0/sidebar.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Separate emoji and bookmarks search results.
=> Categorize search results more.

vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/po/sv.po
=> vboxlauncher@mockturtl: Update sv.po

weather@mockturtl/CHANGELOG.md, weather@mockturtl/files/weather@mockturtl/3.8/weather-applet.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/files/weather@mockturtl/po/weather@mockturtl.pot, weather@mockturtl/src/3_8/config.ts, weather@mockturtl/src/3_8/loop.ts, weather@mockturtl/src/3_8/main.ts
* Fix https://github.com/linuxmint/cinnamon-spices-applets/issues/4255
* Redact more things when generating logs
=> weather@mockturtl update 3.2.1 - fixes
