linuxmint/cinnamon-spices-applets

- printers@linux-man/files/printers@linux-man/README.md
- printers@linux-man/files/printers@linux-man/applet.js
- printers@linux-man/files/printers@linux-man/metadata.json
- printers@linux-man/files/printers@linux-man/po/cs.po
- printers@linux-man/files/printers@linux-man/po/de.po
- printers@linux-man/files/printers@linux-man/po/es.po
- printers@linux-man/files/printers@linux-man/po/fr.po
- printers@linux-man/files/printers@linux-man/po/printers@linux-man.pot
- printers@linux-man/files/printers@linux-man/po/pt_BR.po
- printers@linux-man/files/printers@linux-man/po/pt_PT.po
- printers@linux-man/files/printers@linux-man/settings-schema.json
Applet only updates when receives a Cups signal - faster Menu toggle
3s timeout between updates
More error conditions
Settings change
Code cleanup
> Update to 0.7

- 0dyseus@CustomCinnamonMenu/README.md
- 0dyseus@CustomCinnamonMenu/files/0dyseus@CustomCinnamonMenu/README.md
- 0dyseus@DesktopHandler/README.md
- 0dyseus@DesktopHandler/files/0dyseus@DesktopHandler/README.md
- 0dyseus@ExtensionsManager/README.md
- 0dyseus@ExtensionsManager/files/0dyseus@ExtensionsManager/README.md
- 0dyseus@QuickMenu/README.md
- 0dyseus@QuickMenu/files/0dyseus@QuickMenu/README.md
- 0dyseus@SysmonitorByOrcus/README.md
- 0dyseus@SysmonitorByOrcus/files/0dyseus@SysmonitorByOrcus/README.md
- 0dyseus@window-list-fork/README.md
- 0dyseus@window-list-fork/files/0dyseus@window-list-fork/README.md
- Fixed broken links on READMEs.
> Applets updates

- scripts@paucapo.com/files/scripts@paucapo.com/applet.js
Fixed   #37  thanks to  @Odyseus
> Fix for scripts@paucapo.com

- officeCenter@scollins/files/officeCenter@scollins/applet.js
- officeCenter@scollins/files/officeCenter@scollins/po/de.po
- officeCenter@scollins/files/officeCenter@scollins/po/officeCenter.pot
> officeCenter@scollins: add l10n support & German translation

- weather@mockturtl/files/weather@mockturtl/applet.js
This comments out the modification of Soup and switches to JSON.parse
instead of Json.Parser. The try-catch block was removed in favor of
polling on null reponse, but it wasn't necessary during my testing after
the Soup change was addressed.
@mockturtl 
Fixes #53
> Fix weather applet not loading #53

- 0dyseus@PopupTranslator/CHANGELOG.md
- 0dyseus@PopupTranslator/files/0dyseus@PopupTranslator/applet.js
- 0dyseus@PopupTranslator/files/0dyseus@PopupTranslator/metadata.json
- 0dyseus@PopupTranslator/files/0dyseus@PopupTranslator/po/cs.po
- 0dyseus@PopupTranslator/files/0dyseus@PopupTranslator/po/es.po
- Added Czech localization. Thanks to [Radek71](https://github.com/Radek71).
- Added missing translatable strings.
- Improved clean up when removing applet.
> Popup Translator (0dyseus@PopupTranslator)

- all-in-one-places@jofer/files/all-in-one-places@jofer/schemas/org.cinnamon.applets.AllInOnePlaces.gschema.xml
* Update default file manager to nemo
* Replace "nautilus-connect-server" command with "nemo-connect-server"
> [all-in-one-places@jofer] Update schemas

- all-in-one-places@jofer/files/all-in-one-places@jofer/applet.js
Fix for applet is not loading correctly on recent Cinnamon versions issue
> [all-in-one-places@jofer] Applet is not loading correctly

- all-in-one-places@jofer/files/all-in-one-places@jofer/settings.py
Add nemo file manager support inside file browsers list
> [all-in-one-places@jofer] Add nemo file manager support

- 0dyseus@PopupTranslator/files/0dyseus@PopupTranslator/3.2/applet.js
- Added missing translatable strings.
- Improved clean up when removing applet.
> Popup Translator (0dyseus@PopupTranslator) Cinnamon 3.2 specific

- .github/CONTRIBUTING.md
Remind the users to use proper formatting every time somebody opens an issue or a pull request.
> Spices-Repository: add CONTRIBUTING template

- all-in-one-places@jofer/files/all-in-one-places@jofer/metadata.json
> [all-in-one-places@jofer] update version info

- stopwatch@pdcurtis/files/stopwatch@pdcurtis/applet.js
- stopwatch@pdcurtis/files/stopwatch@pdcurtis/po/de.po
- stopwatch@pdcurtis/files/stopwatch@pdcurtis/po/stopwatch.pot
> stopwatch@pdcurtis: add l10n support & German translation

- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js
Issue description: https://github.com/linuxmint/cinnamon-spices-applets/issues/78
>  [download-and-upload-speed@cardsurf] Enable or disable hover popup on start up

- 0dyseus@SysmonitorByOrcus/CHANGELOG.md
- 0dyseus@SysmonitorByOrcus/README.md
- 0dyseus@SysmonitorByOrcus/files/0dyseus@SysmonitorByOrcus/3.2/applet.js
- 0dyseus@SysmonitorByOrcus/files/0dyseus@SysmonitorByOrcus/applet.js
- 0dyseus@SysmonitorByOrcus/files/0dyseus@SysmonitorByOrcus/metadata.json
- 0dyseus@SysmonitorByOrcus/files/0dyseus@SysmonitorByOrcus/po/es.po
- 0dyseus@SysmonitorByOrcus/files/0dyseus@SysmonitorByOrcus/po/localization-template.pot
- Fixed system freeze on applet removal on Cinnamon 3.2.x.
- Cleaned code of unused constants and functions.
> System Monitor (Fork By Odyseus) (0dyseus@SysmonitorByOrcus) update

- axos88@countdown-timer/files/axos88@countdown-timer/applet.js
- axos88@countdown-timer/files/axos88@countdown-timer/metadata.json
* UUID in applet.js was wrong and it was not possible to add applet to panel
* Link to website didn't launched.
@axos88
> axos88@countdown-timer: fix uuid and broken link in "About..."

- 0dyseus@PopupTranslator/CHANGELOG.md
- 0dyseus@PopupTranslator/files/0dyseus@PopupTranslator/3.2/applet.js
- 0dyseus@PopupTranslator/files/0dyseus@PopupTranslator/applet.js
- 0dyseus@PopupTranslator/files/0dyseus@PopupTranslator/metadata.json
- Fixed keybinding display on applet tooltip.
> Popup Translator (0dyseus@PopupTranslator) update

- feeds@jonbrettdev.wordpress.com/.gitignore
- feeds@jonbrettdev.wordpress.com/CHANGELOG
- feeds@jonbrettdev.wordpress.com/TODO
- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/applet.js
- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/feedreader.js
- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/getFeed.py
- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/manage_feeds.py
- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/metadata.json
- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/settings-schema.json
Updated interface to display when a feed has been redirected to a new url.
Added a context sensitive button to allow users to permanently redirect the feed.
> feeds@jonbrettdev.wordpress.com - Updated interface to handle feed url redirects

- computer@brownsr/files/computer@brownsr/applet.js
- computer@brownsr/files/computer@brownsr/po/computer.pot
- computer@brownsr/files/computer@brownsr/po/de.po
> computer@brownsr: add l10n/translation support and German translation

- network@brownsr/files/network@brownsr/applet.js
- network@brownsr/files/network@brownsr/metadata.json
- network@brownsr/files/network@brownsr/po/de.po
- network@brownsr/files/network@brownsr/po/network.pot
also renamed applet from "network" to "Network"
@brownsr: Are you ok with the renaming?
> network@brownsr: add l10n/translation support and German translation

- vnstat@linuxmint.com/README.md
- vnstat@linuxmint.com/files/vnstat@linuxmint.com/applet.js
- vnstat@linuxmint.com/files/vnstat@linuxmint.com/po/de.po
- vnstat@linuxmint.com/files/vnstat@linuxmint.com/po/vnstat.pot
> vnstat@linuxmint.com: restore README and add l10n/translation support

- commandLauncher@scollins/files/commandLauncher@scollins/applet.js
- commandLauncher@scollins/files/commandLauncher@scollins/po/commandLauncher.pot
- commandLauncher@scollins/files/commandLauncher@scollins/po/de.po
- commandLauncher@scollins/files/commandLauncher@scollins/settings-schema.json
* add German translation
* rename "description" to "tooltipText", because it causes problems with cinnamon-json-makepot
* make some strings in applet.js translatable
@collinss
> commandLauncher@scollins: add translation support

- calendar@simonwiles.net/files/calendar@simonwiles.net/applet.js
also it fixes the time freezing
> calendar@simonwiles: fix world clocks not showing up

- toggle_LookingGlass@kolle/files/toggle_LookingGlass@kolle/applet.js
- toggle_LookingGlass@kolle/files/toggle_LookingGlass@kolle/po/de.po
- toggle_LookingGlass@kolle/files/toggle_LookingGlass@kolle/po/toggle_LookingGlass.pot
Fix applet, so it opens and closes LookingGlass again.
Add l10n template and German translation
> toggle_LookingGlass@kolle: fix applet and add l10n

- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/applet.js
- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/feedreader.js
@jake1164 Thought I'd run this by you before merging in case it interferes with your workflow.
FYI, I also submitted [this pr](https://github.com/linuxmint/Cinnamon/pull/6303) to Cinnamon. When it's merged, it will allow you to move your feeds list to the settings api if you want.
> feeds@jonbrettdev.wordpress.com: fix some variable warnings

- weather@mockturtl/files/weather@mockturtl/po/LINGUAS
- weather@mockturtl/files/weather@mockturtl/po/sl.po
I added Slovenian translation for the Weather applet. I hope everything is OK.
> Slovenian translation for the Weather applet

- vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/applet.js
- vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/po/hr.po
- vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/po/vboxlauncher@mockturtl.pot
> vboxlauncher@mockturtl: add l10n translation support, hr.po

- betterlock/files/betterlock/applet.js
- betterlock/files/betterlock/po/betterlock.pot
- betterlock/files/betterlock/po/de.po
@entelechy
Are you the author of this applet?
If yes, are you okay with this changes?
> betterlock: add feature "Show Notifications"

- system-monitor@pixunil/files/system-monitor@pixunil/po/zh_CN.po
Add Chinese translation for system-monitor@pixunil.
> Add Chinese translation for system-monitor@pixunil

- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/zh_CN.po
- sticky@scollins/files/sticky@scollins/po/zh_CN.po
Add Chinese translation for GPaste Reloaded and Sticky Notes.
> Add Chinese translation for GPaste Reloaded and Sticky Notes

- capture@rjanja/files/capture@rjanja/po/zh_CN.po
- placesCenter@scollins/files/placesCenter@scollins/po/zh_CN.po
Add Chinese translation for Desktop Capture and Place Center.
> Add Chinese translation for Desktop Capture and Place Center

- graphicsCenter@scollins/files/graphicsCenter@scollins/po/zh_CN.po
Add Chinese translation for Graphics Center.
> Add Chinese translation for Graphics Center

- officeCenter@scollins/files/officeCenter@scollins/po/zh_CN.po
Add Chinese translation for Office Center.
> Add Chinese translation for Office Center

- search-box@mtwebster/files/search-box@mtwebster/po/zh_CN.po
Add Chinese translation for Internet Search Box.
> Add Chinese translation for Internet Search Box

- vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/po/zh_CN.po
Add Chinese translations for Vbox Launcher.
> Add Chinese translations for Vbox Launcher

- network@brownsr/files/network@brownsr/po/zh_CN.po
Add Chinese translation for Network.
> Add Chinese translation for Network

- sessionManager@scollins/files/sessionManager@scollins/po/zh_CN.po
Add Chinese translation for Session Manager.
> Add Chinese translation for Session Manager

- printers@linux-man/files/printers@linux-man/po/zh_CN.po
Add Chinese translation for Printers.
> Add Chinese translation for Printers

- 0dyseus@ExtensionsManager/CHANGELOG.md
- 0dyseus@ExtensionsManager/README.md
- 0dyseus@ExtensionsManager/files/0dyseus@ExtensionsManager/3.2/applet.js
- 0dyseus@ExtensionsManager/files/0dyseus@ExtensionsManager/applet.js
- 0dyseus@ExtensionsManager/files/0dyseus@ExtensionsManager/metadata.json
- 0dyseus@ExtensionsManager/files/0dyseus@ExtensionsManager/po/cs.po
- 0dyseus@ExtensionsManager/files/0dyseus@ExtensionsManager/po/es.po
- 0dyseus@ExtensionsManager/files/0dyseus@ExtensionsManager/po/hr.po
- 0dyseus@ExtensionsManager/files/0dyseus@ExtensionsManager/po/localization-template.pot
- Fixed incorrect setting name that prevented the correct update of the enabled/disabled extensions on this applet menu.
- Updated README.
- Updated localization template.
> Extensions Manager (0dyseus@ExtensionsManager) update

- ScreenLocker@tuuxx/files/po/zh_CN.po
ScreenLocker@tuuxx: Create zh_CN.po
> ScreenLocker@tuuxx: Create zh_CN.po

- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/zh_CN.po
CinnVIIStarkMenu @NikoKrause: Create zh_CN.po.
> CinnVIIStarkMenu@NikoKrause: Add Chinese translation

- computer@brownsr/files/computer@brownsr/po/zh_CN.po
Computer @brownsr: Create zh_CN.po
> Add Chinese translation for Computer

- betterlock/files/betterlock/po/ru.po
@entelechy are you okay with this change?
> betterlock: added russian translation

- hamster@projecthamster.wordpress.com/files/hamster@projecthamster.wordpress.com/po/zh_CN.po
Project Hamster Applet @projecthamster: Create zh_CN.po.
> Add Chinese translation for Project Hamster Applet

- places-with-terminal@mtwebster/files/places-with-terminal@mtwebster/po/zh_CN.po
Places with Terminal Launcher @mtwebster: Create zh_CN.po.
> Add Chinese translation for Places with Terminal Launcher

- scripts@paucapo.com/files/scripts@paucapo.com/po/zh_CN.po
Scripts Menu @paucapo: Create zh_CN.po.
> Add Chinese translation for Scripts Menu

- host-entries@hoffis-eck.de/files/po/zh_CN.po
Host Entries @hoffis-eck.de: Create zh_CN.po.
> Add Chinese translation for Host Entries

- betterlock/files/betterlock/po/zh_CN.po
Num Lock/Caps Lock indicator with MessageTray notifications @entelechy: Create zh_CN.po.
> Add Chinese translation for Num Lock/Caps Lock indicator with MessageTray notifications

- restart-cinnamon@kolle/files/restart-cinnamon@kolle/po/zh_CN.po
Restart Cinnamon @kolle:  Create zh_CN.po.
> Add Chinese translation for Restart Cinnamon

- pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/zh_CN.po
pomodoro @gfreeau: Create zh_CN.po.
> Add Chinese translation for Pomodoro Timer

- IcingTaskManager@json/README.md
> Icing Task Manager: Update readme

- commandLauncher@scollins/files/commandLauncher@scollins/po/zh_CN.po
commandlauncher @collinss: Create zh_CN.po.
> Add Chinese translation for Command Launcher

- stopwatch@pdcurtis/files/stopwatch@pdcurtis/po/zh——CN.po
stopwatch @pdcurtis: Create zh_CN.po
> Add Chinese translation for Stopwatch for Cinnamon 1.8+

- timeout@narutrey/files/timeout@narutrey/applet.js
> timeout@narutrey: Fixed automatic work continuation

- toggle_LookingGlass@kolle/files/toggle_LookingGlass@kolle/po/zh_CN.po
togglelookingglass @kolle: Create zh_CN.po
> Add Chinese translation for Toggle LookingGlass

- brightness@markbokil.com/files/brightness@markbokil.com/po/zh_CN.po
Add Chinese translation for Brightness.
> Add Chinese translation for Brightness

- PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/po/zh_CN.po
Add Chinese translation for PDFManager.
> Add Chinese translation for PDFManager

- vnstat@linuxmint.com/files/vnstat@linuxmint.com/po/zh_CN.po
Network usage monitor @clefebvre: Create zh_CN.po.
> Add Chinese translation for Network usage monitor

- ctrl4docker@hoffis-eck.de/files/ctrl4docker@hoffis-eck.de/po/zh_CN.po
Docker Control @hoffis-eck.de: Create zh_CN.po.
> Add Chinese translation for Docker Control

- timeout@narutrey/files/timeout@narutrey/po/zh_CN.po
Time Out @narutrey: Create zh_CN.po.
> Add Chinese translation for Time Out

- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/po/zh_CN.po
collapsiblesystray @feuerfuchs: Create zh_CN.po
> Add Chinese translation for Collapsible Systray

- printers@linux-man/README.md
- printers@linux-man/files/printers@linux-man/po/ru_RU.po
Hello @linux-man.
I am added Russian translation to printers applet.
> Printers(printers@linux-man): added russian translation

- timeout@narutrey/files/timeout@narutrey/applet.js
> timeout@narutrey: fix time display

- vnstat@linuxmint.com/files/vnstat@linuxmint.com/po/ru_RU.po
Hello @clefebvre.
I am added Russian translation.
> Network usage monitor (vnstat@linuxmint.com): added russian translation

- PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/extract.py
- PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/flip-v.py
- PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/merge.py
- PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/po/de.po
- PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/po/es.po
- PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/po/fr.po
- PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/po/hr.po
- PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/po/pdfmanager.pot
- PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/reduce.py
- PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/rotate-left.py
- PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/rotate-right.py
- PDFManager@cinnamon.org/info.json
@mickaelalbertus are you okay with the changes?
> PDFManager@cinnamon.org: update translations & author info

- search-box@mtwebster/files/search-box@mtwebster/po/ru_RU.po
I'm creatin russian language file.
> Add Russian language to search-box@mtwebster

- betterlock/files/betterlock/applet.js
- betterlock/files/betterlock/settings-schema.json
- Fixed inability to disable notifications. Fixes #164.
- Re-added compatibility with **still** supported Cinnamon versions.
Ping author: @entelechy
> Num Lock/Caps Lock indicator with MessageTray notifications (betterlock) update

- WindowListGroup@jake.phy@gmail.com/files/WindowListGroup@jake.phy@gmail.com/locale/zh_CN.po
WindowListGroup @jake-phy: Create zh_CN.po
> Add Chinese translation for Window List With App Grouping

- github-projects@morgan-design.com/files/github-projects@morgan-design.com/po/zh_CN.po
githubexplorer @jamesmorgan: Create zh_CN.po
> Add Chinese translation for Github Explorer

- SW++@mohammad-sn/files/SW++@mohammad-sn/applet.js
- SW++@mohammad-sn/files/SW++@mohammad-sn/metadata.json
- SW++@mohammad-sn/files/SW++@mohammad-sn/po/SW++.pot
- SW++@mohammad-sn/files/SW++@mohammad-sn/po/de.po
- SW++@mohammad-sn/files/SW++@mohammad-sn/settings-schema.json
@mohammad-sn: see the 3 commit messages for more information
> SW++@mohammad-sn: keyboard bugfix, l10n support, standard icon name

- gputemperature@silentage.com/files/gputemperature@silentage.com/applet.js
- Fixed omitted usage of *test* method. Fixes  #261.
> GPU Temperature (gputemperature@silentage.com) update

- printers@linux-man/files/printers@linux-man/applet.js
Second try with (I hope) a correct format.
> printers@linux-man: correct issue #235, no applet icon when no printers installed

- sticky@scollins/files/sticky@scollins/po/sv.po
> sticky@scollins: Create sv.po

- scripts@paucapo.com/files/scripts@paucapo.com/po/sv.po
> scripts@paucapo.com: Create sv.po

- system-monitor@pixunil/files/system-monitor@pixunil/po/hr.po
- system-monitor@pixunil/files/system-monitor@pixunil/po/ru_RU.po
- system-monitor@pixunil/files/system-monitor@pixunil/po/system-monitor.pot
- system-monitor@pixunil/files/system-monitor@pixunil/po/zh_CN.po
> system-monitor@pixunil: add l10n template

- timer-notifications@markbokil.com/files/timer-notifications@markbokil.com/applet.js
- timer-notifications@markbokil.com/files/timer-notifications@markbokil.com/po/sv.po
- timer-notifications@markbokil.com/files/timer-notifications@markbokil.com/po/timer-notifications.pot
Add translation support and translation files
> timer-notifications@markbokil.com: add translation support

- PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/po/sv.po
> PDFManager@cinnamon.org: Create sv.po

- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/po/feeds.pot
> Create feeds.pot for Feeds Reader

- sound-with-apps-volume@koutch/files/sound-with-apps-volume@koutch/applet.js
- sound-with-apps-volume@koutch/files/sound-with-apps-volume@koutch/metadata.json
- sound-with-apps-volume@koutch/files/sound-with-apps-volume@koutch/po/ru_RU.po
- sound-with-apps-volume@koutch/files/sound-with-apps-volume@koutch/po/yourApplet.pot
@koutch are you okay with this change?
> sound-with-apps-volume: added russian translation

- places-bookmarks@dmo60.de/files/places-bookmarks@dmo60.de/po/localization-template.pot
- places-bookmarks@dmo60.de/files/places-bookmarks@dmo60.de/po/zh_CN.po
- places-bookmarks@dmo60.de/files/places-bookmarks@dmo60.de/settings-schema.json
> Add Chinese translation for Places

- sound-with-apps-volume@koutch/files/sound-with-apps-volume@koutch/po/zh_CN.po
> Add Chinese translation for Sound with apps volume

- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletGui.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/download-and-upload-speed@cardsurf.pot
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/zh_CN.po
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/settings-schema.json
> Add Chinese translation for Download and upload speed

- nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/po/zh_CN.po
> Add Chinese translation for nVidia Prime GPU Display

- bumblebee@pdcurtis/files/bumblebee@pdcurtis/po/zh_CN.po
> Add Chinese translation for Bumblebee and nVidia Display

- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/applet.js
- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/feedreader.js
- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/manage_feeds.py
- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/po/feeds.pot
- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/po/zh_CN.po
> Update pot file and add Chinese translation for Feeds Reader

- timer-notifications@markbokil.com/files/timer-notifications@markbokil.com/applet.js
- timer-notifications@markbokil.com/files/timer-notifications@markbokil.com/po/zh_CN.po
> Add Chinese translation for  Timer with Notifications

- bumblebee@pdcurtis/files/bumblebee@pdcurtis/po/hr.po
> bumblebee@pdcurtis: Add hr.po

- 0dyseus@QuickMenu/HELP.pug
- 0dyseus@QuickMenu/docs/HELP-es.md
- 0dyseus@QuickMenu/docs/HELP.md
- 0dyseus@QuickMenu/files/0dyseus@QuickMenu/HELP.html
> Quick Menu (0dyseus@QuickMenu) update

- 0dyseus@CustomCinnamonMenu/HELP.pug
- 0dyseus@CustomCinnamonMenu/docs/HELP-es.md
- 0dyseus@CustomCinnamonMenu/docs/HELP.md
- 0dyseus@CustomCinnamonMenu/files/0dyseus@CustomCinnamonMenu/HELP.html
> Custom Cinnamon Menu (0dyseus@CustomCinnamonMenu) update

- batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/zh_CN.po
> Add Chinese translation for Battery Applet with Monitoring and Shutdown (BAMS)

- Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot
- Cinnamenu@json/files/Cinnamenu@json/po/zh_CN.po
> Add Chinese translation for Cinnamenu

- weather@mockturtl/files/weather@mockturtl/po/weather@mockturtl.pot
- weather@mockturtl/files/weather@mockturtl/po/zh_CN.po
- weather@mockturtl/files/weather@mockturtl/settings-schema.json
> Update translations for weather@mockturtl

- show-hide-applets@mohammad-sn/files/show-hide-applets@mohammad-sn/applet.js
- show-hide-applets@mohammad-sn/files/show-hide-applets@mohammad-sn/po/draw.pot
- show-hide-applets@mohammad-sn/files/show-hide-applets@mohammad-sn/po/zh_CN.po
- show-hide-applets@mohammad-sn/files/show-hide-applets@mohammad-sn/settings-schema.json
> Add Chinese translation for Drawer

- rancher@centurix/files/rancher@centurix/applet.js
- rancher@centurix/files/rancher@centurix/po/rancher.pot
- rancher@centurix/files/rancher@centurix/po/zh_CN.po
> Add translation support and update translation for rancher@centurix

- ScreenShot@tech71/files/ScreenShot@tech71/applet.js
- ScreenShot@tech71/files/ScreenShot@tech71/po/screenshot@tech71.pot
- ScreenShot@tech71/files/ScreenShot@tech71/po/zh_CN.po
> Add translation support for ScreenShot

- ShutdownApplet@shelley/files/ShutdownApplet@shelley/applet.js
- ShutdownApplet@shelley/files/ShutdownApplet@shelley/po/ShutdownApplet@shelley.pot
- ShutdownApplet@shelley/files/ShutdownApplet@shelley/po/zh_CN.po
> Add translation support for Shutdown Applet

- SW++@mohammad-sn/files/SW++@mohammad-sn/po/zh_CN.po
> Add Chinese translation for Show desktop ++

- screen-inhibit@mtwebster/files/applet.js
- screen-inhibit@mtwebster/files/po/screen-inhibit@mtwebster.pot
- screen-inhibit@mtwebster/files/po/zh_CN.po
> Add translation support for Screensaver Inhibitor

- ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/applet.js
- ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/po/ScreenShot+RecordDesktop@tech71.pot
- ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/po/zh_CN.po
> Add translation support for ScreenShot+Record Desktop

- QuitApplet@bownz/files/QuitApplet@bownz/applet.js
- QuitApplet@bownz/files/QuitApplet@bownz/po/quitapplet@bownz.pot
- QuitApplet@bownz/files/QuitApplet@bownz/po/zh_CN.po
- QuitApplet@bownz/files/QuitApplet@bownz/settings.py
> Add translation support for Quit Applet

- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/DataProviders.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/ErrorApplet.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/applet.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/multicore-sys-monitor@ccadeptic23.pot
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/zh_CN.po
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/prefs.js
> Add translation support for Multi-Core System Monitor

- UserMenuV2@bownz/files/UserMenuV2@bownz/applet.js
- UserMenuV2@bownz/files/UserMenuV2@bownz/po/UserMenuV2@bownz.pot
- UserMenuV2@bownz/files/UserMenuV2@bownz/po/zh_CN.po
> Add translation support for UserMenu

- all-in-one-places@jofer/files/all-in-one-places@jofer/applet.js
- all-in-one-places@jofer/files/all-in-one-places@jofer/po/all-in-one-places@jofer.pot
- all-in-one-places@jofer/files/all-in-one-places@jofer/po/zh_CN.po
- all-in-one-places@jofer/files/all-in-one-places@jofer/settings.py
> Add translation support for All-in-one Places

- bettersettings@bownz/files/bettersettings@bownz/applet.js
- bettersettings@bownz/files/bettersettings@bownz/po/bettersettings@bownz.pot
- bettersettings@bownz/files/bettersettings@bownz/po/zh_CN.po
> Add translation support for Better Cinnamon Settings

- hwmonitor@sylfurd/files/hwmonitor@sylfurd/applet.js
- hwmonitor@sylfurd/files/hwmonitor@sylfurd/po/hwmonitor@sylfurd.pot
- hwmonitor@sylfurd/files/hwmonitor@sylfurd/po/zh_CN.po
> Add translation support for Graphical hardware monitor

- mylauncher@markbokil.com/files/mylauncher@markbokil.com/applet.js
- mylauncher@markbokil.com/files/mylauncher@markbokil.com/po/mylauncher@markbokil.com.pot
- mylauncher@markbokil.com/files/mylauncher@markbokil.com/po/zh_CN.po
> Add translation support for  My Launcher

- sysmonitor@orcus/files/sysmonitor@orcus/applet.js
- sysmonitor@orcus/files/sysmonitor@orcus/po/sysmonitor@orcus.pot
- sysmonitor@orcus/files/sysmonitor@orcus/po/zh_CN.po
- sysmonitor@orcus/files/sysmonitor@orcus/settings.js
> Add translation support for System Monitor

- systray-collapsible@koutch/files/systray-collapsible@koutch/applet.js
- systray-collapsible@koutch/files/systray-collapsible@koutch/po/systray-collapsible@koutch.pot
- systray-collapsible@koutch/files/systray-collapsible@koutch/po/zh_CN.po
> Add translation support for System Tray Collapsible

- temperature@fevimu/files/temperature@fevimu/applet.js
- temperature@fevimu/files/temperature@fevimu/po/temperature@fevimu.pot
- temperature@fevimu/files/temperature@fevimu/po/zh_CN.po
> Add translation support for CPU Temperature Indicator

- window-buttons-with-title@fmete/files/window-buttons-with-title@fmete/applet.js
- window-buttons-with-title@fmete/files/window-buttons-with-title@fmete/po/window-buttons-with-title@fmete.pot
- window-buttons-with-title@fmete/files/window-buttons-with-title@fmete/po/zh_CN.po
> Add translation support for Window Buttons with Title

- windows-quick-list-with-close-button@koutch/files/windows-quick-list-with-close-button@koutch/applet.js
- windows-quick-list-with-close-button@koutch/files/windows-quick-list-with-close-button@koutch/po/windows-quick-list-with-close-button@koutch.pot
- windows-quick-list-with-close-button@koutch/files/windows-quick-list-with-close-button@koutch/po/zh_CN.po
> Add translation support for Windows Quick List with close button

- sticky@scollins/files/sticky@scollins/po/ru.po
Translating to Russian language "Sticky Notes by collinss"
> Translating to Russian language

- betterplaces@bownz/files/betterplaces@bownz/applet.js
- betterplaces@bownz/files/betterplaces@bownz/po/betterplaces@bownz.pot
- betterplaces@bownz/files/betterplaces@bownz/po/zh_CN.po
> Add translation support for  Better Places

- calendar@simonwiles.net/files/calendar@simonwiles.net/applet.js
- calendar@simonwiles.net/files/calendar@simonwiles.net/po/calendar@simonwiles.net.pot
- calendar@simonwiles.net/files/calendar@simonwiles.net/po/zh_CN.po
- calendar@simonwiles.net/files/calendar@simonwiles.net/world_clock_calendar_settings.py
> Add translation support for World Clock Calendar

- color-picker@fmete/files/color-picker@fmete/applet.js
- color-picker@fmete/files/color-picker@fmete/po/color-picker@fmete.pot
- color-picker@fmete/files/color-picker@fmete/po/zh_CN.po
> Add translation support for Color Picker

- cpufreq@mtwebster/files/cpufreq@mtwebster/applet.js
- cpufreq@mtwebster/files/cpufreq@mtwebster/po/cpufreq@mtwebster.pot
- cpufreq@mtwebster/files/cpufreq@mtwebster/po/zh_CN.po
> Add translation support for CPU Frequency Applet

- cpu-monitor-text@gnemonix/files/cpu-monitor-text@gnemonix/applet.js
- cpu-monitor-text@gnemonix/files/cpu-monitor-text@gnemonix/po/cpu-monitor-text@gnemonix.pot
- cpu-monitor-text@gnemonix/files/cpu-monitor-text@gnemonix/po/zh_CN.po
> Add translation support for Simple CPU Monitor

- mybookmarks@markbokil.com/files/mybookmarks@markbokil.com/applet.js
- mybookmarks@markbokil.com/files/mybookmarks@markbokil.com/po/mybookmarks@markbokil.com.pot
- mybookmarks@markbokil.com/files/mybookmarks@markbokil.com/po/zh_CN.po
> Add translation support for My Bookmarks

- screen-inhibit@mtwebster/files/applet.js
- screen-inhibit@mtwebster/files/po/screen-inhibit@mtwebster.pot
- screen-inhibit@mtwebster/files/po/zh_CN.po
> Update translation for Screensaver Inhibitor

- slingshot@jfarthing84/files/applet.js
- slingshot@jfarthing84/files/po/slingshot@jfarthing84.pot
- slingshot@jfarthing84/files/po/zh_CN.po
> Add translation support for Slingshot

- web-developer-menu@infiniteshroom/files/applet.js
- web-developer-menu@infiniteshroom/files/po/web-developer-menu@infiniteshroom.pot
- web-developer-menu@infiniteshroom/files/po/zh_CN.po
> Add translation support for Web Developer Menu

- workspace-grid@hernejj/files/workspace-grid@hernejj/po/workspace-grid@hernejj.pot
- workspace-grid@hernejj/files/workspace-grid@hernejj/po/zh_CN.po
> Add translation support for Workspace grid (2D) and switcher

- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/po/zh_CN.po
> Improve Chinese translation for Collapsible Systray

- ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/applet.js
- ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/po/ShutdownMenuWithIcons@LLOBERA.pot
- ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/po/zh_CN.po
> Add translation support for Shutdown Menu With Icons

- acerhk-ctl@mcnielcho.org/files/acerhk-ctl@mcnielcho.org/applet.js
- acerhk-ctl@mcnielcho.org/files/acerhk-ctl@mcnielcho.org/po/acerhk-ctl@mcnielcho.org.pot
- acerhk-ctl@mcnielcho.org/files/acerhk-ctl@mcnielcho.org/po/zh_CN.po
> Add translation support for AcerHK Control

- back-up_state@natsakis.com/files/po/back-up_state@natsakis.com.pot
- back-up_state@natsakis.com/files/po/zh_CN.po
> Add translation support for Back-up State

- CommandRunner@appdevsw/files/CommandRunner@appdevsw/applet.js
- CommandRunner@appdevsw/files/CommandRunner@appdevsw/appletgui.js
- CommandRunner@appdevsw/files/CommandRunner@appdevsw/cmdrunner.js
- CommandRunner@appdevsw/files/CommandRunner@appdevsw/po/CommandRunner@appdevsw.pot
- CommandRunner@appdevsw/files/CommandRunner@appdevsw/po/zh_CN.po
- CommandRunner@appdevsw/files/CommandRunner@appdevsw/simplexml.js
> Add translation support for CommandRunner

- devutils@fogl/files/devutils@fogl/applet.js
- devutils@fogl/files/devutils@fogl/po/devutils@fogl.pot
- devutils@fogl/files/devutils@fogl/po/zh_CN.po
> Add translation support for Development Utils

- ink-level-monitor@r0p01ach/files/ink-level-monitor@r0p01ach/applet.js
- ink-level-monitor@r0p01ach/files/ink-level-monitor@r0p01ach/po/ink-level-monitor@r0p01ach.pot
- ink-level-monitor@r0p01ach/files/ink-level-monitor@r0p01ach/po/zh_CN.po
> Add translation support for Printer Ink Level Monitor Applet

- mem-monitor-text@datanom.net/files/mem-monitor-text@datanom.net/applet.js
- mem-monitor-text@datanom.net/files/mem-monitor-text@datanom.net/po/mem-monitor-text@datanom.net.pot
- mem-monitor-text@datanom.net/files/mem-monitor-text@datanom.net/po/zh_CN.po
> Add translation support for Simple Memory Monitor

- pa-equalizer@jschug.com/files/pa-equalizer@jschug.com/applet.js
- pa-equalizer@jschug.com/files/pa-equalizer@jschug.com/po/pa-equalizer@jschug.com.pot
- pa-equalizer@jschug.com/files/pa-equalizer@jschug.com/po/zh_CN.po
> Add translation support for Equalizer

- serviceLauncher@hulygun/files/po/serviceLauncher@hulygun.pot
- serviceLauncher@hulygun/files/po/zh_CN.po
> Add translation support for Service Launcher

- sshlauncher@sumo/files/sshlauncher@sumo/applet.js
- sshlauncher@sumo/files/sshlauncher@sumo/po/sshlauncher@sumo.pot
- sshlauncher@sumo/files/sshlauncher@sumo/po/zh_CN.po
> Add translation support for SSH Launcher

- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/applet.js
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/po/text-to-speech-applet@cardsurf.pot
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/po/zh_CN.po
> Add translation support for Text to speech applet

- xampp-panel@backids99/files/xampp-panel@backids99/applet.js
- xampp-panel@backids99/files/xampp-panel@backids99/po/xampp-panel@backids99.pot
- xampp-panel@backids99/files/xampp-panel@backids99/po/zh_CN.po
> Add translation support for Xampp Panel Menu

- a4techTool@mous/files/a4techTool@mous/applet.js
- a4techTool@mous/files/a4techTool@mous/po/a4techTool@mous.pot
- a4techTool@mous/files/a4techTool@mous/po/zh_CN.po
> Add translation support for A4Tech battery checker

- bash-sensors@pkkk/files/bash-sensors@pkkk/applet.js
- bash-sensors@pkkk/files/bash-sensors@pkkk/po/bash-sensors@pkkk.pot
- bash-sensors@pkkk/files/bash-sensors@pkkk/po/zh_CN.po
> Add translation support for Bash Sensors

- customplaces@llobera/files/customplaces@llobera/applet.js
- customplaces@llobera/files/customplaces@llobera/po/customplaces@llobera.pot
- customplaces@llobera/files/customplaces@llobera/po/zh_CN.po
> Add translation support for Custom Places

- desktopiconsize@lotsrc/files/desktopiconsize@lotsrc/applet.js
- desktopiconsize@lotsrc/files/desktopiconsize@lotsrc/desktopiconsize.py
- desktopiconsize@lotsrc/files/desktopiconsize@lotsrc/po/desktopiconsize@lotsrc.pot
- desktopiconsize@lotsrc/files/desktopiconsize@lotsrc/po/zh_CN.po
> Add translation support for Desktop Icon Size

- mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/applet.js
- mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/mailnagapplet@ozderya.net.pot
- mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/zh_CN.po
> Add translation support for Mailnag

- netctlstatus@prmurthy/files/netctlstatus@prmurthy/applet.js
- netctlstatus@prmurthy/files/netctlstatus@prmurthy/po/netctlstatus@prmurthy.pot
- netctlstatus@prmurthy/files/netctlstatus@prmurthy/po/zh_CN.po
> Add translation support for Netctl Status

- path-monitor@kamikaze/files/path-monitor@kamikaze/applet.js
- path-monitor@kamikaze/files/path-monitor@kamikaze/po/path-monitor@kamikaze.pot
- path-monitor@kamikaze/files/path-monitor@kamikaze/po/zh_CN.po
> Add translation support for Path Monitor

- places-system-menu@fogl/files/places-system-menu@fogl/applet.js
- places-system-menu@fogl/files/places-system-menu@fogl/po/places-system-menu@fogl.pot
- places-system-menu@fogl/files/places-system-menu@fogl/po/zh_CN.po
> Add translation support for Places and System Menu

- sane-menu@nooulaif/files/applet.js
- sane-menu@nooulaif/files/po/sane-menu@nooulaif.pot
- sane-menu@nooulaif/files/po/zh_CN.po
> Add translation support for Sane Menu

- smallcalc_applet@lerc.sds/files/smallcalc_applet@lerc.sds/applet.js
- smallcalc_applet@lerc.sds/files/smallcalc_applet@lerc.sds/po/smallcalc_applet@lerc.sds.pot
- smallcalc_applet@lerc.sds/files/smallcalc_applet@lerc.sds/po/zh_CN.po
> Add translation support for SmallCalc

- uptime@vatanuki.kun/files/uptime@vatanuki.kun/applet.js
- uptime@vatanuki.kun/files/uptime@vatanuki.kun/po/uptime@vatanuki.kun.pot
- uptime@vatanuki.kun/files/uptime@vatanuki.kun/po/zh_CN.po
> Add translation support for Up Time

- lookingglass-restart@markbokil.com/files/lookingglass-restart@markbokil.com/applet.js
- lookingglass-restart@markbokil.com/files/lookingglass-restart@markbokil.com/po/lookingglass-restart@markbokil.com.pot
- lookingglass-restart@markbokil.com/files/lookingglass-restart@markbokil.com/po/zh_CN.po
> Add translation support for LookingGlass Restart

- PDFManager@cinnamon.org/files/PDFManager@cinnamon.org/po/zh_CN.po
> Update Chinese translation for PDFManager

- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/sv.po
> multicore-sys-monitor@ccadeptic23: sv.po

- netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/po/zh_CN.po
> Add Chinese translation for Network Data Usage Monitor

- windowTitle2@hanspr/files/windowTitle2@hanspr/applet.js
- windowTitle2@hanspr/files/windowTitle2@hanspr/po/windowTitle2@hanspr.pot
- windowTitle2@hanspr/files/windowTitle2@hanspr/po/zh_CN.po
> Add translation support for Window Title Applet 2

- window-buttons-with-title2@hanspr/files/window-buttons-with-title2@hanspr/applet.js
- window-buttons-with-title2@hanspr/files/window-buttons-with-title2@hanspr/po/window-buttons-with-title2@hanspr.pot
- window-buttons-with-title2@hanspr/files/window-buttons-with-title2@hanspr/po/zh_CN.po
> Add translation support for Window Buttons with Title 2

- suspend@janax/files/suspend@janax/applet.js
- suspend@janax/files/suspend@janax/po/suspend@janax.pot
- suspend@janax/files/suspend@janax/po/zh_CN.po
> Add translation support for Suspend computer

- turn-off-monitor@zablotski/files/turn-off-monitor@zablotski/applet.js
- turn-off-monitor@zablotski/files/turn-off-monitor@zablotski/po/turn-off-monitor@zablotski.pot
- turn-off-monitor@zablotski/files/turn-off-monitor@zablotski/po/zh_CN.po
> Add translation support for Turn Off Monitor

- places@tycho/files/places@tycho/applet.js
- places@tycho/files/places@tycho/po/places@tycho.pot
- places@tycho/files/places@tycho/po/zh_CN.po
> Add translation support for Tycho Places

- profile-switcher@pixunil/files/profile-switcher@pixunil/applet.js
- profile-switcher@pixunil/files/profile-switcher@pixunil/po/profile-switcher@pixunil.pot
- profile-switcher@pixunil/files/profile-switcher@pixunil/po/zh_CN.po
> Add translation support for Profile switcher

- location-detection@heimdall/files/location-detection@heimdall/applet.js
- location-detection@heimdall/files/location-detection@heimdall/po/location-detection@heimdall.pot
- location-detection@heimdall/files/location-detection@heimdall/po/zh_CN.po
> Add translation support for Location Detection + Flags

- localipswithsettings@edaubert/files/localipswithsettings@edaubert/applet.js
- localipswithsettings@edaubert/files/localipswithsettings@edaubert/po/localipswithsettings@edaubert.pot
- localipswithsettings@edaubert/files/localipswithsettings@edaubert/po/zh_CN.po
> Add translation support for Local IPs with setting

- IcingWindowSaver@json/files/applet.js
- IcingWindowSaver@json/files/po/IcingWindowSaver@json.pot
- IcingWindowSaver@json/files/po/zh_CN.po
> Add translation support for Icing Window Saver

- workspace-name@willurd/files/workspace-name@willurd/po/workspace-name@willurd.pot
- workspace-name@willurd/files/workspace-name@willurd/po/zh_CN.po
> Add translation support for Workspace Name

- axos88@countdown-timer/files/axos88@countdown-timer/applet.js
- axos88@countdown-timer/files/axos88@countdown-timer/po/axos88@countdown-timer.pot
- axos88@countdown-timer/files/axos88@countdown-timer/po/zh_CN.po
> Add translation support for Countdown timer with notifications

- diaspora-notif@douze12/files/diaspora-notif@douze12/applet.js
- diaspora-notif@douze12/files/diaspora-notif@douze12/po/diaspora-notif@douze12.pot
- diaspora-notif@douze12/files/diaspora-notif@douze12/po/zh_CN.po
> Add translation support for Diaspora* notifications

- softyubikey@yubiserver.include.gr/files/softyubikey@yubiserver.include.gr/applet.js
- softyubikey@yubiserver.include.gr/files/softyubikey@yubiserver.include.gr/po/softyubikey@yubiserver.include.gr.pot
- softyubikey@yubiserver.include.gr/files/softyubikey@yubiserver.include.gr/po/zh_CN.po
> Add translation support for SoftYubikey

- todo@threefi/files/todo@threefi/applet.js
- todo@threefi/files/todo@threefi/po/todo@threefi.pot
- todo@threefi/files/todo@threefi/po/zh_CN.po
> Add translation support for Todo

- devutils@fogl/files/devutils@fogl/po/zh_CN.po
> Update Chinese translation for Development Utils

- Window-List-Hotkey@HenryNugraha/files/Window-List-Hotkey@HenryNugraha/applet.js
- Window-List-Hotkey@HenryNugraha/files/Window-List-Hotkey@HenryNugraha/po/Window-List-Hotkey@HenryNugraha.pot
- Window-List-Hotkey@HenryNugraha/files/Window-List-Hotkey@HenryNugraha/po/zh_CN.po
> Add translation support for Window list with hotkey

- AutostartPrograms@spacy01/files/AutostartPrograms@spacy01/po/AutostartPrograms.pot
...and update bg.po file against template
@spacy01
> AutostartPrograms@spacy01: add translation template file

- system-monitor@spacy01/files/system-monitor@spacy01/po/bg.po
> system-monitor@spacy01: use UTF-8 character encoding

- printers@linux-man/files/printers@linux-man/po/ru.po
@linux-man sorry I missed this one last time
> printer@linux-man: use proper language ID ru

- clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/QRLib.js
- clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/applet.js
- clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/po/clipboard-qr@wrouesnel.pot
- clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/po/zh_CN.po
> Add translation support for Clipboard QR code applet

- back-up_state@natsakis.com/info.json
The github user name of this applets author is @tassos (see http://www.natsakis.com/post/back-ups/)
> back-up_state@natsakis.com: found github username of author

- vnstat@linuxmint.com/files/vnstat@linuxmint.com/po/ru.po
> vnstat@linuxmint.com: use proper language ID

- sound-with-apps-volume@koutch/files/sound-with-apps-volume@koutch/po/ru.po
> sound-with-apps-volume@koutch: use proper language ID

- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/applet.js
@cardsurf
My mistake,change UUID to uuid it can be added to panel otherwise it can't be.
> Fix UUID caused issue for Text to speech applet

- places-with-terminal@mtwebster/files/places-with-terminal@mtwebster/po/places-with-terminal.pot
- places-with-terminal@mtwebster/files/places-with-terminal@mtwebster/po/zh_CN.po
> Update translation for Places with Terminal Launcher

- soft-numlock@d5xtgr/files/soft-numlock@d5xtgr/applet.js
- soft-numlock@d5xtgr/files/soft-numlock@d5xtgr/po/soft-numlock@d5xtgr.pot
- soft-numlock@d5xtgr/files/soft-numlock@d5xtgr/po/zh_CN.po
> Add translation support for Num Lock indicator

- search@bownz/files/search@bownz/applet.js
- search@bownz/files/search@bownz/po/search@bownz.pot
- search@bownz/files/search@bownz/po/zh_CN.po
> Add translation support for Search Applet

- power-off@martin/files/power-off@martin/applet.js
- power-off@martin/files/power-off@martin/po/power-off@martin.pot
- power-off@martin/files/power-off@martin/po/zh_CN.po
> Add translation support for power-off

- netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/applet.js
- netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/po/netusagemonitor.pot
- netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/po/zh_CN.po
> Update translation for Network Data Usage Monitor

- logout@martin/files/logout@martin/applet.js
- logout@martin/files/logout@martin/po/logout@martin.pot
- logout@martin/files/logout@martin/po/zh_CN.po
> Add translation support for logout

- gputemperature@silentage.com/files/gputemperature@silentage.com/applet.js
- gputemperature@silentage.com/files/gputemperature@silentage.com/po/gputemperature@silentage.com.pot
- gputemperature@silentage.com/files/gputemperature@silentage.com/po/zh_CN.po
> Add translation support for GPU Temperature

- github-projects@morgan-design.com/files/github-projects@morgan-design.com/applet.js
- github-projects@morgan-design.com/files/github-projects@morgan-design.com/po/github-projects.pot
- github-projects@morgan-design.com/files/github-projects@morgan-design.com/po/zh_CN.po
> Update translation for Github Explorer

- force-quit@mohammad-sn/files/force-quit@mohammad-sn/applet.js
- force-quit@mohammad-sn/files/force-quit@mohammad-sn/po/force-quit@mohammad-sn.pot
- force-quit@mohammad-sn/files/force-quit@mohammad-sn/po/zh_CN.po
> Add translation support for Force Quit II

- CustomApplicationsMenu@LLOBERA/files/CustomApplicationsMenu@LLOBERA/applet.js
- CustomApplicationsMenu@LLOBERA/files/CustomApplicationsMenu@LLOBERA/po/CustomApplicationsMenu@LLOBERA.pot
- CustomApplicationsMenu@LLOBERA/files/CustomApplicationsMenu@LLOBERA/po/zh_CN.po
> Add translation support for Custom Applications Menu

- window-list-multi-monitor@mazz/files/window-list-multi-monitor@mazz/applet.js
- window-list-multi-monitor@mazz/files/window-list-multi-monitor@mazz/po/window-list-multi-monitor@mazz.pot
- window-list-multi-monitor@mazz/files/window-list-multi-monitor@mazz/po/zh_CN.po
> Add translation support for Window list for multi monitors

- usertile@uszaty/files/applet.js
- usertile@uszaty/files/po/usertile@uszaty.pot
- usertile@uszaty/files/po/zh_CN.po
> Add translation support for UserTile Applet

- update-manager@rotten1.org/files/update-manager@rotten1.org/applet.js
- update-manager@rotten1.org/files/update-manager@rotten1.org/po/update-manager@rotten1.org.pot
- update-manager@rotten1.org/files/update-manager@rotten1.org/po/zh_CN.po
> Add translation support for Update Manager

- ThemeRefresh@JosephM/files/ThemeRefresh@JosephM/applet.js
- ThemeRefresh@JosephM/files/ThemeRefresh@JosephM/po/ThemeRefresh@JosephM.pot
- ThemeRefresh@JosephM/files/ThemeRefresh@JosephM/po/zh_CN.po
> Add translation support for Reload Current Theme

- system-monitor@ebbes/files/system-monitor@ebbes/po/system-monitor@ebbes.pot
- system-monitor@ebbes/files/system-monitor@ebbes/po/zh_CN.po
> Update translation for System Monitor

- MessagingMenuV3@blub/files/MessagingMenuV3@blub/applet.js
- MessagingMenuV3@blub/files/MessagingMenuV3@blub/po/MessagingMenuV3@blub.pot
- MessagingMenuV3@blub/files/MessagingMenuV3@blub/po/zh_CN.po
> Add translation support for Messaging Menu V3

- localip@mrieracrespi/files/localip@mrieracrespi/applet.js
- localip@mrieracrespi/files/localip@mrieracrespi/po/localip@mrieracrespi.pot
- localip@mrieracrespi/files/localip@mrieracrespi/po/zh_CN.po
> Add translation support for Local IPs

- ioDisk@ctrlesc/files/ioDisk@ctrlesc/applet.js
- ioDisk@ctrlesc/files/ioDisk@ctrlesc/po/ioDisk@ctrlesc.pot
- ioDisk@ctrlesc/files/ioDisk@ctrlesc/po/zh_CN.po
> Add translation support for Disk Utilization

- extensions@dalcde/files/extensions@dalcde/applet.js
- extensions@dalcde/files/extensions@dalcde/po/extensions@dalcde.pot
- extensions@dalcde/files/extensions@dalcde/po/zh_CN.po
> Add translation support for Extensions Manager

- gmail@lauritsriple/files/gmail@lauritsriple/applet.js
- gmail@lauritsriple/files/gmail@lauritsriple/po/gmail@lauritsriple.pot
- gmail@lauritsriple/files/gmail@lauritsriple/po/zh_CN.po
> Add translation support for GmailNotifier

- rwall@typicalfoobar/files/rwall@typicalfoobar/applet.js
- rwall@typicalfoobar/files/rwall@typicalfoobar/po/rwall@typicalfoobar.pot
- rwall@typicalfoobar/files/rwall@typicalfoobar/po/zh_CN.po
> Add translation support for rwall

- windowTitle@rymate1234/files/windowTitle@rymate1234/applet.js
- windowTitle@rymate1234/files/windowTitle@rymate1234/po/windowTitle@rymate1234.pot
- windowTitle@rymate1234/files/windowTitle@rymate1234/po/zh_CN.po
> Add translation support for Window Title Applet

- serviceLauncher@hulygun/files/applet.js
- serviceLauncher@hulygun/files/po/serviceLauncher@hulygun.pot
- serviceLauncher@hulygun/files/po/zh_CN.po
> Update translation for Service Launcher

- betterplaces@dewman12/files/betterplaces@dewman12/applet.js
- betterplaces@dewman12/files/betterplaces@dewman12/po/betterplaces@dewman12.pot
- betterplaces@dewman12/files/betterplaces@dewman12/po/zh_CN.po
> Add translation support for Better Places

- back-up_state@natsakis.com/files/applet.js
- back-up_state@natsakis.com/files/po/back-up_state@natsakis.com.pot
- back-up_state@natsakis.com/files/po/zh_CN.po
> Update translation for Back-up State

- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/zh_CN.po
> Update Chinese translation for Multi-Core System Monitor

- system-monitor@pixunil/files/system-monitor@pixunil/po/sv.po
> system-monitor@pixunil: sv.po

- stackoverflow-questions-notifier@higuaro/files/stackoverflow-questions-notifier@higuaro/applet.js
- stackoverflow-questions-notifier@higuaro/files/stackoverflow-questions-notifier@higuaro/po/stackoverflow-questions-notifier@higuaro.pot
- stackoverflow-questions-notifier@higuaro/files/stackoverflow-questions-notifier@higuaro/po/zh_CN.po
> Add translation support for Stackoverflow Questions Notifier

- cwgMintMenu@clockworkgobin.org/files/cwgMintMenu@clockworkgobin.org/applet.js
- cwgMintMenu@clockworkgobin.org/files/cwgMintMenu@clockworkgobin.org/po/cwgMintMenu@clockworkgobin.org.pot
- cwgMintMenu@clockworkgobin.org/files/cwgMintMenu@clockworkgobin.org/po/zh_CN.po
> Add translation support for cwgMintMenu

- launchers-draggable-switch@r0p01ach/files/launchers-draggable-switch@r0p01ach/applet.js
- launchers-draggable-switch@r0p01ach/files/launchers-draggable-switch@r0p01ach/po/launchers-draggable-switch@r0p01ach.pot
- launchers-draggable-switch@r0p01ach/files/launchers-draggable-switch@r0p01ach/po/zh_CN.po
> Add translation support for Launchers Draggable Switch

- tfmKeyboard@alexpp/files/tfmKeyboard@alexpp/po/tfmKeyboard@alexpp.pot
- tfmKeyboard@alexpp/files/tfmKeyboard@alexpp/po/zh_CN.po
> Add Chinese translation for Transformice helper

- download-and-upload-speed@cardsurf/README.md
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletConstants.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletGui.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/cssStylization.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/dates.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/files.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/filesCsv.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/metadata.json
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/download-and-upload-speed@cardsurf.pot
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/sv.po
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/zh_CN.po
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/settings-schema.json
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/shellUtils.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/translation.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/translation.sh
[Changelog](https://github.com/cardsurf/download-and-upload-speed/blob/master/CHANGELOG.md)
> [download-and-upload-speed@cardsurf] Updated version to 1.4.0

- AutostartPrograms@spacy01/files/AutostartPrograms@spacy01/applet.js
- AutostartPrograms@spacy01/files/AutostartPrograms@spacy01/po/AutostartPrograms.pot
- AutostartPrograms@spacy01/files/AutostartPrograms@spacy01/po/bg.po
- AutostartPrograms@spacy01/files/AutostartPrograms@spacy01/po/zh_CN.po
> Update translation for Autostart programs

- text-to-speech-applet@cardsurf/README.md
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/applet.js
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/appletGui.js
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/clipboard.js
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/metadata.json
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/po/text-to-speech-applet@cardsurf.pot
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/po/zh_CN.po
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/settings-schema.json
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/shellUtils.js
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/translation.js
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/translation.sh
[Changelog](https://github.com/cardsurf/text-to-speech-applet/blob/master/CHANGELOG.md)
> [text-to-speech-applet@cardsurf] Updated version to 1.1.0

- netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/po/hr.po
> netusagemonitor@pdcurtis-hr.po add hr.po

- sound-with-apps-volume@koutch/files/sound-with-apps-volume@koutch/po/sv.po
> sound-with-apps-volume@koutch: add sv.po

- montrer-le-bureau@cannelle.org/files/montrer-le-bureau@cannelle.org/po/zh_CN.po
> Add Chinese translation for Show or record desktop

- placesCenter@scollins/files/placesCenter@scollins/po/sv.po
> placesCenter@scollins: add sv.po

- placesCenter@scollins/files/placesCenter@scollins/po/placesCenter.pot
Add missing strings and fix some errors
> placesCenter@scollins: update pot file

- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/ConfigSettings.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/DataProviders.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/ErrorApplet.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/Graphs.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/SpawnProcess.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/applet.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/prefs.js
@ccadeptic23
Edit: This has more issues than using block scoped constants. Applet loads when added to the panel, but not when Cinnamon restarts.
```
error t=2017-04-29T21:17:56.493Z [boxed instance proxy GIName:GLib.Error jsobj@0x7fd67ce362e0 native@0x55bfab97ec50]
error t=2017-04-29T21:17:56.493Z [Applet "multicore-sys-monitor@ccadeptic23"]: Failed to load applet: multicore-sys-monitor@ccadeptic23/29
```
Edit 2:
GTop init error was worked around by partially deferring the initialization. Removed the huge try-catch blocks and cleaned up formatting.
> multicore-sys-monitor@ccadeptic23: Apply 3.4 fixes, clean up white space

- officeCenter@scollins/files/officeCenter@scollins/po/sv.po
> officeCenter@scollins: add sv.po

- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/applet.js
Fixes an [issue](https://github.com/linuxmint/cinnamon-spices-applets/pull/519#issuecomment-298247613).
> [brightness-and-gamma-applet@cardsurf] Declared a variable once

- temperature@fevimu/files/temperature@fevimu/po/ru.po
- temperature@fevimu/files/temperature@fevimu/po/ru_RU.po
New Russian translation for temperature@fevimu
> temperature@fevimu: ru_RU po

- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/GPasteHistoryItem.js
- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/GPasteNotInstalledDialog.js
- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/applet.js
- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/metadata.json
- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/de.po
- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/hr.po
- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/localization.pot
- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/zh_CN.po
Closes #370 
@giwhub, @muzena: There are two new strings you may want to translate.
> gpaste-reloaded@feuerfuchs.eu: Display fallback if GPaste daemon is missing

- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/applet.js
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/appletGui.js
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/brightness-and-gamma-applet@cardsurf.pot
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/zh_CN.po
> Add translation support for Brightness and gamma applet

- placesCenter@scollins/files/placesCenter@scollins/po/zh_CN.po
> Update Chinese translation for Places Center

- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/sv.po
Add Swedish translation. Hope this is okay, because I wasn't allowed to upload to this repo at Launchpad.
> CinnVIIStarkMenu@NikoKrause: add sv.po

- vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/po/sv.po
> vboxlauncher@mockturtl: add sv.po

- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/applet.js
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/settings-schema.json
[Feature request description](https://github.com/cardsurf/brightness-and-gamma-applet/issues/1)
> [brightness-and-gamma-applet@cardsurf] Adjust brightness on scroll

- feeds@jonbrettdev.wordpress.com/CHANGELOG
- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/ConfigFileManager.py
- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/applet.js
- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/manage_feeds.py
- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/metadata.json
Resolved path issues with reading feeds.json file.
Now require python 3 for better unicode support.
> feeds@jonbrettdev.wordpress.com - Resolved path issues 

- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ru.po
Small update. Add trailing spaces when needed.
> multicore-sys-monitor@ccadeptic23: update ru.po

- scripts@paucapo.com/files/scripts@paucapo.com/applet.js
I have put the sort function of javascript to sort arrays (dirs and files). See lines 189 e 201.
> sort dir and files

- force-quit@cinnamon.org/files/force-quit@cinnamon.org/applet.js
- force-quit@cinnamon.org/files/force-quit@cinnamon.org/po/force-quit@cinnamon.org.pot
- force-quit@cinnamon.org/files/force-quit@cinnamon.org/po/zh_CN.po
> Add translation support for Force Quit

- stocks@adonut/files/stocks@adonut/applet.js
- stocks@adonut/files/stocks@adonut/po/stocks@adonut.pot
- stocks@adonut/files/stocks@adonut/po/zh_CN.po
> Add translation support for stocks

- separator2@zyzz/files/separator2@zyzz/applet.js
- separator2@zyzz/files/separator2@zyzz/po/separator2@zyzz.pot
- separator2@zyzz/files/separator2@zyzz/po/zh_CN.po
> Add translation support for Separator2

- lorem@vxstorm/files/lorem@vxstorm/applet.js
- lorem@vxstorm/files/lorem@vxstorm/po/lorem@vxstorm.pot
- lorem@vxstorm/files/lorem@vxstorm/po/zh_CN.po
> Add translation support for Lorem Pastesum

- weather@mockturtl/files/weather@mockturtl/po/ru.po
- changed Horizon to sort of Length for better context
- add 3 untranslated items
> weather@mockturtl: update ru.po

- CinnVIIStarkMenu@NikoKrause/README.md
- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/3.2/applet.js
- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/metadata.json
closes https://github.com/linuxmint/cinnamon-spices-applets/issues/619
> CinnVIIStarkMenu@NikoKrause: version 1.5

- printers@linux-man/files/printers@linux-man/po/sv.po
> printers@linux-man: add sv.po

- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/sv.po
> gpaste-reloaded@feuerfuchs.eu: add sv.po

- CinnVIIStarkMenu@NikoKrause/README.md
- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/3.2/applet.js
- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/metadata.json
- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/CinnVIIStarkMenu.pot
- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/cs.po
- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/de.po
- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/es.po
- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/fr.po
- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/hr.po
- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/ku.po
- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/pt.po
- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/ru.po
- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/sr.po
- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/sv.po
- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/zh_CN.po
improved recent files handling
improved vectorbox for categories
updated l10n
> CinnVIIStarkMenu@NikoKrause: version 1.7

- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/applet.js
- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/po/feeds.pot
- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/po/sv.po
> feeds@jonbrettdev.wordpress.com: add sv.po

- IcingTaskManager@json/files/IcingTaskManager@json/po/sv.po
Line 21 metadata do not translate:
`#. src->metadata.json->description`
> IcingTaskManager@json: add sv.po

- windowlist@cobinja.de/files/windowlist@cobinja.de/po/zh_CN.po
> Add Chinese translation for CobiWindowList

- IcingTaskManager@json/files/IcingTaskManager@json/po/default.pot
- IcingTaskManager@json/files/IcingTaskManager@json/po/sv.po
Fixed error and add missing strings
> IcingTaskManager@json: fix translation error

- commandLauncher@scollins/files/commandLauncher@scollins/po/sv.po
> commandLauncher@scollins: add sv.po

- netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/po/zh_CN.po
> Update Chinese translation for Network Data Usage Monitor

- temperature@fevimu/files/temperature@fevimu/po/sv.po
> temperature@fevimu: add sv.po

- stopwatch@pdcurtis/files/stopwatch@pdcurtis/po/sv.po
> stopwatch@pdcurtis: add sv.po

- sessionManager@scollins/files/sessionManager@scollins/po/sv.po
> sessionManager@scollins: add sv.po

- MessagingMenuV3@blub/files/MessagingMenuV3@blub/po/sv.po
> MessagingMenuV3@blub: add sv.po

- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/po/sv.po
> collapsible-systray@feuerfuchs.eu: add sv.po

- calendar@simonwiles.net/files/calendar@simonwiles.net/applet.js
- calendar@simonwiles.net/files/calendar@simonwiles.net/po/de.po
- calendar@simonwiles.net/files/calendar@simonwiles.net/world_clock_calendar_settings.py
- calendar@simonwiles.net/info.json
> calendar@simonwiles.net: fix author name and add German translation

- calendar@simonwiles.net/files/calendar@simonwiles.net/po/sv.po
Add Swedish translation.
**Bug:**
Line 53 "#: world_clock_calendar_settings.py:214" do not translate
> calendar@simonwiles.net: add sv.po

- show-hide-applets@mohammad-sn/files/show-hide-applets@mohammad-sn/po/sv.po
> show-hide-applets@mohammad-sn: add sv.po

- search@bownz/files/search@bownz/po/sv.po
> search@bownz: add sv.po

- places-with-terminal@mtwebster/files/places-with-terminal@mtwebster/po/sv.po
> places-with-terminal@mtwebster: add sv.po

- clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/po/sv.po
> clipboard-qr@wrouesnel: add sv.po

- multicore-sys-monitor@ccadeptic23/.gitignore
- multicore-sys-monitor@ccadeptic23/README.md
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/ConfigSettings.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/Graphs.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/applet.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/prefs.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/prefsui.glade
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/ConfigSettings.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/Graphs.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/applet.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/prefs.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/prefsui.glade
- multicore-sys-monitor@ccadeptic23/gulpfile.js
- multicore-sys-monitor@ccadeptic23/info.json
- multicore-sys-monitor@ccadeptic23/package.json
- Added a setting for changing the label color.
- Changed the author in info.json to jaszhix.
- Added a gulpfile for hot reloading (dev).
- Updated the readme.
Tested in Cinnamon 3.2/3.4, with and without fresh settings.
Closes #607
> multicore-sys-monitor@ccadeptic23: 1.6.0 [abandoned]

- ScreenShot+RecordDesktop@tech71/info.json
- ScreenShot@tech71/info.json
- acerhk-ctl@mcnielcho.org/info.json
- ctrl4docker@hoffis-eck.de/info.json
- devutils@fogl/info.json
- gputemperature@silentage.com/info.json
- host-entries@hoffis-eck.de/info.json
- ink-level-monitor@r0p01ach/info.json
- ioDisk@ctrlesc/info.json
- launchers-draggable-switch@r0p01ach/info.json
- localip@mrieracrespi/info.json
- lorem@vxstorm/info.json
- mem-monitor-text@datanom.net/info.json
- menu@csknet.org/info.json
- places-system-menu@fogl/info.json
- sane-menu@nooulaif/info.json
- shutdown-timer@webum.by/info.json
- softyubikey@yubiserver.include.gr/info.json
- synapse@ctolly/info.json
- todo@threefi/info.json
- update-manager@rotten1.org/info.json
set authors name to `none`, because those usernames do not respond to any GitHub user
> 21 applets: nonexistent GitHub usernames

- Cinnamenu@json/files/Cinnamenu@json/po/sv.po
These lines are correct in .pot file, but do not translate:
```
#: panel.js:1800
#: panel.js:1823
#: panel.js:1579
#: panel.js:1582
```
> Cinnamenu@json: add sv.po

- desktopiconsize@lotsrc/files/desktopiconsize@lotsrc/po/sv.po
> desktopiconsize@lotsrc: add sv,po

- sysmonitor@orcus/info.json
> sysmonitor@orcus: fix author name

- github-projects@morgan-design.com/files/github-projects@morgan-design.com/applet.js
- github-projects@morgan-design.com/files/github-projects@morgan-design.com/po/github-projects.pot
- github-projects@morgan-design.com/files/github-projects@morgan-design.com/po/sv.po
Enable notification messages for translation
Add missing notification strings to translation template
> github-projects@morgan-design.com: update applet.js

- CommandRunner@appdevsw/info.json
- Favorites@bownz/info.json
- HabitRPGApplet/info.json
- PDFManager@cinnamon.org/info.json
- QuitApplet@bownz/info.json
- SettingsPlus@lusito.info/info.json
- ThemeRefresh@JosephM/info.json
- TouchpadIndicatorClassic@lusito.info/info.json
- UserMenuV2@bownz/info.json
- Window-List-Hotkey@HenryNugraha/info.json
- back-up_state@natsakis.com/info.json
- betterplaces@bownz/info.json
- betterplaces@dewman12/info.json
- bettersettings@bownz/info.json
- cinnamon-multi-line-taskbar-applet/info.json
- cinnamon-utils-menu@pithdillinja/info.json
- cwgMintMenu@clockworkgobin.org/info.json
- diaspora-notif@douze12/info.json
- extensions@dalcde/info.json
- force-quit@cinnamon.org/info.json
- ifstat@tagadan/info.json
- montrer-le-bureau@cannelle.org/info.json
- path-monitor@kamikaze/info.json
- places-bookmarks@dmo60.de/info.json
- places@tycho/info.json
- search@bownz/info.json
- sports-update@pavanred/info.json
- titleBar@errt/info.json
- vnstat@linuxmint.com/info.json
- window-list@mdcb.github/info.json
> Donated applets: set authors to none

- hwmonitor@sylfurd/files/hwmonitor@sylfurd/po/sv.po
> hwmonitor@sylfurd: add sv.po

- SW++@mohammad-sn/files/SW++@mohammad-sn/po/sv.po
> SW++@mohammad-sn: add sv.po

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE
explain how to notify the author
> Spices Repo: update CONTRIBUTING and ISSUE_TEMPLATE

- windows-quick-list-with-close-button@koutch/files/windows-quick-list-with-close-button@koutch/po/sv.po
> windows-quick-list-with-close-button@koutch: add sv.po

- search-box@mtwebster/files/search-box@mtwebster/po/sv.po
> search-box@mtwebster: add sv.po

- graphicsCenter@scollins/files/graphicsCenter@scollins/po/sv.po
> graphicsCenter@scollins: add sv.po

- montrer-le-bureau@cannelle.org/files/montrer-le-bureau@cannelle.org/po/sv.po
> montrer-le-bureau@cannelle.org: add sv.po

- WindowListGroup@jake.phy@gmail.com/files/WindowListGroup@jake.phy@gmail.com/metadata.json
- WindowListGroup@jake.phy@gmail.com/info.json
This is being marked abandoned so others can improve it if they'd like.
Closes #114
> WindowListGroup@jake.phy@gmail.com: Limit support to Cinnamon 2.6-3.0, set author to none

- back-up_state@natsakis.com/files/po/sv.po
> back-up_state@natsakis.com: add sv.po

- sane-menu@nooulaif/files/po/sv.po
> sane-menu@nooulaif: add sv.po

- workspace-grid@hernejj/files/workspace-grid@hernejj/po/sv.po
> workspace-grid@hernejj: add sv.po

- rwall@typicalfoobar/files/rwall@typicalfoobar/po/sv.po
> rwall@typicalfoobar: add sv.po

- mybookmarks@markbokil.com/files/mybookmarks@markbokil.com/po/sv.po
> mybookmarks@markbokil.com: add sv.po

- CustomApplicationsMenu@LLOBERA/files/CustomApplicationsMenu@LLOBERA/po/sv.po
> CustomApplicationsMenu@LLOBERA: add sv.po

- batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/applet.js
- batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/batterymonitor.pot
- batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/sv.po
> batterymonitor@pdcurtis: add sv.po

- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/metadata.json
Continuation of #680 to investigate why there are issues for some people on Cinnamon 3.4.
> collapsible-systray@feuerfuchs.eu: Mark as compatible with Cinnamon 3.4

- location-detection@heimdall/files/location-detection@heimdall/applet.js
- location-detection@heimdall/files/location-detection@heimdall/po/de.po
- location-detection@heimdall/files/location-detection@heimdall/po/location-detection@heimdall.pot
- location-detection@heimdall/files/location-detection@heimdall/settings-schema.json
@heimdall
Added settings to applet, so the user can easily register on IPInfoDB and set/use his own API key.
And updated translation files.
> location-detection@heimdall: add ability to set API key in Settings

- bettersettings@bownz/files/bettersettings@bownz/po/sv.po
> bettersettings@bownz: add sv.po

- places-bookmarks@dmo60.de/files/places-bookmarks@dmo60.de/po/sv.po
> places-bookmarks@dmo60.de: add sv.po

- todo@threefi/files/todo@threefi/po/sv.po
> todo@threefi: add sv.po

- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/CSCollapseBtn.js
- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/applet.js
- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/metadata.json
- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/po/de.po
- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/po/localization.pot
Fixing the errors and usability problems described here: https://github.com/linuxmint/cinnamon-spices-applets/pull/710#issuecomment-302641766
> collapsible-systray@feuerfuchs.eu: Fix St-CRITICAL warnings; more user-friendly behavior if there are no icons to hide/reveal

- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/po/sv.po
> collapsible-systray@feuerfuchs.eu: update sv.po

- UserMenuV2@bownz/files/UserMenuV2@bownz/po/sv.po
> UserMenuV2@bownz: add sv.po

- location-detection@heimdall/files/location-detection@heimdall/po/sv.po
> location-detection@heimdall: add sv.po

- usertile@uszaty/files/po/sv.po
> usertile@uszaty: add sv.po

- pa-equalizer@jschug.com/files/pa-equalizer@jschug.com/applet.js
Sorry for the noise caused by my previous pull request (https://github.com/linuxmint/cinnamon-spices-applets/pull/739) where I mixed two different, unrelated changesets. I hope to do it right this time
> pa-equalizer@jschug.com: Fix #208, #738 and some other minor problems

- mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/sv.po
> mailnagapplet@ozderya.net: add sv.po

- CommandRunner@appdevsw/files/CommandRunner@appdevsw/po/sv.po
> CommandRunner@appdevsw: add sv.po

- bash-sensors@pkkk/files/bash-sensors@pkkk/po/sv.po
> bash-sensors@pkkk: add sv.po

- mem-monitor-text@datanom.net/files/mem-monitor-text@datanom.net/po/sv.po
> mem-monitor-text@datanom.net: add sv.po

- mylauncher@markbokil.com/files/mylauncher@markbokil.com/po/sv.po
> mylauncher@markbokil.com: add sv.po

- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/brightness-and-gamma-applet@cardsurf.pot
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/sv.po
Add missing strings to brightness-and-gamma-applet@cardsurf.pot
> brightness-and-gamma-applet@cardsurf: add sv.po

- vnstat@linuxmint.com/files/vnstat@linuxmint.com/po/sv.po
> vnstat@linuxmint.com: add sv.po

- ink-level-monitor@r0p01ach/files/ink-level-monitor@r0p01ach/po/sv.po
> ink-level-monitor@r0p01ach: add sv.po

- smallcalc_applet@lerc.sds/files/smallcalc_applet@lerc.sds/po/sv.po
> smallcalc_applet@lerc.sds: add sv.po

- gmail@lauritsriple/files/gmail@lauritsriple/po/sv.po
> gmail@lauritsriple: add sv.po

- ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/po/sv.po
> ShutdownMenuWithIcons@LLOBERA: add sv.po

- ShutdownApplet@DeathMD/files/ShutdownApplet@DeathMD/po/sv.po
> ShutdownApplet@DeathMD: add sv.po

- profile-switcher@pixunil/files/profile-switcher@pixunil/po/sv.po
> profile-switcher@pixunil: add sv.po

- weather@mockturtl/files/weather@mockturtl/applet.js
- weather@mockturtl/files/weather@mockturtl/po/sv.po
> weather@mockturtl: update sv.po

- cpufreq@mtwebster/files/cpufreq@mtwebster/applet.js
- cpufreq@mtwebster/files/cpufreq@mtwebster/panelMenu.js
Adds the missing PanelMenu class, so the applet runs on Cinnamon 3.4.
> cpufreq@mtwebster: Add PanelMenu

- xampp-panel@backids99/files/xampp-panel@backids99/po/sv.po
> xampp-panel@backids99: add sv.po

- betterlock/files/betterlock/po/sv.po
> betterlock: add sv.po

- separator2@zyzz/files/separator2@zyzz/po/sv.po
> separator2@zyzz: add sv.po

- slingshot@jfarthing84/files/po/sv.po
> slingshot@jfarthing84: add sv.po

- screen-inhibit@mtwebster/files/po/sv.po
> screen-inhibit@mtwebster: add sv.po

- web-developer-menu@infiniteshroom/files/po/sv.po
> web-developer-menu@infiniteshroom: add sv.po

- gputemperature@silentage.com/files/gputemperature@silentage.com/po/sv.po
> gputemperature@silentage.com: add sv.po

- batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/ru.po
> batterymonitor@pdcurtis: Added Russian translation

- 0dyseus@ExtensionsManager/CHANGE_LOG.md
- 0dyseus@ExtensionsManager/files/0dyseus@ExtensionsManager/po/zh_CN.po
- Updated Chinese localization.
> Desktop Handler (0dyseus@DesktopHandler) update

- 0dyseus@WallpaperChangerApplet/CHANGE_LOG.md
- 0dyseus@WallpaperChangerApplet/files/0dyseus@WallpaperChangerApplet/po/zh_CN.po
- Updated Chinese localization.
> Wallpaper Changer (0dyseus@WallpaperChangerApplet) update

- turn-off-monitor@zablotski/files/turn-off-monitor@zablotski/po/sv.po
> turn-off-monitor@zablotski: add sv.po

- workspace-name@willurd/files/workspace-name@willurd/po/sv.po
> workspace-name@willurd: add sv.po

- suspend@janax/files/suspend@janax/po/sv.po
> suspend@janax: add sv.po

- ioDisk@ctrlesc/files/ioDisk@ctrlesc/po/sv.po
> ioDisk@ctrlesc: add sv.po

- brightness@markbokil.com/files/brightness@markbokil.com/po/sv.po
> brightness@markbokil.com: add sv.po

- binaryclock@entelechy/files/binaryclock@entelechy/po/sv.po
> binaryclock@entelechy: add sv.po

- windowlist@cobinja.de/files/windowlist@cobinja.de/po/sv.po
> windowlist@cobinja.de: add sv.po

- timeout@narutrey/files/timeout@narutrey/po/sv.po
> timeout@narutrey: add sv.po

- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/po/sv.po
> text-to-speech-applet: add sv.po

- ScreenShot@tech71/files/ScreenShot@tech71/po/sv.po
> ScreenShot@tech71: add sv.po

- vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/po/pl.po
> vboxlauncher@mockturtl: Add pl.po

- netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/po/sv.po
> netusagemonitor@pdcurtis: add sv.po

- devutils@fogl/files/devutils@fogl/po/sv.po
> devutils@fogl: add sv.po

- sysmonitor@orcus/files/sysmonitor@orcus/po/sv.po
> sysmonitor@orcus: add sv.po

- ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/po/sv.po
> ScreenShot+RecordDesktop@tech71: add sv.po

- restart-cinnamon@kolle/files/restart-cinnamon@kolle/po/sv.po
> restart-cinnamon@kolle: add sv.po

- cheaty@centurix/files/cheaty@centurix/po/sv.po
> cheaty@centurix: add sv.po

- serviceLauncher@hulygun/files/po/sv.po
> serviceLauncher@hulygun: add sv.po

- IcingWindowSaver@json/files/po/sv.po
> IcingWindowSaver@json: add sv.po

- force-quit@cinnamon.org/files/force-quit@cinnamon.org/po/sv.po
> force-quit@cinnamon.org: add sv.po

- color-picker@fmete/files/color-picker@fmete/po/sv.po
> color-picker@fmete: add sv.po

- AutostartPrograms@spacy01/files/AutostartPrograms@spacy01/po/sv.po
> AutostartPrograms@spacy01: add sv.po

- cpu-monitor-text@gnemonix/files/cpu-monitor-text@gnemonix/po/sv.po
> cpu-monitor-text@gnemonix: add sv.po

- logout@martin/files/logout@martin/po/sv.po
> logout@martin: add sv.po

- nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/po/sv.po
> nvidiaprime@pdcurtis: add sv.po

- path-monitor@kamikaze/files/path-monitor@kamikaze/po/sv.po
> path-monitor@kamikaze: add sv.po

- QuitApplet@bownz/files/QuitApplet@bownz/po/sv.po
> QuitApplet@bownz: add sv.po

- netctlstatus@prmurthy/files/netctlstatus@prmurthy/po/sv.po
> netctlstatus@prmurthy: add sv.po

- lookingglass-restart@markbokil.com/files/lookingglass-restart@markbokil.com/po/sv.po
> lookingglass-restart@markbokil.com: add sv.po

- diaspora-notif@douze12/files/diaspora-notif@douze12/po/av.po
> diaspora-notif@douze12: add sv.po

- ctrl4docker@hoffis-eck.de/files/ctrl4docker@hoffis-eck.de/po/sv.po
> ctrl4docker@hoffis-eck.de: add sv.po

- computer@brownsr/files/computer@brownsr/po/sv.po
> computer@brownsr: add sv.po

- toggle_LookingGlass@kolle/files/toggle_LookingGlass@kolle/po/sv.po
> toggle_LookingGlass@kolle: add sv.po

- ThemeRefresh@JosephM/files/ThemeRefresh@JosephM/po/sv.po
> ThemeRefresh@JosephM: add sv.po

- stackoverflow-questions-notifier@higuaro/files/stackoverflow-questions-notifier@higuaro/po/sv.po
> stackoverflow-questions-notifier@higuaro: add sv.po

- power-off@martin/files/power-off@martin/po/sv.po
> power-off@martin: add sv.po

- windowTitle@rymate1234/files/windowTitle@rymate1234/po/sv.po
> windowTitle@rymate1234: add sv.po

- windowTitle2@hanspr/files/windowTitle2@hanspr/po/sv.po
> windowTitle2@hanspr: add sv.po

- Window-List-Hotkey@HenryNugraha/files/Window-List-Hotkey@HenryNugraha/po/sv.po
> Window-List-Hotkey@HenryNugraha: add sv.po

- host-entries@hoffis-eck.de/files/po/sv.po
> host-entries@hoffis-eck.de: add sv.po

- hamster@projecthamster.wordpress.com/files/hamster@projecthamster.wordpress.com/applet.js
> hamster@projecthamster.wordpress.com: fix let redeclaration

- uptime@vatanuki.kun/files/uptime@vatanuki.kun/po/sv.po
> uptime@vatanuki.kun: add sv.po

- pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/sv.po
> pomodoro@gregfreeman.org: add sv.po

- hamster@projecthamster.wordpress.com/files/hamster@projecthamster.wordpress.com/po/sv.po
> hamster@projecthamster.wordpress.com: add sv.po

- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/Graphs.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/applet.js
> multicore-sys-monitor@ccadeptic23: Move prefs.json to ~/.cinnamon/configs

- slingshot@jfarthing84/files/applet.js
@jfarthing84 this fixes the applet for Cinnamon 3.4
> slingshot@jfarthing84: fix redeclaration of let for Cinnamon 3.4

- windowlist@cobinja.de/files/windowlist@cobinja.de/3.2/applet.js
- windowlist@cobinja.de/files/windowlist@cobinja.de/3.2/settings-schema.json
- windowlist@cobinja.de/files/windowlist@cobinja.de/po/de.po
- windowlist@cobinja.de/files/windowlist@cobinja.de/po/windowlist@cobinja.de.pot
This adds an option to close windows from the previews popup menu, it defaults to false.
> windowlist@cobinja.de Add option to close windows with middle click

- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletGui.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/translation.js
Added an option to update a list of network interfaces.
> [download-and-upload-speed@cardsurf] Update network interfaces

- nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/CHANGELOG.md
- nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/README.md
- nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/applet.js
- nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/changelog.txt
- nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/metadata.json
- nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/po/nvidiaprime.pot
* Updates to some tooltips and README.md to reflect the changes in v3.3.1 better.
* Update nvidiaprime.pot to identify changes which may need to be translated.
@muzena @eson57 @giwhub Many thanks for your previous translations for this applet.
> nvidiaprime@pdcurtis Update to Version 3.3.2

- nvidiaprime@pdcurtis/files/nvidiaprime@pdcurtis/po/sv.po
> nvidiaprime@pdcurtis: Update sv.po

- IcingTaskManager@json/CHANGELOG.md
- IcingTaskManager@json/files/IcingTaskManager@json/__init__.js
- IcingTaskManager@json/files/IcingTaskManager@json/appGroup.js
- IcingTaskManager@json/files/IcingTaskManager@json/appList.js
- IcingTaskManager@json/files/IcingTaskManager@json/applet.js
- IcingTaskManager@json/files/IcingTaskManager@json/metadata.json
- IcingTaskManager@json/files/IcingTaskManager@json/specialButtons.js
- IcingTaskManager@json/files/IcingTaskManager@json/specialMenus.js
- IcingTaskManager@json/files/IcingTaskManager@json/timers.js
* Added support for Cinnamon's minimize animation positioning.
* Improved timer handling.
* Fixed orphan St.Label errors.
> Icing Task Manager: v4.6.0

- officeCenter@scollins/files/officeCenter@scollins/po/tr.po
officeCenter@scollins: Added Turkish Translation
> officeCenter@scollins: Added Turkish Translation

- xampp-panel@backids99/files/xampp-panel@backids99/po/tr.po
xampp-panel@backids99: Added Turkish Translation
> xampp-panel@backids99: Added Turkish Language

- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/tr.po
brightness-and-gamma-applet@cardsurf: Added Turkish Translation
> brightness-and-gamma-applet@cardsurf: Added Turkish Translation

- sysmonitor@orcus/files/sysmonitor@orcus/applet.js
> sysmonitor@orcus: Launch settings with cjs instead of gjs

- brightness@markbokil.com/info.json
- lookingglass-restart@markbokil.com/info.json
- mybookmarks@markbokil.com/info.json
- mylauncher@markbokil.com/info.json
- timer-notifications@markbokil.com/info.json
the author @mbokil does not respond
set author to none for his 5 applets
> 5 applets: set author mbokil to none

- Cinnamenu@json/CHANGELOG.md
- Cinnamenu@json/files/Cinnamenu@json/applet.js
- Cinnamenu@json/files/Cinnamenu@json/buttons.js
- Cinnamenu@json/files/Cinnamenu@json/metadata.json
- Cinnamenu@json/files/Cinnamenu@json/settings-schema.json
* Changed the default column count to 4.
* Improved the context menu positioning.
> Cinnamenu: Update to 2.0.1

- multicore-sys-monitor@ccadeptic23/README.md
> multicore-sys-monitor@ccadeptic23: Add instructions to readme for upgrading to Cinnamon 3.4

- sound-with-apps-volume@koutch/files/sound-with-apps-volume@koutch/applet.js
> sound-with-apps-volume@koutch: Fix startup crash

- IcingTaskManager@json/CHANGELOG.md
- IcingTaskManager@json/README.md
- IcingTaskManager@json/files/IcingTaskManager@json/metadata.json
- IcingTaskManager@json/files/IcingTaskManager@json/settings-schema.json
- IcingTaskManager@json/files/IcingTaskManager@json/specialButtons.js
[Issue](https://github.com/jaszhix/icingtaskmanager/issues/125)
> IcingTaskManager@json: Fix icon sizing in high DPI mode

- 0dyseus@ArgosForCinnamon/README.md
- 0dyseus@ArgosForCinnamon/files/0dyseus@ArgosForCinnamon/HELP.html
- 0dyseus@ArgosForCinnamon/files/0dyseus@ArgosForCinnamon/__init__.js
- 0dyseus@ArgosForCinnamon/files/0dyseus@ArgosForCinnamon/metadata.json
- Commented out the unused TryExec function to prevent a warning.
- Initialization of the PopupSubMenuMenuItem prototype with an empty label to prevent an error that will be caused when a change in Cinnamon gets merged. ¬¬
- Removed font size style from the README header. This style was causing rendering problems on the Spices website.
- Updated help file.
> Argos for Cinnamon (0dyseus@ArgosForCinnamon) update

- localipswithsettings@edaubert/files/localipswithsettings@edaubert/applet.js
- localipswithsettings@edaubert/files/localipswithsettings@edaubert/settings-schema.json
I simply  added the possibility to disable the logs as there were useful during development but introduce to much lines when you are working on another one.
> localipswithsettings@edaubert: Add option to hide logs

- windowlist@cobinja.de/files/windowlist@cobinja.de/po/pl.po
> [windowlist@cobinja.de] Create pl.po

- IcingTaskManager@json/files/IcingTaskManager@json/po/sv.po
> IcingTaskManager@json: Update sv.po

- weather@mockturtl/files/weather@mockturtl/applet.js
> weather@mockturtl: display location in tooltip

- IcingTaskManager@json/files/IcingTaskManager@json/3.2/applet.js
- IcingTaskManager@json/files/IcingTaskManager@json/3.2/specialButtons.js
- IcingTaskManager@json/files/IcingTaskManager@json/3.2/specialMenus.js
- IcingTaskManager@json/files/IcingTaskManager@json/metadata.json
Fixed some bugs that may cause Cinnamon to freeze.
> IcingTaskManager@json: 5.1.1

- mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/ru.po
> Add russian translation for Mailnag notifier.

- Cinnamenu@json/files/Cinnamenu@json/po/ru.po
The msgid "Type to search" is duplicated
> Cinnamenu@json: duplicate msgid in ru.po

- Cinnamenu@json/files/Cinnamenu@json/po/sv.po
The msgid "Type to search..." is duplicated
> Cinnamenu@json: duplicate msgid in sv.po

- IcingTaskManager@json/CHANGELOG.md
- IcingTaskManager@json/files/IcingTaskManager@json/3.2/applet.js
- IcingTaskManager@json/files/IcingTaskManager@json/3.2/settings-schema.json
- IcingTaskManager@json/files/IcingTaskManager@json/3.2/specialButtons.js
- IcingTaskManager@json/files/IcingTaskManager@json/3.2/specialMenus.js
- IcingTaskManager@json/files/IcingTaskManager@json/metadata.json
* Rewrote the hover peek functionality. It now only overlays a single window object on the screen!
* Improved the styling of closed pinned app buttons.
> IcingTaskManager@json: 5.3.0

- axos88@countdown-timer/files/axos88@countdown-timer/po/sv.po
> axos88@countdown-timer: add sv.po

- weather@mockturtl/files/weather@mockturtl/po/sl.po
Added new strings and some minor fixes.
> Updated Slovenian translation for Weather

- redshift@marvel4u/files/redshift@marvel4u/po/tr.po
> redshift@marvel4u: add tr.po

- mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/mailnagapplet@ozderya.net.pot
- mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/ru.po
Fix for russian translation and add few missing strings to template.
> mailnagapplet@ozderya.net: fix for russian translation and template

- Cinnamenu@json/CHANGELOG.md
- Cinnamenu@json/files/Cinnamenu@json/applet.js
- Cinnamenu@json/files/Cinnamenu@json/buttons.js
- Cinnamenu@json/files/Cinnamenu@json/lodash.js
- Cinnamenu@json/files/Cinnamenu@json/metadata.json
* Fixed an error occurring when favorites change before the menu has been opened for the first time.
* Improved signal management.
> Cinnamenu@json: 2.0.2

- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletGui.js
Fixed a bug where an applet size was too large when UI scaling was set to Hi-DPI.
> [download-and-upload-speed@cardsurf] Fixed applet size

- ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/po/sv.po
> ScreenShot+RecordDesktop@tech71: Update sv.po

- redshift@marvel4u/files/redshift@marvel4u/po/tr.po
redshift@marvel4u: update tr.po
>  redshift@marvel4u: update tr.po

- 0dyseus@SimpleToDoList/files/0dyseus@SimpleToDoList/metadata.json
- 0dyseus@SimpleToDoList/files/0dyseus@SimpleToDoList/po/0dyseus@SimpleToDoList.pot
- 0dyseus@SimpleToDoList/files/0dyseus@SimpleToDoList/po/es.po
- 0dyseus@SimpleToDoList/files/0dyseus@SimpleToDoList/po/sv.po
- 0dyseus@SimpleToDoList/files/0dyseus@SimpleToDoList/po/zh_CN.po
- Updated localization template and localizations.
> Simple ToDo List (0dyseus@SimpleToDoList) update

- 0dyseus@window-list-fork/files/0dyseus@window-list-fork/HELP.html
- 0dyseus@window-list-fork/files/0dyseus@window-list-fork/metadata.json
- 0dyseus@window-list-fork/files/0dyseus@window-list-fork/po/cs.po
- 0dyseus@window-list-fork/files/0dyseus@window-list-fork/po/de.po
- 0dyseus@window-list-fork/files/0dyseus@window-list-fork/po/es.po
- 0dyseus@window-list-fork/files/0dyseus@window-list-fork/po/hr.po
- 0dyseus@window-list-fork/files/0dyseus@window-list-fork/po/sv.po
- 0dyseus@window-list-fork/files/0dyseus@window-list-fork/po/zh_CN.po
- Added Czech localization. Thanks to [Radek71](https://github.com/Radek71).
- Updated localization template, localizations and help file.
> Window list (Fork By Odyseus) (0dyseus@window-list-fork) update

- tor-button@shatur/files/tor-button@shatur/metadata.json
- tor-button@shatur/info.json
@Goodevil95 For your reference.
> tor-button@shatur: Remove dangerous flag, correct author

- IcingTaskManager@json/CHANGELOG.md
- IcingTaskManager@json/files/IcingTaskManager@json/3.2/appGroup.js
- IcingTaskManager@json/files/IcingTaskManager@json/3.2/applet.js
- IcingTaskManager@json/files/IcingTaskManager@json/3.2/specialButtons.js
- IcingTaskManager@json/files/IcingTaskManager@json/metadata.json
* Fixed a regression causing pinned unopened icons to have the wrong aspect ratio, or become off-center.
* Fixed the number display still showing "1" after a pinned app is closed when number display is set to Normal or All.
* Fixed the number display not showing on unopened pinned apps when it is set to All.
> IcingTaskManager@json: 5.3.3

- redshift@marvel4u/files/redshift@marvel4u/applet.js
Hello.
Fixed 24px size has not seemed to me a perfect solution, since when you do changes in the panel size the size changes and I think that 24px is a too much big size.
For me this works fine. @jaszhix and @Marvel4U, could you test if it breaks nothing and works totally fine?
I have also changed tabs to spaces in applet.js because they was mixed.
Thanks and regards.
> [redshift@marvel4u] Changed fixed 24px height to sending panelHeight to the applet

- IcingTaskManager@json/files/IcingTaskManager@json/3.2/lodash.js
> IcingTaskManager@json: Re-add mozjs24 fix in lodash.js

- ctrl4docker@hoffis-eck.de/files/ctrl4docker@hoffis-eck.de/HttpSocket.js
> ctrl4docker@hoffis-eck.de: Fix redeclaration of let

- binaryclock@entelechy/files/binaryclock@entelechy/3.2/applet.js
> binaryclock@entelechy: Fix imports for Cinnamon 3.6

- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/CSCollapseBtn.js
- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/applet.js
@feuerfuchs
[PR causing the change](https://github.com/linuxmint/Cinnamon/pull/6790).
> collapsible-systray@feuerfuchs.eu: Fix imports for Cinnamon 3.6

- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/GPasteNewItemDialog.js
- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/GPasteNotInstalledDialog.js
- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/GPasteSearchItem.js
- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/applet.js
> gpaste-reloaded@feuerfuchs.eu: Fix imports for Cinnamon 3.6

- batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/applet.js
- batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/changelog.txt
* Revert change in handling empty battery
> batterymonitor@pdcurtis Update Version 1.3.2

- redshift@marvel4u/files/redshift@marvel4u/applet.js
[redshift@marvel4u] Fix settings window issue related to panelHeight. Fix #1183.
> [redshift@marvel4u] Fix settings window issue related to panelHeight. Fix #1183

- .github/LICENSES/LGPL-2.1
- .github/LICENSES/LGPL-3.0
- .github/LICENSES/README.md
LGPL-2.1 is used in this theme https://github.com/linuxmint/cinnamon-spices-themes/blob/master/Eleganse/files/Eleganse/cinnamon/cinnamon.css
> LICENSES: Add LGPL-2.1 and LGPL-3.0 licenses

- netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/CHANGELOG.md
- netusagemonitor@pdcurtis/files/netusagemonitor@pdcurtis/applet.js
* Changes in initialisation to remove some CJS warnings from .xsession-errors
> netusagemonitor@pdcurtis Update  Version 3.2.3

- jalalicalendar@mohammad-sn/files/jalalicalendar@mohammad-sn/applet.js
@mohammad-sn 
[PR causing the change](https://github.com/linuxmint/Cinnamon/pull/6790).
> jalalicalendar@mohammad-sn: Fix imports for Cinnamon 3.6

- location-detection@heimdall/files/location-detection@heimdall/applet.js
> location-detection@heimdall: Ensure icon scaling

- mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/sv.po
> mailnagapplet@ozderya.net: Update sv.po

- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/3.4/applet.js
- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/3.4/settings-schema.json
also changed some default values
Cinnamon 3.4 changes only
> CinnVIIStarkMenu@NikoKrause: fix quicklauncher labels

- betterlock/files/betterlock/applet.js
- betterlock/files/betterlock/indicator-off-symbolic.svg
- betterlock/files/betterlock/metadata.json
- betterlock/files/betterlock/po/betterlock.pot
- betterlock/files/betterlock/po/de.po
- betterlock/files/betterlock/settings-schema.json
closes https://github.com/linuxmint/cinnamon-spices-applets/issues/31
> betterlock: add settings to hide/show Num/Caps Lock icon

- IcingTaskManager@json/files/IcingTaskManager@json/3.2/appGroup.js
- IcingTaskManager@json/files/IcingTaskManager@json/3.2/appList.js
- IcingTaskManager@json/files/IcingTaskManager@json/3.2/applet.js
- IcingTaskManager@json/files/IcingTaskManager@json/3.2/constants.js
- IcingTaskManager@json/files/IcingTaskManager@json/3.2/each.js
- IcingTaskManager@json/files/IcingTaskManager@json/3.2/specialButtons.js
- IcingTaskManager@json/files/IcingTaskManager@json/3.2/specialMenus.js
Regression from https://github.com/linuxmint/cinnamon-spices-applets/commit/1915dc0710ef08e18375922a065b04f905725385.
Also set up module imports testing for [Cinnamon PR #6878](https://github.com/linuxmint/Cinnamon/pull/6878).
> IcingTaskManager@json: Fix applet dragging in panel edit mode

- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js
Update the list of available network interfaces when the context menu opens.
> [download-and-upload-speed@cardsurf] Auto update interfaces

- sysmonitor@orcus/files/sysmonitor@orcus/applet.js
- sysmonitor@orcus/files/sysmonitor@orcus/providers.js
@OrcusCZ 
[PR causing the change](https://github.com/linuxmint/Cinnamon/pull/6790).
> sysmonitor@orcus: Fix imports for Cinnamon 3.6

- .github/validate-spices-repo
- README.md
- validate-spice
> applet validation: add script, which checks if applet is valid

- README.md
- cinnamon-spices-makepot
> add cinnamon-spices-makepot script

- windowlist@cobinja.de/CHANGELOG.md
- windowlist@cobinja.de/files/windowlist@cobinja.de/3.2/applet.js
- windowlist@cobinja.de/files/windowlist@cobinja.de/metadata.json
> [windowlist@cobinja.de] Add ability to add launchers via the menu

- slingshot@jfarthing84/files/slingshot@jfarthing84/po/tr.po
slingshot@jfarthing84: add tr.po
> slingshot@jfarthing84: add tr.po

- IcingTaskManager@json/CHANGELOG.md
- IcingTaskManager@json/files/IcingTaskManager@json/3.2/appGroup.js
- IcingTaskManager@json/files/IcingTaskManager@json/3.2/applet.js
- IcingTaskManager@json/files/IcingTaskManager@json/metadata.json
* Fixed app button dragging not working correctly on Cinnamon 3.4.
* Fixed the styling not resetting sometimes when pinned apps are closed.
* Cinnamon 3.5 (dev): Updated window progress styling.
> IcingTaskManager@json: 6.0.2

- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/applet.js
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/settings-schema.json
Added an option to apply values periodically.
> [brightness-and-gamma-applet@cardsurf] Apply values

- Cinnamenu@json/CHANGELOG.md
- Cinnamenu@json/files/Cinnamenu@json/applet.js
- Cinnamenu@json/files/Cinnamenu@json/buttons.js
- Cinnamenu@json/files/Cinnamenu@json/metadata.json
* Fixed a regression preventing the applet from working on vertical panels on Cinnamon <= 3.4.
* Fixed a context menu item key navigation bug.
> Cinnamenu@json: 3.0.1

- windowlist@cobinja.de/files/windowlist@cobinja.de/po/windowlist@cobinja.de.pot
> windowlist@cobinja.de Fix translation pot-file

- brightness-and-gamma-applet@cardsurf/README.md
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/applet.js
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/appletGui.js
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/filesCsv.js
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/brightness-and-gamma-applet@cardsurf.pot
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/da.po
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/de.po
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/hr.po
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/sv.po
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/tr.po
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/zh_CN.po
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/settings-schema.json
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/shellUtils.js
Added an option to apply values to multiple outputs.
> [brightness-and-gamma-applet@cardsurf] Multiple outputs

- windowlist@cobinja.de/files/windowlist@cobinja.de/po/da.po
> windowlist@cobinja.de Update da.po to fixed pot-file

- BgRadio@spacy01/files/BgRadio@spacy01/applet.js
Fixed one of the radio streams.
> Update applet.js on BgRadio@spacy01

- ScreenShot@tech71/files/ScreenShot@tech71/po/bg.po
> Update bg. po for ScreenShot@tech71

- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/bg.po
> bg.po for CinnVIIStarkMenu@NikoKrause

- ioDisk@ctrlesc/files/ioDisk@ctrlesc/po/pl.po
> ioDisk@ctrlesc: Add polish translation

- ioDisk@ctrlesc/files/ioDisk@ctrlesc/applet.js
- ioDisk@ctrlesc/files/ioDisk@ctrlesc/po/de.po
- ioDisk@ctrlesc/info.json
Set author back to @ctrlesc
Remove unused imports and trailing whitespaces
Add German translation
> ioDisk@ctrlesc: Return of the author

- windowlist@cobinja.de/files/windowlist@cobinja.de/3.2/applet.js
Apply this (no pun intended):
https://github.com/linuxmint/Cinnamon/commit/d4fc18e0d81051091324a4fe87c06e35f5865510
> windowlist@cobinja.de Performance improvement

- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/SpawnProcess.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/applet.js
Fixed prefs.js running as an executable.
> multicore-sys-monitor: Fix preferences not opening

- hideable-applets@cardsurf/README.md
- hideable-applets@cardsurf/files/hideable-applets@cardsurf/metadata.json
- hideable-applets@cardsurf/files/hideable-applets@cardsurf/settings-schema.json
Updated descriptions of configuration parameters.
> [hideable-applets@cardsurf] Updated descriptions

- hideable-applets@cardsurf/files/hideable-applets@cardsurf/metadata.json
Increased version number to 1.1.0.
> [hideable-applets@cardsurf] Increased version number

- IcingTaskManager@json/files/IcingTaskManager@json/po/bg.po
Fixed and updated translation.
> Update bg.po for IcingTaskManager@json

- tor-button@shatur/files/tor-button@shatur/po/tr.po
> tor-button@shatur: add tr.po

- website-notifier@cardsurf/files/website-notifier@cardsurf/metadata.json
Increased version number to 1.0.1.
> [website-notifier@cardsurf] Increased version number

- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/ru.po
Please, update rssian translation for CinnVIIStarkMenu@NikoKrause
> CinnVIIStarkMenu: Update russian translation

- batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/sv.po
> batterymonitor@pdcurtis: Update sv.po

- radio@driglu4it/files/radio@driglu4it/po/ru.po
> radio@driglu4it: Create ru.po

- radio@driglu4it/README.md
> radio@driglu4it: Update README.md

- radio@driglu4it/files/radio@driglu4it/po/tr.po
> radio@driglu4it: add tr.po

- places-bookmarks@dmo60.de/files/places-bookmarks@dmo60.de/po/tr.po
places-bookmarks@dmo60.de: add tr.po
> places-bookmarks@dmo60.de: add tr.po

- color-picker@fmete/README.md
- color-picker@fmete/files/color-picker@fmete/applet.js
- color-picker@fmete/files/color-picker@fmete/cp.py
- color-picker@fmete/files/color-picker@fmete/po/color-picker@fmete.pot
- color-picker@fmete/files/color-picker@fmete/po/de.po
Check for required python packages.
> color-picker@fmete: Required package 'python-numpy'

- color-picker@fmete/files/color-picker@fmete/po/bg.po
Bulgarian translation for color-picker@fmete
> bg.po for color-picker@fmete

- BgRadio@spacy01/files/BgRadio@spacy01/po/bg.po
> Update bg.po for BgRadio@spacy01

- redshift@marvel4u/files/redshift@marvel4u/applet.js
Tried to improve localization. Just added a new gettext function and make one string translatable.
> Update applet.js on redshift@marvel4u

- redshift@marvel4u/files/redshift@marvel4u/po/redshift.pot
Added a few more strings, that was missed.
> Update redshift.pot for redshift@marvel4u

- redshift@marvel4u/files/redshift@marvel4u/po/bg.po
> Create bg.po for redshift@marvel4u

- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/bg.po
> bg.po for brightness-and-gamma-applet@cardsurf

- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/brightness-and-gamma-applet@cardsurf.pot
@cardsurf, just added some missing strings.
> brightness-and-gamma-applet@cardsurf update pot file

- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/bg.po
> Create bg.po for multicore-sys-monitor@ccadeptic23

- sessionManager@scollins/files/sessionManager@scollins/po/bg.po
> Create bg.po for sessionManager@scollins

- placesCenter@scollins/files/placesCenter@scollins/po/bg.po
> Create bg.po for placesCenter@scollins

- placesCenter@scollins/files/placesCenter@scollins/po/placesCenter.pot
@collinss, update the pot file with strings from search script
> Update pot file for placesCenter@scollins

- placesCenter@scollins/files/placesCenter@scollins/search.py
@collinss, tried to add gettext support for the search script.
> Update search.py for placesCenter@scollins

- ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/po/ScreenShot+RecordDesktop@tech71.pot
@tech71, there was a missed string and some strings needs to be updated.
>  ScreenShot+RecordDesktop@tech71 - Update a pot file

- ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/po/bg.po
>  ScreenShot+RecordDesktop@tech71 - Create bg.po

- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/bg.po
> bg.po for download-and-upload-speed@cardsurf

- hwmonitor@sylfurd/files/hwmonitor@sylfurd/po/bg.po
> bg.po for hwmonitor@sylfurd

- temperature@fevimu/files/temperature@fevimu/po/bg.po
> bg.po for temperature@fevimu

- radio@driglu4it/files/radio@driglu4it/po/bg.po
> bg.po for radio@driglu4it

- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/bg.po
> Update bg.po for download-and-upload-speed@cardsurf

- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/DataProviders.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json
> multicore-sys-monitor@ccadeptic23: Fix download/upload values

- azan@fahri.nurul.id/info.json
> azan@fahri.nurul.id: Change author field to Github username

- placesCenter@scollins/files/placesCenter@scollins/po/sv.po
> placesCenter@scollins: Update sv.po

- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/bg.po
Updated bulgarian localization.
> gpaste-reloaded@feuerfuchs.eu: updated bg.po file

- weather@mockturtl/files/weather@mockturtl/applet.js
> weather@mockturtl: fix broken location link

- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/sv.po
> gpaste-reloaded@feuerfuchs.eu: Update sv.po

- IcingTaskManager@json/files/IcingTaskManager@json/po/bg.po
Update bulgarian localization.
> IcingTaskManager@json: Update bg.po

- IcingTaskManager@json/files/IcingTaskManager@json/po/pl.po
This time I'll post any changes here :)
> Updated polish language

- BgRadio@spacy01/files/BgRadio@spacy01/applet.js
> bgRadio@spacy01: Update applet.js

- BgRadio@spacy01/files/BgRadio@spacy01/applet.js
- BgRadio@spacy01/files/BgRadio@spacy01/po/BgRadio@spacy01.pot
- BgRadio@spacy01/files/BgRadio@spacy01/po/bg.po
@spacy01 
Just added the Darik Nostalgie radio station.
> BgRadio@spacy01: Added radio Darik Nostalgie.

- windowlist@cobinja.de/CHANGELOG.md
- windowlist@cobinja.de/files/windowlist@cobinja.de/3.2/applet.js
- windowlist@cobinja.de/files/windowlist@cobinja.de/3.2/settings-schema.json
- windowlist@cobinja.de/files/windowlist@cobinja.de/po/de.po
- windowlist@cobinja.de/files/windowlist@cobinja.de/po/windowlist@cobinja.de.pot
- Various bugfixes (HiDPI, preventing a crash)
- New options for the preview menu and preview size
> windowlist@cobinja.de Upgrade to 2.2

- Cinnamenu@json/CHANGELOG.md
- Cinnamenu@json/files/Cinnamenu@json/applet.js
- Cinnamenu@json/files/Cinnamenu@json/metadata.json
* Fixed the menu width changing when left positioned descriptions are used.
> Cinnamenu@json: 3.1.2

- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/applet.js
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/keyboard.js
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/settings-schema.json
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/translation.js
Closes https://github.com/linuxmint/cinnamon-spices-applets/issues/1568.
> [text-to-speech-applet@cardsurf] Added keyboard shortcuts

- Cinnamenu@json/CHANGELOG.md
- Cinnamenu@json/files/Cinnamenu@json/applet.js
- Cinnamenu@json/files/Cinnamenu@json/buttons.js
- Cinnamenu@json/files/Cinnamenu@json/metadata.json
* Fixed clicking context menu items from the first app in a list not working.
* Fixed category entries being invisbly entered when using key navigation in search mode.
* Fixed the category selection not resetting after a search.
> Cinnamenu@json: 3.1.3

- IcingTaskManager@json/CHANGELOG.md
- IcingTaskManager@json/files/IcingTaskManager@json/3.4/applet.js
- IcingTaskManager@json/files/IcingTaskManager@json/3.4/specialMenus.js
- IcingTaskManager@json/files/IcingTaskManager@json/3.4/store_mozjs24.js
- IcingTaskManager@json/files/IcingTaskManager@json/metadata.json
* Fixed regressions occurring in some situations:
* Context menus not opening
* Thumbnails not displaying correctly
* Fixed ITM not completing its initial load while system favorites are enabled during a Cinnamon restart.
> IcingTaskManager@json: 6.2.1

- sticky@scollins/files/sticky@scollins/po/sv.po
> sticky@scollins: Update sv.po

- vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/applet.js
- vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/po/pl.po
Add running indicator for vbox vms in list.
@mockturtl
@jaszhix
> vboxlauncher@mockturtl: Add running indicator for vbox vms in list

- search-box@mtwebster/files/search-box@mtwebster/3.2/applet.js
- search-box@mtwebster/files/search-box@mtwebster/3.2/settings-schema.json
- search-box@mtwebster/files/search-box@mtwebster/po/de.po
- search-box@mtwebster/files/search-box@mtwebster/po/search-box.pot
Default keybinding: `Ctrl+Alt+F`
> search-box@mtwebster: Add keybinding to open search box

- IcingTaskManager@json/CHANGELOG.md
- IcingTaskManager@json/files/IcingTaskManager@json/3.4/appGroup.js
- IcingTaskManager@json/files/IcingTaskManager@json/3.4/applet.js
- IcingTaskManager@json/files/IcingTaskManager@json/3.4/settings-schema.json
- IcingTaskManager@json/files/IcingTaskManager@json/3.4/specialMenus.js
- IcingTaskManager@json/files/IcingTaskManager@json/metadata.json
- IcingTaskManager@json/files/IcingTaskManager@json/po/bg.po
- IcingTaskManager@json/files/IcingTaskManager@json/po/da.po
- IcingTaskManager@json/files/IcingTaskManager@json/po/de.po
- IcingTaskManager@json/files/IcingTaskManager@json/po/default.pot
- IcingTaskManager@json/files/IcingTaskManager@json/po/es.po
- IcingTaskManager@json/files/IcingTaskManager@json/po/fr.po
- IcingTaskManager@json/files/IcingTaskManager@json/po/he.po
- IcingTaskManager@json/files/IcingTaskManager@json/po/hr.po
- IcingTaskManager@json/files/IcingTaskManager@json/po/pl.po
- IcingTaskManager@json/files/IcingTaskManager@json/po/ru.po
- IcingTaskManager@json/files/IcingTaskManager@json/po/sv.po
- IcingTaskManager@json/files/IcingTaskManager@json/po/tr.po
- IcingTaskManager@json/files/IcingTaskManager@json/po/zh_CN.po
- IcingTaskManager@json/locale.sh
* Fixed an issue with hovering over the thumbnail close button causing the window preview to flicker.
* Addressed an issue with JavaEmbeddedFrame appearing in the window list.
* Added launcher animation effect options.
> IcingTaskManager@json: 6.3.0

- show-hide-applets@mohammad-sn/files/show-hide-applets@mohammad-sn/applet.js
- Returning false inside Mainloop callbacks will ensure it doesn't loop
Merging since it could be causing stability issues (#1515)
@mohammad-sn
> show-hide-applets@mohammad-sn: Fix invalid/null mainloop source id's, return false in handlers

- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/scripts/run_lsof.sh
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/scripts/run_nethogs.sh
Added scripts that list current Internet connections. Closes cardsurf/download-and-upload-speed#8.
> [download-and-upload-speed@cardsurf] Added scripts that list connections

- sysmonitor@orcus/files/sysmonitor@orcus/po/de.po
This pull request only adds German translation, applet code is not changed. It resolves #1635 .
> sysmonitor@orcus: Added german translation

- IcingTaskManager@json/CHANGELOG.md
- IcingTaskManager@json/files/IcingTaskManager@json/3.4/applet.js
- IcingTaskManager@json/files/IcingTaskManager@json/metadata.json
> IcingTaskManager@json: Fix findIndex calls

- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/Graphs.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/applet.js
Fixed applet graphics being slightly off-center and clipped.
(Width and height were off by a few pixels.)
Fixed incorrect vertical scaling in HiDPI.
(`panel_height` is already scaled and scaling factor was applied once more to it, leaving half the applet off-screen at 2x scale)
@jaszhix
> multicore-sys-monitor@ccadeptic23: Fix applet geometry bugs.

- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/Graphs.js
Continuation of #1659
Fixed labels not scaling.
Fixed horizontal scaling for NET and DISK graphs.
I hope I haven't missed anything else.
> multicore-sys-monitor@ccadeptic23: Fix not everything scaling for HiDPI.

- bash-sensors@pkkk/files/bash-sensors@pkkk/applet.js
- bash-sensors@pkkk/files/bash-sensors@pkkk/metadata.json
- Enable multiple instances
This fixes issue #1664
> [bash-sensors@pkkk] Multi-instances support

- sticky@scollins/files/sticky@scollins/po/fr.po
Hi @collinss,
I propose this file fr.po.
Best regards.
claudiux
>  sticky@scollins: Added fr.po - French translation

- workspace-grid@hernejj/files/workspace-grid@hernejj/applet.js
> workspace-grid@hernejj: Fix for Cinnamon 3.8

- cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/applet.js
- cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/metadata.json
- cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/settings-schema.json
- Enable multiple instances
- Each instance is a pair Coin/Crypto. The list of coins and cryptos is fixed
> cryptocoin@guantanamoe: unlimited instances and multiple coins

- SettingsPlus@lusito.info/files/SettingsPlus@lusito.info/applet.js
- SettingsPlus@lusito.info/files/SettingsPlus@lusito.info/config.json
Fixes applet crashing on menu item click
> SettingsPlus@lusito.info: Fix for Cinnamon 3.8

- calendar@simonwiles.net/files/calendar@simonwiles.net/applet.js
> calendar@simonwiles.net: Fix for Cinnamon 3.8

- Cinnamenu@json/files/Cinnamenu@json/constants.js
- Cinnamenu@json/files/Cinnamenu@json/fuzzy.js
- Cinnamenu@json/files/Cinnamenu@json/po/es.po
- Cinnamenu@json/files/Cinnamenu@json/utils.js
- Spanish translation ct. @germanfr
> Cinnamenu@json: Fix exported variables, add Spanish translation

- windowlist@cobinja.de/files/windowlist@cobinja.de/3.2/applet.js
> windowlist@cobinja.de Fix grouping/ungrouping not taking effect

- cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/applet.js
- cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/metadata.json
- cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/settings-schema.json
Allow displaying coin icon (from cryptocompare, blame them if not transparent), and optionally suppress ticker name and/or show currency name
> cryptocoin@guantanamoe: applet icon

- stevedore@centurix/files/stevedore@centurix/applet.js
> stevedore@centurix: Fix for Cinnamon 3.8

- rancher@centurix/files/rancher@centurix/applet.js
- rancher@centurix/files/rancher@centurix/homestead.js
> rancher@centurix: Fix for Cinnamon 3.8

- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/CSCollapseBtn.js
- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/applet.js
> collapsible-systray@feuerfuchs.eu: Fix for Cinnamon 3.8

- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/GPasteNewItemDialog.js
- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/GPasteNotInstalledDialog.js
- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/GPasteSearchItem.js
- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/applet.js
> gpaste-reloaded@feuerfuchs.eu: Fix for Cinnamon 3.8

- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletConstants.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletGui.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/filesCsv.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/translation.js
> download-and-upload-speed@cardsurf: Fix for Cinnamon 3.8

- disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/applet.js
- disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/appletConstants.js
- disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/appletGui.js
> disk-read-and-write-speed@cardsurf: Fix for Cinnamon 3.8

- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/applet.js
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/appletGui.js
- brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/filesCsv.js
> brightness-and-gamma-applet@cardsurf: Fix for Cinnamon 3.8

- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/applet.js
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/appletConstants.js
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/clipboard.js
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/shellUtils.js
- text-to-speech-applet@cardsurf/files/text-to-speech-applet@cardsurf/translation.js
> text-to-speech-applet@cardsurf: Fix for Cinnamon 3.8

- website-notifier@cardsurf/files/website-notifier@cardsurf/applet.js
- website-notifier@cardsurf/files/website-notifier@cardsurf/appletConstants.js
- website-notifier@cardsurf/files/website-notifier@cardsurf/appletGui.js
- website-notifier@cardsurf/files/website-notifier@cardsurf/shellUtils.js
> website-notifier@cardsurf: Fix for Cinnamon 3.8

- hideable-applets@cardsurf/files/hideable-applets@cardsurf/applet.js
- hideable-applets@cardsurf/files/hideable-applets@cardsurf/appletConstants.js
- hideable-applets@cardsurf/files/hideable-applets@cardsurf/appletGui.js
- hideable-applets@cardsurf/files/hideable-applets@cardsurf/filesCsv.js
> hideable-applets@cardsurf: Fix for Cinnamon 3.8

- sound150@claudiux/CHANGELOG.md
- sound150@claudiux/files/sound150@claudiux/2.8/applet.js
- sound150@claudiux/files/sound150@claudiux/3.4/applet.js
- sound150@claudiux/files/sound150@claudiux/CHANGELOG.md
- sound150@claudiux/files/sound150@claudiux/metadata.json
Hi,
This is the version 1.4.0 of the sound150@claudiux applet.
* The 100% mark in sound settings becomes magnetic.
* The applet and sound settings sliders become synchronized.
Can you merge my sound150 branch with your master branch, please?
Best regards.
claudiux
> sound150@claudiux: v1.4.0

- placesCenter@scollins/files/placesCenter@scollins/po/fr.po
Hi,
I propose a new translation, in French, for the applet placesCenter@scollins. This file fr.po, made from the file placesCenter@scollins.pot, did not exist until now. Here it is.
Best regards.
claudiux
> placesCenter@scollins - fr.po - French translation

- temperature@fevimu/files/temperature@fevimu/po/pt.po
Hi, I updated the European Portuguese translation for temperature@fevimu applet.
> temperature@fevimu: Updated pt-PT translation

- Cinnamenu@json/CHANGELOG.md
- Cinnamenu@json/files/Cinnamenu@json/applet.js
- Cinnamenu@json/files/Cinnamenu@json/buttons.js
- Cinnamenu@json/files/Cinnamenu@json/metadata.json
- Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu.pot
- Cinnamenu@json/files/Cinnamenu@json/po/ar.po
- Cinnamenu@json/files/Cinnamenu@json/po/da.po
- Cinnamenu@json/files/Cinnamenu@json/po/de.po
- Cinnamenu@json/files/Cinnamenu@json/po/es.po
- Cinnamenu@json/files/Cinnamenu@json/po/fr.po
- Cinnamenu@json/files/Cinnamenu@json/po/hr.po
- Cinnamenu@json/files/Cinnamenu@json/po/it.po
- Cinnamenu@json/files/Cinnamenu@json/po/ja.po
- Cinnamenu@json/files/Cinnamenu@json/po/pl.po
- Cinnamenu@json/files/Cinnamenu@json/po/pt_BR.po
- Cinnamenu@json/files/Cinnamenu@json/po/pt_PT.po
- Cinnamenu@json/files/Cinnamenu@json/po/ru.po
- Cinnamenu@json/files/Cinnamenu@json/po/sk.po
- Cinnamenu@json/files/Cinnamenu@json/po/sv.po
- Cinnamenu@json/files/Cinnamenu@json/po/zh_CN.po
- Cinnamenu@json/files/Cinnamenu@json/settings-schema.json
- Cinnamenu@json/files/Cinnamenu@json/utils.js
- Cinnamenu@json/locale.sh
* Added drag and drop category re-ordering.
* Fixed a styling issue with context menus.
> Cinnamenu@json: 3.2.0

- vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/po/pl.po
Small corrections and delete out-of-date mail address.
@mockturtl
@jaszhix
> vboxlauncher@mockturtl: Corrections and delete out-of-date address

- places-bookmarks@dmo60.de/files/places-bookmarks@dmo60.de/po/pl.po
Add polish translation
@dmo60
@NikoKrause
> places-bookmarks@dmo60.de: Add pl.po

- radio@driglu4it/files/radio@driglu4it/po/pl.po
Add polish translation
@Driglu4it 
@NikoKrause
> radio@driglu4it: Add pl.po

- places-bookmarks@dmo60.de/files/places-bookmarks@dmo60.de/po/pl.po
Correction for pl.po
@dmo60
@NikoKrause
> places-bookmarks@dmo60.de: pl.po small correct

- jalalicalendar@mohammad-sn/files/jalalicalendar@mohammad-sn/applet.js
> jalalicalendar@mohammad-sn: Fix for Cinnamon 3.8

- sticky@scollins/files/sticky@scollins/po/pl.po
Add polish translation
@collinss 
@NikoKrause
> sticky@scollins: Add pl.po

- sticky@scollins/files/sticky@scollins/po/pl.po
pl.po update and typo fix
@collinss 
@jaszhix
> sticky@scollins: pl.po update and typo fix

- sticky@scollins/files/sticky@scollins/po/tr.po
> sticky@scollins: add tr.po

- vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/po/tr.po
vboxlauncher@mockturtl: add tr.po
> vboxlauncher@mockturtl: add tr.po

- Cinnamenu@json/files/Cinnamenu@json/po/fr.po
This fr.po file is updated; all messages located in Cinnamenu@json.pot have been translated.
Best regards.
claudiux
> Cinnamenu@json - fr.po updated

- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/pl.po
Add polish translation for download-and-upload-speed@cardsurf
@cardsurf 
@jaszhix
> download-and-upload-speed@cardsurf: Add pl.po

- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/pl.po
Add polish translation for multicore-sys-monitor@ccadeptic23.
@ccadeptic23
@jaszhix
> multicore-sys-monitor@ccadeptic23: Add pl.po

- sticky@scollins/files/sticky@scollins/po/pl.po
- sticky@scollins/files/sticky@scollins/po/sticky.pot
Updated sticky.pot and updated polish translation
Need detail check because I first time do "cinnamon-json-makepot --js po/sticky.pot"
and update .POT file
@collinss
> sticky@scollins: pl.po and .pot update

- sticky@scollins/files/sticky@scollins/po/pl.po
Update polish translation
@collinss
> sticky@scollins: pl.po update

- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/pl.po
Add polish translation to gpaste-reloaded@feuerfuchs.eu aplet
@Feuerfuchs 
@jaszhix
> gpaste-reloaded@feuerfuchs.eu: Add pl.po

- feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/po/fr.po
Hi,
I propose this fr.po file for French translation.
Best regards.
claudiux
> feeds@jonbrettdev.wordpress.com: Added fr.po - French translation

- radio@driglu4it/README.md
- radio@driglu4it/files/radio@driglu4it/applet.js
- radio@driglu4it/files/radio@driglu4it/po/radio.pot
- radio@driglu4it/files/radio@driglu4it/po/ru.po
- radio@driglu4it/files/radio@driglu4it/settings-schema.json
radio@driglu4it add control volume on mouse wheel and checkbox for display station
> radio@driglu4it: add control volume on mouse wheel and checkbox for display station

- radio@driglu4it/files/radio@driglu4it/po/pl.po
Update from pot file and complete translation.
@Driglu4it 
@jaszhix
> radio@driglu4it: pl.po update

- gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/pl.po
Update polish translation.
@Feuerfuchs 
@jaszhix
> gpaste-reloaded@feuerfuchs.eu: pl.po update

- betterlock/files/betterlock/applet.js
This is more consistent within every option. Moved the switches to the context menu.
> betterlock: enable locks on click also when both icons are visible

- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/Graphs.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/applet.js
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/prefsui.glade
- multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json
- Fixes a bug that can cause loss of input control after removing the applet from the panel
- Fixes the network and device lists not being scroll-able
- Minor optimizations
> multicore-sys-monitor@ccadeptic23: 1.8.4

- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/applet.js
- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/metadata.json
- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/po/de.po
- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/po/localization.pot
- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/settings-schema.json
- Updated settings schema
- Fixed shaking icons on animations (https://github.com/Feuerfuchs/Collapsible-Systray-Cinnamon-Applet/issues/24)
- Added animation-less mode which fixes an issue that icons stop updating under certain circumstances (https://github.com/Feuerfuchs/Collapsible-Systray-Cinnamon-Applet/issues/25)
Localizations for this applet (except for German) need to be updated.
> [collapsible-systray@feuerfuchs.eu] Update to version 1.11

- Cinnamenu@json/CHANGELOG.md
- Cinnamenu@json/files/Cinnamenu@json/applet.js
- Cinnamenu@json/files/Cinnamenu@json/buttons.js
- Cinnamenu@json/files/Cinnamenu@json/metadata.json
* Addressed an issue with the context menu labels being truncated.
* Fixed search text clipping.
> Cinnamenu@json: 3.2.1

- azan@fahri.nurul.id/files/azan@fahri.nurul.id/applet.js
> azan@fahri.nurul.id: Fix for Cinnamon 3.8

- slingshot@jfarthing84/files/slingshot@jfarthing84/applet.js
- slingshot@jfarthing84/files/slingshot@jfarthing84/granite.js
> slingshot@jfarthing84: Fix for Cinnamon 3.8

- smallcalc_applet@lerc.sds/files/smallcalc_applet@lerc.sds/applet.js
@lerc 
Depends on https://github.com/linuxmint/Cinnamon/pull/7553
> smallcalc_applet@lerc.sds: Fix for Cinnamon 3.8

- sysmonitor@orcus/files/sysmonitor@orcus/3.2/applet.js
- sysmonitor@orcus/files/sysmonitor@orcus/3.2/providers.js
> sysmonitor@orcus: Fix imports for 3.6

- redshift@marvel4u/files/redshift@marvel4u/po/cs.po
> redshift@marvel4u: Add cs.po

- scripts@paucapo.com/files/scripts@paucapo.com/po/cs.po
> scripts@paucapo.com: Add cs.po

- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletGui.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/cssStylization.js
> [download-and-upload-speed@cardsurf] Fixes for Cinnamon 3.8

- windowlist@cobinja.de/files/windowlist@cobinja.de/3.2/applet.js
This fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/1798
> windowlist@cobinja.de Fix non-shwowing borders at certain panel heights

- temperature@fevimu/files/temperature@fevimu/po/cs.po
> temperature@fevimu: Add cs.po

- brightness-and-gamma-applet@cardsurf/info.json
- disk-read-and-write-speed@cardsurf/info.json
- download-and-upload-speed@cardsurf/info.json
- hideable-applets@cardsurf/files/hideable-applets@cardsurf/filesCsv.js
- hideable-applets@cardsurf/info.json
- text-to-speech-applet@cardsurf/info.json
- website-notifier@cardsurf/info.json
Fixed a loading problem on older version of Cinnamon.
> [hideable-applets@cardsurf] Fix loading problem

- website-notifier@cardsurf/files/website-notifier@cardsurf/applet.js
Fixed a loading problem on older version of Cinnamon.
> [website-notifier@cardsurf] Fix loading problem

- vpnLookOut@claudiux/CHANGELOG.md
- vpnLookOut@claudiux/files/vpnLookOut@claudiux/CHANGELOG.md
- vpnLookOut@claudiux/files/vpnLookOut@claudiux/LICENSE
- vpnLookOut@claudiux/files/vpnLookOut@claudiux/applet.js
- vpnLookOut@claudiux/files/vpnLookOut@claudiux/metadata.json
- vpnLookOut@claudiux/info.json
Hi,
Can you merge this vpnlookout branch with your master branch, please ?
Best regards.
Claudiux
> v2.1.0: Now compatible with Fedora 27.

- CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/3.4/applet.js
They do nothing but interfere with theming.
@NikoKrause
> CinnVIIStarkMenu@NikoKrause: remove separators custom styles

- IcingTaskManager@json/files/IcingTaskManager@json/po/fr.po
Hi,
Here is an update of the fr.po file, made from the last .pot file.
Best regards.
claudiux
> [IcingTaskManager@json] French translation: update of fr.po

- sessionManager@scollins/files/sessionManager@scollins/po/fr.po
Hi,
Here the fr.po file for French translation.
Best regards.
Claudiux
> [sessionManager@scollins]: French translation - Added fr.po

- vpnLookOut@claudiux/CHANGELOG.md
- vpnLookOut@claudiux/README.md
- vpnLookOut@claudiux/files/vpnLookOut@claudiux/CHANGELOG.md
- vpnLookOut@claudiux/files/vpnLookOut@claudiux/README.md
- vpnLookOut@claudiux/files/vpnLookOut@claudiux/applet.js
- vpnLookOut@claudiux/files/vpnLookOut@claudiux/metadata.json
Hi,
Can you merge this branch with your master one, please ?
Thank you.
Best regards.
Claudiux
> [vpnLookOut@claudiux]: v2.2.0 - Now compatible with Archlinux

- download-and-upload-speed@cardsurf/README.md
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletGui.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/infos.js
- download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/settings-schema.json
Added a feature to show a sum of download and upload speed values when multiple network interfaces are checked.
Closes #1842.
> [download-and-upload-speed@cardsurf] Sum of values

- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/applet.js
- collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/metadata.json
See https://github.com/Feuerfuchs/Collapsible-Systray-Cinnamon-Applet/issues/27
> [collapsible-systray@feuerfuchs.eu] Enlarge tray icon click area
