linuxmint/cinnamon-spices-applets

qredshift@quintao/files/qredshift@quintao/js/QUtils.js, qredshift@quintao/files/qredshift@quintao/js/to-string.js
Hi @raphaelquintao,
I propose a new version of the `to_string()` function. I also modified `QUtils.js` to better take into account this new version.
Hope you find these changes helpful.
Regards.
Claudiux
=> qredshift@quintao: Improvements of to_string() function and its usage

radio@driglu4it/files/radio@driglu4it/po/hr.po
@jonath92 
From which source Radio applet obtains the radio stations playlist?
=> radio@driglu4it: Add Croatian translation

weather@mockturtl/files/weather@mockturtl/po/id.po
adding indonesian translate
@mockturtl
=> Weather : adding indonesian translate

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserBookmarks.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserHistory.js, Cinnamenu@json/files/Cinnamenu@json/4.0/getFavicons.py, Cinnamenu@json/files/Cinnamenu@json/4.0/searchHistory.py, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Ensure no temp files are left behind after exception.
=> [Cinnamenu@json] Bugfix.

.typescript-declarations/cinnamon/ui/tooltips.d.ts, .typescript-declarations/cinnamon/ui/tweener.d.ts, weather@mockturtl/CHANGELOG.md, weather@mockturtl/files/weather@mockturtl/3.8/weather-applet.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/files/weather@mockturtl/po/weather@mockturtl.pot, weather@mockturtl/src/3_8/providers/met_uk.ts, weather@mockturtl/src/3_8/providers/us_weather.ts, weather@mockturtl/src/3_8/types.ts, weather@mockturtl/src/3_8/ui.ts, weather@mockturtl/src/3_8/ui_elements/uiBar.ts, weather@mockturtl/src/3_8/ui_elements/uiHourlyForecasts.ts
Changes
* Fixes #4292
* Fixes #4285
* Make some of the JS Cinnamon types generic/infer types correctly, like `Tooltip` and `addTween`
=> weather@mockturtl Update 3.2.2

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language file update for the Weather applet latest pot template file from 2022-04-08.
=> weather@mockturtl Update sv.po 3.2.2

app-launcher@mchilli/files/app-launcher@mchilli/applet.js, app-launcher@mchilli/files/app-launcher@mchilli/po/app-launcher@mchilli.pot, app-launcher@mchilli/files/app-launcher@mchilli/po/de.po, app-launcher@mchilli/files/app-launcher@mchilli/widgets.py
- added: duplicate items
- update: pot-file
- update: german translation
- fix: wrong index when edit
=> app-launcher@mchilli: duplicate items, fix

darkMode@linuxedo.com/README.md, darkMode@linuxedo.com/files/darkMode@linuxedo.com/applet.js
=> Fix dark mode applet to work without local dirs

weather@mockturtl/CHANGELOG.md, weather@mockturtl/files/weather@mockturtl/3.8/weather-applet.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/src/3_8/ui_elements/uiBar.ts
=> weather@mockturtl update 3.2.3

pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/applet.js
This change adds the time left (noticeable as the `(minutes:seconds)` part) at the
end of the tooltip message, thus making it easy for
anyone who does not have the pomodoro timer enabled
in the applet panel to see the time left for the current cycle.
The tooltip message will update as often as the ticker changes.
The code changes aim to preserve the current applet behavior when displaying a tooltip. All the messages that were already present in code were reused, so translations will not require an update. 
How will the new message look like:
- during a pomodori run: ![pomodori run](https://user-images.githubusercontent.com/18380274/163717775-6960c1b1-b46f-458b-b907-802d4bc9d36e.png)
- during a short break: ![short break tooltip](https://user-images.githubusercontent.com/18380274/163717833- …
=> pomodoro@gregfreeman.org: add time left in tooltip

clean-show-desktop@filipetorresbr/files/clean-show-desktop@filipetorresbr/settings-schema.json, clean-show-desktop@filipetorresbr/files/clean-show-desktop@filipetorresbr/themecolor.sh
fixing problem while trying to get theme color and removing quotes from a boolean value on settings-schema.json
=> [clean-show-desktop@filipetorresbr]

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/appsview.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserHistory.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Show more recent apps in grid view if space available
Fix drag to panel launcher not working bug. Fixes #4300
=> [Cinnamenu@json] Show more recent apps + bugfix

weather@mockturtl/CHANGELOG.md, weather@mockturtl/files/weather@mockturtl/3.8/weather-applet.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/src/3_8/ui_elements/uiBar.ts
* Fix issue on Cinnamon versions where `is_finalized` is not injected into GObject
=> weather@mockturtl Update 3.2.4 

radio@driglu4it/files/radio@driglu4it/po/is.po
Adding a new Icelandic translation
=> @radio@driglu4it Create is.po

Cinnamenu@json/README.md, Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Additional fix for bug causing occasional system freeze.
=> {Cinnamenu@json] Bugfix update

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/po/fr.po
Hello,
I updated the French translation with the latest .pot file via poedit.
Regards,
Roxfr
=> Update fr.po for CinnVIIStarkMenu@NikoKrause

.translation-tables/LINGUAS
=> Add Persian to LINGUAS file.

qredshift@quintao/files/qredshift@quintao/po/fr.po
Hello,
I updated the French translation with the latest .pot file via poedit.
Regards,
Roxfr
=> Update fr.po for qredshift@quintao

printers@linux-man/files/printers@linux-man/po/fr.po
Hello,
I updated the French translation with the latest .pot file via poedit.
Regards,
Roxfr
=> Update fr.po for printers@linux-man

clean-show-desktop@filipetorresbr/files/clean-show-desktop@filipetorresbr/po/fr.po, redshift@marvel4u/files/redshift@marvel4u/po/fr.po
Hello,
Here is the French translation (fr.po) for the applets :
- redshift@marvel4u,
- clean-show-desktop@filipetorresbr.
Regards,
Roxfr
=> Add French translation (fr.po) for the applets

ScreenLocker@tuuxx/files/ScreenLocker@tuuxx/applet.js
=> [ScreenLocker@tuuxx] Fix applet icon size not following panel settings.

weather@mockturtl/files/weather@mockturtl/po/sv.po
Language file update for the Weather applet changing to the correct Swedish translation word for applet used in Cinnamon. Thanks to @eson57
=> weather@mockturtl Update sv.po 3.2.4

batterypower@joka42/files/batterypower@joka42/applet.js
Resolves crashes by catching exceptions.
=> batterypower@joka42: fixed crashes during plugging/unplugging

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/categoriesview.js, Cinnamenu@json/files/Cinnamenu@json/4.0/resizer.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
and replace grab_pointer() with get_device().grab for compatibility with cinnamon 5.4
=> [Cinnamenu@json] Improve app sorting in other languages

weather@mockturtl/README.md
Added some read more about links to the providers and new end date for DarkSky.
ping @Gr3q :)
=> weather@mockturtl Update readme

Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Fix regex doesn't work in Mint 19.3 bug - prevents applet from starting.
@brownsr @mtwebster @clefebvre @Cobinja This is an urgent bugfix, can someone merge ASAP, thanks.
=> [Cinnamenu@json] Bugfix

weather@mockturtl/CHANGELOG.md, weather@mockturtl/README.md, weather@mockturtl/files/weather@mockturtl/3.8/settings-schema.json, weather@mockturtl/files/weather@mockturtl/3.8/weather-applet.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/files/weather@mockturtl/po/weather@mockturtl.pot, weather@mockturtl/package.json, weather@mockturtl/src/3_8/config.ts, weather@mockturtl/src/3_8/providers/deutscherWetterdienst.ts, weather@mockturtl/src/3_8/providers/met_uk.ts, weather@mockturtl/src/3_8/types.ts, weather@mockturtl/test.sh
=> weather@mockturtl update 3.2.5 - Add Deutsche Wetterdienst as a provider

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/appsview.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserBookmarks.js, Cinnamenu@json/files/Cinnamenu@json/4.0/categoriesview.js, Cinnamenu@json/files/Cinnamenu@json/4.0/emoji.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/4.0/stylesheet.css, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu@json.pot
Add Emoji category.
update .pot file
=> [Cinnamenu@json] Add Emoji category

weather@mockturtl/CHANGELOG.md, weather@mockturtl/README.md, weather@mockturtl/files/weather@mockturtl/3.8/weather-applet.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/src/3_8/main.ts, weather@mockturtl/src/3_8/providers/deutscherWetterdienst.ts
* Fix #4387
* also add some more location-related entries into the applet label override
=> weather@mockturtl 3.2.6 - fix issue where station name is prioritized over the initial location in DWD provider

ipindicator@matus.benko@gmail.com/README.md
Same change as #4400 - sorry, missed one. @PrimaMateria @brownsr
=> Updated the README with full URL to images

qredshift@quintao/files/qredshift@quintao/js/QUtils.js
@raphaelquintao This is a complete fix, using device from event to grab the pointer instead of removed function.
* Fixes #4406
This PR is now ready
=> qredshift@quintao - Fix applet on 5.4

weather@mockturtl/CHANGELOG.md, weather@mockturtl/files/weather@mockturtl/3.8/weather-applet.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/src/3_8/config.ts, weather@mockturtl/src/3_8/utils.ts
* Fix #4390  - Make sure applet works with not configured Locale
=> weather@mockturtl Update 3.2.7

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/appsview.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserBookmarks.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserHistory.js, Cinnamenu@json/files/Cinnamenu@json/4.0/suggestions.js, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/4.0/wikipediaSearch.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/fr.po
Quit early from search suggestions and wikipedia search if Soup version 2 is not loaded (temporary fix)
remove peekpanel() because it covers the applet in cinnamon 5.4
Some code restructuring.
update fr.po thanks to melomane63
=> [Cinnamenu@json] Update for cinnamon 5.4.x

radio@driglu4it/files/radio@driglu4it/4.6/radio-applet.js, radio@driglu4it/package.json, radio@driglu4it/src/lib/AppletContainer.ts, radio@driglu4it/src/lib/AppletIcon.ts, radio@driglu4it/src/lib/PopupSubMenu.ts, radio@driglu4it/src/lib/SimpleMenuItem.ts, radio@driglu4it/src/lib/Slider.ts, radio@driglu4it/src/ui/RadioApplet/RadioAppletContainer.ts, radio@driglu4it/src/ui/VolumeSlider.ts
=> fix radio scroll issue

weather@mockturtl/files/weather@mockturtl/po/fr.po
Update the French pot file to the last version
=> weather@mockturtl: Update French Translation for the 3.2.7 version

workspace-grid@hernejj/files/workspace-grid@hernejj/5.4/applet.js
Tested successfully on Cinnamon 5.4.9.
cc: @hernejj
=> workspace-grid@hernejj: Fix ReferenceError Exception

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/suggestions.js, Cinnamenu@json/files/Cinnamenu@json/4.0/wikipediaSearch.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
and add code in case libsoup3 is loaded.
Fixes #4437
Fixes #4438
=> [Cinnamenu@json] Fix key navigation for mint 21

collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/4.0/CSRemovableSwitchMenuItem.js, collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/4.0/applet.js
* Fix arrow not clickable after toggling an active application off
* Fix critical (hidden in looking glass) errors
=> collapsible-systray@feuerfuchs.eu - Fix minor issues

spices-notifier@germanfr/files/spices-notifier@germanfr/applet.js
@germanfr Add support for libsoup3, for more info see: https://github.com/linuxmint/cinnamon/commit/76224fe409d074f8a44c70e4fd5e1289f92800b9
=> [spices-notifier@germanfr] Add libsoup3 compatibility

stevedore@centurix/files/stevedore@centurix/applet.js
=> [stevedore@centurix] Add support for libsoup3

calendar@ccprog/files/calendar@ccprog/5.2/holidays.js
=> [calendar@ccprog] Add support for libsoup3

octopussy@centurix/files/octopussy@centurix/octoprint.js
@Centurix 
Note: I am unable to test these changes with either soup 2.4 or 3.0
=> [octopussy@centurix] Add support for libsoup3

ipindicator@matus.benko@gmail.com/files/ipindicator@matus.benko@gmail.com/applet.js
=> [ipindicator@matus.benko@gmail.com] Add support for libsoup3

better-backgrounds@simonmicro/files/better-backgrounds@simonmicro/applet.js
=> [better-backgrounds@simonmicro] Add support for libsoup3

ratecurrency@magner/files/ratecurrency@magner/applet.js
=> [ratecurrency@magner] Add support for libsoup3

better-backgrounds@simonmicro/files/better-backgrounds@simonmicro/applet.js, better-backgrounds@simonmicro/files/better-backgrounds@simonmicro/settings-schema.json
- Added pause button
- Merged soup updates
- Added Unsplash warning :man_shrugging:
=> [better-backgrounds@simonmicro] Updated to 7f819c9e48226983761fe6d4cbb4f3a687b8c0ce

bing-wallpaper@starcross.dev/files/bing-wallpaper@starcross.dev/applet.js
=> [bing-wallpaper@starcross.dev] Add support for libsoup3

cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/applet.js
=> [cryptocoin@guantanamoe] Add support for libsoup3

github-projects@morgan-design.com/files/github-projects@morgan-design.com/github.js
=> [github-projects@morgan-design.com] Add support for libsoup3

bible@nodeengineer.com/files/bible@nodeengineer.com/applet.js
=> [bible@nodeengineer.com] Add support for libsoup3

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language file update for the Weather applet latest pot template file from 2022-09-05.
=> weather@mockturtl Update sv.po 3.2.9

weather@mockturtl/files/weather@mockturtl/po/fr.po
Update the French .pot file to the version 3.2.9
=> [weather@mockturt] Update the French translation

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language file Weather applet update from pot template file created 2022-09-27.
=> weather@mockturtl Update sv.po 3.2.10

Cinnamenu@json/files/Cinnamenu@json/po/nl.po
=> Cinnamenu@json: Update nl.po

MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/settings-schema.json
=> Fix typo in MuteToggler

Sensors@claudiux/files/Sensors@claudiux/po/Sensors@claudiux.pot, Sensors@claudiux/files/Sensors@claudiux/po/fr.po, applet.js, settings-schema.json, stylesheet.css
Now displays disk temp!
Also, solves https://github.com/linuxmint/cinnamon-spices-applets/issues/3336 and https://github.com/linuxmint/cinnamon-spices-applets/issues/4431
=> Sensors 2.0.0

radio@driglu4it/files/radio@driglu4it/4.6/radio-applet.js, radio@driglu4it/files/radio@driglu4it/metadata.json, radio@driglu4it/src/lib/PopupMenu.ts, radio@driglu4it/webpack.config.js
Fixes #4562. Thanks @fredcw (For now the the previous change is reverted.)
=> [radio@driglu4it]: Hotfix popup menu wrong position 

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ja.po
Added & completed japanese translation.
=> multicore-sys-monitor: add ja.po

force-quit@cinnamon.org/files/force-quit@cinnamon.org/po/ja.po
Added & completed japanese translation.
=> force-quit: add ja.po

weather@mockturtl/files/weather@mockturtl/po/ja.po
Updated ja.po to current translation template with Poedit 2.4.2.
No translations were modified on my own in the commit.
=> weather@mockturtl: Reflected POT update to ja.po

betterlock/files/betterlock/po/ja.po
This includes Japanese translation file for betterlock.
=> betterlock: added ja.po (Japanese translation)

Cinnamenu@json/files/Cinnamenu@json/4.0/settings.js, Cinnamenu@json/files/Cinnamenu@json/4.0/stylesheet.css, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Update setting.js to add config file location changes in cinnamon 5.6
Adjust subheading style.
=> [Cinnamenu@json] cinnamon 5.6 compatibility update

redshift@marvel4u/files/redshift@marvel4u/po/ja.po
Added Japanese translation for redshift.
=> redshift: add Japanese translation

weather@mockturtl/CHANGELOG.md, weather@mockturtl/files/weather@mockturtl/3.8/weather-applet.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/src/3_8/main.ts
Fix issue where refresh loop wouldn't ever resume after a single configuration error
=> weather@mockturtl update 3.2.11 - Loop paused forever

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/resizer.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Fix resizing after workspace area & scale changes.
=> [Cinnamenu@json] Resizing bug fix.

radio@driglu4it/files/radio@driglu4it/4.6/radio-applet.js, radio@driglu4it/files/radio@driglu4it/metadata.json, radio@driglu4it/src/consts.ts, radio@driglu4it/src/index.ts, radio@driglu4it/src/services/mpv/CheckInstallation.ts, radio@driglu4it/src/ui/RadioApplet/RadioAppletTooltip.ts, radio@driglu4it/webpack.config.js
=> [radio@driglu4it] fix radio not working on LM 21.1

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po
Also updated the translation template for 5.4 (will need assistance to update the other languages)
@claudiux
Fixes #4611
(Rebasing and reopening #4501 since I closed it when I thought it wasn't necessary but it looks like it would help. I find the default Sound applet has the needed functionality.)
=> sound150@claudiux: Rebase and update for cinnamon 5.4 (add tooltip section)

Cinnamenu@json/README.md, Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/appsview.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserBookmarks.js, Cinnamenu@json/files/Cinnamenu@json/4.0/categoriesview.js, Cinnamenu@json/files/Cinnamenu@json/4.0/contextmenu.js, Cinnamenu@json/files/Cinnamenu@json/4.0/getFavicons.py, Cinnamenu@json/files/Cinnamenu@json/4.0/stylesheet.css, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Add features:
* `Shift-Enter` Run currently highlighted application as root user.
* `Alt-Enter` - Open launcher properties dialogue of currently highlighted application.
* `Ctrl-d` - Open .desktop file of currently highlighted app in default text editor (opens file in user mode.)
Fixes: https://github.com/linuxmint/cinnamon-spices-applets/issues/4631
Fix some web bookmark issues.
Remove app running indicator.
Use .menu-category-button:hover instead of menu-category-button-hover.
Add vertical padding to grid buttons.
=> [Cinnamenu@json] Add some expert features.

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/3.4/applet.js, CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/applet.js
Fix bug causing "Add to desktop" of flatpak apps not working. Fixes #4615
@NikoKrause
=> [CinnVIIStarkMenu] Bug fix.

kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/fr.po
fr.po based on the .pot file found in #4656.
=> [kdecapplet@joejoetv] Add fr.po - French translation

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language file Weather applet update from pot template file released 2023-01-24.
=> weather@mockturtl Update sv.po 3.2.12

xsession@claudiux/CHANGELOG.md, xsession@claudiux/files/xsession@claudiux/CHANGELOG.md, xsession@claudiux/files/xsession@claudiux/applet.js, xsession@claudiux/files/xsession@claudiux/metadata.json, xsession@claudiux/files/xsession@claudiux/po/fr.po, xsession@claudiux/files/xsession@claudiux/po/xsession@claudiux.pot
=> Xsession v1.0.1 - Middle-click on icon shows ~/.xsession-errors

weather@mockturtl/files/weather@mockturtl/po/uk.po
weather@mockturtl: update uk.po 3.2.12
=> weather@mockturtl: update uk.po 3.2.12

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/help/MANUAL.html, Radio3.0@claudiux/files/Radio3.0@claudiux/help/MANUAL.md, Radio3.0@claudiux/files/Radio3.0@claudiux/help/fr/MANUAL.html, Radio3.0@claudiux/files/Radio3.0@claudiux/help/fr/MANUAL.md, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/checkDependencies.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/po/Radio3.0@claudiux.pot, Radio3.0@claudiux/files/Radio3.0@claudiux/po/fr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/scripts/update-yt-dlp.sh, Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json
Hi @brownsr 
This is the version 1.0.3 of Radio3.0@claudiux.
Regards.
Claudiux
=> [Radio3.0@claudiux] v1.0.3 - Now can update yt-dlp and support shortcuts

kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/sv.po
=> kdecapplet@joejoetv: add sv.po

kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/fr.po
Compatible with last version of .pot file.
=> [kdecapplet@joejoetv] Update fr.po for v2.0.0 - French translation

workspace-grid@hernejj/files/workspace-grid@hernejj/5.6/BarIndicatorStyle.js, workspace-grid@hernejj/files/workspace-grid@hernejj/5.6/GridStyle.js, workspace-grid@hernejj/files/workspace-grid@hernejj/5.6/WorkspaceController.js, workspace-grid@hernejj/files/workspace-grid@hernejj/5.6/applet.js, workspace-grid@hernejj/files/workspace-grid@hernejj/5.6/settings-schema.json
Per linuxmint/cinnamon#11452, replacing CinnamonScreen calls.
cc @hernejj (though this applet appears to be orphaned)
=> workspace-grid: Deprecate CinnamonScreen calls

app-launcher@mchilli/files/app-launcher@mchilli/applet.js, app-launcher@mchilli/files/app-launcher@mchilli/dialogs.glade, app-launcher@mchilli/files/app-launcher@mchilli/dialogs.py
- added drag'n'drop in submenus
- closed #4686
- add/edit dialog: increase default size
- add/edit dialog: make it resizable
- closed #4701
=> app-launcher@mchilli: drag'n'drop in submenus, dialogs resizable

qredshift@quintao/files/qredshift@quintao/po/sk.po
=> Added slovak translation

Sensors@claudiux/files/Sensors@claudiux/po/nl.po
=> [Sensors@claudiux] Update nl.po

app-launcher@mchilli/files/app-launcher@mchilli/dialogs.py
=> app-launcher@mchilli: hotfix

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/po/Radio3.0@claudiux.pot, Radio3.0@claudiux/files/Radio3.0@claudiux/po/fr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json
=> [Radio3.0@claudiux] v1.1.0 - Adds ability to keep YT video

ssm@Severga/files/ssm@Severga/applet.js, ssm@Severga/files/ssm@Severga/po/makepot, ssm@Severga/files/ssm@Severga/po/ru.po, ssm@Severga/files/ssm@Severga/po/ssm@Severga.pot
Some improvements to allow localization.
Attaching the applet's complete package for testing and creating other translations.
[ssm@Severga.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/10948646/ssm%40Severga.zip)
Creating translations is described here: [link](https://github.com/linuxmint/cinnamon-spices-applets/pull/4688#issue-1589529372)
=> Localizable Simplified system monitor + Russian translation

kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/sv.po
=> kdecapplet@joejoetv: update sv.po

kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/es.po
update spanish translation to 2.1.0 version
=> kdecapplet@joejoetv - update es.po

kdeccc@Severga/files/kdeccc@Severga/applet.js, kdeccc@Severga/files/kdeccc@Severga/po/kdeccc@Severga.pot, kdeccc@Severga/files/kdeccc@Severga/po/makepot, kdeccc@Severga/files/kdeccc@Severga/po/ru.po
@chezdom
Some improvements to allow localization.
Attaching the applet's complete package for testing and creating other translations.
[kdeccc@Severga.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/10948627/kdeccc%40Severga.zip)
Creating translations is described here: [link](https://github.com/linuxmint/cinnamon-spices-applets/pull/4688#issue-1589529372)
=> Localizable KDECCC + Russian translation

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json
This PR fixes #4693 and fixes #3765
=> [multicore-sys-monitor@ccadeptic23] - v1.9.0 - Now compatible with fresh install of Linux Mint 21.1

vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/applet.js
@mockturtl 
This PR fixes #4770.
=> [vboxlauncher@mockturtl] Fix #4770 - Array.toString() error

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/ConfigSettings.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/Graphs.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/SpawnProcess.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/prefs.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/prefsui.glade, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/tostring.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/bg.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/da.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/de.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/es.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/fi.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/fr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/hr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/hu.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/it.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ja.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/multicore-sys-monitor.pot, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/pl.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ro.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ru.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/sv.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/tr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/zh_CN.po, multicore-sys-monitor@ccadeptic23/locale.sh
Hi,
This PR fixes #4622.
Regards.
Claudiux
=> [multicore-sys-monitor@ccadeptic23] v1.9.1 - Add the possibility to choose the thickness of the curves

Radio3.0@claudiux/files/Radio3.0@claudiux/po/ru.po
@claudiux 
This is Russian translation for the Radio3.0 applet.
=> Radio3.0@claudiux - Add Russian translation

kdecapplet@joejoetv/files/kdecapplet@joejoetv/applet.js
Add initial support for KDE Connect 22.12.3
cc: @JoeJoeTV 
Closes #4772
=> kdecapplet@joejoetv: Add initial support for KDE Connect 22.12.3

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/icons/webradioreceiver-high-symbolic.svg, Radio3.0@claudiux/files/Radio3.0@claudiux/icons/webradioreceiver-low-symbolic.svg, Radio3.0@claudiux/files/Radio3.0@claudiux/icons/webradioreceiver-medium-symbolic.svg, Radio3.0@claudiux/files/Radio3.0@claudiux/icons/webradioreceiver-muted-symbolic.svg, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/volumeslider.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/po/Radio3.0@claudiux.pot, Radio3.0@claudiux/files/Radio3.0@claudiux/po/fr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json
@brownsr 
Hi Simon,
This PR allows the user to display an OSD while changing the radio volume (which is independent of the general sound volume).
Kind regards.
Claudiux
=> [Radio3.0@claudiux] v1.2.0 - Add ability to show OSD while changing radio volume

c-eyes@anaximeno/files/c-eyes@anaximeno/4.2/applet.js, c-eyes@anaximeno/files/c-eyes@anaximeno/4.2/clickAnimationModes.js, c-eyes@anaximeno/files/c-eyes@anaximeno/4.2/eyeModes.js, c-eyes@anaximeno/files/c-eyes@anaximeno/4.2/settings-schema.json, c-eyes@anaximeno/files/c-eyes@anaximeno/5.4/applet.js, c-eyes@anaximeno/files/c-eyes@anaximeno/5.4/clickAnimationModes.js, c-eyes@anaximeno/files/c-eyes@anaximeno/5.4/eyeModes.js, c-eyes@anaximeno/files/c-eyes@anaximeno/5.4/settings-schema.json, c-eyes@anaximeno/files/c-eyes@anaximeno/metadata.json
Update c-eyes to the most recent versions **1.11.x**
=> [c-eyes@anaximeno] updates on click animations, settings, and code refactoring

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/5.6/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
Hi @brownsr 
Just a minor bugfix in applet.js.
Kind regards
Claudiux
=> [SpicesUpdate@claudiux] v6.4.2 - Minor bugfix

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/DataProviders.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/prefs.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/4.0/prefsui.glade, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/fr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/zh_CN.po, multicore-sys-monitor@ccadeptic23/locale.sh
@brownsr 
Hi Simon,
This is my new PR fixing bug in translation.
EDIT: It also fixes #3580 and fixes #4227.
Can you merge it, please?
Kind regards
Claudiux
=> [multicore-sys-monitor@ccadeptic23] v1.9.3 - Fixes bug in translations

windowlist@cobinja.de/files/windowlist@cobinja.de/5.4/applet.js
This fixes https://github.com/Cobinja/CobiWindowList/issues/39
=> Fix focus change with ungrouped windows

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/README.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/checkDependencies.js, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/volumeslider.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json
Hi @brownsr 
checkDependencies.js is now able to install all dependencies on openSUSE.
Kind regards.
Claudiux
=> [Radio3.0@claudiux] v1.2.1 - Now compatible with openSUSE. Add new shortkeys.

vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/applet.js, vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/metadata.json, vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/po/fr.po, vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/po/vboxlauncher@mockturtl.pot, vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/settings-schema.json
@mockturtl
I offer a version 'not dangerous' of your applet, without Danger signal:
Also, I added a "Show Headless Mode" option (set to true by default) to allow users (like me) who never use headless mode to get a menu with direct access to their virtual machines.
Regards
Claudiux
=> [vboxlauncher@mockturtl] v0.4.1 - Make this applet 'not dangerous' - Add option 'Show Headless Mode'

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/applet.js
Fixes: #4807
Due to Clutter version change in cinnamon 5.4 (Mint 21)
@NikoKrause
=> [CinnVIIStarkMenu@NikoKrause] Fix key nav for new version of Clutter.

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json
Requested by an user on https://cinnamon-spices.linuxmint.com/applets/view/360#count
=> [Radio3.0@claudiux] v1.2.2 - Volume scrolling is now in the same direction as Cinnamon

weather@mockturtl/files/weather@mockturtl/po/pt_BR.po
Update for Brazilian Portuguese language:
Replacement of "Parece com" with "Sensação Térmica"
=> weather@mockturtl - Update pt_BR.po - Translation update

BgRadio@spacy01/files/BgRadio@spacy01/po/fr.po, SW++@mohammad-sn/files/SW++@mohammad-sn/po/fr.po, commandLauncher@scollins/files/commandLauncher@scollins/po/fr.po, computer@brownsr/files/computer@brownsr/po/fr.po, cpu-monitor-text@gnemonix/files/cpu-monitor-text@gnemonix/po/fr.po, ctrl4docker@hoffis-eck.de/files/ctrl4docker@hoffis-eck.de/po/fr.po, darkMode@linuxedo.com/files/darkMode@linuxedo.com/po/fr.po, devbar@ludvigbostrom/files/devbar@ludvigbostrom/po/fr.po, devutils@fogl/files/devutils@fogl/po/fr.po, diaspora-notif@douze12/files/diaspora-notif@douze12/po/fr.po, gmail@lauritsriple/files/gmail@lauritsriple/po/fr.po
=> French translations created for some applets

radio@driglu4it/files/radio@driglu4it/po/pt_BR.po
Added translation to Brazilian Portuguese language.
=> radio@driglu4it - Translation - Create pt_BR.po

xsession@claudiux/CHANGELOG.md, xsession@claudiux/README.md, xsession@claudiux/files/xsession@claudiux/CHANGELOG.md, xsession@claudiux/files/xsession@claudiux/applet.js, xsession@claudiux/files/xsession@claudiux/metadata.json
@brownsr 
Hi Simon,
This is a simple code cleanup and regression fix.
Kind regards
Claudiux
=> [xsession@claudiux] v1.0.3 - Code cleanup

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/checkDependencies.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/lib/checkDependencies.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/CHANGELOG.md, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/lib/checkDependencies.js, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/metadata.json
@brownsr 
Hi Simon,
This PR fixes #4828.
Kind regards
Claudiux
=> Fix lib/checkDependencies.js for applets using it

betterlock/files/betterlock/po/pt_BR.po
Added translation for Brazilian Portuguese.
=> Betterlock - Create pt_BR.po

VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/CHANGELOG.md, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/applet.js, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/lib/ipgateway.js, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/metadata.json
Related to discussion in #4849
=> [VPN-Sentinel@claudiux] v2.1.0 - Now compatible with Soup3

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/httpLib.js, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/volumeslider.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json
Hi @brownsr 
This PR is related to the discussion in #4849.
Can you merge it, please?
Kind regards.
Claudiux
=> [Radio3.0@claudiux] v1.3.0 - Now compatible with Soup3 for Cinnamon 5.8

VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/CHANGELOG.md, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/lib/checkDependencies.js, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/metadata.json
=> [VPN-Sentinel@claudiux] v2.1.1 - Fixes a dependency for Arch

spices-notifier@germanfr/files/spices-notifier@germanfr/applet.js, spices-notifier@germanfr/files/spices-notifier@germanfr/lib/httpLib.js, spices-notifier@germanfr/files/spices-notifier@germanfr/metadata.json, spices-notifier@germanfr/files/spices-notifier@germanfr/po/fr.po, spices-notifier@germanfr/files/spices-notifier@germanfr/po/spices-notifier@germanfr.pot, spices-notifier@germanfr/files/spices-notifier@germanfr/settings-schema.json
@germanfr 
This PR makes spices-notifier@germanfr compatible with Cinnamon 5.8.
It fixes #4858.
Also, it uses real list to add other UUIDs to follow.
I hope that will suit you.
Regards
Claudiux
=> [spices-notifier@germanfr] v4.1 - Compatible with Cinnamon 5.8

qredshift@quintao/files/qredshift@quintao/metadata.json, qredshift@quintao/files/qredshift@quintao/po/oc.po, qredshift@quintao/files/qredshift@quintao/po/ru.po
* 1.7.4 
- Sync with main repository.
- Added new translations.
=> Version 1.7.4

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/httpLib.js, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/mpv-commands.txt, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/po/Radio3.0@claudiux.pot, Radio3.0@claudiux/files/Radio3.0@claudiux/po/fr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/scripts/download-favicon.sh, Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json
@brownsr 
This is the v1.4.0 of Radio3.0. Can you merge this PR, please?
Kind regards
Claudiux
=> [Radio3.0@claudiux] v1.4.0 - Now able to display the station logo

cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/po/cinnamon-timer@jake1164.pot, cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/po/sv.po
=> cinnamon-timer@jake1164: Update sv.po

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json
=> [Sensors@claudiux] v3.0.2 - Fixes the double separator error

fw_fanctrl@juleskreuer.eu/README.md
This PR will improve the readme of `fw_fanctrl@juleskreuer.eu`
=> update readme of fw_fanctrl@juleskreuer.eu

Sensors@claudiux/files/Sensors@claudiux/po/nl.po
=> Sensors@claudiux update nl.po

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/po/Radio3.0@claudiux.pot, Radio3.0@claudiux/files/Radio3.0@claudiux/po/fr.po
Hi @brownsr 
This PR only contains a minor bugfix.
Kind regards
Claudiux
=> [Radio3.0@claudiux] v1.4.1 - Minor bugfix for Cinnamon 5.8

CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot
1. When a modal dialog (transient) window is open the focus tracking would get a bit messed up. I fixed it so the focused button will properly reflect the button associated with the window that has the focus.
2. Enhanced the tooltip text for the hotkeys assigned to the window. (i.e. "<Alt><Super><e>::" -> "Alt+Super+E"). I also fixed the text when two hotkeys are specified for a single hotkey list entry.
3. Added a context menu option under the "Pin to other workspace" menu that will pin an application to all the workspaces so you don't have to do it one at a time.
=> [CassiaWindowList@klangman] Minor fixes and enhancements

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/po/Sensors@claudiux.pot, Sensors@claudiux/files/Sensors@claudiux/po/fr.po, Sensors@claudiux/files/Sensors@claudiux/scripts/make_smartctl_usable_by_sudoers.sh, Sensors@claudiux/files/Sensors@claudiux/scripts/pkexec_make_smartctl_usable_by_sudoers.sh, Sensors@claudiux/files/Sensors@claudiux/settings-schema.json
=> [Sensors@claudiux] v3.0.3 - Fixes #4846 (/var/log/auth.log flooding by sudo)

c-eyes@anaximeno/files/c-eyes@anaximeno/4.2/applet.js, c-eyes@anaximeno/files/c-eyes@anaximeno/5.4/applet.js
Either end of the eye was being cutoff in hidpi mode:
=> c-eyes@anaximeno: Account for the global scale when setting the overall area width/height.

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/appsview.js, Cinnamenu@json/files/Cinnamenu@json/4.0/contextmenu.js, Cinnamenu@json/files/Cinnamenu@json/4.0/display.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/4.0/stylesheet.css, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/5.8/applet.js, Cinnamenu@json/files/Cinnamenu@json/5.8/appsview.js, Cinnamenu@json/files/Cinnamenu@json/5.8/contextmenu.js, Cinnamenu@json/files/Cinnamenu@json/5.8/display.js, Cinnamenu@json/files/Cinnamenu@json/5.8/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/5.8/stylesheet.css, Cinnamenu@json/files/Cinnamenu@json/5.8/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu@json.pot
-Show calculator error messages
-show shortcuts on tips tab
-open place folders in Nemo by default
-add "app info" to app context menus when pamac-manager is available
=> [Cinnamenu@json] A few tweaks

Sensors@claudiux/files/Sensors@claudiux/README.md
README.md updated to explain the new feature.
=> [Sensors@claudiux] v3.0.3 - Update README.md

sound150@claudiux/files/sound150@claudiux/5.8/applet.js, sound150@claudiux/files/sound150@claudiux/5.8/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
Fixes alignment error, like sound@cinnamon.org for cinnamon 5.8.
=> [sound150@claudiux] v4.0.0 - Cinnamon 5.8

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/README.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/lib/checkDependencies.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/scripts/make_smartctl_usable_by_sudoers.sh, Sensors@claudiux/files/Sensors@claudiux/scripts/pkexec_make_smartctl_usable_by_sudoers.sh
Fixes issues flagged by Nitrooo on: https://cinnamon-spices.linuxmint.com/applets/view/337#count
Fixes #4917
=> [Sensors@claudiux] v3.1.0 - Fixes issues for Manjaro and Arch

app-launcher@mchilli/files/app-launcher@mchilli/widgets.py
Fixes issue flagged by @likengmx: https://cinnamon-spices.linuxmint.com/applets/view/344#count
=> app-launcher@mchilli: fix settings doesn't open

CinnVIIStarkMenu@NikoKrause/info.json
If @NikoKrause is no longer interested in being the current maintainer of this applet then I would like my name to be put as the current owner as he seems to no longer be active on github. I would of course be happy to relinquish control back to him in the future should he wish that.
=> [CinnVIIStarkMenu@NikoKrause] Change author name

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/applet.js
Use a different method to prevent category button missellection by calculating tangent of mouse movement instead of St.polygon leave event
Fixes: #4641
@NikoKrause
=> [CinnVIIStarkMenu@NikoKrause] Fix bug causing triangle to appear on menu.

weather@mockturtl/files/weather@mockturtl/po/nl.po
=> weather@mockturtl: update for Dutch translation

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/README.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/scripts/make_smartctl_usable_by_sudoers.sh
=> [Sensors@claudiux] v3.1.1 - Fixes #4929

CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/appUtils.js, CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/4.2/applet.js, CinnVIIStarkMenu@NikoKrause/files/CinnVIIStarkMenu@NikoKrause/metadata.json
Allow use of special chars in web search
+replace use of some util.js utility functions with js natives.
Fixes: #4476
=> CinnVIIStarkMenu@NikoKrause: Bug fix.

.github/CODEOWNERS, skeuos-remix@benlazhar.com/files/skeuos-remix@benlazhar.com/metadata.json, skeuos-remix@benlazhar.com/info.json
@rcalixte This PR changes the CODEOWNERS file.
=> [skeuos-remix] fix author name

app-launcher@mchilli/files/app-launcher@mchilli/dialogs.py
add feature by @SelfMadeSystem: https://cinnamon-spices.linuxmint.com/applets/view/344#count
=> app-launcher@mchilli: select a file will open with xdg-open

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/browserHistory.js, Cinnamenu@json/files/Cinnamenu@json/4.0/categoriesview.js, Cinnamenu@json/files/Cinnamenu@json/4.0/display.js, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/5.8/applet.js, Cinnamenu@json/files/Cinnamenu@json/5.8/browserHistory.js, Cinnamenu@json/files/Cinnamenu@json/5.8/categoriesview.js, Cinnamenu@json/files/Cinnamenu@json/5.8/display.js, Cinnamenu@json/files/Cinnamenu@json/5.8/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
+improve category button mis-selection method.
=> [Cinnamenu@json] Improve search performance

Sensors@claudiux/files/Sensors@claudiux/po/cs.po, weather@mockturtl/files/weather@mockturtl/po/cs.po
Czech translation update for applets
=> Sensors@claudiux, weather@mockturtl

qredshift@quintao/README.md, qredshift@quintao/files/qredshift@quintao/applet.js, qredshift@quintao/files/qredshift@quintao/metadata.json, qredshift@quintao/files/qredshift@quintao/po/fr.po, qredshift@quintao/files/qredshift@quintao/po/qredshift@quintao.pot
@raphaelquintao
Hi Raphael,
This PR fixes #4559 and fixes #4473.
I hope this suits you.
=> [qredshift@quintao] v1.7.5 - Fixes #4559 and #4473

desaturate-all@hkoosha/files/desaturate-all@hkoosha/metadata.json
I noticed that people usually search "gray" or "grayscale" to search this applets. 
I added keyword "gray" in the description so that it could be searchable.
If you have better description, please edit it.
=> Add more description

Cinnamenu@json/files/Cinnamenu@json/4.0/contextmenu.js, Cinnamenu@json/files/Cinnamenu@json/5.8/applet.js, Cinnamenu@json/files/Cinnamenu@json/5.8/appsview.js, Cinnamenu@json/files/Cinnamenu@json/5.8/categoriesview.js, Cinnamenu@json/files/Cinnamenu@json/5.8/contextmenu.js, Cinnamenu@json/files/Cinnamenu@json/5.8/display.js, Cinnamenu@json/files/Cinnamenu@json/5.8/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/5.8/sidebar.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu@json.pot
add options to hide sidebar and categories list (5.8 version only)
+separate settings(administration+preferences) from apps in all applications category  (5.8 version only)
+add "open containing folder" to context menu of file search results.
+update .pot file
=> [Cinnamenu@json] Add layout options

Cinnamenu@json/files/Cinnamenu@json/po/pt.po
Update Portuguese translation (pt.po)
=> [Cinnamenu@json] Update Portuguese(pt) translation

weather@mockturtl/CHANGELOG.md, weather@mockturtl/files/weather@mockturtl/3.8/weather-applet.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/src/3_8/location_services/nominatim.ts
Fix nominatim not getting location data due to API changes. Related issues:
* Fix #4983 
* Fix #4981
* Fix #4980
Not nice, but issues that were supposed to be closed with https://github.com/linuxmint/cinnamon-spices-applets/pull/4804 : 
* Resolve #4801 
* Resolve #4800
* Resolve #4780
=> weather@mockturtl 3.3.1 - Fix location search

networkmonitor@axel358/files/networkmonitor@axel358/po/networkmonitor@axel358.pot
@axel358 Creating a template file for translations
=> networkmonitor@axel358: Create .pot file

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/appsview.js, Cinnamenu@json/files/Cinnamenu@json/4.0/categoriesview.js, Cinnamenu@json/files/Cinnamenu@json/4.0/contextmenu.js, Cinnamenu@json/files/Cinnamenu@json/4.0/display.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/4.0/sidebar.js, Cinnamenu@json/files/Cinnamenu@json/4.0/suggestions.js, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/5.8/applet.js, Cinnamenu@json/files/Cinnamenu@json/5.8/appsview.js, Cinnamenu@json/files/Cinnamenu@json/5.8/categoriesview.js, Cinnamenu@json/files/Cinnamenu@json/5.8/contextmenu.js, Cinnamenu@json/files/Cinnamenu@json/5.8/display.js, Cinnamenu@json/files/Cinnamenu@json/5.8/sidebar.js, Cinnamenu@json/files/Cinnamenu@json/5.8/suggestions.js, Cinnamenu@json/files/Cinnamenu@json/5.8/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Add show categories and show sidebar options to 4.0 version of applet.
=> [Cinnamenu@json] Add layout options to 4.0 version.

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/appsview.js, Cinnamenu@json/files/Cinnamenu@json/4.0/contextmenu.js, Cinnamenu@json/files/Cinnamenu@json/4.0/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/5.8/applet.js, Cinnamenu@json/files/Cinnamenu@json/5.8/appsview.js, Cinnamenu@json/files/Cinnamenu@json/5.8/contextmenu.js, Cinnamenu@json/files/Cinnamenu@json/5.8/settings-schema.json, Cinnamenu@json/files/Cinnamenu@json/metadata.json, Cinnamenu@json/files/Cinnamenu@json/po/Cinnamenu@json.pot
(right click on blank part of apps view to toggle option)
+update .pot file
=> [Cinnamenu@json] Add option to show all apps in one list.

c-eyes@anaximeno/files/c-eyes@anaximeno/4.2/applet.js, c-eyes@anaximeno/files/c-eyes@anaximeno/5.4/applet.js, c-eyes@anaximeno/files/c-eyes@anaximeno/metadata.json, c-eyes@anaximeno/files/c-eyes@anaximeno/po/c-eyes@anaximeno.pot, c-eyes@anaximeno/files/c-eyes@anaximeno/po/es.po, c-eyes@anaximeno/files/c-eyes@anaximeno/po/fr.po, c-eyes@anaximeno/files/c-eyes@anaximeno/po/hu.po, c-eyes@anaximeno/files/c-eyes@anaximeno/po/pt.po
- Made a fix regarding the deactivate on fullscreen option
- Add portuguese translation + update other translations
=> [c-eyes@anaximeno]: Update to 1.13.5

sessionManager@scollins/files/sessionManager@scollins/po/uk.po
Thank you for making LinuxMint!
Please consider adding Ukrainian translation for sessionManager
=> Add Ukrainian translation for sessionManager

radio@driglu4it/files/radio@driglu4it/po/uk.po
=> Add Ukrainian translation for radio@driglu4it

cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/po/uk.po
=> Add Ukrainian translation for cinnamon-timer

github-projects@morgan-design.com/files/github-projects@morgan-design.com/po/uk.po
=> Add Ukrainian translation for github-projects

placesCenter@scollins/files/placesCenter@scollins/po/uk.po
=> Add Ukrainian translation for placesCenter

ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/po/uk.po
=> Add Ukrainian translation for ScreenShot+RecordDesktop

placesCenter@scollins/files/placesCenter@scollins/po/eu.po, sessionManager@scollins/files/sessionManager@scollins/po/eu.po
=> Add basque (eu) translation of sessionManager@scollins

Cinnamenu@json/files/Cinnamenu@json/4.0/applet.js, Cinnamenu@json/files/Cinnamenu@json/4.0/utils.js, Cinnamenu@json/files/Cinnamenu@json/5.8/applet.js, Cinnamenu@json/files/Cinnamenu@json/5.8/utils.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
\+ fix startpage web search not working
\+ fix panel covering menu in cinnamon 5.8
Fixes: #5018
=> [Cinnamenu@json] Allow 2 search terms separated by a space

Radio3.0@claudiux/files/Radio3.0@claudiux/po/sv.po
Add Swedish translation.
What a great radio applet! Thanks!
=> Radio3.0@claudiux: Add sv.po

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/stations/Radio3.0_EXAMPLES.json
More than 300 radio stations in Radio3.0_EXAMPLES.json
=> [Radio3.0@claudiux] v1.6.0 - More than 300 radio stations in Radio3.0_EXAMPLES.json

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
Sometimes (often), the title also contains the artist's name. This version attempts to distinguish between the artist and the song title.
=> [sound150@claudiux] v4.2.0 - Try to distinguish between the artist and the song title

sync@szlldm/files/sync@szlldm/applet.js, sync@szlldm/files/sync@szlldm/po/ko.po, sync@szlldm/files/sync@szlldm/po/sync@szlldm.pot
Add ko.po file and modify text variable to add Korean translation
- Changed text variable value in applet.js
- Added ko.po and pot file
=> Add Korean translation

smallcalc_applet@lerc.sds/files/smallcalc_applet@lerc.sds/applet.js, smallcalc_applet@lerc.sds/files/smallcalc_applet@lerc.sds/metadata.json, smallcalc_applet@lerc.sds/files/smallcalc_applet@lerc.sds/settings-schema.json, smallcalc_applet@lerc.sds/files/smallcalc_applet@lerc.sds/stylesheet.css
@lerc
See https://github.com/orgs/linuxmint/discussions/193
=> [smallcalc_applet@lerc.sds] Allows the user to define the precision for the result

moonphase@techi-freki/files/moonphase@techi-freki/js/moon.js, moonphase@techi-freki/files/moonphase@techi-freki/metadata.json, moonphase@techi-freki/files/moonphase@techi-freki/po/fr.po, moonphase@techi-freki/files/moonphase@techi-freki/po/moonphase@techi-freki.pot
@Techi-Freki 
Thanks for this applet! Adopted!
It now supports translations. I've added the French translation.
I hope you'll find it useful.
Claudiux
=> [moonphase@techi-freki] v0.0.2 - Allows translations + French translation

IntelTurboBoost@wsmenezes/README.md
=> IntelTurboBoost@wsmenezes: update README.md for better installation steps.

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/metadata.json
=> v4.3.0 - Fixes 5005: Icon color changing with theme

moonphase@techi-freki/files/moonphase@techi-freki/js/moon.js, moonphase@techi-freki/files/moonphase@techi-freki/js/moonPhase.js, moonphase@techi-freki/files/moonphase@techi-freki/po/moonphase@techi-freki.pot, moonphase@techi-freki/files/moonphase@techi-freki/settings-schema.json
Display of phase name and/or phase percentage can be independently configured for the label and the tooltip.
=> [moonphase@techi-freki] Adds percentage display to label and tooltip.

Cinnamenu@json/files/Cinnamenu@json/po/it.po, IntelTurboBoost@wsmenezes/files/IntelTurboBoost@wsmenezes/po/it.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/it.po, Sensors@claudiux/files/Sensors@claudiux/po/it.po, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/it.po, calendar@simonwiles.net/files/calendar@simonwiles.net/po/it.po, cheaty@centurix/files/cheaty@centurix/po/it.po, cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/po/it.po, gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/it.po, moonphase@techi-freki/files/moonphase@techi-freki/po/it.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/it.po, qredshift@quintao/files/qredshift@quintao/po/it.po, restart-cinnamon@kolle/files/restart-cinnamon@kolle/po/it.po, shadowsocks-switch@Klavionik/files/shadowsocks-switch@Klavionik/po/it.po, smallcalc_applet@lerc.sds/files/smallcalc_applet@lerc.sds/po/it.po, spices-notifier@germanfr/files/spices-notifier@germanfr/po/it.po, sync@szlldm/files/sync@szlldm/po/it.po, uiscaler@joka42/files/uiscaler@joka42/po/it.po, vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/po/it.po, weather@mockturtl/files/weather@mockturtl/po/it.po
Hi,
I've reviewed and updated some translations for Italian language and added some new ones :D
=> Adds/updates Italian translation for some applets

CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/po/it.po, c-eyes@anaximeno/files/c-eyes@anaximeno/po/it.po, moonphase@techi-freki/files/moonphase@techi-freki/po/it.po, networkmonitor@axel358/files/networkmonitor@axel358/po/it.po, power-profiles@rcalixte/files/power-profiles@rcalixte/po/it.po, stacks@centurix/files/stacks@centurix/po/it.po, wallpaper-slideshow@amaan-mohib/files/wallpaper-slideshow@amaan-mohib/po/it.po
Hi,
With this pull request we'll reach 100% in Italian translations 😃
=> Adds and reviews Italian translations for other applets

weather@mockturtl/files/weather@mockturtl/po/fr.po
=> [weather@mockturtl]: Update the French translation

moonphase@techi-freki/files/moonphase@techi-freki/po/ru.po
Adding Russian translation. Thank you for your contribution @Severga!
=> Adding russian from Severga

moonphase@techi-freki/files/moonphase@techi-freki/metadata.json
Sorry, forgot to update the version in metadata.json.
=> moonphase@techi-freki: updating version for Russian commit.

moonphase@techi-freki/files/moonphase@techi-freki/js/moonPhase.js, moonphase@techi-freki/files/moonphase@techi-freki/metadata.json
Bug fix for #5072. Thank you @Gr3q!
=> Moonphase@techi freki/bug fix #5072

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot
Perhaps an alternative solution for #5088 and #3979.
=> [sound150@claudiux] v4.4.0 - Always allow microphone to be reactivated

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/checkDependencies.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json
Fixes the bug reported by @Severga on https://cinnamon-spices.linuxmint.com/applets/view/360#count
=> [Radio3.0@claudiux] v1.8.1 - Updated dependencies.js for Soup3 - Bugfix

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/checkDependencies.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json
=> [Radio3.0@claudiux] v1.9.1 - Fixes #5097 and removes mpv-mpris dependency for certain distros

MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/applet.js
Supersedes #5100.
Thanks @sphh !
=> Fix TextDecoder usage

MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/applet.js, MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/lib/to-string.js, MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/metadata.json, MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/settings-schema.json
=> [MuteToggler@jebeaudet.com] Fixes #5102

MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/applet.js, MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/po/MuteToggler@jebeaudet.com.pot, MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/po/fr.po
@jebeaudet This PR allows all messages to be translated and offers a French translation. I hope you'll find it to your liking.
=> [MuteToggler@jebeaudet.com] Allow translations + French translation

MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/applet.js, MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/po/MuteToggler@jebeaudet.com.pot, MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/po/fr.po, MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/settings-schema.json
@jebeaudet 
This PR allows users to choose between solid and symbolic icons.
=> [MuteToggler@jebeaudet.com] Allow the use of symbolic icons

Cinnamenu@json/files/Cinnamenu@json/5.8/applet.js, Cinnamenu@json/files/Cinnamenu@json/5.8/sidebar.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
Fix logout button not working with cinnamon 6.0
fixes: #5134
=> [Cinnamenu@json] Fix logout button not working

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/README.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot
Includes changes from https://github.com/linuxmint/cinnamon/pull/11913/commits/dce7bbdeb02515ded0b39739569b68a6d9b464b1
Thanks to @sphh!
=> [sound150@claudiux] v4.5.0 - Adds a shift-middle click action

MonitorInputSource@klangman/files/MonitorInputSource@klangman/applet.js, MonitorInputSource@klangman/files/MonitorInputSource@klangman/metadata.json, MonitorInputSource@klangman/files/MonitorInputSource@klangman/po/MonitorInputSource@klangman.pot
1 Remove a global app variable so that >1 instances can work 
2 Set the max-instances to -1
=> [MonitorInputSource@klangman] Allow multiple applet instances

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/01_bug_report.yml, .github/ISSUE_TEMPLATE/02_feature_request.yml, healthyeyes@ipolozov/info.json
=> Update maintainer for healthyeyes@ipolozov per #5146

MonitorInputSource@klangman/README.md, MonitorInputSource@klangman/files/MonitorInputSource@klangman/applet.js, MonitorInputSource@klangman/files/MonitorInputSource@klangman/po/MonitorInputSource@klangman.pot
Added a help menu item that opens a browser window to the spices page
Added some more information to the README.md to explain the applet menu items do and how to use them
=> [MonitorInputSource@klangman] Added a "help" menu item

healthyeyes@ipolozov/files/healthyeyes@ipolozov/applet.js
Fixed a bug where the colour would change back immediately after clicking it if the time was the same. Also added some logging.
=> healthyeyes@ipolozov - Fixed a bug where the colour would change back immediately

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/01_bug_report.yml, .github/ISSUE_TEMPLATE/02_feature_request.yml, radio@driglu4it/info.json
Updating radio@driglu4it per #5174
=> Updating templates

cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/po/ru.po
Use short hours/minuts/seconds besouse applet no have different variant translation for single/multiple values 1 hour, 2 hours. Short translation give best UI looks
=> Update Russian translation for cinnamon-timer@jake1164

kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/fi.po, kdeccc@Severga/files/kdeccc@Severga/po/fi.po
KDE Connect to kdeccc@Severga and kdecapplet@joejoetv
Written and tested on Mint 21.3
=> New Finnish translations

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/htmlEncodeDecode.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json
=> [Radio3.0@claudiux] v1.11.3 - Minor bugfixes. Maybe fixes #5201

CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po, MonitorInputSource@klangman/files/MonitorInputSource@klangman/po/it.po, MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/po/it.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/it.po, azan@fahri.nurul.id/files/azan@fahri.nurul.id/po/it.po, backgroundroll@Sokawaii25/files/backgroundroll@Sokawaii25/po/it.po, batterypower@joka42/files/batterypower@joka42/po/it.po, better-backgrounds@simonmicro/files/better-backgrounds@simonmicro/po/it.po, bing-wallpaper@starcross.dev/files/bing-wallpaper@starcross.dev/po/it.po, bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/po/it.po, calc-js@ptandler/files/calc-js@ptandler/po/it.po, cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/po/it.po, sound150@claudiux/files/sound150@claudiux/po/it.po, ssm@Severga/files/ssm@Severga/po/it.po
Hi,
I've added and reviewed some of the Italian translations, to achieve the 100% translated :)
Have a nice day
=> Adds new Italian translations

CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po
Hi,
I saw that there was 19 new lines to translate on the applet CassiaWindowList@klangman.
Here they are, have a nice day :D
=> Updates Italian translations for CassiaWindowList@klangman

CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/hu.po
Update for the last unfinished translation
=> Update for Hungarian translation of CassiaWindowList@klangman applet

Radio3.0@claudiux/files/Radio3.0@claudiux/po/hu.po
Update for Hungarian translation of Radio3.0 applet.
THX @claudiux
=> Update for Hungarian translation of Radio3.0 applet

moonphase@techi-freki/files/moonphase@techi-freki/js/moon.js, moonphase@techi-freki/files/moonphase@techi-freki/metadata.json
=> [moonphase@techi-freki] Fixes day 28 bug

anime-wallpaper@flyflyan/LICENSE, anime-wallpaper@flyflyan/README.zh_CN.md, anime-wallpaper@flyflyan/files/anime-wallpaper@flyflyan/applet.js, anime-wallpaper@flyflyan/files/anime-wallpaper@flyflyan/settings-schema.json
1. fix the context switch does not work.
2. Modify the README.md.
3. add README.zn_CN.md and LICENSE.
4. Modify the Image Source API option.
5. Turn off the log printing by default
=> anime-wallpaper@flyflyan: bug fixes and file updates

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/01_bug_report.yml, .github/ISSUE_TEMPLATE/02_feature_request.yml, anime-wallpaper@flyflyan/info.json
=> Update author info

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/README.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/po/Radio3.0@claudiux.pot, Radio3.0@claudiux/files/Radio3.0@claudiux/po/fr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json
Also updated .pot and fr.po files.
=> v1.12.0 - Added an option (context menu) to display the volume level near the icon

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot
Also updates .pot and fr.po files.
=> [sound150@claudiux] v4.6.0 - Adds the ability to display the volume level near the icon

bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/metadata.json
=> [bluetooth-battery@zamszowy]: allow multiple applet instances

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/po/Radio3.0@claudiux.pot, Radio3.0@claudiux/files/Radio3.0@claudiux/po/fr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json
Fixes #5246. 
Display of volume level near icon and fixes scrolling problems with Cinnamon prior to 5.1.
=> [Radio3.0@claudiux] v1.13.0 - Fixes #5246

desaturate-all@hkoosha/files/desaturate-all@hkoosha/applet.js, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/desaturate-all@hkoosha.pot, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/fr.po
@hkoosha 
Saves space on the panel. Adds files for translations.
=> [desaturate-all@hkoosha] Change to icon applet. Add .pot and fr.po files.

download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletGui.js
Solves https://github.com/linuxmint/cinnamon-spices-applets/issues/5320
=>  download-and-upload-speed@cardsurf: fix null text label value

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/po/Sensors@claudiux.pot, Sensors@claudiux/files/Sensors@claudiux/po/fr.po
=> v3.2.0 - Adds a menu option to suspend this applet

ipindicator@matus.benko@gmail.com/files/ipindicator@matus.benko@gmail.com/po/hu.po
The translation had to be adjusted.
=> Updated Hungarian translation for the ipindicator applet

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/po/Sensors@claudiux.pot, Sensors@claudiux/files/Sensors@claudiux/po/fr.po, Sensors@claudiux/files/Sensors@claudiux/settings-schema.json
=> v3.4.0 - Added an option in the General tab to display a tooltip or not

Sensors@claudiux/files/Sensors@claudiux/po/es.po
=> Sensors@claudiux. - update es.po

ssm@Severga/files/ssm@Severga/applet.js
Fixing errors flood caused by addressing to inactive net devices (fixes #5356).
Eliminating negative net speed values.
=> [ssm@Severga] Fixing some bugs

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot
=> [sound150@claudiux] v4.7.0 - Adds the ability to redefine multimedia shortcuts

MonitorInputSource@klangman/files/MonitorInputSource@klangman/applet.js
Automatically detect and refresh the monitor input list when the attached monitors change.
=> [MonitorInputSource@klangman] Automatically detect when monitors change

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/lib/util.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json
=> [Sensors@claudiux] v3.5.0 - Subprocess improvement

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/checkTranslations.js, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/to-string.js, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/util.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/po/Radio3.0@claudiux.pot, Radio3.0@claudiux/files/Radio3.0@claudiux/po/fr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json
and adds a button "Open the recordings folder" in YT tab of settings.
=> [Radio3.0@claudiux] v1.14.0 - Improves sub-processes

c-eyes@anaximeno/files/c-eyes@anaximeno/4.2/applet.js, c-eyes@anaximeno/files/c-eyes@anaximeno/4.2/settings-schema.json, c-eyes@anaximeno/files/c-eyes@anaximeno/5.4/applet.js, c-eyes@anaximeno/files/c-eyes@anaximeno/5.4/settings-schema.json, c-eyes@anaximeno/files/c-eyes@anaximeno/metadata.json, c-eyes@anaximeno/files/c-eyes@anaximeno/po/c-eyes@anaximeno.pot
=> c-eyes@anaximeno: increase margin limits, simplify tooltips

temperature@fevimu/files/temperature@fevimu/applet.js, temperature@fevimu/files/temperature@fevimu/metadata.json, temperature@fevimu/files/temperature@fevimu/po/fr.po, temperature@fevimu/files/temperature@fevimu/po/temperature@fevimu.pot, temperature@fevimu/files/temperature@fevimu/settings-schema.json, temperature@fevimu/files/temperature@fevimu/stylesheet.css
=> [temperature@fevimu] Fixes #5405

temperature@fevimu/files/temperature@fevimu/applet.js
=> temperature@fevimu - Fixes #5410

Exit@claudiux/files/Exit@claudiux/5.4/applet.js, Exit@claudiux/files/Exit@claudiux/5.4/settings-schema.json, Exit@claudiux/files/Exit@claudiux/CHANGELOG.md, Exit@claudiux/files/Exit@claudiux/metadata.json, Exit@claudiux/files/Exit@claudiux/po/Exit@claudiux.pot, Exit@claudiux/files/Exit@claudiux/po/fr.po
A solution to[ #12021](https://github.com/linuxmint/cinnamon/issues/12021).
=> Exit@claudiux - v1.1.0 - Adds Log Out Mode option

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/stations/Rock Melodic Radio - AOR MELODIC ROCK HARD ROCK.xspf
Try to minimize disk writes.
Uses class instead of prototype.
=> [Radio3.0@claudiux] v1.15.0

Cinnamenu@json/files/Cinnamenu@json/5.8/applet.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
delay loading of web bookmarks as mitigation for libgda bug causing cinnamon crash
mitigates: #5404
=> Cinnamenu@json: firefox bookmarks bug mitigation

weather@mockturtl/files/weather@mockturtl/po/pt.po
Removed unnecessary colon
Following https://github.com/linuxmint/cinnamon-spices-applets/pull/5435
=> weather@mockturtl: Update Portuguese translation

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json
Prevents data loss.
Code cleanup.
=> [Radio3.0@claudiux] v1.15.1

Radio3.0@claudiux/files/Radio3.0@claudiux/po/sv.po
=> Radio3.0@claudiux: Update sv.po

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language file Weather applet update from pot template file released 2024-01-30.
=> weather@mockturtl Update sv.po 3.4.0

VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/applet.js, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/metadata.json, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/po/VPN-Sentinel@claudiux.pot, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/po/fr.po, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/settings-schema.json
=> [VPN-Sentinel@claudiux] v2.2.2 - Fixes #5449

VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/po/es.po
=> VPN-Sentinel@claudiux - update es.po

Sensors@claudiux/files/Sensors@claudiux/po/cs.po, weather@mockturtl/files/weather@mockturtl/po/cs.po
Sensors@claudiux
weather@mockturtl
=> Sensors@claudiux and weather@mockturtl Czech translation update

directory-menu@torchipeppo/README.md
Update compatibility info on the README now that more tests and fixes are in:
- https://github.com/linuxmint/cinnamon-spices-applets/pull/5451
- https://github.com/linuxmint/cinnamon-spices-applets/pull/5453
=> [directory-menu@torchipeppo] Update README

directory-menu@torchipeppo/files/directory-menu@torchipeppo/metadata.json, directory-menu@torchipeppo/files/directory-menu@torchipeppo/po/directory-menu@torchipeppo.pot
cc @torchipeppo
I believe this way it will be clearer to the users what the functionality of this cool applet is.
=> directory-menu@torchipeppo: Rephrase the description for better comprehension of the functionality

weather@mockturtl/files/weather@mockturtl/po/hu.po
- Fix typos
- Fix wrong weather naming
- Fix wrong use of placeholder {precipStart} instead of {precipEnd}
=> weather@mockturtl: hu.po - Fix Hungarian language minor typos and placeholders

CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/hu.po, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/po/hu.po, calendar@ccprog/files/calendar@ccprog/po/hu.po, directory-menu@torchipeppo/files/directory-menu@torchipeppo/po/hu.po, sct@skulptist.de/files/sct@skulptist.de/po/hu.po
* calendar@ccprog: update hu.po
* CassiaWindowList@klangman: update hu.po
* directory-menu@torchipeppo: add hu.po
* sct@skulptist.de: add hu.po
* VPN-Sentinel@claudiux: update hu.po
=> Multiple cinnamon applet translations & updates for Hungarian language

ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/metadata.json, ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/po/ShutdownMenuWithIcons@LLOBERA.pot, ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/po/da.po, ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/po/de.po, ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/po/es.po, ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/po/fr.po, ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/po/hu.po, ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/po/it.po, ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/po/nl.po, ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/po/sv.po, ShutdownMenuWithIcons@LLOBERA/files/ShutdownMenuWithIcons@LLOBERA/po/zh_CN.po
=> ShutdownMenuWithIcons@LLOBERA: Add version to metadata and update translation templates

PanelTranslator@klangman/files/PanelTranslator@klangman/applet.js
1. Add the current from/to language to the tooltip text for Cinnamon 5+
2. Trim clipboard text before inserting into text box
3. Fix translating text that contains double quotes
=> [PanelTranslator@klangman] Improve Tooltips and fixes

PanelTranslator@klangman/files/PanelTranslator@klangman/metadata.json, PanelTranslator@klangman/files/PanelTranslator@klangman/po/PanelTranslator@klangman.pot, PanelTranslator@klangman/files/PanelTranslator@klangman/po/es.po, PanelTranslator@klangman/files/PanelTranslator@klangman/po/hu.po
cc @klangman I wasn't sure what you wanted for the version.
=> PanelTranslator@klangman: Update metadata.json, translation template, and translations

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/settings-schema.json
=> [Sensors@claudiux] v3.5.3

sct@skulptist.de/files/sct@skulptist.de/applet.js, sct@skulptist.de/files/sct@skulptist.de/metadata.json, sct@skulptist.de/files/sct@skulptist.de/po/de.po, sct@skulptist.de/files/sct@skulptist.de/po/es.po, sct@skulptist.de/files/sct@skulptist.de/po/fr.po, sct@skulptist.de/files/sct@skulptist.de/po/hu.po, sct@skulptist.de/files/sct@skulptist.de/po/it.po, sct@skulptist.de/files/sct@skulptist.de/po/sct@skulptist.de.pot, sct@skulptist.de/files/sct@skulptist.de/settings-schema.json
some code cleanup, fixed typos and necessarily updated translations
=> sct@skulptist.de 1.2.3

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json
Sometimes it's better to write to disk more often, to avoid losing data...
=> [Radio3.0@claudiux] - v1.16.0 - Bugfixes

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json
Slight improvements in settings and context menu.
=> [Radio3.0@claudiux] v1.16.1 - Slight improvements

suspend@janax/CHANGELOG.md, suspend@janax/files/suspend@janax/applet.js, suspend@janax/files/suspend@janax/metadata.json, suspend@janax/files/suspend@janax/po/da.po, suspend@janax/files/suspend@janax/po/de.po, suspend@janax/files/suspend@janax/po/es.po, suspend@janax/files/suspend@janax/po/fr.po, suspend@janax/files/suspend@janax/po/hr.po, suspend@janax/files/suspend@janax/po/hu.po, suspend@janax/files/suspend@janax/po/it.po, suspend@janax/files/suspend@janax/po/pt_BR.po, suspend@janax/files/suspend@janax/po/ru.po, suspend@janax/files/suspend@janax/po/suspend@janax.pot, suspend@janax/files/suspend@janax/po/sv.po, suspend@janax/files/suspend@janax/po/zh_CN.po, suspend@janax/files/suspend@janax/settings-schema.json
1. Limit count down timer to a minimum of 1 rather than 0
2. Added a config button to open Power Management (convenient access to other suspend related options)
3. Added CHANGELOG.md
=> [suspend@janax] Minor fix

PanelTranslator@klangman/files/PanelTranslator@klangman/applet.js, PanelTranslator@klangman/files/PanelTranslator@klangman/metadata.json, PanelTranslator@klangman/files/PanelTranslator@klangman/po/PanelTranslator@klangman.pot, PanelTranslator@klangman/files/PanelTranslator@klangman/po/es.po, PanelTranslator@klangman/files/PanelTranslator@klangman/po/fr.po, PanelTranslator@klangman/files/PanelTranslator@klangman/po/hu.po
When the TTS command results in stderr text, show it on the menu. Typically this is a message stating that the language does not support TTS.
=> [PanelTranslator@klangman] Show text-to-speech errors

Cinnamenu@json/files/Cinnamenu@json/5.8/utils.js
=> [Cinnamenu@json] Fix tooltips going off screen

ssm@Severga/files/ssm@Severga/applet.js
Eliminating error which appears when removing the applet from panel
=> [ssm@Severga] Eliminating error which appears when removing the applet from panel

sound150@claudiux/files/sound150@claudiux/po/sv.po
=> sound150@claudiux: Update sv.po

batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/5.4/applet.js, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/CHANGELOG.md, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/metadata.json, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/batterymonitor@pdcurtis.pot, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/da.po, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/de.po, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/es.po, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/fr.po, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/hr.po, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/hu.po, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/it.po, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/ru.po, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/sv.po, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/tr.po, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/uk.po, batterymonitor@pdcurtis/files/batterymonitor@pdcurtis/po/zh_CN.po
* Added a label for the applet menu slider
* Added automatic updating of the applet menu when the slider is adjusted
* Fixed a rounding bug between the slider and configuration option
* Fixed a potential display bug when the charging level reached 100%
* Updated strings
* Cleaned up metadata and CHANGELOG files
* Closes #5500
=> batterymonitor@pdcurtis: Version 2.2.0

MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/po/de.po
@Matthias-Hermsdorf @erwn16 @mikehaertl @AbulfaslAhmadi
Can you please check my translations?
=> MuteToggler@jebeaudet.com: add german translation

c-eyes@anaximeno/files/c-eyes@anaximeno/4.2/applet.js, c-eyes@anaximeno/files/c-eyes@anaximeno/4.2/eyeModes.js, c-eyes@anaximeno/files/c-eyes@anaximeno/4.2/settings-schema.json, c-eyes@anaximeno/files/c-eyes@anaximeno/5.4/applet.js, c-eyes@anaximeno/files/c-eyes@anaximeno/5.4/eyeModes.js, c-eyes@anaximeno/files/c-eyes@anaximeno/5.4/settings-schema.json, c-eyes@anaximeno/files/c-eyes@anaximeno/metadata.json, c-eyes@anaximeno/files/c-eyes@anaximeno/po/c-eyes@anaximeno.pot, c-eyes@anaximeno/files/c-eyes@anaximeno/po/da.po, c-eyes@anaximeno/files/c-eyes@anaximeno/po/es.po, c-eyes@anaximeno/files/c-eyes@anaximeno/po/fr.po, c-eyes@anaximeno/files/c-eyes@anaximeno/po/hu.po, c-eyes@anaximeno/files/c-eyes@anaximeno/po/it.po, c-eyes@anaximeno/files/c-eyes@anaximeno/po/pt.po, c-eyes@anaximeno/files/c-eyes@anaximeno/po/ru.po
feat: Allow to configure the eye update sensitivity
chore: Change the eye mode fill settings
=> c-eyes@anaximeno: Update to v1.14.1

sound150@claudiux/files/sound150@claudiux/5.4/applet.js
=> [sound150@claudiux] Fixes #5576

calendar@ccprog/files/calendar@ccprog/3.8/icon.png, calendar@ccprog/files/calendar@ccprog/5.2/icon.png
=> [calendar@ccprog] Fixes #5566

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
=> [sound150@claudiux] v6.3.1 - Fixes #5576

ScreenShot+RecordDesktop@tech71/files/ScreenShot+RecordDesktop@tech71/applet.js
fixes: #5027
Don't know what changed, if anything, to cause this bug but this fixes it.
@icarter09
=> [ScreenShot+RecordDesktop@tech71] Bugfix

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/volumeslider.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/scripts/mpvWatchTitle.lua
=> v1.17.6 - Fixes #5571

MonitorInputSource@klangman/CHANGELOG.md, MonitorInputSource@klangman/files/MonitorInputSource@klangman/applet.js, MonitorInputSource@klangman/files/MonitorInputSource@klangman/metadata.json, MonitorInputSource@klangman/files/MonitorInputSource@klangman/po/MonitorInputSource@klangman.pot, MonitorInputSource@klangman/files/MonitorInputSource@klangman/po/da.po, MonitorInputSource@klangman/files/MonitorInputSource@klangman/po/es.po, MonitorInputSource@klangman/files/MonitorInputSource@klangman/po/fr.po, MonitorInputSource@klangman/files/MonitorInputSource@klangman/po/hu.po, MonitorInputSource@klangman/files/MonitorInputSource@klangman/po/it.po
1. Fixed a minor bug
2. added a version number
3. added a changelog
=> [MonitorInputSource@klangman] Minor fix, version number, changelog

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
Improved seeker. Elapsed time and duration are now displayed on either side of the seeker in the menu.
=> [sound150@claudiux] v6.5.0 - Improved seeker

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
=> [sound150@claudiux] v6.5.2 - Fixes  #5604

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/scripts/run_playerctld.sh
Minor bugfix.
Runs playerctld, if exists.
=> [sound150@claudiux] v6.5.3 - Ready for LM 22

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/scripts/kill_playerctld.sh
=> [sound150@claudiux] Fixes #5616

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
=> [sound150@claudiux] v6.5.5 - Fixes #5622

anime-wallpaper@flyflyan/files/anime-wallpaper@flyflyan/po/de.po
@Matthias-Hermsdorf @mikehaertl @AbulfaslAhmadi
Can you please check my translations?
=> anime-wallpaper@flyflyan: adds german translation

backgroundroll@Sokawaii25/files/backgroundroll@Sokawaii25/po/de.po
@Matthias-Hermsdorf @mikehaertl @AbulfaslAhmadi
Can you please check my translations?
=> backgroundroll@Sokawaii25: adds german translation

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
The Previous, Next, Stop and Close buttons act on the Radio3.0@claudiux applet.
=> [sound150@claudiux] v6.6.0 - Greater interaction with Radio3.0@claudiux

sound150@claudiux/files/sound150@claudiux/5.4/icons/audio-volume-high-with-mic-disabled-symbolic.svg, sound150@claudiux/files/sound150@claudiux/5.4/icons/audio-volume-low-with-mic-disabled-symbolic.svg, sound150@claudiux/files/sound150@claudiux/5.4/icons/audio-volume-medium-with-mic-disabled-symbolic.svg, sound150@claudiux/files/sound150@claudiux/5.4/icons/audio-volume-muted-with-mic-disabled-symbolic.svg, sound150@claudiux/files/sound150@claudiux/5.4/icons/audio-volume-overamplified-with-mic-disabled-symbolic.svg, sound150@claudiux/files/sound150@claudiux/5.4/icons/audio-x-generic-with-mic-disabled-symbolic.svg, sound150@claudiux/files/sound150@claudiux/5.4/icons/highlights.css, sound150@claudiux/files/sound150@claudiux/5.4/icons/media-optical-cd-audio-with-mic-disabled-symbolic.svg, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
The new icons are more pleasing.
=> [sound150@claudiux] v6.7.0 - New icons

Sensors@claudiux/files/Sensors@claudiux/po/es.po
=> Sensors@claudiux - update es.po

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fi.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po
as requested by @angelotux on https://cinnamon-spices.linuxmint.com/applets/view/306
=> [sound150@claudiux] v6.7.2 - New option: whether show OSD on startup

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json
As requested by @JackDawson2026 on https://cinnamon-spices.linuxmint.com/applets/view/337.
=> [Sensors@claudiux] v3.6.2 - Displays the tooltip regardless of the refresh interval

weather@mockturtl/files/weather@mockturtl/po/fi.po
Updated translation to weather applet. I have used the words used by the Finnish Meteorological Institute. In addition, I also improved other texts to make it more comfortable for the user to read.
My source is ilmatieteenlaitos dot fi
=> Updated fi-language pack weather@mockturtl

weather@mockturtl/files/weather@mockturtl/po/lt.po
after 12 years, full translate in to Lithuania language
=> Updated Lithuania lt.po file

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fi.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po
Fixes #5678.
Adds an option to keep open the player list in menu.
=> [sound150@claudiux] v6.7.3 - Fixes #5678

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
Fixes #5682 and many other bugs.
=> [SpicesUpdate@claudiux] v7.1.0 for Cinnamon 6.0

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
=> v7.1.2 - Fixes #5682: also works on distributions that don't use mintupdate

sound150@claudiux/files/sound150@claudiux/po/es.po
=> sound150@claudiux - update es.po

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fi.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po
=> [sound150@claudiux] v6.8.0 - Fixes #5721: Adds Previous and Next track shortcuts

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fi.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po
=> [sound150@claudiux] v6.9.1 - Fixes #5767

pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/applet.js, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/ca.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/da.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/de.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/es.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/fi.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/fr.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/hr.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/hu.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/it.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/nl.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/pl.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/pomodoro@gregfreeman.org.pot, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/pt_BR.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/sv.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/tr.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/uk.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/zh_CN.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/settings-schema.json, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/sound.js, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/timer.js
* Add new hotkey feature to open applet menu
* Add new feature to optionally show a dialog after a pomodoro ends just like with a short break so you don't miss your stopping point.
* Updated code to use ES6 classes
=> pomodoro@gregfreeman.org: New features: hotkey and pomodoro finished dialog

pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/applet.js, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/metadata.json, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/ca.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/da.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/de.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/es.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/fi.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/fr.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/hr.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/hu.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/it.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/nl.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/pl.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/pomodoro@gregfreeman.org.pot, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/pt_BR.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/sv.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/tr.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/uk.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/zh_CN.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/settings-schema.json
* This adds an option to start pomodoro immediately on startup/applet load/boot, feature requested by a user.
=> pomodoro@gregfreeman.org: Add feature to start pomodoro automatically on load

mylauncher@markbokil.com/info.json
=> mylauncher@markbokil.com: Update maintainer

rancher@centurix/files/rancher@centurix/applet.js, rancher@centurix/files/rancher@centurix/homestead.js
Change all reference to Main.Util.spawnCommandLine() to Util.spawnCommandLine()
=> Change references to Main.Util.spawnCommandLine()

stacks@centurix/files/stacks@centurix/applet.js, stacks@centurix/files/stacks@centurix/dockercompose.js
Fix references to Main.Util.spawnCommandLine() to Util.spawnCommandLine()
=> Fix references to Main.Util.spawnCommandLine()

betterlock/files/betterlock/applet.js, betterlock/files/betterlock/settings-schema.json, betterlock/info.json
Added silent notification setting to configuration as requested here: https://github.com/linuxmint/cinnamon-spices-applets/issues/32
=> betterlock: Add silent notifications

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/SU_messageTray.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/constants.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/settings-schema.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/SpicesUpdate@claudiux.pot, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/fr.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/makepot, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/scripts/thumb-downloader.sh
=> v7.4.0 - Now smoother so as not to be blocked by the cinnamon-spices.linuxmint.com server

pomodoro@gregfreeman.org/CHANGELOG.md, pomodoro@gregfreeman.org/README.md, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/settings-schema.json
* Make symbolic icons the default and create separate Changelog
=> pomodoro@gregfreeman.org: Make symbolic icons the default and separate Changelog

pomodoro@gregfreeman.org/CHANGELOG.md, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/applet.js, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/metadata.json, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/ca.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/da.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/de.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/es.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/fi.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/fr.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/hr.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/hu.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/it.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/nl.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/pl.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/pomodoro@gregfreeman.org.pot, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/pt_BR.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/sv.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/tr.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/uk.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/po/zh_CN.po, pomodoro@gregfreeman.org/files/pomodoro@gregfreeman.org/settings-schema.json
* Add option to run custom scripts when short and long breaks start
By user request
=> pomodoro@gregfreeman.org: Add option to run custom scripts when breaks start

gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/pt.po
=> Add Portuguese translation

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
=> [SpicesUpdate@claudiux] v7.4.1 - Fixes #5969

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fi.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/nl.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po
=> [sound150@claudiux] v6.11.0 - Fixes #5967 and improves multimedia shortcuts management

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fi.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/nl.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po
=> v6.12.0 - Adds a keyboard shortcut to switch between players

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fi.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/nl.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po
=> [sound150@claudiux] v6.13.0 - Fixes #6008

mybookmarks@markbokil.com/files/mybookmarks@markbokil.com/applet.js
Handle legacy configuration options better
=> mybookmarks@markbokil.com: Handle legacy configurations correctly

moonphase@techi-freki/files/moonphase@techi-freki/po/ru.po
=> Update Russian translation

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/5.4/icons/audio-volume-high-with-mic-enabled-symbolic.svg, sound150@claudiux/files/sound150@claudiux/5.4/icons/audio-volume-low-with-mic-enabled-symbolic.svg, sound150@claudiux/files/sound150@claudiux/5.4/icons/audio-volume-medium-with-mic-enabled-symbolic.svg, sound150@claudiux/files/sound150@claudiux/5.4/icons/audio-volume-muted-with-mic-enabled-symbolic.svg, sound150@claudiux/files/sound150@claudiux/5.4/icons/audio-volume-overamplified-with-mic-enabled-symbolic.svg, sound150@claudiux/files/sound150@claudiux/5.4/icons/audio-x-generic-with-mic-enabled-symbolic.svg, sound150@claudiux/files/sound150@claudiux/5.4/icons/media-optical-cd-audio-with-mic-enabled-symbolic.svg, sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/README.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fi.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/nl.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po
=> [sound150@claudiux] v6.15.0 - Fixes #6026

weather@mockturtl/files/weather@mockturtl/po/fr.po
Update the fr.po file to the last applet version 3.5.0
=> weather@mockturtl : update French translation to the 3.5.0 version

weather@mockturtl/files/weather@mockturtl/po/de.po
=> weather@mockturtl: Update German translation

weather@mockturtl/files/weather@mockturtl/po/de.po
=> Update German translation

xampp-panel@backids99/files/xampp-panel@backids99/applet.js
=> xampp-panel@backids99: Add more shortcuts to applet

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fi.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/nl.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po
=> [sound150@claudiux] v6.16.0 - Added option: Use the same shortcuts as those defined by Cinnamon

weather@mockturtl/files/weather@mockturtl/po/nl.po
Corrections for some minor mistakes and omissions.
=> weather@mockturtl: minor improvements for Dutch translation

weather@mockturtl/files/weather@mockturtl/po/sv.po
Swedish language file Weather applet update from pot template file released 2024-06-03.
=> weather@mockturtl: Update Swedish translation

moonphase@techi-freki/README.md, multicore-sys-monitor@ccadeptic23/README.md, xsession@claudiux/files/xsession@claudiux/README.md
Applets:
- moonphase@techi-freki @techi-freki 
- multicore-sys-monitor@ccadeptic23
- xsession@claudiux
=> Adds Translations section in README.md

cpufreq@mtwebster/files/cpufreq@mtwebster/applet.js
Fixes cpufreq@mtwebster: make stable and localized frequency format to avoid layout shifts #6064
@mtwebster , will appreciate your review
=> cpufreq@mtwebster: Make panel frequency formatting width stable (#.##)

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
Reported by @Stef-00012 on https://cinnamon-spices.linuxmint.com/applets/view/306
=> [sound150@claudiux] v6.17.0 - Fixes a regression problem

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/01_bug_report.yml, .github/ISSUE_TEMPLATE/02_feature_request.yml, cpufreq@mtwebster/info.json
=> Update cpufreq@mtwebster and templates

c-eyes@anaximeno/files/c-eyes@anaximeno/6.2/applet.js, c-eyes@anaximeno/files/c-eyes@anaximeno/6.2/eyeModes.js, c-eyes@anaximeno/files/c-eyes@anaximeno/6.2/settings-schema.json, c-eyes@anaximeno/files/c-eyes@anaximeno/metadata.json
Fix unintentional deactivation on monitors changed
Improve padding settings
=> c-eyes@anaximeno: Version 2.1.2

weather@mockturtl/files/weather@mockturtl/po/ru.po
=> Update russian translations

search-box@mtwebster/files/search-box@mtwebster/5.4/applet.js, search-box@mtwebster/files/search-box@mtwebster/5.4/settings-schema.json, search-box@mtwebster/files/search-box@mtwebster/CHANGELOG.md, search-box@mtwebster/files/search-box@mtwebster/metadata.json
As requested by @immolo on https://cinnamon-spices.linuxmint.com/applets/view/57
=> [search-box@mtwebster] v2.1.0 - You can choose the colors of the search-box

c-eyes@anaximeno/files/c-eyes@anaximeno/4.2/applet.js, c-eyes@anaximeno/files/c-eyes@anaximeno/5.4/applet.js, c-eyes@anaximeno/files/c-eyes@anaximeno/5.4/settings-schema.json, c-eyes@anaximeno/files/c-eyes@anaximeno/6.2/applet.js, c-eyes@anaximeno/files/c-eyes@anaximeno/6.2/settings-schema.json, c-eyes@anaximeno/files/c-eyes@anaximeno/metadata.json, c-eyes@anaximeno/files/c-eyes@anaximeno/po/c-eyes@anaximeno.pot, c-eyes@anaximeno/files/c-eyes@anaximeno/po/da.po, c-eyes@anaximeno/files/c-eyes@anaximeno/po/es.po, c-eyes@anaximeno/files/c-eyes@anaximeno/po/fr.po, c-eyes@anaximeno/files/c-eyes@anaximeno/po/hu.po, c-eyes@anaximeno/files/c-eyes@anaximeno/po/it.po, c-eyes@anaximeno/files/c-eyes@anaximeno/po/nl.po, c-eyes@anaximeno/files/c-eyes@anaximeno/po/pt.po, c-eyes@anaximeno/files/c-eyes@anaximeno/po/ru.po
- Add information about the mouse click effects split in settings
- Backport some fixes to the 5.4 and 4.2 versions of the applet
- Update translations
=> c-eyes@anaximeno: Version 2.1.3

screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/CHANGELOG.md, screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/applet.js, screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/metadata.json, screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/settings-schema.json
=> [screen-inhibit@mtwebster] v2.1.0 - Fixes #6079

Exit@claudiux/files/Exit@claudiux/5.4/applet.js, Exit@claudiux/files/Exit@claudiux/CHANGELOG.md, Exit@claudiux/files/Exit@claudiux/metadata.json
=> [Exit@claudiux] v1.1.2 - Improves translations

screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/CHANGELOG.md, screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/applet.js, screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/metadata.json, screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/da.po, screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/de.po, screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/es.po, screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/fr.po, screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/hu.po, screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/it.po, screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/nl.po, screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/screen-inhibit@mtwebster.pot, screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/sv.po, screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/zh_CN.po, screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/settings-schema.json
Fixes #6079.
Adds two aggressive modes to block the screensaver.
=> [screen-inhibit@mtwebster] v2.1.2 - Fixes #6079

download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/pt.po, weather@mockturtl/files/weather@mockturtl/po/pt.po
- weather@mockturl
- download-and-upload-speed@cardsurf
=> Update Portuguese translations for some applets

CommandRunner@appdevsw/files/CommandRunner@appdevsw/po/fi.po, CustomApplicationsMenu@LLOBERA/files/CustomApplicationsMenu@LLOBERA/po/fi.po, CustomPlaces@Nicolas01/files/CustomPlaces@Nicolas01/po/fi.po, clipboard-eraser@Techcrafter/files/clipboard-eraser@Techcrafter/po/fi.po, collapsible-systray@feuerfuchs.eu/files/collapsible-systray@feuerfuchs.eu/po/fi.po, commandLauncher@scollins/files/commandLauncher@scollins/po/fi.po, cpu-monitor-text@gnemonix/files/cpu-monitor-text@gnemonix/po/fi.po, darkMode@linuxedo.com/files/darkMode@linuxedo.com/po/fi.po, ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/po/ddcci-multi-monitor@tim-we.pot, ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/po/fi.po, force-quit@cinnamon.org/files/force-quit@cinnamon.org/po/fi.po, gmail@lauritsriple/files/gmail@lauritsriple/po/fi.po
New Finnish language packages. In this batch, there is another applet for which I created a pot file according to Linux Mint instructions.
=> New Finnish language packages

SpiceSpy@claudiux/files/SpiceSpy@claudiux/CHANGELOG.md, SpiceSpy@claudiux/files/SpiceSpy@claudiux/applet.js, SpiceSpy@claudiux/files/SpiceSpy@claudiux/metadata.json, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/SpiceSpy@claudiux.pot, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/es.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/fr.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/it.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/settings-schema.json
* Adds the  number of new translations to the label.
* Adds an option to display only non-zero values in the label.
=> [SpiceSpy@claudiux] v2.1.0

SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/it.po
cc @claudiux (#6125 was merged into the wrong branch)
=> SpiceSpy@claudiux: Update Italian translation

weather@mockturtl/files/weather@mockturtl/po/fi.po
New lines done. A few language improvements, so that the user understands the applet better.
=> Updated Finnish translation

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
=> [sound150@claudiux] v6.17.2 - Fixes #6143

Cinnamenu@json/files/Cinnamenu@json/po/ca.po
small typo correction + better wording
=> Cinnamenu@json: Update ca.po

weather@mockturtl/CHANGELOG.md, weather@mockturtl/files/weather@mockturtl/3.8/weather-applet.js, weather@mockturtl/files/weather@mockturtl/metadata.json, weather@mockturtl/src/3_8/config.ts, weather@mockturtl/src/3_8/location_services/geoip_services/base.ts, weather@mockturtl/src/3_8/location_services/geoip_services/geoclue.ts, weather@mockturtl/src/3_8/location_services/geoip_services/geoip.fedora.ts, weather@mockturtl/src/3_8/location_services/geoip_services/geoiplookup.io.ts, weather@mockturtl/src/3_8/location_services/geoip_services/geojs.io.ts, weather@mockturtl/src/3_8/location_services/geoip_services/ipApi.ts, weather@mockturtl/src/3_8/location_services/nominatim.ts, weather@mockturtl/src/3_8/location_services/tz_lookup.ts, weather@mockturtl/src/3_8/main.ts, weather@mockturtl/src/3_8/providers/visualcrossing/provider.ts, weather@mockturtl/src/3_8/types.ts
* Fix https://github.com/linuxmint/cinnamon-spices-applets/issues/6086
* Fix https://github.com/linuxmint/cinnamon-spices-applets/issues/6137
=> weather@mockturtl update 3.6.3

Sensors@claudiux/files/Sensors@claudiux/po/it.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/it.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/it.po, anime-wallpaper@flyflyan/files/anime-wallpaper@flyflyan/po/it.po, bose@tuuxx/files/bose@tuuxx/po/it.po, ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/po/it.po, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/po/it.po, expressvpn@Hukuta/files/expressvpn@Hukuta/po/it.po, googledrive@pbojan/files/googledrive@pbojan/po/it.po, gpumonitor@axel358/files/gpumonitor@axel358/po/it.po, hideable-applets@cardsurf/files/hideable-applets@cardsurf/po/it.po, ipindicator@matus.benko@gmail.com/files/ipindicator@matus.benko@gmail.com/po/it.po, jalalicalendar@mohammad-sn/files/jalalicalendar@mohammad-sn/po/it.po, mic-level@zamszowy/files/mic-level@zamszowy/po/it.po, nightlight@Severga/files/nightlight@Severga/po/it.po, nightscout@ranneft/files/nightscout@ranneft/po/it.po, notification-mute@jgillula/files/notification-mute@jgillula/po/it.po, notifications-enhanced@hilyxx/files/notifications-enhanced@hilyxx/po/it.po, paneldo@beatlink/files/paneldo@beatlink/po/it.po, password-generator@spencerlommel.com/files/password-generator@spencerlommel.com/po/it.po, screen-inhibit@mtwebster/files/screen-inhibit@mtwebster/po/it.po, shutdown-timer@webum.by/files/shutdown-timer@webum.by/po/it.po, stevedore@centurix/files/stevedore@centurix/po/it.po, website-notifier@cardsurf/files/website-notifier@cardsurf/po/it.po, window-list@zeripath.sdf-eu.org/files/window-list@zeripath.sdf-eu.org/po/it.po
Hi,
In theory with this, we reached now the 100% in Italian translations for all the applets! :)
Have a nice day
=> Updates/Adds Italian translations for various Cinnamon Applets

search-box@mtwebster/files/search-box@mtwebster/CHANGELOG.md, search-box@mtwebster/files/search-box@mtwebster/applet.js, search-box@mtwebster/files/search-box@mtwebster/metadata.json, search-box@mtwebster/files/search-box@mtwebster/po/da.po, search-box@mtwebster/files/search-box@mtwebster/po/de.po, search-box@mtwebster/files/search-box@mtwebster/po/es.po, search-box@mtwebster/files/search-box@mtwebster/po/fr.po, search-box@mtwebster/files/search-box@mtwebster/po/hr.po, search-box@mtwebster/files/search-box@mtwebster/po/hu.po, search-box@mtwebster/files/search-box@mtwebster/po/it.po, search-box@mtwebster/files/search-box@mtwebster/po/nl.po, search-box@mtwebster/files/search-box@mtwebster/po/ru.po, search-box@mtwebster/files/search-box@mtwebster/po/search-box@mtwebster.pot, search-box@mtwebster/files/search-box@mtwebster/po/sv.po, search-box@mtwebster/files/search-box@mtwebster/po/tr.po, search-box@mtwebster/files/search-box@mtwebster/po/zh_CN.po, search-box@mtwebster/files/search-box@mtwebster/settings-schema.json
Feature request by @toolgrinder on https://cinnamon-spices.linuxmint.com/applets/view/57#count
=> [search-box@mtwebster] v2.3.0 - Now considers the case where the default provider is not selected

wallpaper-slideshow@amaan-mohib/files/wallpaper-slideshow@amaan-mohib/po/ca.po, website-notifier@cardsurf/files/website-notifier@cardsurf/po/ca.po, window-list@sangorys/files/window-list@sangorys/po/ca.po, window-list@zeripath.sdf-eu.org/files/window-list@zeripath.sdf-eu.org/po/ca.po, windowlist@cobinja.de/files/windowlist@cobinja.de/po/ca.po, workspace-grid@hernejj/files/workspace-grid@hernejj/po/ca.po, xampp-panel@backids99/files/xampp-panel@backids99/po/ca.po, xsession@claudiux/files/xsession@claudiux/po/ca.po
* wallpaper-slideshow@amaan-mohib
* website-notifier@cardsurf
* window-list@sangorys
* window-list@zeripath.sdf-eu.org
* windowlist@cobinja.de
* workspace-grid@hernejj
* xampp-panel@backids99
* xsession@claudiux
=> Add Catalan translations

brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/applet.js
(tested on Linux Mint 21.3 - Cinnamon v6.0.4)
related to https://cinnamon-spices.linuxmint.com/applets/view/286
before
after
=> brightness-and-gamma-applet@cardsurf: Fix issue with mouse scroll to increase brightness

CustomPlaces@Nicolas01/files/CustomPlaces@Nicolas01/po/de.po
CustomPlaces@Nicolas01 added de.po
=> CustomPlaces@Nicolas01 added german translations

ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/applet.js, ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/metadata.json, ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/po/ca.po, ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/po/ddcci-multi-monitor@tim-we.pot, ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/po/es.po, ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/po/fi.po, ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/po/it.po, ddcci-multi-monitor@tim-we/info.json
cc @tim-we @GingerGigiCat 
Ref: #5673
=> ddcci-multi-monitor@tim-we: Update maintainer and add translation support

Cinnamenu@json/files/Cinnamenu@json/po/ca.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/ca.po, ratecurrency@magner/files/ratecurrency@magner/po/ca.po
* Cinnamenu@json
* ratecurrency@magner
* Radio3.0@claudiux
Minor corrections for a few applets. 100% done now.
=> Update Catalan translations

c-eyes@anaximeno/files/c-eyes@anaximeno/po/nl.po
=> c-eyes@anaximeno: Update Dutch translation

CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po, ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/po/it.po, search-box@mtwebster/files/search-box@mtwebster/po/it.po
Hi,
I've updated the Italian translation for 3 applets.
Have a nice day :)
=> Updates Italian translations

bose@tuuxx/files/bose@tuuxx/po/de.po
=> bose@tuuxx added german translations

Cinnamenu@json/files/Cinnamenu@json/5.8/applet.js, Cinnamenu@json/files/Cinnamenu@json/metadata.json
And add keypad navigation, fix RTL key nav.
Fixes: #6215
=> Cinnamenu@json: Separate apps and files in search results

gpaste-reloaded@feuerfuchs.eu/README.md
=> gpaste-reloaded@feuerfuchs.eu: update dependency instructions in README

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.0/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json
As requested by users @Wolfen113 and @FireStarW on https://cinnamon-spices.linuxmint.com/applets/view/79#count
=> [multicore-sys-monitor@ccadeptic23] v1.9.6 - Changes method to launch system monitor

betterlock/files/betterlock/po/betterlock.pot, betterlock/files/betterlock/po/ca.po, betterlock/files/betterlock/po/da.po, betterlock/files/betterlock/po/de.po, betterlock/files/betterlock/po/es.po, betterlock/files/betterlock/po/fi.po, betterlock/files/betterlock/po/fr.po, betterlock/files/betterlock/po/he.po, betterlock/files/betterlock/po/hr.po, betterlock/files/betterlock/po/hu.po, betterlock/files/betterlock/po/it.po, betterlock/files/betterlock/po/ja.po, betterlock/files/betterlock/po/nl.po, betterlock/files/betterlock/po/pt_BR.po, betterlock/files/betterlock/po/ru.po, betterlock/files/betterlock/po/sv.po, betterlock/files/betterlock/po/tr.po, betterlock/files/betterlock/po/zh_CN.po, betterlock/files/betterlock/settings-schema.json
Fixed spelling mistake in betterlock settings. Tested changes on Mint 22 in a VM.
=> [betterlock] Correct spelling in betterlock settings

CassiaWindowList@klangman/CHANGELOG.md, CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js, CassiaWindowList@klangman/files/CassiaWindowList@klangman/makepot, CassiaWindowList@klangman/files/CassiaWindowList@klangman/metadata.json, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ca.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/da.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/es.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fr.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/hu.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/nl.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ru.po
Improve the window icon geometry update logic for more accurate minimize/unminimize animations. It's still not perfect, but this fixes most of the issues.
=> [CassiaWindowList@klangman] Fix for setting window icon geometry

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/po/Sensors@claudiux.pot, Sensors@claudiux/files/Sensors@claudiux/po/fr.po
=> [Sensors@claudiux] v3.8.0 - Fixes #6300. Better display on a vertical panel

weather@mockturtl/files/weather@mockturtl/po/fr.po
Update the French translation to the 3.6.4 version
=> [weather@mockturtl] Update French translation

pin-unpin-panel@anaximeno/files/pin-unpin-panel@anaximeno/5.4/applet.js, pin-unpin-panel@anaximeno/files/pin-unpin-panel@anaximeno/metadata.json
-  Update panel autohide type if the autohide type applet settings is changed
=> pin-unpin-panel@anaximeno: Version 0.1.3

tapo@smiklosovic/files/tapo@smiklosovic/po/tapo@smiklosovic.pot
=> tapo@smiklosovic: Add translation template

tapo@smiklosovic/files/tapo@smiklosovic/devices.sh, tapo@smiklosovic/files/tapo@smiklosovic/metadata.json
@rcalixte would you mind to merge this? it is just the removal of some redundant logging into a file. It leaks the token as well.
=> tapo@smiklosovic: cleanup of redundant debug logging

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/settings-schema.json, Sensors@claudiux/files/Sensors@claudiux/stylesheet.css
=> [Sensors@claudiux] v3.8.1 - Fixes #6353

wine-utils@elblake/files/wine-utils@elblake/applet.js, wine-utils@elblake/files/wine-utils@elblake/scripts/version.sh
Hello,
I've made a small fix (removed debugging code). Sorry I didn't notice it when I reviewed changes.
Thanks,
=> wine-utils@elblake: Small fix

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
=> [sound150@claudiux] v6.18.1 - Fixes #6301

app-launcher@mchilli/files/app-launcher@mchilli/po/app-launcher@mchilli.pot, app-launcher@mchilli/files/app-launcher@mchilli/po/ca.po, app-launcher@mchilli/files/app-launcher@mchilli/po/da.po, app-launcher@mchilli/files/app-launcher@mchilli/po/de.po, app-launcher@mchilli/files/app-launcher@mchilli/po/es.po, app-launcher@mchilli/files/app-launcher@mchilli/po/fi.po, app-launcher@mchilli/files/app-launcher@mchilli/po/fr.po, app-launcher@mchilli/files/app-launcher@mchilli/po/hu.po, app-launcher@mchilli/files/app-launcher@mchilli/po/it.po, app-launcher@mchilli/files/app-launcher@mchilli/po/nl.po, app-launcher@mchilli/files/app-launcher@mchilli/po/ru.po, app-launcher@mchilli/files/app-launcher@mchilli/po/tr.po, app-launcher@mchilli/files/app-launcher@mchilli/po/zh_CN.po, app-launcher@mchilli/files/app-launcher@mchilli/ui/app.glade, app-launcher@mchilli/files/app-launcher@mchilli/ui/confirm.glade, app-launcher@mchilli/files/app-launcher@mchilli/ui/group.glade, app-launcher@mchilli/files/app-launcher@mchilli/ui/import.glade, app-launcher@mchilli/files/app-launcher@mchilli/ui/widget.glade
- all strings not required for translation removed or deactivated
=> app-launcher@mchilli: update translation files

cinnamon-spices-makepot
Fix the error depicted in the following image:
=> FIx makepot failing if result not returned on git log command

panel-tweaks@anaximeno/files/panel-tweaks@anaximeno/5.4/constants.js, panel-tweaks@anaximeno/files/panel-tweaks@anaximeno/5.4/helpers.js, panel-tweaks@anaximeno/files/panel-tweaks@anaximeno/5.4/settings-schema.json, panel-tweaks@anaximeno/files/panel-tweaks@anaximeno/5.4/settingsController.js, panel-tweaks@anaximeno/files/panel-tweaks@anaximeno/metadata.json
- Round values to avoid floating point errors while setting style values
- Update tweak style unset constant name
- Small update in settings  ordering
=> panel-tweaks@anaximeno: Version 0.1.2

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/po/Radio3.0@claudiux.pot, Radio3.0@claudiux/files/Radio3.0@claudiux/po/fr.po
Now the "unassigned" word can be translated. See #6415.
=> [Radio3.0@claudiux] v2.1.3

CassiaWindowList@klangman/CHANGELOG.md, CassiaWindowList@klangman/README.md, CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js, CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/settings-schema.json, CassiaWindowList@klangman/files/CassiaWindowList@klangman/6.0/settings-schema.json, CassiaWindowList@klangman/files/CassiaWindowList@klangman/metadata.json, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ca.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/da.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/es.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fr.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/hu.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/nl.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ru.po
1. Save scroll-wheel adjusted Thumbnail sizes in the json
2. Apply scroll-wheel adjusted default Thumbnail sizes to other Workspaces
3. Further improvements to setting icon geometry
=> [CassiaWindowList@klangman] Version 2.3.4

c-eyes@anaximeno/files/c-eyes@anaximeno/po/pt.po, power-profiles@rcalixte/files/power-profiles@rcalixte/po/pt.po
Updated Portuguese translation for power-profiles and c-eyes applets
=> Update Portuguese translation

disk-read-and-write-speed@cardsurf/README.md, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/applet.js, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/appletGui.js, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/metadata.json, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/po/ca.po, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/po/disk-read-and-write-speed@cardsurf.pot, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/po/es.po, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/po/fr.po, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/po/hu.po, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/po/it.po, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/po/nl.po, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/settings-schema.json
=> [disk-read-and-write-speed@cardsurf] v1.1.2 - Binary or decimal units can now be selected

download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletGui.js, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/metadata.json, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/bg.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/ca.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/da.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/de.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/download-and-upload-speed@cardsurf.pot, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/es.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/fi.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/fr.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/hr.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/hu.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/it.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/nl.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/pl.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/pt.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/sv.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/tr.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/zh_CN.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/settings-schema.json
@cardsurf 
This PR improves the display on panel.
Also, there are new .pot and fr.po files.
=> [download-and-upload-speed@cardsurf] v1.6.7 - Display improvement

disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/applet.js, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js
@cardsurf 
Concerned applets:
- disk-read-and-write-speed@cardsurf
- download-and-upload-speed@cardsurf
Avoids calculating Math.pow(2, n0) on every loop.
=> Optimizes speed applets

suspend@janax/CHANGELOG.md, suspend@janax/files/suspend@janax/applet.js, suspend@janax/files/suspend@janax/metadata.json, suspend@janax/files/suspend@janax/po/ca.po, suspend@janax/files/suspend@janax/po/da.po, suspend@janax/files/suspend@janax/po/de.po, suspend@janax/files/suspend@janax/po/es.po, suspend@janax/files/suspend@janax/po/fr.po, suspend@janax/files/suspend@janax/po/hr.po, suspend@janax/files/suspend@janax/po/hu.po, suspend@janax/files/suspend@janax/po/it.po, suspend@janax/files/suspend@janax/po/nl.po, suspend@janax/files/suspend@janax/po/pt_BR.po, suspend@janax/files/suspend@janax/po/ru.po, suspend@janax/files/suspend@janax/po/suspend@janax.pot, suspend@janax/files/suspend@janax/po/sv.po, suspend@janax/files/suspend@janax/po/zh_CN.po
Better handling of cases where the UI scale factor is not 100%
=> [suspend@janax] Fix handling of UI scale factors

moonphase@techi-freki/CHANGELOG.md, moonphase@techi-freki/files/moonphase@techi-freki/js/compass.js, moonphase@techi-freki/files/moonphase@techi-freki/metadata.json
=> [moonphase@techi-freki] v1.0.1 - Fixes #6185

gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/is.po
Initial translation for Icelandic
=> Gpaste-reloaded - Create is.po

sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/scripts/get_album_art.sh
Fixes #6504.
Improvements are planed.
=> [sound150@claudiux] v7.2.0 - Fixes #6504

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/scripts/get_album_art.sh
See https://github.com/linuxmint/cinnamon-spices-applets/issues/6504#issuecomment-2420401977
=> [sound150@claudiux] v7.2.1 - Some improvements to fix #6504

CassiaWindowList@klangman/CHANGELOG.md, CassiaWindowList@klangman/README.md, CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js, CassiaWindowList@klangman/files/CassiaWindowList@klangman/metadata.json, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ca.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/da.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/es.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fr.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/hu.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/nl.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ru.po
Added context menu options to close all/other windows for the buttons application (when button is not grouped)
=> [CassiaWindowList@klangman] v2.3.6 New context menu options

auto-dark-light@gihaume/CHANGELOG.md, auto-dark-light@gihaume/files/auto-dark-light@gihaume/applet.js, auto-dark-light@gihaume/files/auto-dark-light@gihaume/lib/background_handler.js, auto-dark-light@gihaume/files/auto-dark-light@gihaume/lib/color_scheme_change_listener.js, auto-dark-light@gihaume/files/auto-dark-light@gihaume/lib/commands_launcher/commands_launcher.js, auto-dark-light@gihaume/files/auto-dark-light@gihaume/lib/commands_launcher/launch_command.js, auto-dark-light@gihaume/files/auto-dark-light@gihaume/lib/dbus.js, auto-dark-light@gihaume/files/auto-dark-light@gihaume/lib/event_scheduler.js, auto-dark-light@gihaume/files/auto-dark-light@gihaume/lib/sleep_wakeup_listener/screen_lock_checker.js, auto-dark-light@gihaume/files/auto-dark-light@gihaume/lib/sleep_wakeup_listener/sleep_wakeup_listener.js, auto-dark-light@gihaume/files/auto-dark-light@gihaume/lib/themes_handler.js, auto-dark-light@gihaume/files/auto-dark-light@gihaume/lib/time_change_listener/Makefile, auto-dark-light@gihaume/files/auto-dark-light@gihaume/lib/time_change_listener/main.cpp, auto-dark-light@gihaume/files/auto-dark-light@gihaume/lib/time_change_listener/time_change_listener.js, auto-dark-light@gihaume/files/auto-dark-light@gihaume/lib/time_of_day.js, auto-dark-light@gihaume/files/auto-dark-light@gihaume/lib/timer_absolute.js, auto-dark-light@gihaume/files/auto-dark-light@gihaume/lib/timezone_change_listener.js, auto-dark-light@gihaume/files/auto-dark-light@gihaume/lib/twilights_calculator/suncalc.js, auto-dark-light@gihaume/files/auto-dark-light@gihaume/lib/twilights_calculator/twilights_calculator.js, auto-dark-light@gihaume/files/auto-dark-light@gihaume/metadata.json, auto-dark-light@gihaume/files/auto-dark-light@gihaume/po/auto-dark-light@gihaume.pot, auto-dark-light@gihaume/files/auto-dark-light@gihaume/po/ca.po, auto-dark-light@gihaume/files/auto-dark-light@gihaume/po/es.po, auto-dark-light@gihaume/files/auto-dark-light@gihaume/po/fr.po, auto-dark-light@gihaume/files/auto-dark-light@gihaume/po/hu.po, auto-dark-light@gihaume/files/auto-dark-light@gihaume/po/nl.po, auto-dark-light@gihaume/files/auto-dark-light@gihaume/settings-schema.json
Custom commands launching feature:
- Corrected list's `Active` attribute default to `true`
- Added shell features support
=> auto-dark-light@gihaume: Version 1.2.1

profile-switcher@pixunil/files/profile-switcher@pixunil/po/de.po
Add german translation to profile-switcher@pixunil
=> profile-switcher@pixunil add german translation

radio@driglu4it/files/radio@driglu4it/4.6/radio-applet.js, radio@driglu4it/files/radio@driglu4it/4.6/settings-schema.json, radio@driglu4it/src/services/youtubeDownload/YoutubeDownloadManager.ts
- fix single quotes not escaped
- make yt-dlp the default
=> radio@driglu4it: fix single quotes not escaped

Radio3.0@claudiux/files/Radio3.0@claudiux/po/de.po
Add German translations for newly added settings.
=> Radio3.0@claudiux: Update German (de) translation

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/lib/sensorsReaper.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json
=> [Sensors@claudiux] v3.9.0 - Fixes #6076: Ignores 'empty' sensors (sensors not sending data)

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.0/DataProviders.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.0/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json
=> [multicore-sys-monitor@ccadeptic23] Fixes #5630

AutostartPrograms@spacy01/files/AutostartPrograms@spacy01/po/fi.po, Cinnamenu@json/files/Cinnamenu@json/po/fi.po, auto-dark-light@gihaume/files/auto-dark-light@gihaume/po/fi.po, backgroundroll@Sokawaii25/files/backgroundroll@Sokawaii25/po/fi.po, betterlock/files/betterlock/po/fi.po, bettersettings@bownz/files/bettersettings@bownz/po/fi.po, bumblebee@pdcurtis/files/bumblebee@pdcurtis/po/fi.po, cinnamon-timer@jake1164/files/cinnamon-timer@jake1164/po/fi.po
Corrections and improvements to Finnish translations. New lines completed and tested.
=> Language update Finnish

show-hide-applets@mohammad-sn/files/show-hide-applets@mohammad-sn/applet.js, show-hide-applets@mohammad-sn/files/show-hide-applets@mohammad-sn/metadata.json
=> [show-hide-applets@mohammad-sn] Fixes #4908

show-hide-applets@mohammad-sn/files/show-hide-applets@mohammad-sn/1v-symbolic.svg, show-hide-applets@mohammad-sn/files/show-hide-applets@mohammad-sn/2v-symbolic.svg, show-hide-applets@mohammad-sn/files/show-hide-applets@mohammad-sn/applet.js, show-hide-applets@mohammad-sn/files/show-hide-applets@mohammad-sn/metadata.json
Fixes #2481.
Fixes #2799.
Fixes #4423.
Fixes #6559.
=> [show-hide-applets@mohammad-sn] Now works in any zone of any panel

Exit@claudiux/files/Exit@claudiux/po/fi.po, cinnamonvantage@garlayntoji/files/cinnamonvantage@garlayntoji/po/fi.po, clean-show-desktop@filipetorresbr/files/clean-show-desktop@filipetorresbr/po/fi.po, ctrl4docker@hoffis-eck.de/files/ctrl4docker@hoffis-eck.de/po/fi.po, ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/po/fi.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/fi.po, directory-menu@torchipeppo/files/directory-menu@torchipeppo/po/fi.po, disk-read-and-write-speed@cardsurf/files/disk-read-and-write-speed@cardsurf/po/fi.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/fi.po, gnote@brett-smith/files/gnote@brett-smith/po/fi.po, gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/fi.po, gpumonitor@axel358/files/gpumonitor@axel358/po/fi.po, graphicsCenter@scollins/files/graphicsCenter@scollins/po/fi.po
Finnish language updates, text improvements and new translations.
=> Updates in Finnish

show-hide-applets@mohammad-sn/files/show-hide-applets@mohammad-sn/applet.js
Fixes #2756.
Adds an option in context menu to switch autohide.
=> [show-hide-applets@mohammad-sn] Fixes #2756

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
Thanks to @benmccann!
Fixes #6513
=> v7.2.4 - Fixes #6513: Always show mute icon when sound is muted

MessagingMenuV3@blub/files/MessagingMenuV3@blub/po/fi.po, MonitorInputSource@klangman/files/MonitorInputSource@klangman/po/fi.po, MuteToggler@jebeaudet.com/files/MuteToggler@jebeaudet.com/po/fi.po, hideable-applets@cardsurf/files/hideable-applets@cardsurf/po/fi.po, mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/po/fi.po, mic-level@zamszowy/files/mic-level@zamszowy/po/fi.po, moonphase@techi-freki/files/moonphase@techi-freki/po/fi.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/fi.po, mybookmarks@markbokil.com/files/mybookmarks@markbokil.com/po/fi.po, mylauncher@markbokil.com/files/mylauncher@markbokil.com/po/fi.po, networkmonitor@axel358/files/networkmonitor@axel358/po/fi.po, notification-mute@jgillula/files/notification-mute@jgillula/po/fi.po, notifications-enhanced@hilyxx/files/notifications-enhanced@hilyxx/po/fi.po
Finnish translations. New and a few updated language packs.
=> Finnish update

CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/de.po
=> CassiaWindowList Add german translation

Radio3.0@claudiux/files/Radio3.0@claudiux/lib/checkDependencies.js
=> [Radio3.0@claudiux] v2.2.3 - Fixes #6583

CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ca.po, Exit@claudiux/files/Exit@claudiux/po/ca.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/ca.po, directory-menu@torchipeppo/files/directory-menu@torchipeppo/po/ca.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ca.po, rssNewsticker@KopfDesDaemons/files/rssNewsticker@KopfDesDaemons/po/ca.po
* CassiaWindowList@klangman
* directory-menu@torchipeppo
* Exit@claudiux
* multicore-sys-monitor@ccadeptic23
* rssNewsticker@KopfDesDaemons
* SpiceSpy@claudiux
=> Add/Update Catalan translations

app-launcher@mchilli/README.md, app-launcher@mchilli/files/app-launcher@mchilli/applet.js, app-launcher@mchilli/files/app-launcher@mchilli/po/app-launcher@mchilli.pot, app-launcher@mchilli/files/app-launcher@mchilli/po/ca.po, app-launcher@mchilli/files/app-launcher@mchilli/po/da.po, app-launcher@mchilli/files/app-launcher@mchilli/po/de.po, app-launcher@mchilli/files/app-launcher@mchilli/po/es.po, app-launcher@mchilli/files/app-launcher@mchilli/po/fi.po, app-launcher@mchilli/files/app-launcher@mchilli/po/fr.po, app-launcher@mchilli/files/app-launcher@mchilli/po/hu.po, app-launcher@mchilli/files/app-launcher@mchilli/po/it.po, app-launcher@mchilli/files/app-launcher@mchilli/po/nl.po, app-launcher@mchilli/files/app-launcher@mchilli/po/ru.po, app-launcher@mchilli/files/app-launcher@mchilli/po/tr.po, app-launcher@mchilli/files/app-launcher@mchilli/po/zh_CN.po, app-launcher@mchilli/files/app-launcher@mchilli/settings-schema.json
Feature request by @freewee on https://cinnamon-spices.linuxmint.com/applets/view/344
=> app-launcher@mchilli: menu at mouse position

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.0/DataProviders.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/scripts/commands.txt, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/scripts/get-swap.sh
=> [multicore-sys-monitor@ccadeptic23] v1.9.9 - Fixes #5177: Better reading of swap usage

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/is.po
Updated Icelandic translation of SpicesUpdate@claudiux
=> SpicesUpdate@claudiux - Update is.po

Radio3.0@claudiux/files/Radio3.0@claudiux/po/is.po
Finishing Icelandic translation
=> Radio3.0@claudiux - Update is.po

Cinnamenu@json/files/Cinnamenu@json/po/is.po
Updated Icelandic translation. [Would have done it long time ago, if the Google-Translate terms hadn't been so hilarious ;-) ]
=> Cinnamenu@json - Update is.po

mailnagapplet@ozderya.net/files/mailnagapplet@ozderya.net/applet.js
This is just a suggestion. Values are hardcoded and the coding style is probably all wrong.
=> mailnagapplet: Limits the length when displaying subjects [#5230]

CassiaWindowList@klangman/CHANGELOG.md, CassiaWindowList@klangman/README.md, CassiaWindowList@klangman/files/CassiaWindowList@klangman/4.0/applet.js, CassiaWindowList@klangman/files/CassiaWindowList@klangman/metadata.json, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ca.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/da.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/de.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/es.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fi.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fr.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/hu.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/nl.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ru.po
1. Fix the Thumbnail menu item remove animation that is used when the window-list is on a vertical panel
2. Use an "up arrow" unicode character as the minimized window status indicator when the window-list is on the top panel
3. Activate a buttons window when the user drags an object onto a window-list button
=> [CassiaWindowList@klangman] V2.3.9 fixes an improvements

Exit@claudiux/files/Exit@claudiux/5.4/applet.js, Exit@claudiux/files/Exit@claudiux/CHANGELOG.md, Exit@claudiux/files/Exit@claudiux/metadata.json, Exit@claudiux/files/Exit@claudiux/po/Exit@claudiux.pot, Exit@claudiux/files/Exit@claudiux/po/ca.po, Exit@claudiux/files/Exit@claudiux/po/de.po, Exit@claudiux/files/Exit@claudiux/po/es.po, Exit@claudiux/files/Exit@claudiux/po/fi.po, Exit@claudiux/files/Exit@claudiux/po/fr.po, Exit@claudiux/files/Exit@claudiux/po/hu.po, Exit@claudiux/files/Exit@claudiux/po/it.po, Exit@claudiux/files/Exit@claudiux/po/nl.po, Exit@claudiux/files/Exit@claudiux/scripts/can-shutdown.sh
Related to https://github.com/linuxmint/cinnamon/issues/10282
=> [Exit@claudiux] v1.4.0 - Take into account inhibition during automatic updates

sound150@claudiux/files/sound150@claudiux/5.4/applet.js, sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/6.2/applet.js, sound150@claudiux/files/sound150@claudiux/6.2/settings-schema.json, sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/6.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/ca.po, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fi.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/nl.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po
=> [sound150@claudiux] v7.3.2 - Fixes some OSD problems

CassiaWindowList@klangman/CHANGELOG.md, CassiaWindowList@klangman/README.md, CassiaWindowList@klangman/files/CassiaWindowList@klangman/6.4/applet.js, CassiaWindowList@klangman/files/CassiaWindowList@klangman/6.4/settings-schema.json, CassiaWindowList@klangman/files/CassiaWindowList@klangman/6.4/stylesheet.css, CassiaWindowList@klangman/files/CassiaWindowList@klangman/metadata.json, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/CassiaWindowList@klangman.pot, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ca.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/da.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/de.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/es.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fi.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fr.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/hu.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/it.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/nl.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/ru.po
Apply the recent CobiWindowList fix (for issues when running under Cinnamon 6.4) into the CassiaWindowList code.
=> [CassiaWindowList@klangman] v2.4.0 Fix issues running under Cinnamon 6.4

SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/de.po
Add german translation for SpiceSpy Applet
=> Add german Translation (SpiceSpy)

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json
New features:
* You can now set/unset favorite radio stations by clicking on ♥︎ in the menu while listening to them.
* The first category you see is ♥︎.
* Stations are displayed beside their category. (Forced.)
=> [Radio3.0@claudiux] v2.5.0 - 'Favorites' Category

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/desklet/AlbumArt3.0@claudiux/desklet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json
The menu no longer closes when you switch from the station list to the category list.
=> [Radio3.0@claudiux] v2.5.2: Improved menu behavior

power-profiles@rcalixte/files/power-profiles@rcalixte/5.4/applet.js
Red Hat based distributions like Fedora started using [TuneD](https://github.com/redhat-performance/tuned) instead of power-profiles-daemon. See #6613.
The TuneD daemon supports a  power-profiles compatibility API, but the current impelementation of the power-profiles applet explicitly checks whether the `powerprofilesctl` command is installed.
This PR changes the logic to first check, whether the corresponding DBus is available and only, if it is not available checks, whether the powerprofilesctl command is available or not.
This allows for other daemon providing a compatible DBus system to work with the power-profiles applet.
=> power-profiles@rcalixte: Support TuneD PP API by only checking for powerprofilesctl if DBus is not found

sysmonitor@orcus/files/sysmonitor@orcus/po/ja.po
=> sysmonitor@orcus: add Japanese translations.

sound150@claudiux/files/sound150@claudiux/6.2/applet.js, sound150@claudiux/files/sound150@claudiux/6.2/settings-schema.json, sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/6.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/ca.po, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fi.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/nl.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po
=> v7.3.4: New option to set volume at start-up

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/desklet/AlbumArt3.0@claudiux/desklet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json
Fixes some bugs concerning context menu and desklet.
=> [Radio3.0@claudiux] v2.5.4: Fixes some bugs

sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
=> [sound150@claudiux] v7.3.7: Improved functionality (icons and album art)

sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/6.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/ca.po, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fi.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/nl.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po
* Better compatibility with Cinnamon 6.4.
* Make optional suppressing unpleasant noise at computer shutdown. (See option in Sound tab of settings.)
* Improves management of objects and signals when restarting this applet.
=> [sound150@claudiux] v7.4.0: Better compatibility with Cinnamon 6.4

click-clock@wernerstucky/files/click-clock@wernerstucky/applet.js
added the date as well, will take a look into translation
=> added date and time

sound150@claudiux/files/sound150@claudiux/6.2/applet.js, sound150@claudiux/files/sound150@claudiux/6.2/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
=> [sound150@claudiux] v7.4.3: Corrects a regression in Cinnamon 6.2

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/desklet/AlbumArt3.0@claudiux/desklet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
Applets: Radio3.0@claudiux & sound150@claudiux.
=> Improved functioning

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/scripts/install_symbola_on_Arch.sh
=> [SpicesUpdate@claudiux] v7.4.7: Now compatible with Cinnamon on Gentoo

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/desklet/AlbumArt3.0@claudiux.json, Radio3.0@claudiux/files/Radio3.0@claudiux/desklet/AlbumArt3.0@claudiux/desklet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json
Issue reported by @ON4CDJ on https://cinnamon-spices.linuxmint.com/applets/view/360#count
=> [Radio3.0@claudiux] v2.6.1: Fixes desklet issue for Cinnamon 6.0

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/desklet/AlbumArt3.0@claudiux/desklet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/po/Radio3.0@claudiux.pot, Radio3.0@claudiux/files/Radio3.0@claudiux/po/ca.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/de.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/es.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/fi.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/fr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/hr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/hu.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/is.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/it.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/nl.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/ru.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/sv.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/tr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/scripts/get_song_art.sh, Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json
* You can choose the Quality of the downloaded album cover.
* Desklet AlbumArt3.0: New option in context menu to display the Album Art at full size. Middle-clicking on the desklet does the same.
* Bufixes in applet and in desklet.
=> [Radio3.0@claudiux] v2.7.0: You can choose the Quality of the downloaded Album Art

vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/applet.js, vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/metadata.json
@mockturtl
This PR changes the list with a sorted list.
I hope you'll like it.
Regards
Claudiux
=> [vboxlauncher@mockturtl] Sort the VM-list

Sensors@claudiux/files/Sensors@claudiux/po/cs.po, weather@mockturtl/files/weather@mockturtl/po/cs.po
Sensors@claudiux
weather@mockturtl
=> Czech translation update

cheaty@centurix/files/cheaty@centurix/refdocs/Regex/sheet.json
fixed an unescaped "\b" in the anchors sections
=> cheaty@centurix: fixed typo in regex sheet.json

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/radiodb/server-list.json, Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json
Also, sets the default value for each multimedia key bind.
=> Radio3.0 v2.7.3: Increases the size of the stream buffer for improved listening comfort

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/lib/mainloopTools.js, Sensors@claudiux/files/Sensors@claudiux/lib/sensorsReaper.js, Sensors@claudiux/files/Sensors@claudiux/lib/util.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json
This may be a solution for #6744.
=> [Sensors@claudiux] v4.0.0: Uses now the mainloopTools library to better manage loops

xsession@claudiux/files/xsession@claudiux/CHANGELOG.md, xsession@claudiux/files/xsession@claudiux/applet.js, xsession@claudiux/files/xsession@claudiux/lib/to-string.js, xsession@claudiux/files/xsession@claudiux/metadata.json, xsession@claudiux/files/xsession@claudiux/po/ca.po, xsession@claudiux/files/xsession@claudiux/po/da.po, xsession@claudiux/files/xsession@claudiux/po/de.po, xsession@claudiux/files/xsession@claudiux/po/es.po, xsession@claudiux/files/xsession@claudiux/po/fr.po, xsession@claudiux/files/xsession@claudiux/po/hu.po, xsession@claudiux/files/xsession@claudiux/po/it.po, xsession@claudiux/files/xsession@claudiux/po/nl.po, xsession@claudiux/files/xsession@claudiux/po/tr.po, xsession@claudiux/files/xsession@claudiux/po/xsession@claudiux.pot, xsession@claudiux/files/xsession@claudiux/po/zh_CN.po, xsession@claudiux/files/xsession@claudiux/scripts/watch-xse.sh, xsession@claudiux/files/xsession@claudiux/settings-schema.json
Improves applet stability and user comfort.
=> [xsession@claudiux] v2.0.0 - Spices icons in menus

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/constants.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/settings-schema.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/help/en/README.html, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/help/en/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/help/fr/README.html, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/help/fr/README.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/SpicesUpdate@claudiux.pot, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/ca.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/da.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/de.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/es.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/fi.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/fr.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/hr.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/hu.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/is.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/it.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/nl.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/ro.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/sv.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/tr.po, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/zh_CN.po
* Does not check private spices. A private spice is a spice that is not listed on the Cinnamon Spices website.
* Code: Avoids using Lang.bind() in response to signals.
=> [SpicesUpdate@claudiux] v7.6.0 - Does not check private Spices

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/mainloopTools.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
=> [SpicesUpdate@claudiux] v7.6.1: Fixes #6776

Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/desklet/AlbumArt3.0@claudiux/desklet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/desklet/AlbumArt3.0@claudiux/mainloopTools.js, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/mainloopTools.js, Radio3.0@claudiux/files/Radio3.0@claudiux/lib/volumeslider.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/po/Radio3.0@claudiux.pot, Radio3.0@claudiux/files/Radio3.0@claudiux/po/ca.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/de.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/es.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/fi.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/fr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/hr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/hu.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/is.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/it.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/nl.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/ru.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/sv.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/tr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/lib/mainloopTools.js, SpiceSpy@claudiux/files/SpiceSpy@claudiux/applet.js, SpiceSpy@claudiux/files/SpiceSpy@claudiux/lib/mainloopTools.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/mainloopTools.js, sound150@claudiux/files/sound150@claudiux/6.4/lib/mainloopTools.js
Applets:
- Radio3.0@claudiux
- Sensors@claudiux
- SpiceSpy@claudiux
- SpicesUpdate@claudiux
- sound150@claudiux
=> Updates mainloopTools library

NightLightSwitch@claudiux/files/NightLightSwitch@claudiux/6.4/applet.js, NightLightSwitch@claudiux/files/NightLightSwitch@claudiux/CHANGELOG.md, NightLightSwitch@claudiux/files/NightLightSwitch@claudiux/metadata.json
=> [NightLightSwitch@claudiux] v1.0.1 - No longer requires the gir1.2-gweather-4.0 package

sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
More tests on the existence of objects before acting on them.
=> [sound150@claudiux] v8.0.2: Improved stability with Cinnamon 6.4

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
=> [SpicesUpdate@claudiux] v7.6.2: Modification of the menu to fix #6781

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/lib/sensorsReaper.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/settings-schema.json
=> [Sensors@claudiux] v4.0.3: Improved code. Greater stability.

SpiceSpy@claudiux/files/SpiceSpy@claudiux/CHANGELOG.md, SpiceSpy@claudiux/files/SpiceSpy@claudiux/applet.js, SpiceSpy@claudiux/files/SpiceSpy@claudiux/lib/mainloopTools.js, SpiceSpy@claudiux/files/SpiceSpy@claudiux/metadata.json, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/SpiceSpy@claudiux.pot, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/ca.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/de.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/es.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/fi.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/fr.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/hu.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/it.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/nl.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/scripts/get_issues_json.sh
Now uses Github API.
Fixes many errors in menu management.
=> [SpiceSpy@claudiux] v4.3.0: New method to check recent issues

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/lib/checkDependencies.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/po/Sensors@claudiux.pot, Sensors@claudiux/files/Sensors@claudiux/po/ca.po, Sensors@claudiux/files/Sensors@claudiux/po/cs.po, Sensors@claudiux/files/Sensors@claudiux/po/da.po, Sensors@claudiux/files/Sensors@claudiux/po/de.po, Sensors@claudiux/files/Sensors@claudiux/po/es.po, Sensors@claudiux/files/Sensors@claudiux/po/fr.po, Sensors@claudiux/files/Sensors@claudiux/po/hu.po, Sensors@claudiux/files/Sensors@claudiux/po/it.po, Sensors@claudiux/files/Sensors@claudiux/po/nl.po, Sensors@claudiux/files/Sensors@claudiux/po/tr.po
=> [Sensors@claudiux] v4.1.0: Improves dependency installation

sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/6.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
=> [sound150@claudiux] v8.0.3: Improved OSD management

sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/6.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
=> [sound150@claudiux] v9.0.0: Major changes for OSD and menu

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
=> [SpicesUpdate@claudiux] v7.6.5: Improves stability

PanelTranslator@klangman/CHANGELOG.md, PanelTranslator@klangman/files/PanelTranslator@klangman/applet.js, PanelTranslator@klangman/files/PanelTranslator@klangman/metadata.json, PanelTranslator@klangman/files/PanelTranslator@klangman/po/PanelTranslator@klangman.pot, PanelTranslator@klangman/files/PanelTranslator@klangman/po/ca.po, PanelTranslator@klangman/files/PanelTranslator@klangman/po/de.po, PanelTranslator@klangman/files/PanelTranslator@klangman/po/es.po, PanelTranslator@klangman/files/PanelTranslator@klangman/po/fi.po, PanelTranslator@klangman/files/PanelTranslator@klangman/po/fr.po, PanelTranslator@klangman/files/PanelTranslator@klangman/po/hu.po, PanelTranslator@klangman/files/PanelTranslator@klangman/po/it.po, PanelTranslator@klangman/files/PanelTranslator@klangman/po/nl.po
- Fix for a 1.2.0 regression when running under older Cinnamon releases where the PopupResizeHandler class does not exist.
=> [PanelTranslator@klangman] Fixes running under older Cinnamon releases

sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/6.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/ca.po, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fi.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/nl.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po
=> [sound150@claudiux] v9.2.0: Add custom commands

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/lib/sensorsReaper.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/po/Sensors@claudiux.pot, Sensors@claudiux/files/Sensors@claudiux/po/ca.po, Sensors@claudiux/files/Sensors@claudiux/po/cs.po, Sensors@claudiux/files/Sensors@claudiux/po/da.po, Sensors@claudiux/files/Sensors@claudiux/po/de.po, Sensors@claudiux/files/Sensors@claudiux/po/es.po, Sensors@claudiux/files/Sensors@claudiux/po/fr.po, Sensors@claudiux/files/Sensors@claudiux/po/hu.po, Sensors@claudiux/files/Sensors@claudiux/po/it.po, Sensors@claudiux/files/Sensors@claudiux/po/nl.po, Sensors@claudiux/files/Sensors@claudiux/po/tr.po, Sensors@claudiux/files/Sensors@claudiux/scripts/get_disk_temp.sh, Sensors@claudiux/files/Sensors@claudiux/scripts/get_disk_temp_ORIG.sh, Sensors@claudiux/files/Sensors@claudiux/settings-schema.json
Fixes #6845.
Fixes #6766.
Fixes #6842.
=> [Sensors@claudiux] v4.2.0: Fixes several issues

sound150@claudiux/files/sound150@claudiux/5.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/6.2/settings-schema.json, sound150@claudiux/files/sound150@claudiux/6.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/ca.po, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fi.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/nl.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po
=> [sound150@claudiux] v9.2.1: Fixes a typo in settings

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
Consider AlbumArt3.0@claudiux as a common desklet.
=> [SpicesUpdate@claudiux] v7.7.0

download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletGui.js, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/mainloopTools.js, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/metadata.json, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/po/fr.po, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/shellUtils.js
@cardsurf
Improved code for more stability.
=> [download-and-upload-speed@cardsurf] Improved code: No Mainloop, no Lang

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet_OLD.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/scripts/get_disk_temp.sh
=> [Sensors@claudiux] v4.2.1: Fixes #6868

download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/applet.js, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/appletGui.js, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/metadata.json, download-and-upload-speed@cardsurf/files/download-and-upload-speed@cardsurf/shellUtils.js
=> [download-and-upload-speed@cardsurf] Bugfixes

bing-wallpaper@starcross.dev/files/bing-wallpaper@starcross.dev/po/zh_CN.po, radio@driglu4it/files/radio@driglu4it/po/zh_CN.po
* bing-wallpaper@starcross.dev
* radio@driglu4it
=> Add Chinese translations

Sensors@claudiux/files/Sensors@claudiux/po/de.po
Update a string which became fuzzy after last release.
=> Sensors@claudiux: Update German (de) translation

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/lib/checkDependencies.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/po/Sensors@claudiux.pot, Sensors@claudiux/files/Sensors@claudiux/po/ca.po, Sensors@claudiux/files/Sensors@claudiux/po/cs.po, Sensors@claudiux/files/Sensors@claudiux/po/da.po, Sensors@claudiux/files/Sensors@claudiux/po/de.po, Sensors@claudiux/files/Sensors@claudiux/po/es.po, Sensors@claudiux/files/Sensors@claudiux/po/fr.po, Sensors@claudiux/files/Sensors@claudiux/po/hu.po, Sensors@claudiux/files/Sensors@claudiux/po/it.po, Sensors@claudiux/files/Sensors@claudiux/po/nl.po, Sensors@claudiux/files/Sensors@claudiux/po/tr.po, Sensors@claudiux/files/Sensors@claudiux/settings-schema.json
=> [Sensors@claudiux] v5.0.0: Major changes - Fixes #6846

weather@mockturtl/files/weather@mockturtl/po/de.po
Provide German translations for untranslated strings.
=> weather@mockturtl: Update German (de) translation

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/settings-schema.json, Sensors@claudiux/files/Sensors@claudiux/stylesheet.css
=> Sensors v5.1.0: Font size can now be set from 60% to 120% of standard size

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/po/Sensors@claudiux.pot, Sensors@claudiux/files/Sensors@claudiux/po/ca.po, Sensors@claudiux/files/Sensors@claudiux/po/cs.po, Sensors@claudiux/files/Sensors@claudiux/po/da.po, Sensors@claudiux/files/Sensors@claudiux/po/de.po, Sensors@claudiux/files/Sensors@claudiux/po/es.po, Sensors@claudiux/files/Sensors@claudiux/po/fr.po, Sensors@claudiux/files/Sensors@claudiux/po/hu.po, Sensors@claudiux/files/Sensors@claudiux/po/it.po, Sensors@claudiux/files/Sensors@claudiux/po/nl.po, Sensors@claudiux/files/Sensors@claudiux/po/tr.po, Sensors@claudiux/files/Sensors@claudiux/settings-schema.json
=> [Sensors@claudiux] v5.3.0: Users can now choose the type of separator

SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/de.po
Provided German translations for untranslated strings.
Made a few adjustments and corrections on existing ones.
=> SpiceSpy@claudiux: Update German (de) translation

app-launcher@mchilli/files/app-launcher@mchilli/applet.js, app-launcher@mchilli/files/app-launcher@mchilli/po/app-launcher@mchilli.pot, app-launcher@mchilli/files/app-launcher@mchilli/po/ca.po, app-launcher@mchilli/files/app-launcher@mchilli/po/da.po, app-launcher@mchilli/files/app-launcher@mchilli/po/de.po, app-launcher@mchilli/files/app-launcher@mchilli/po/es.po, app-launcher@mchilli/files/app-launcher@mchilli/po/fi.po, app-launcher@mchilli/files/app-launcher@mchilli/po/fr.po, app-launcher@mchilli/files/app-launcher@mchilli/po/hu.po, app-launcher@mchilli/files/app-launcher@mchilli/po/it.po, app-launcher@mchilli/files/app-launcher@mchilli/po/nl.po, app-launcher@mchilli/files/app-launcher@mchilli/po/ru.po, app-launcher@mchilli/files/app-launcher@mchilli/po/tr.po, app-launcher@mchilli/files/app-launcher@mchilli/po/zh_CN.po, app-launcher@mchilli/files/app-launcher@mchilli/settings-schema.json
Feature request by @rtcunningham1 on https://cinnamon-spices.linuxmint.com/applets/view/344
=> app-launcher@mchilli: bind to workspace

SpiceSpy@claudiux/files/SpiceSpy@claudiux/CHANGELOG.md, SpiceSpy@claudiux/files/SpiceSpy@claudiux/README.md, SpiceSpy@claudiux/files/SpiceSpy@claudiux/applet.js, SpiceSpy@claudiux/files/SpiceSpy@claudiux/metadata.json
=> [SpiceSpy@claudiux] v5.2.0: Adapts the panel display to the size of the information

SpiceSpy@claudiux/files/SpiceSpy@claudiux/CHANGELOG.md, SpiceSpy@claudiux/files/SpiceSpy@claudiux/applet.js, SpiceSpy@claudiux/files/SpiceSpy@claudiux/metadata.json
Removed debug messages. Related to #6926.
=> SpiceSpy v5.2.1

gpaste-reloaded@feuerfuchs.eu/files/gpaste-reloaded@feuerfuchs.eu/po/de.po
Add translations for untranslated strings.
=> gpaste-reloaded@feuerfuchs.eu: Update German (de) translation

Bps@claudiux/files/Bps@claudiux/po/de.po
Add German translations for new Bsp applet.
=> Bps@claudiux: Provide German (de) translation

Bps@claudiux/files/Bps@claudiux/po/de.po
Update German translations for latest release.
=> Bps@claudiux: Update German (de) translation

PanelTranslator@klangman/files/PanelTranslator@klangman/po/de.po
Provide German translations for untranslated strings. Fix fuzzy strings.
=> PanelTranslator@klangman: Update German (de) translation

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/constants.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/httpLib.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/mainloopTools.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/notifications.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/to-string.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/utils.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
=> [SpicesUpdate@claudiux] v7.8.1: Fixes #6933

SpiceSpy@claudiux/files/SpiceSpy@claudiux/CHANGELOG.md, SpiceSpy@claudiux/files/SpiceSpy@claudiux/applet.js, SpiceSpy@claudiux/files/SpiceSpy@claudiux/metadata.json, SpiceSpy@claudiux/files/SpiceSpy@claudiux/scripts/spices-cache-init.sh, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/constants.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
For applets:
* SpicesUpdate@claudiux
*  SpiceSpy@claudiux
=> Solve translation issues

SpiceSpy@claudiux/files/SpiceSpy@claudiux/CHANGELOG.md, SpiceSpy@claudiux/files/SpiceSpy@claudiux/applet.js, SpiceSpy@claudiux/files/SpiceSpy@claudiux/metadata.json, SpiceSpy@claudiux/files/SpiceSpy@claudiux/scripts/spices-cache-init.sh, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
- SpiceSpy@claudiux
- SpicesUpdate@claudiux
=> Applet Bugfixes

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/po/Radio3.0@claudiux.pot, Radio3.0@claudiux/files/Radio3.0@claudiux/po/ca.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/de.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/es.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/fi.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/fr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/hr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/hu.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/is.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/it.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/nl.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/ru.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/sv.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/tr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json
=> [Radio3.0@claudiux] v2.9.0: Vertical maximization of the Settings Window becomes optional

sshlauncher@sumo/files/sshlauncher@sumo/po/ru.po
=> sshlauncher@sumo: Add Russian language

color-picker@fmete/files/color-picker@fmete/po/ru.po, ipindicator@matus.benko@gmail.com/files/ipindicator@matus.benko@gmail.com/po/ru.po, sshlauncher@sumo/files/sshlauncher@sumo/po/ru.po
=> Add russian translation

Cinnamenu@json/files/Cinnamenu@json/po/ru.po
* Added a missing translations
* Slightly corrected the existing translation
=> Cinnamenu@json: Update Russian translation

sysmonitor@orcus/files/sysmonitor@orcus/po/ca.po, sysmonitor@orcus/files/sysmonitor@orcus/po/da.po, sysmonitor@orcus/files/sysmonitor@orcus/po/de.po, sysmonitor@orcus/files/sysmonitor@orcus/po/es.po, sysmonitor@orcus/files/sysmonitor@orcus/po/fi.po, sysmonitor@orcus/files/sysmonitor@orcus/po/fr.po, sysmonitor@orcus/files/sysmonitor@orcus/po/hr.po, sysmonitor@orcus/files/sysmonitor@orcus/po/hu.po, sysmonitor@orcus/files/sysmonitor@orcus/po/it.po, sysmonitor@orcus/files/sysmonitor@orcus/po/ja.po, sysmonitor@orcus/files/sysmonitor@orcus/po/nl.po, sysmonitor@orcus/files/sysmonitor@orcus/po/pl.po, sysmonitor@orcus/files/sysmonitor@orcus/po/pt.po, sysmonitor@orcus/files/sysmonitor@orcus/po/sv.po, sysmonitor@orcus/files/sysmonitor@orcus/po/sysmonitor@orcus.pot, sysmonitor@orcus/files/sysmonitor@orcus/po/zh_CN.po
Updating sysmonitor@orcus POT file with new setting and European Portuguese translation
@OrcusCZ
=> Update sysmonitor@orcus pot and pt-PT translation

gpumonitor@axel358/files/gpumonitor@axel358/po/de.po
=> added German language file

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/scripts/thumb-downloader.sh
=> Fixes #6992: Improves the appearance of the label in a horizontal panel

xsession@claudiux/files/xsession@claudiux/CHANGELOG.md, xsession@claudiux/files/xsession@claudiux/applet.js, xsession@claudiux/files/xsession@claudiux/lib/mainloopTools.js, xsession@claudiux/files/xsession@claudiux/metadata.json
* Uses mainloopTools.
* Code cleanup.
=> [xsession@claudiux] v2.0.1

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/po/Sensors@claudiux.pot, Sensors@claudiux/files/Sensors@claudiux/po/ca.po, Sensors@claudiux/files/Sensors@claudiux/po/cs.po, Sensors@claudiux/files/Sensors@claudiux/po/da.po, Sensors@claudiux/files/Sensors@claudiux/po/de.po, Sensors@claudiux/files/Sensors@claudiux/po/es.po, Sensors@claudiux/files/Sensors@claudiux/po/fr.po, Sensors@claudiux/files/Sensors@claudiux/po/hu.po, Sensors@claudiux/files/Sensors@claudiux/po/it.po, Sensors@claudiux/files/Sensors@claudiux/po/nl.po, Sensors@claudiux/files/Sensors@claudiux/po/tr.po, Sensors@claudiux/files/Sensors@claudiux/settings-schema.json
=> [Sensors@claudiux] v5.4.0: Applet width can be set by user

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/po/Radio3.0@claudiux.pot, Radio3.0@claudiux/files/Radio3.0@claudiux/po/ca.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/de.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/es.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/fi.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/fr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/hr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/hu.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/is.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/it.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/nl.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/ru.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/sv.po, Radio3.0@claudiux/files/Radio3.0@claudiux/po/tr.po, Radio3.0@claudiux/files/Radio3.0@claudiux/radiodb/server-list.json, Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json
Improved Alarm-Clock settings.
Updated server list.
=> [Radio3.0@claudiux] v3.1.2

Bps@claudiux/files/Bps@claudiux/po/fi.po, CassiaWindowList@klangman/files/CassiaWindowList@klangman/po/fi.po, Exit@claudiux/files/Exit@claudiux/po/fi.po, app-launcher@mchilli/files/app-launcher@mchilli/po/fi.po, bing-wallpaper@starcross.dev/files/bing-wallpaper@starcross.dev/po/fi.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/fi.po, calendar@ccprog/files/calendar@ccprog/po/fi.po, cheaty@centurix/files/cheaty@centurix/po/fi.po
Finnish language pack and improvements
=> Finnish language pack

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/ru.po, radio@driglu4it/files/radio@driglu4it/po/ru.po, turn-off-monitor@zablotski/files/turn-off-monitor@zablotski/po/ru.po
* radio@driglu4it: updated ru.po
* SpicesUpdate@claudiux: added ru.po
* turn-off-monitor@zablotski: updated ru.po
=> Added some Russian translations

brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/6.4/applet.js, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/6.4/settings-schema.json, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/metadata.json, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/bg.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/brightness-and-gamma-applet@cardsurf.pot, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/ca.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/da.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/de.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/es.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/fi.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/fr.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/hr.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/hu.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/it.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/nl.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/pt_BR.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/ru.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/sv.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/tr.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/zh_CN.po
* Adds the ability to define or modify presets in settings, which are then accessible via the context menu.
* Settings are now on 2 tabs: General and Presets.
=> [brightness-and-gamma-applet@cardsurf] v1.4.0: Presets

xsession@claudiux/files/xsession@claudiux/CHANGELOG.md, xsession@claudiux/files/xsession@claudiux/applet.js, xsession@claudiux/files/xsession@claudiux/metadata.json, xsession@claudiux/files/xsession@claudiux/po/ca.po, xsession@claudiux/files/xsession@claudiux/po/da.po, xsession@claudiux/files/xsession@claudiux/po/de.po, xsession@claudiux/files/xsession@claudiux/po/es.po, xsession@claudiux/files/xsession@claudiux/po/fr.po, xsession@claudiux/files/xsession@claudiux/po/hu.po, xsession@claudiux/files/xsession@claudiux/po/it.po, xsession@claudiux/files/xsession@claudiux/po/nl.po, xsession@claudiux/files/xsession@claudiux/po/tr.po, xsession@claudiux/files/xsession@claudiux/po/xsession@claudiux.pot, xsession@claudiux/files/xsession@claudiux/po/zh_CN.po, xsession@claudiux/files/xsession@claudiux/scripts/watch-xse-latest.sh, xsession@claudiux/files/xsession@claudiux/settings-schema.json
=> [xsession@claudiux] v4.0.0: Added ability to show only latest messages and ability to edit messages

VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/CHANGELOG.md, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/applet.js, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/lib/checkDependencies.js, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/lib/mainloopTools.js, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/lib/util.js, VPN-Sentinel@claudiux/files/VPN-Sentinel@claudiux/metadata.json
Solves a problem reported by @cbazand on https://cinnamon-spices.linuxmint.com/applets/view/368#count.
=> [VPN-Sentinel@claudiux] v2.4.1: Updates checkDependencies.js and uses mainloopTools

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/radiodb/server-list.json, Radio3.0@claudiux/files/Radio3.0@claudiux/scripts/get_song_art.sh
=> [Radio3.0@claudiux] v3.3.1: The 'Try to download it from YT' menu option works again

sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/6.4/lib/controlButton.js, sound150@claudiux/files/sound150@claudiux/6.4/lib/s150PopupMenu.js, sound150@claudiux/files/sound150@claudiux/6.4/lib/volumeSlider.js, sound150@claudiux/files/sound150@claudiux/6.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/scripts/del_song_arts.sh, sound150@claudiux/files/sound150@claudiux/scripts/get_album_art.sh
=> [sound150@claudiux] v11.5.0: Best album cover change

weather@mockturtl/files/weather@mockturtl/po/zh_TW.po
=> Update and improve zh_TW locale for cinnamon-weather

xsession@claudiux/files/xsession@claudiux/CHANGELOG.md, xsession@claudiux/files/xsession@claudiux/README.md, xsession@claudiux/files/xsession@claudiux/applet.js, xsession@claudiux/files/xsession@claudiux/metadata.json, xsession@claudiux/files/xsession@claudiux/po/ca.po, xsession@claudiux/files/xsession@claudiux/po/da.po, xsession@claudiux/files/xsession@claudiux/po/de.po, xsession@claudiux/files/xsession@claudiux/po/es.po, xsession@claudiux/files/xsession@claudiux/po/fr.po, xsession@claudiux/files/xsession@claudiux/po/hu.po, xsession@claudiux/files/xsession@claudiux/po/it.po, xsession@claudiux/files/xsession@claudiux/po/nl.po, xsession@claudiux/files/xsession@claudiux/po/tr.po, xsession@claudiux/files/xsession@claudiux/po/xsession@claudiux.pot, xsession@claudiux/files/xsession@claudiux/po/zh_CN.po
* Ctrl+MiddleClick opens only latest messages.
* Can set from menu the number of latest messages.
=> [xsession@claudiux] v5.0.0: New icon and menu features

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/radiodb/server-list.json, Radio3.0@claudiux/files/Radio3.0@claudiux/scripts/get_song_art.sh
=> [Radio3.0@claudiux] v3.4.4: Fixes #7074

app-launcher@mchilli/files/app-launcher@mchilli/po/zh_TW.po
=> Add zh_TW locale for app-launcher@mchilli

anime-wallpaper@flyflyan/files/anime-wallpaper@flyflyan/po/zh_TW.po
=> Add zh_TW locale for anime-wallpaper@flyflyan

asl@santiago/files/asl@santiago/po/zh_TW.po
=> Add zh_TW locale for asl@santiago

AutostartPrograms@spacy01/files/AutostartPrograms@spacy01/po/zh_TW.po
=> Add zh_TW locale for AutostartPrograms@spacy01

backgroundroll@Sokawaii25/files/backgroundroll@Sokawaii25/po/zh_TW.po
=> Add zh_TW locale for backgroundroll@Sokawaii25

bash-sensors@pkkk/files/bash-sensors@pkkk/po/zh_TW.po
=> Add zh_TW locale for bash-sensors@pkkk

batterypower@joka42/files/batterypower@joka42/po/zh_TW.po
=> Add zh_TW locale for batterypower@joka42

auto-dark-light@gihaume/files/auto-dark-light@gihaume/po/zh_TW.po
=> Add zh_TW locale for auto-dark-light@gihaume

sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/6.4/lib/s150PopupMenu.js, sound150@claudiux/files/sound150@claudiux/6.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/README.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/ca.po, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fi.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/nl.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po, sound150@claudiux/files/sound150@claudiux/scripts/del_song_arts.sh, sound150@claudiux/files/sound150@claudiux/scripts/get_album_art.sh, sound150@claudiux/files/sound150@claudiux/scripts/install_imagemagick.sh, sound150@claudiux/files/sound150@claudiux/scripts/make_icon.sh, sound150@claudiux/files/sound150@claudiux/scripts/rm_tmp_files.sh
* Produces square rendered images from album covers to display a more pleasing icon.
* Requires installation of `imagemagick` package to obtain this result.
=> [sound150@claudiux] v12.0.0: Produces square rendered images from album covers to display a more pleasing icon

computer@brownsr/files/computer@brownsr/po/zh_TW.po
=> Add zh_TW locale for computer@brownsr

commandLauncher@scollins/files/commandLauncher@scollins/po/zh_TW.po
=> Add zh_TW locale for commandLauncher@scollins-zh_TW

cpu-monitor-text@gnemonix/files/cpu-monitor-text@gnemonix/po/zh_TW.po
=> cpu-monitor-text: Add Chinese Traditional translation

ctrl4docker@hoffis-eck.de/files/ctrl4docker@hoffis-eck.de/po/zh_TW.po
=> ctrl4docker@hoffis-eck.de: Add Chinese Traditional translation

feeds@jonbrettdev.wordpress.com/files/feeds@jonbrettdev.wordpress.com/po/zh_TW.po
=> feeds@jonbrettdev.wordpress.com: Add Chinese Traditional translation

duolingo-helper@nodeengineer.com/files/duolingo-helper@nodeengineer.com/po/zh_TW.po
=> duolingo-helper@nodeengineer.com: Add Chinese Traditional translation

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/6.0/applet.js, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/CHANGELOG.md, SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/metadata.json
=> [SpicesUpdate@claudiux] v7.8.8: Fixes #7090

bing-wallpaper@starcross.dev/files/bing-wallpaper@starcross.dev/po/zh_TW.po
=> bing-wallpaper@starcross.dev: Add Chinese Traditional translation

clipboard-eraser@Techcrafter/files/clipboard-eraser@Techcrafter/po/zh_TW.po
=> clipboard-eraser@Techcrafter: Add Chinese Traditional translation

gamemode@axel358/files/gamemode@axel358/po/zh_TW.po
=> gamemode@axel358: Add Chinese Traditional translation

network@brownsr/files/network@brownsr/po/zh_TW.po
=> network@brownsr: Add Chinese Traditional translation

force-quit@cinnamon.org/files/force-quit@cinnamon.org/po/zh_TW.po
=> force-quit@cinnamon.org: Add Chinese Traditional translation

lorem@vxstorm/files/lorem@vxstorm/po/zh_TW.po
=> lorem@vxstorm: Add Chinese Traditional translation

localip@mrieracrespi/files/localip@mrieracrespi/po/zh_TW.po
=> localip@mrieracrespi: Add Chinese Traditional translation

healthyeyes@ipolozov/files/healthyeyes@ipolozov/po/zh_TW.po
=> healthyeyes@ipolozov: Add Chinese Traditional translation

devbar@ludvigbostrom/files/devbar@ludvigbostrom/po/zh_TW.po
=> devbar@ludvigbostrom: Add Chinese Traditional translation

nextslide@yaya-cout/files/nextslide@yaya-cout/po/zh_TW.po
=> nextslide@yaya-cout: Add Chinese Traditional translation

temperature@fevimu/files/temperature@fevimu/po/ru.po
Partially translated applet settings
=> temperature@fevimu: Add/Update Russian translation

Sensors@claudiux/files/Sensors@claudiux/po/ru.po
Created ru.po and partially translated the applet
=> Sensors@claudiux: Create ru.po

kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/ca.po, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/da.po, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/de.po, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/es.po, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/fi.po, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/fr.po, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/hu.po, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/it.po, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/kdecapplet@joejoetv.pot, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/nl.po, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/ru.po, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/sv.po, kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/zh_CN.po
Create ru.po and and partially translated the applet
=> kdecapplet@joejoetv: Create ru.po and and partially translated the applet

desaturate-all@hkoosha/README.md, desaturate-all@hkoosha/files/desaturate-all@hkoosha/applet.js, desaturate-all@hkoosha/files/desaturate-all@hkoosha/metadata.json, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/ca.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/da.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/de.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/desaturate-all@hkoosha.pot, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/es.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/fi.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/fr.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/hu.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/it.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/nl.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/settings-schema.json
1. Added "bedtime mode" where the user can configure an enable/disable time
2. Added an option to restore the previous effect state on Cinnamon startup
3. Added the ability to control the saturation amount (gray-scale 0% to 100%)
=> [desaturate-all@hkoosha] Add some new features

binaryclock@entelechy/files/binaryclock@entelechy/po/zh_TW.po
=> binaryclock@entelechy: Add Chinese Traditional translation

bluetooth-battery@zamszowy/files/bluetooth-battery@zamszowy/po/zh_TW.po
=> bluetooth-battery@zamszowy: Add Chinese Traditional translation

bose@tuuxx/files/bose@tuuxx/po/zh_TW.po
=> bose@tuuxx: Add Chinese Traditional translation

clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/po/zh_TW.po
=> clipboard-qr@wrouesnel: Add Chinese Traditional translation

kdecapplet@joejoetv/files/kdecapplet@joejoetv/po/ru.po
=> kdecapplet@joejoetv: Update ru.po

ScreenLocker@tuuxx/files/ScreenLocker@tuuxx/po/zh_TW.po
=> ScreenLocker@tuuxx: Add Chinese Traditional translation

IntelTurboBoost@wsmenezes/files/IntelTurboBoost@wsmenezes/po/zh_TW.po
=> IntelTurboBoost@wsmenezes: Add Chinese Traditional translation

ifstat@tagadan/files/ifstat@tagadan/po/zh-TW.po
=> ifstat@tagadan: Add Chinese Traditional translation

CustomPlaces@Nicolas01/files/CustomPlaces@Nicolas01/po/zh_TW.po
=> CustomPlaces@Nicolas01: Add Chinese Traditional translation

nordvpn-indicator@nickdurante/files/nordvpn-indicator@nickdurante/po/zh_TW.po
=> nordvpn-indicator@nickdurante: Add Chinese Traditional translation

ioDisk@ctrlesc/files/ioDisk@ctrlesc/po/zh_TW.po
=> ioDisk@ctrlesc: Add Chinese Traditional translation

nvidia-temp@sophie-la-li/files/nvidia-temp@sophie-la-li/po/zh_TW.po
=> nvidia-temp@sophie-la-li: Add Chinese Traditional translation

sleepTimer@JDatPNW/files/sleepTimer@JDatPNW/po/zh_TW.po
=> sleepTimer@JDatPNW: Add Chinese Traditional translation

separator2@zyzz/files/separator2@zyzz/po/zh_TW.po
=> separator2@zyzz: Add Chinese Traditional translation

serviceLauncher@hulygun/files/serviceLauncher@hulygun/po/zh_TW.po
=> serviceLauncher@hulygun: Add Chinese Traditional translation

SpicesUpdate@claudiux/files/SpicesUpdate@claudiux/po/de.po
=> SpicesUpdate@claudiux: Update German (de) translation

ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/applet.js
As seen in issue #7092, some monitors use a different ddcutil feature flag to change the brightness. 
Therefore, I made it automatically detect the feature flag needed for each monitor and it applies this, falling back to the standard which is `10` in case it does not find the feature flag.
=> [ddcci-multi-monitor@tim-weMade]: Fix for some monitors using a different ddcutil feature flag to change brightness

desaturate-all@hkoosha/CHANGELOG.md, desaturate-all@hkoosha/files/desaturate-all@hkoosha/applet.js, desaturate-all@hkoosha/files/desaturate-all@hkoosha/metadata.json, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/ca.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/da.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/de.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/desaturate-all@hkoosha.pot, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/es.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/fi.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/fr.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/hu.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/it.po, desaturate-all@hkoosha/files/desaturate-all@hkoosha/po/nl.po, desaturate-all@hkoosha/info.json
- Added a Tooltip which will show when the next automatic enable/disable action will occur
- Changed info.json to set the author to myself (added original_author set to hkoosha)
- Added a change log file
=> [desaturate-all@hkoosha] Add a tooltip showing the next auto action time

notifications-enhanced@hilyxx/files/notifications-enhanced@hilyxx/po/fr.po, notifications-enhanced@hilyxx/files/notifications-enhanced@hilyxx/po/notifications-enhanced@hilyxx.pot, notifications-enhanced@hilyxx/files/notifications-enhanced@hilyxx/settings-schema.json
- Fix error with translations
- Update settings-schema ( forgot to change it in my pull request)
=>  [notifications-enhanced@hilyxx] - Fix error with translations

sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
Related to https://github.com/linuxmint/cinnamon/issues/12895
=> [sound150@claudiux] v12.0.4: Do not play sound notification when the volume has reached its maximum limit

sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/6.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/ca.po, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fi.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/nl.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po
=> sound150 v13.0.0: Keeps certain context menu submenus open

sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/6.4/lib/s150PopupMenu.js, sound150@claudiux/files/sound150@claudiux/6.4/settings-schema.json, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/po/ca.po, sound150@claudiux/files/sound150@claudiux/po/da.po, sound150@claudiux/files/sound150@claudiux/po/es.po, sound150@claudiux/files/sound150@claudiux/po/fi.po, sound150@claudiux/files/sound150@claudiux/po/fr.po, sound150@claudiux/files/sound150@claudiux/po/hu.po, sound150@claudiux/files/sound150@claudiux/po/it.po, sound150@claudiux/files/sound150@claudiux/po/nl.po, sound150@claudiux/files/sound150@claudiux/po/ru.po, sound150@claudiux/files/sound150@claudiux/po/sound150@claudiux.pot, sound150@claudiux/files/sound150@claudiux/po/sv.po
Related to https://github.com/linuxmint/cinnamon/issues/12920
=> sound150 v13.1.0: New option View Full Album Art

sound150@claudiux/files/sound150@claudiux/6.4/lib/s150PopupMenu.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
Related to https://github.com/linuxmint/cinnamon/issues/12920#issuecomment-2944956432
=> sound150 v13.1.1: Improved option View Full Album Art

any-alarm@sophie-la-li/files/any-alarm@sophie-la-li/applet.js
=> fixed bug in any-alarm@sophie-la-li

app-launcher@mchilli/files/app-launcher@mchilli/applet.js, app-launcher@mchilli/files/app-launcher@mchilli/po/app-launcher@mchilli.pot, app-launcher@mchilli/files/app-launcher@mchilli/po/ca.po, app-launcher@mchilli/files/app-launcher@mchilli/po/da.po, app-launcher@mchilli/files/app-launcher@mchilli/po/de.po, app-launcher@mchilli/files/app-launcher@mchilli/po/es.po, app-launcher@mchilli/files/app-launcher@mchilli/po/fi.po, app-launcher@mchilli/files/app-launcher@mchilli/po/fr.po, app-launcher@mchilli/files/app-launcher@mchilli/po/hu.po, app-launcher@mchilli/files/app-launcher@mchilli/po/it.po, app-launcher@mchilli/files/app-launcher@mchilli/po/nl.po, app-launcher@mchilli/files/app-launcher@mchilli/po/ru.po, app-launcher@mchilli/files/app-launcher@mchilli/po/tr.po, app-launcher@mchilli/files/app-launcher@mchilli/po/zh_CN.po, app-launcher@mchilli/files/app-launcher@mchilli/po/zh_TW.po, app-launcher@mchilli/files/app-launcher@mchilli/settings-schema.json
- add possibility to open menus by hovering over them
(Feature request by @PCCV on https://cinnamon-spices.linuxmint.com/applets/view/344)
- rearrange settings
- update translations files
=> app-launcher@mchilli: open menus by hovering over them

sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
=> [sound150@claudiux] v13.1.2: Minor bugfix

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/lib/sensorsReaper.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json
Attempts to solve the problems reported by @binarynoise on https://cinnamon-spices.linuxmint.com/applets/view/337#count.
=> Sensors v5.6.0: Ignores invalid sensors

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/settings-schema.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/CHANGELOG.md, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/bg.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ca.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/da.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/de.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/es.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/fi.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/fr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/hr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/hu.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/it.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ja.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/multicore-sys-monitor@ccadeptic23.pot, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/nl.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/pl.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ro.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ru.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/sv.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/tr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/zh_CN.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/zh_TW.po
Fixes #7440 
Fixes #7439 
Fixes #3016
=> [multicore-sys-monitor@ccadeptic23] v2.1.0

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/CHANGELOG.md, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/scripts/get-cpu-data2.sh, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/scripts/get-cpu-data3.sh
=> [multicore-sys-monitor@ccadeptic23] v2.2.0

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/CHANGELOG.md, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json
Fixes #7453
Fixes #7458
Many thanks again to @LeosBitto for his script offered in #7475.
=> multicore-sys-monitor@ccadeptic23 - v2.2.2

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/settings-schema.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/CHANGELOG.md, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/bg.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ca.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/da.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/de.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/es.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/fi.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/fr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/hr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/hu.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/it.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ja.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/multicore-sys-monitor@ccadeptic23.pot, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/nl.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/pl.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ro.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ru.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/sv.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/tr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/zh_CN.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/zh_TW.po
Added "Label" and "Merge all" options.
Up to 32 different colors.
=> multicore-sys-monitor@ccadeptic23 - v2.3.0

brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/6.4/applet.js, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/6.4/scripts/number-of-monitors.sh, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/6.4/settings-schema.json, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/CHANGELOG.md, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/README.md, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/metadata.json, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/bg.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/brightness-and-gamma-applet@cardsurf.pot, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/ca.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/da.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/de.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/es.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/fi.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/fr.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/hr.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/hu.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/it.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/nl.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/pt_BR.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/ru.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/sv.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/tr.po, brightness-and-gamma-applet@cardsurf/files/brightness-and-gamma-applet@cardsurf/po/zh_CN.po
* Fixes #7452
* New option in General tab: "Apply when the number of monitors changes".
=> brightness-and-gamma-applet@cardsurf - v2.1.0

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/CHANGELOG.md, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json
* New script `get-cpu-data3.sh` created by @LeosBitto. Again, this script improves performance. Many thanks to him!
* Show icon when the 'Without any graphics' option is selected in context menu.
=> multicore-sys-monitor@ccadeptic23 - v2.3.1

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/lib/Graphs.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/CHANGELOG.md, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json
=> multicore-sys-monitor@ccadeptic23 - v2.3.2

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/settings-schema.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/CHANGELOG.md, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/bg.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ca.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/da.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/de.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/es.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/fi.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/fr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/hr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/hu.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/it.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ja.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/multicore-sys-monitor@ccadeptic23.pot, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/nl.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/pl.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ro.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ru.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/sv.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/tr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/zh_CN.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/zh_TW.po
* Fixes #7444
* From now on, you can choose the Square view for each widget.
=> multicore-sys-monitor@ccadeptic23 - v2.3.3

sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/6.4/lib/s150PopupMenu.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
Fixes #7497
The code should be optimized soon.
=> sound150@claudiux - v13.2.0

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, sound150@claudiux/files/sound150@claudiux/6.4/applet.js, sound150@claudiux/files/sound150@claudiux/6.4/lib/del_song_arts.js, sound150@claudiux/files/sound150@claudiux/6.4/lib/s150PopupMenu.js, sound150@claudiux/files/sound150@claudiux/CHANGELOG.md, sound150@claudiux/files/sound150@claudiux/metadata.json
Concerned applets:
* Radio3.0@claudiux
* sound150@claudiux
=> Improved speed and code cleanup

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/CHANGELOG.md, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/scripts/get-cpu-data3 (autre copie).sh
Speed improvement.
Ping @LeosBitto.
=> multicore-sys-monitor@ccadeptic23 - v2.5.2

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/CHANGELOG.md, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/scripts/get-cpu-raw-data.sh
Improved processor measurement speed!
=> multicore-sys-monitor@ccadeptic23 - v2.6.0

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/CHANGELOG.md, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/scripts/get-mem-raw-data.sh
=> multicore-sys-monitor@ccadeptic23 - v2.6.1

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/CHANGELOG.md, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/scripts/get-disk-info.sh
Updated `get-disk-info.sh` script.
=> multicore-sys-monitor@ccadeptic23 - v2.6.3

envycontrol@zamszowy/README.md, envycontrol@zamszowy/files/envycontrol@zamszowy/applet.js, envycontrol@zamszowy/files/envycontrol@zamszowy/control.sh, envycontrol@zamszowy/files/envycontrol@zamszowy/po/envycontrol@zamszowy.pot, envycontrol@zamszowy/files/envycontrol@zamszowy/po/pl.po
* make all relevant strings translatable strings
* add translation template along with Polish translation
* fix README.md image links
* change /bin/bash invocations to /usr/bin/bash
* change '#!/bin/bash' shebang to '#!/usr/bin/env bash'
=> envycontrol@zamszowy: localization and other improvements

Gears@claudiux/files/Gears@claudiux/README.md
=> [Gears@claudiux] v1.0.0 - Update README.md

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/lib/Graphs.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/lib/tostring.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/CHANGELOG.md, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json
* Improved loops.
* Changed to_string method.
* Code cleanup.
=> multicore-sys-monitor@ccadeptic23 - v2.7.2

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json, Radio3.0@claudiux/files/Radio3.0@claudiux/settings-schema.json
Restart listening to the current station when the applet is restarted (except when it is Cinnamon that is reloaded).
=> Radio3.0@claudiux - v3.6.1

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/lib/Graphs.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/settings-schema.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/CHANGELOG.md, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/bg.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ca.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/da.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/de.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/es.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/fi.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/fr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/hr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/hu.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/it.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ja.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/multicore-sys-monitor@ccadeptic23.pot, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/nl.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/pl.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ro.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/ru.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/sv.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/tr.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/zh_CN.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/po/zh_TW.po, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/scripts/get-disk-mounts.sh
=> multicore-sys-monitor@ccadeptic23 - v2.8.0

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/lib/Graphs.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/settings-schema.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/CHANGELOG.md, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json
=> multicore-sys-monitor@ccadeptic23 - v2.8.2

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/CHANGELOG.md, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json
* Improves the context menu for accessing settings.
* Clicking the center button opens the settings.
=> multicore-sys-monitor@ccadeptic23 - v2.8.4

mouse-keys-shortcut@GabrielCamara3526/files/mouse-keys-shortcut@GabrielCamara3526/applet.js, mouse-keys-shortcut@GabrielCamara3526/files/mouse-keys-shortcut@GabrielCamara3526/metadata.json, mouse-keys-shortcut@GabrielCamara3526/files/mouse-keys-shortcut@GabrielCamara3526/po/fr.po, mouse-keys-shortcut@GabrielCamara3526/files/mouse-keys-shortcut@GabrielCamara3526/po/mouse-keys-shortcut@GabrielCamara3526.pot, mouse-keys-shortcut@GabrielCamara3526/files/mouse-keys-shortcut@GabrielCamara3526/settings-schema.json
Also, adding translations.
@GabrielCamara3526 
I hope you'll like it.
=> [mouse-keys-shortcut@GabrielCamara3526] Add OSD and make notifications optional

SpiceSpy@claudiux/files/SpiceSpy@claudiux/CHANGELOG.md, SpiceSpy@claudiux/files/SpiceSpy@claudiux/applet.js, SpiceSpy@claudiux/files/SpiceSpy@claudiux/metadata.json, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/SpiceSpy@claudiux.pot, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/ca.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/de.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/es.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/fi.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/fr.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/hu.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/it.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/po/nl.po, SpiceSpy@claudiux/files/SpiceSpy@claudiux/settings-schema.json
Alerts also on issues related to Spices.
=> SpiceSpy@claudiux - v5.4.0

mouse-keys-shortcut@GabrielCamara3526/files/mouse-keys-shortcut@GabrielCamara3526/applet.js
- Add context menu sliders
- Bind each slider to their mouse keys access
- Add labels and tooltips to identify each slider
- Clean empty space lines
=> mouse-keys-shortcut@GabrielCamara3526: Add mouse keys context menu sliders

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/lib/Graphs.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/settings-schema.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/CHANGELOG.md, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/scripts/MemoryStats.txt
Using code from the author of htop.
=> multicore-sys-monitor@ccadeptic23 - v3.0.0: The different colors for cache and buffer memory in the RAM graph are back!

hwmonitor@sylfurd/files/hwmonitor@sylfurd/3.8/applet.js, hwmonitor@sylfurd/files/hwmonitor@sylfurd/metadata.json
=> hwmonitor v1.3.2: Fixes #7545

mouse-keys-shortcut@GabrielCamara3526/files/mouse-keys-shortcut@GabrielCamara3526/applet.js, mouse-keys-shortcut@GabrielCamara3526/files/mouse-keys-shortcut@GabrielCamara3526/metadata.json, mouse-keys-shortcut@GabrielCamara3526/files/mouse-keys-shortcut@GabrielCamara3526/po/es.po, mouse-keys-shortcut@GabrielCamara3526/files/mouse-keys-shortcut@GabrielCamara3526/po/fr.po, mouse-keys-shortcut@GabrielCamara3526/files/mouse-keys-shortcut@GabrielCamara3526/po/mouse-keys-shortcut@GabrielCamara3526.pot, mouse-keys-shortcut@GabrielCamara3526/files/mouse-keys-shortcut@GabrielCamara3526/settings-schema.json
@GabrielCamara3526 
I hope this PR will suit you.
=> mouse-keys-shortcut@GabrielCamara3526: Improve icon and tooltip

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/lib/sensorsReaper.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/scripts/DisksDaemon.sh, Sensors@claudiux/files/Sensors@claudiux/scripts/SensorsDaemon.sh
=> Sensors@claudiux - v5.7.2: Improves stability

ifstat@tagadan/files/ifstat@tagadan/po/zh_TW.po
=> ifstat@tagadan: Fix Traditional Chinese translation

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/scripts/SensorsDaemon.sh
Takes into account the "Refresh interval" value in the `SensorsDaemon.sh` script.
=> Sensors@claudiux - v5.7.3

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/lib/sensorsReaper.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json, Sensors@claudiux/files/Sensors@claudiux/scripts/DisksDaemon.sh, Sensors@claudiux/files/Sensors@claudiux/scripts/SensorsDaemon.sh
Increases the speed at which disk temperatures are read.
=> Sensors@claudiux - v5.8.0

Sensors@claudiux/files/Sensors@claudiux/CHANGELOG.md, Sensors@claudiux/files/Sensors@claudiux/applet.js, Sensors@claudiux/files/Sensors@claudiux/lib/sensorsReaper.js, Sensors@claudiux/files/Sensors@claudiux/metadata.json
=> Sensors@claudiux - v5.8.1

Radio3.0@claudiux/files/Radio3.0@claudiux/CHANGELOG.md, Radio3.0@claudiux/files/Radio3.0@claudiux/applet.js, Radio3.0@claudiux/files/Radio3.0@claudiux/metadata.json
=> Radio3.0@claudiux - v3.7.1

Exit@claudiux/files/Exit@claudiux/6.4/applet.js, Exit@claudiux/files/Exit@claudiux/6.4/settings-schema.json, Exit@claudiux/files/Exit@claudiux/CHANGELOG.md, Exit@claudiux/files/Exit@claudiux/README.md, Exit@claudiux/files/Exit@claudiux/metadata.json, Exit@claudiux/files/Exit@claudiux/po/Exit@claudiux.pot, Exit@claudiux/files/Exit@claudiux/po/ca.po, Exit@claudiux/files/Exit@claudiux/po/de.po, Exit@claudiux/files/Exit@claudiux/po/es.po, Exit@claudiux/files/Exit@claudiux/po/fi.po, Exit@claudiux/files/Exit@claudiux/po/fr.po, Exit@claudiux/files/Exit@claudiux/po/hu.po, Exit@claudiux/files/Exit@claudiux/po/it.po, Exit@claudiux/files/Exit@claudiux/po/nl.po, Exit@claudiux/files/Exit@claudiux/po/zh_TW.po, Exit@claudiux/files/Exit@claudiux/scripts/mice.sh
as requested by @sophar231 on https://cinnamon-spices.linuxmint.com/applets/view/386#count.
=> Exit@claudiux - v1.7.0: Adds shortcuts and menu keys

Exit@claudiux/files/Exit@claudiux/CHANGELOG.md
=> Exit@claudiux - v1.7.1

SpiceSpy@claudiux/files/SpiceSpy@claudiux/CHANGELOG.md, SpiceSpy@claudiux/files/SpiceSpy@claudiux/README.md, SpiceSpy@claudiux/files/SpiceSpy@claudiux/applet.js, SpiceSpy@claudiux/files/SpiceSpy@claudiux/lib/httpLib.js, SpiceSpy@claudiux/files/SpiceSpy@claudiux/lib/to-string.js, SpiceSpy@claudiux/files/SpiceSpy@claudiux/metadata.json
=> SpiceSpy v5.5.1: Minor changes in menu about new commits

weather@mockturtl/files/weather@mockturtl/po/nl.po
Updated Dutch translation for version 3.6.8
=> weather@mockturtl: Update nl.po for version 3.6.8

weather@mockturtl/files/weather@mockturtl/po/sv.po
Update Swedish translation sv.po from latest template file 2025-09-28.
=> weather@mockturtl: Update Swedish translation 3.6.8

ddcci-multi-monitor@tim-we/files/ddcci-multi-monitor@tim-we/metadata.json
Bump version to 1.3.1 (missed in the #7829 PR)
No further changes. 
(Sorry for the extra hassle.)
(cc. @GingerGigiCat & @rcalixte)
=> ddcci-multi-monitor@tim-we: Fix: Forgotten version adjustment of #7829 

Bps@claudiux/files/Bps@claudiux/CHANGELOG.md, Bps@claudiux/files/Bps@claudiux/applet.js, Bps@claudiux/files/Bps@claudiux/metadata.json, Bps@claudiux/files/Bps@claudiux/scripts/get-network-data.sh
Avoids display errors like "Nan" or "Infinity".
=> Bps v1.3.2: Bugfix (using VPN)

multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/6.4/applet.js, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/CHANGELOG.md, multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/metadata.json
=> multicore-sys-monitor@ccadeptic23 v3.1.0: Improved tooltip - Fixes #7849
